### ISSUE TITLE
Change BN code for PayPal

### ISSUE THREAD

**Issue by schmengler** [OpenMage/magento-lts#1006]
To distinguish OpenMage from Magento 1, you should change the BN code for PayPal:

https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Paypal/etc/config.xml#L195

**Comment by schmengler** [comment]
BTW, this is an optional field and contains a "partner attribution ID" from PayPal. So as long as OpenMage is not partnering with PayPal, it's safe to remove entirely

https://developer.paypal.com/docs/subscriptions/reference/customize-the-sdk/?mark=bn%20code#partner-attribution-id

**Comment by tmotyl** [comment]
@schmengler do you know if it can be changed on our side to different value, or does the value has to be approved by paypal first?
I imagine that it would be beneficial to change the value, so paypal can see how many transactions are going through openmage.

**Comment by schmengler** [comment]
I *assume* that if you change it to an arbitrary value it will just be ignored. If OpenMage partners with PayPal, PayPal will assign an ID. *Then* the numbers are interesting for them.

**Comment by Flyingmana** [comment]
What I wonder, if we put an own value in there which is not a partner, will they still let the payments through and just ignore it? Could someone try this out?
Till then I would say, we remove the `->setData('BNCODE', $bnCode)` https://github.com/OpenMage/magento-lts/search?q=bncode&unscoped_q=bncode

personally I would like to add one, even if we are not an official partner, just to set a sign of how many people are using it.

**Comment by richardferaro** [comment]
The BN code can be any value as long as the maintainer of the module is a recognized PayPal 
Parner. The value is passed along within PayPal ecosystem and it is known internally as Partner Attribution ID.

**Comment by colinmollenhour** [comment]
I don't think any of us want to create a PayPal business account right now.. I think the questions are:

- If we set it to some arbitrary value like "OpenMage_LTS" will it still work in production?
- If not can we leave it empty?

**Comment by rvelhote** [comment]
> What I wonder, if we put an own value in there which is not a partner, will they still let the payments through and just ignore it? Could someone try this out?
> Till then I would say, we remove the `->setData('BNCODE', $bnCode)` https://github.com/OpenMage/magento-lts/search?q=bncode&unscoped_q=bncode

I added a breakpoint to the [method](https://github.com/OpenMage/magento-lts/blob/f19c4af0ffd13152dcfb0b112a171d9138aaf482/app/code/core/Mage/Paypal/Model/Config.php#L930) where internal configuration setting is invoked and also to those `->setData('BNCODE', $bnCode)`. I also forced the setting to return null and detected no side-effects.

This might be store specific however the BNCODE setting was only used to set a parameter called `BUTTONSOURCE` and the breakpoints I added to the two references of `->setData('BNCODE', $bnCode)` were never hit.

**Comment by fballiano** [comment]
I'm closing this since:
- no updates since 2 years
- realistically nobody will ask for a paypal partnership id
- it's difficult to test this change, nobody did it in 2 years and the real practical benefit is not very big

But, by any mean, if somebody wants to take this matter further, please feel free to reopen it.
