### ISSUE TITLE
Paypal Express issue : Expected PayPal field not found in NVP Response: AMT

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1010]
**LTS version 1.9.4.x**
Since shortly we are seeing this error in logs `Paypal Express issue : Expected PayPal field not found in NVP Response: AMT`

**Customer Problem:** 
Problem is that customer has DONE the payment, only no order is created and only a warning is shown to the customer

**Investigation**
Now I have read the AMT value is deprecated but to date have not found a sourec for this. If AMT is really deprecated and now being ommitted then we shold remove it from `_validateResponse` and `    protected $_requiredResponseParams = array(
        self::DO_DIRECT_PAYMENT             => array('ACK', 'CORRELATIONID', 'AMT'),
        self::DO_EXPRESS_CHECKOUT_PAYMENT   => array('ACK', 'CORRELATIONID', 'AMT'),
    );` in app/code/core/Mage/Paypal/Model/Api/Nvp.php

**Possible solution**
Remove AMT from the validation of fields

**Missing information before we can continue**
 1. Need to find the proof that AMT is really deprecated
 2. And need to be certain AMT is not used in Magento further in the process

References: 
https://community.magento.com/t5/Payments-PayPal/PayPal-response-hasn-t-required-fields-AMT-field-is-deprecated/td-p/51852
https://www.experts-exchange.com/questions/29115407/Magento-shows-error-message-when-trying-to-make-payment-with-PayPal.html
https://github.com/gtaylor/paypal-python/issues/4

```
2020-05-29T10:57:19+00:00 ERR (3): 
Exception: Antwoord van PayPal bevat de vereiste velden niet. in app/code/core/Mage/Paypal/Model/Api/Nvp.php:996
Stack trace:
#0 app/code/core/Mage/Paypal/Model/Api/Nvp.php(644): Mage_Paypal_Model_Api_Nvp->call('DoExpressChecko...', Array)
#1 app/code/core/Mage/Paypal/Model/Express.php(581): Mage_Paypal_Model_Api_Nvp->callDoExpressCheckoutPayment()
#2 app/code/core/Mage/Paypal/Model/Express.php(377): Mage_Paypal_Model_Express->_placeOrder(Object(Mage_Sales_Model_Order_Payment), '45.44')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(443): Mage_Paypal_Model_Express->capture(Object(Mage_Sales_Model_Order_Payment), '45.44')
#4 app/code/core/Mage/Sales/Model/Order/Invoice.php(390): Mage_Sales_Model_Order_Payment->capture(Object(Mage_Sales_Model_Order_Invoice))
#5 app/code/core/Mage/Sales/Model/Order/Payment.php(608): Mage_Sales_Model_Order_Invoice->capture()
#6 app/code/core/Mage/Sales/Model/Order/Payment.php(410): Mage_Sales_Model_Order_Payment->_invoice()
#7 app/code/core/Mage/Sales/Model/Order/Payment.php(348): Mage_Sales_Model_Order_Payment->capture(NULL)
#8 app/code/core/Mage/Sales/Model/Order.php(897): Mage_Sales_Model_Order_Payment->place()
#9 app/code/core/Mage/Sales/Model/Order.php(1115): Mage_Sales_Model_Order->_placePayment()
#10 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#11 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 app/code/core/Mage/Sales/Model/Service/Quote.php(248): Mage_Sales_Model_Service_Quote->submitOrder()
#14 app/code/core/Mage/Paypal/Model/Express/Checkout.php(614): Mage_Sales_Model_Service_Quote->submitAll()
#15 app/code/core/Mage/Paypal/Controller/Express/Abstract.php(320): Mage_Paypal_Model_Express_Checkout->place('EC-36N87767J543...')
#16 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Paypal_Controller_Express_Abstract->placeOrderAction()
#17 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('placeOrder')
#18 app/code/core/Mage/Core/Controller/Varien/Front.php(174): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#20 app/Mage.php(745): Mage_Core_Model_App->run(Array)
#21 index.php(97): Mage::run('ovh_nl', 'store')
#22 {main}
```

**Comment by Flyingmana** [comment]
Can you check how this part is done in M2?
I guess they are more up2date if there was a deprecation.

**Comment by seansan** [comment]
Cant find source via Google

And looking at here it also seems to exist
https://github.com/pepe1518/magento2/blob/master/vendor/magento/module-paypal/Model/Api/Nvp.php

The error started occurring since today .. maybe the deprecation started
today? Will keep an eye on it

**Comment by daboss84** [comment]
Hm, "here" on "our" Magento Version 1.9.4.5, it is still correctly processing Paypal payements (Paypal Express as well as Paypal Plus. But PPP is handled via a different plugin).

**Comment by simbus82** [comment]
This is an old bug.
https://community.magento.com/t5/Payments-PayPal/PayPal-response-hasn-t-required-fields-AMT-field-is-deprecated/td-p/51852

**Comment by kestraly** [comment]
Having this issue as well now

**Comment by luigifab** [comment]
Same on our website, same solution.

Moreover, without this change, when **Skip Order Review Step** is set to **Yes**:
» when PayPal refuse the transaction, the customer is redirected to order review step,
» the following PayPal error message is lost (here I previously tried to pay with a VISA card).

![image](https://user-images.githubusercontent.com/31816829/111326459-dac70c80-866c-11eb-983d-d740090fe2a7.png)

**Comment by sreichel** [comment]
@all-contributors add @seansan bug
