### ISSUE TITLE
Suggestion about endif/endforeach

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1027]
Can I suggest (and make a PR) to replace all variants of _endif_?

```php
<?php endif; ?>
<?php endif;?>
<?php endif?>
<?php else:?>
```

By:

```php
<?php endif ?>
<?php else: ?>
```

(same for endforeach)
Perhaps it's a little duplicate of the "Project Cleanup".

**Comment by sreichel** [comment]
I'd keep it open until your PR is merged. As soon it is done i'll mark it as "fixes" ...
