### ISSUE TITLE
Module management

### ISSUE THREAD

**Issue by ollyboy** [OpenMage/magento-lts#1049]
We use composer to install additional modules. Like most medium/large sites ( sales > $10Million ) we have lots of modules. Software support for these is coming to an end. How do we as a team build some sort of "good module list" for LTS.

As an example, we found that "Amastey one page checkout" does not enable/disable correctly when we have Braintree and after-pay installed. The module "extends" Braintree via the addition of javascript ( vZeroIntegration.addMethods ) . These methods are not removed when the module is disabled. standard One page payment then crashes with javascript errors as the amastey methods were dependent on the one-page main module.

We would be happy to share our working module list for LTS, plus we could share modules we have rejected.

Last thought is maybe we could take over M1 good modules and maintain in github ( we do this in private repository ) if the suppliers no longer want to support them.

**Comment by colinmollenhour** [comment]
Thanks for the suggestions, @ollyboy.

For modules that already live on github I think it'd be best to leave them where they are but perhaps link to them from a page or document of some sort (e.g. "Awesome OpenMage").

For ones that the authors are willing to "hand over" to the community I think we could provide a place for them but support would be limited and we'd probably just choose community members such as yourself to add as maintainers.

Unfortunately for commercial modules the vendors will not have a marketplace to sell them, just the web, although we are maintaining a list of module vendors that wish to support OpenMage.

The core maintainers need to stay focused on maintaining the core so the community will really have to step up for this to be successful. Let us know specifically how you'd like to help and let's make it happen!

**Comment by colinmollenhour** [comment]
See https://www.openmage.org/patches%20&%20addons/2019/08/18/new-home-magento-connect-modules.html and maybe talk to @Flyingmana about what you'd like to help with if interested.

**Comment by loekvangool** [comment]
Considering that all M1 modules have just been removed from Magento Marketplace, there is no central place anymore with M1 modules. Rolling our own intelligence became more valuable.

**Comment by waynetheisinger** [comment]
An OpenMage Marketplace could provide module producers an advertising space for their existing Magento 1 modules that they are still selling and maintaining - it could run sa OpenMage Marketplace in the same way that Magento ran Magento Marketplace and take a small commission to provide a revenue stream to support the project's expenses?

Perhaps Unirgy could be persuaded to provide a licence for their Marketplace extension and then each vendor could manage their own modules and customer service within the marketplace - then only the skin and initial setup work would have to be done by the project collaborators? (@unirgy - what do you think?)

**Comment by fballiano** [comment]
At the moment we've https://openmage.readthedocs.io/en/latest/modules/index.html which can be edited by anybody sending a PR to https://github.com/OpenMage/documentation

I'm closing this issue (which should be in the "discussions" area) cause it's dead since 2 years and I think we'll never have the possibility to develop a real marketplace. Feel free to reopen it if somebody wants to do that.
