### ISSUE TITLE
Docs: Composer.json => magento-source vs. magento-core

### ISSUE THREAD

**Issue by kkrieger85** [OpenMage/magento-lts#1053]
I tried to install OpenMage with `aydin-hassan/magento-core-composer-installer like recommended in docs - but it doesn't work. 

It seems, that in OM composer.json `magento-source` is not valid to this installer.

**Refs**:
https://github.com/OpenMage/magento-lts/blob/f19c4af0ffd13152dcfb0b112a171d9138aaf482/composer.json#L4

https://github.com/AydinHassan/magento-core-composer-installer#installation
Code Example from there:

    {
        "name": "magento/magento",
        "description": "Magento Mirror",
        "type": "magento-core"
    }

[magento-source](https://github.com/AydinHassan/magento-core-composer-installer/search?q=magento-source&type=Code ) vs. [magento-core](https://github.com/AydinHassan/magento-core-composer-installer/search?q=magento-core&unscoped_q=magento-core&type=Code)

**Comment by Flyingmana** [comment]
Do we have a reference ticket there?
Last time I checked it did work, and even if not, it should not be hard to support both keywords.
Or at lest for us to get a reason why one os better then the other.

**Comment by spinsch** [comment]
i use a composer file like the following below and works with the latest composer:
```bash
Composer version 1.10.6 2020-05-06 10:28:10
```

```json
{
    "name": "spinsch/shop",
    "require": {
        "aydin-hassan/magento-core-composer-installer": "*",
        "magento-hackathon/magento-composer-installer": "3.2.*",
        "openmage/magento-lts": "1.9.4.x"
    },
    "extra": {
        "auto-append-gitignore": true,
        "magento-core-deploy": {
            "excludes": [
                "downloader",
                ".htaccess.sample",
                ".travis.yml",
                "README.md",
                "RELEASE_NOTES.txt",
                "index.php.sample",
                "install.php",
                "php.ini.sample",
                "app/etc/local.xml.additional",
                "app/etc/local.xml.template",
                "CODE_OF_CONDUCT.md"
            ]
        },
        "magento-core-package-type": "magento-source",
        "magento-deploy-sort-priority": {
        },
        "magento-deploystrategy": "copy",
        "magento-force": true,
        "magento-root-dir": "htdocs/"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.firegento.com"
        }
    ],
    "minimum-stability": "dev"
}
```

**Comment by kkrieger85** [comment]
Ah, ok. You define the magento-core-package-type:

`        "magento-core-package-type": "magento-source", `

That works fine

**Comment by kkrieger85** [comment]
TODO: Update documentation with this information

**Comment by Flyingmana** [comment]
for note what composer.json is currently used to deploy the demo: https://github.com/OpenMage/OpenMage-demo-deployment/blob/main/src/composer.json

**Comment by fballiano** [comment]
> TODO: Update documentation with this information

I'd do that but I don't know which documentation we should update

**Comment by elidrissidev** [comment]
The [install page](https://www.openmage.org/magento-lts/install.html) on the website already states the correct way. There is no other documentation for this.


![Screen Shot 2022-10-04 at 11 24 16 AM](https://user-images.githubusercontent.com/67818913/193796199-b2251fd1-d278-4a12-bafa-0bb7a51586b7.png)

**Comment by fballiano** [comment]
we have now integrated some doc in the README, I'm closing this ATM :-)
