### ISSUE TITLE
Retrieve table name - getTable(), getTableName()

### ISSUE THREAD

**Issue by Sekiphp** [OpenMage/magento-lts#1055]
In Magento 1.x there are multiple ways how to get table name, when we knows `entityName`. Sometimes you have to use method `getTable` and sometimes `getTableName`. It depends on context, where you take resource from. 

**Perhaps we should consider implementing the method `getTableName` just like alias of function `getTable`.**

Check the examples below:

## Get name using core/resource singleton (class: Mage_Core_Model_Resource)
``` 
$resource = Mage::getSingleton('core/resource');
var_dump(get_class($resource)); // Mage_Core_Model_Resource

var_dump($resource->getTableName('sales/order'));
``` 

## Get resource from standart Magento core collection
``` 
$resource = Mage::getModel('catalog/product')->getResource();
var_dump(get_class($resource)); // Mage_Catalog_Model_Resource_Product

var_dump($resource->getTable('sales/order'));
// Mage_Catalog_Model_Resource_Product --> Mage_Catalog_Model_Resource_Abstract --> Mage_Eav_Model_Entity_Abstract --- call: Mage_Core_Model_Resource
``` 

## Get resource from custom collection
``` 
$resource = Mage::getModel('namespace_custom/model')->getCollection()->getResource();
var_dump(get_class($resource)); // Namespace_Custom_Model_Resource_Model

var_dump($resource->getTable('sales/order'));
// Namespace_Custom_Model_Resource_Model--> Mage_Core_Model_Resource_Db_Abstract --> Mage_Core_Model_Resource_Abstract --- call: Mage_Core_Model_Resource
```

**Comment by luigifab** [comment]
I agree, +1.

**Comment by fballiano** [comment]
@Sekiphp would it be possible for you to create a PR about this? Thank you!

**Comment by fballiano** [comment]
since nobody acted on this, and it's not really a bug, and we've many things to check, i'm sorry but I'll close this. if somebody is willing to provide a PR then feel free to reopen it
