### ISSUE TITLE
Should I use magento-lts instead of Magento 1.9.2.4?

### ISSUE THREAD

**Issue by emateu** [OpenMage/magento-lts#106]
Hello guys,

I'm following this project closely and trying to understand if dropping the default 1.9.2.4 and move to magento-lts has benefits and if it also provides stability to run it on production. Thank you!

**Comment by seansan** [comment]
This is arbitrary .... and I am not an expert. However I am a auser of LTS
who did make the switch

Magento default
- Stable
- But as time passes & technology advances may change

LTS
- That said: LITS currently seems the only project moving forward
- And excepts bug fixes
- Is merged if a new Magento release is released (and merge-able)
- You can't just post "bugs" and demand a fix (hut hey! Magento/Varien/Ebay
have never had this service for Community)

I can only share "why" we use it
- Sense of moving forward
- We sometimes encounter bugs / improvements: and now at least there is a
place to share it

I general my advice would be.  There has to be a person on your team who
knows some PHP and the Magento MVC. Extension providers will often support
a Magento version, but not a split off like Magento LTS ..... so you may
loose some support there

Does this help?

**Comment by drobinson** [comment]
@emateu Another benefit of this repo which I find most useful is Composer support.  Our CI process runs smoothly because we can define what version of LTS we want in Composer and just install during packaging.  You can assume there won't be any BC breaks (at least until Magento drops support for 1.* - and in that case we'd bump the version).

**Comment by tmotyl** [comment]
I'm using magento lts on production for multiple websites. I don't see any benefit on staying on Magento official distribution.
