### ISSUE TITLE
Orders - Bill to Name and Ship to Name allow only one word for searching

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1062]
Go to **Admin -> Sales -> Orders**.  In my case there are customers who placed orders with 2 - 4 names like John Paul Doe. 

If I want to filter all orders by **Bill to Name** field for john paul doe it won't work, Magento shows no results. It seems the field allows only one word but in this case I get a long list of names then I have to sort them by clicking on the column header and find where is positioned john paul doe. The same thing happens for **Ship to Name** field too.

By the way this is not happening in Admin -> Customer -> Manage Customers. The field Name allows to search as many words as I want providing the correct results.

I searched the Internet for a solution but nobody approached this issue before. Thank you.

**Comment by kiatng** [comment]
I tested the name filtering for several versions of OpenMage from 1.9.1.1 to 1.9.4.5, I cannot replicate the issue. Could it be that your issue is caused by a 3rd-party extension? You may disable the extension one by one and see if the issue goes away.

**Comment by ADDISON74** [comment]
Thank you for your reply. It is Magento CE 1.9.2.4 installed from scratch not Open Mage version. There are no extensions installed except the ones which come from Magento. I made a new attempt and I installed it again. I created a few orders with different names then tried to filter by Bill/Ship names. No positive results. I will check what are the differences between files related to Admin -> Orders in case the latest version works fine.

If anyone encounter this issue please leave a post.

**Comment by AlterWeb** [comment]
This sounds like the Magento bug solved already in OpenMage https://github.com/OpenMage/magento-lts/pull/578. This has to do with first name and last name however and not with multiple first names. So John Doe has the same problem. Migrating to open mage should solve this for you.

**Comment by jhejlik** [comment]
@ADDISON74 This bug is in Magento only. Enter two spaces between the first and last name.

**Comment by ADDISON74** [comment]
I appreciate all for your help. Inserting one space between the words did the job.

Off topic: I am one who supported Magento Community since 2014 and I really like Magento 1. I have a lot of corrections made by myself inside Magento CE. I will check if they already being fixed here. If not with your permission I will post them for reviewing. In case they will help you can merge the solution into the master branch.

Thank you.

**Comment by sreichel** [comment]
Hi @ADDISON74,

if you have something to fix please open a PR ... :+1: 

I started to track known bugs that have been fixed, but its not up to date .... maybe it helps ...

- https://magento.stackexchange.com/questions/187271/magento-1-9-3-x-core-issues-and-possible-fixes
- https://gist.github.com/sreichel/215a05b524ff2201e896e3273922d6bf

**Comment by ADDISON74** [comment]
> This sounds like the Magento bug solved already in OpenMage #578. This has to do with first name and last name however and not with multiple first names. So John Doe has the same problem. Migrating to open mage should solve this for you.

Please note **This issue is not fix in OpenMage 20.0.4**. I just tested it a few moments ago. I suggest you doing the same thing in different scenarios.

1. If Name has one part (e.g. John) the results are as expected.

2. If Name has two parts (e.g. John Doe) you won't get any results without inserting a second space between the parts.

3. If Name has three parts (e.g. John Doe Doe). If you search after the first two parts (e.g. John Doe) the results are as expected. If you search all three parts you won't get any results without inserting a second space between the second part and the third one.

It is clear to me Magento is trimming the space after the part position calculated as (number of parts - 1).
