### ISSUE TITLE
composer.json: No such file or directory

### ISSUE THREAD

**Issue by michaelj000** [OpenMage/magento-lts#1063]
New at this, trying to migrate from 1.9.4.3, followed directions. Tried to apply patch as shown and I'm getting: 

composer.json: No such file or directory

copied composer.json to magento directly, then showed: 

error: patch failed: composer.json:
error: composer.json: patch does not apply

**Comment by kkrieger85** [comment]
What exactly did you try? Migrate from plain 1.9.4.3 without composer to openmage with composer? 

Could you also please post your composer.json?

**Comment by AlterWeb** [comment]
Can you post the part of your patch file after: 

`diff --git a/composer.json b/composer.json`

untill the next:

`diff --git a/...........`

It looks like you'r trying to patch a existing composer.json file but that file doesn't exist. If you'r migrating from the official Magento 1.9.4.3 code I think there shouldn't be an existing composer.json file however and the code after:

`diff --git a/composer.json b/composer.json`

Should read something like:

```
new file mode 100644
index 0000000..e10ea5e
--- /dev/null
+++ b/composer.json
@@ -0,0 +1,27 @@
+{
+  "name": "openmage/magento-lts",
+  "license": "OSL-3.0",
+  "type": "magento-source",
+  "require": {
+    "php": ">=7.0 <7.5",
+    "magento-hackathon/magento-composer-installer": "^3.1 || ^2.1"
+  },
+  "description": " A fork of Magento-1 that is accepting bug fixes (backward compatible, drop in replacement for official Magento)",
+  "authors": [
+    {
+      "name": "Lee Saferite",
+      "email": "lee.saferite@aoe.com",
+      "role": "Maintainer"
+    },
+      {
+        "name": "Daniel Fahlke aka Flyingmana",
+        "email": "flyingmana@googlemail.com",
+        "role": "Maintainer"
+      },
+    {
+      "name": "David Robinson",
+      "email": "david.robinson@aoe.com",
+      "role": "Maintainer"
+    }
+  ]
+}
```

**Comment by michaelj000** [comment]
Yes - I was trying to migrate from official magento 1.9.4.3 without composer to openmage with. No existing composer file. 

From the patch file:

diff --git a/composer.json b/composer.json
index f3b70ab07..e10ea5eb6 100644
--- a/composer.json
+++ b/composer.json
@@ -1,6 +1,27 @@
 {
-    "name": "openmage/magento-mirror",
-    "type": "magento-core",
-    "license": ["OSL-3.0", "AFL-3.0"],
-    "description": "Magento CE"
+  "name": "openmage/magento-lts",
+  "license": "OSL-3.0",
+  "type": "magento-source",
+  "require": {
+    "php": ">=7.0 <7.5",
+    "magento-hackathon/magento-composer-installer": "^3.1 || ^2.1"
+  },
+  "description": " A fork of Magento-1 that is accepting bug fixes (backward compatible, drop in replacement for official Magento)",
+  "authors": [
+    {
+      "name": "Lee Saferite",
+      "email": "lee.saferite@aoe.com",
+      "role": "Maintainer"
+    },
+      {
+        "name": "Daniel Fahlke aka Flyingmana",
+        "email": "flyingmana@googlemail.com",
+        "role": "Maintainer"
+      },
+    {
+      "name": "David Robinson",
+      "email": "david.robinson@aoe.com",
+      "role": "Maintainer"
+    }
+  ]
 }
diff --git a/cron.php b/cron.php
....

**Comment by AlterWeb** [comment]
That looks like the patch file indeed expects there to be a composer.json file. The easiest way I know to fix this is to remove those lines **before** `diff --git a/cron.php b/cron.php` from your patch file. You already copied the composer.json file by hand so it doesn't need patching anymore.

**Comment by Flyingmana** [comment]
If you followed the instructions from the website, a diff from the mirror repository to the LTS repository would expect a composer.json to exist(in this specific version we had one in the mirror).
The easiest solution would be, to copy this file from the mirror into you directory before applying the patch

**Comment by michaelj000** [comment]
Thanks for the help, rebuilt the patch file and applied it without issue on my dev site. 

Trying on my production site, getting this when applying patch: 

error: patch failed: .htaccess:26
error: .htaccess: patch does not apply

from my .htaccess file:

## default index file

    DirectoryIndex index.php

<IfModule mod_php5.c>

in the patch file:

diff --git a/.htaccess b/.htaccess
index 63e17295e..4c9cdad1d 100644
--- a/.htaccess
+++ b/.htaccess
@@ -26,13 +26,14 @@
 
     DirectoryIndex index.php
 
+############################################

**Comment by michaelj000** [comment]
Was able to create a new patch (on my dev site) and it worked without issue.
