### ISSUE TITLE
Admin Captcha (After number of attempts to login) has a default value of 1000 tries per IP and no way to change this

### ISSUE THREAD

**Issue by AlterWeb** [OpenMage/magento-lts#1065]
### Description (*)

The Captcha for the admin login can be set to a mode "After number of attempts to login" you then have the options to specify after how many attempts this will be required. Standard this is 3 attempts, so I thought this would mean that after I tried 3 wrong credentials I would get the Captcha. But after some testing I found out this is only applied to the attempts to login to the same account. You can hover try multiple accounts without triggering this Captcha. Not a big security risk because you already should know the password and only guessing the account name but still I think it would be nice to block a bot from guessing more than the 3 combinations of users and passwords.

There seems to be a mechanism however that does that based on IP address. This value is set to 1000 attempts however, which I find quit a lot. There is no admin setting to override this value so I can only change this by overriding this in the core config files, directly in the database or by creating a custom module for that.

### Expected behavior (*)

I see several ways to make this feature more useful.

1. Make a admin config setting for this so every shop owner can change this for them self.
2. Change this behavior to make use of the same value already set in the backend (now used for the number of attempts to login on a single account).
3. Lower this number (1000) to a more appropriate number like for instance 10. If someone is providing more then 10 different combinations I would say there is something wrong there. 

### Benefits

Improve security (slightly) and make the feature behave more like expected (or at least what I was expecting it to behave like).

### Additional information

If more people find this useful I am happy to create a pull request to add this feature. Please also let me know then which option you prefer and why or if you see a problem with one of the options.

**Comment by colinmollenhour** [comment]
What's this? Haven't you ever forgotten your password and only successfully remembered it on your 1001st try? 🤣

**Comment by tmotyl** [comment]
I would show captcha after 3 attempts and block the account after 10

**Comment by sreichel** [comment]
>     3\. Lower this number (1000) to a more appropriate number like for instance 10. If someone is providing **more then 10** different combinations I would say there is something wrong there.

Limit of 10 could hit me. ;)

>     1. Make a admin config setting for this so every shop owner can change this for them self.

PR welcome :+1:
