### ISSUE TITLE
Change Github REPO description/about

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1070]
### Description (*)
This project is not listed at its best in google and this can be improved. We need to be found on search strings like "Magento", "Magento 1", "Magento 1.9" and "Magento LTS" or "Openmage"

### Expected behavior (*)
Search for Magento LS in Google

Instead of the current result
![image](https://user-images.githubusercontent.com/652395/85947791-1d18b400-b94d-11ea-94e1-5bfc91d3a7cc.png)

It could look like
![image](https://user-images.githubusercontent.com/652395/85947781-168a3c80-b94d-11ea-8112-3cd416458c13.png)

### Additional information
The information in Google comes from here
![image](https://user-images.githubusercontent.com/652395/85947825-476a7180-b94d-11ea-80a1-e234a3091264.png)

**Change to? (just suggesting)**

Before the DASH = title? => "Official OpenMage Codebase"

After the DASH = description? => "Download or contribute OpenMage. Empowering thousands of Magento 1 stores with the best eCommerce platform around. Community driven Long Term Support for Magento 1.9.x."

**Comment by simbus82** [comment]
Another tip: to split concepts, you can use the | instead of the -. It takes up fewer pixels. The visual limit in the SERP of the title and description is not in characters, but in pixels. ;-)

**Comment by colinmollenhour** [comment]
Thanks for the suggestions, description updated.

**Comment by seansan** [comment]
> Another tip: if you have to split concepts and do something visually engaging (in description for example) , you can use the | instead of the -. It takes up fewer pixels because the visual limit in the SERP of the title and description is not in characters, but in pixels. ;-)
> 
> To make the repository easily found in Google, the Readme file is also very important.
> So an SEO optimization can also be done there, respecting the headings (h1, h2, etc.) and adding different information about "answers" to be given to users' questions (queries).
> 
> Do not worry if you go to compete with the same OpenMage site, 2 results in SERP are always better than one ;-)

Maybe you can make suggestions by editing the README? and create a pull request

**Comment by simbus82** [comment]
> > Another tip: if you have to split concepts and do something visually engaging (in description for example) , you can use the | instead of the -. It takes up fewer pixels because the visual limit in the SERP of the title and description is not in characters, but in pixels. ;-)
> > To make the repository easily found in Google, the Readme file is also very important.
> > So an SEO optimization can also be done there, respecting the headings (h1, h2, etc.) and adding different information about "answers" to be given to users' questions (queries).
> > Do not worry if you go to compete with the same OpenMage site, 2 results in SERP are always better than one ;-)
> 
> Maybe you can make suggestions by editing the README? and create a pull request

Something like this?
If you don't see too many English mistakes, I can make a PR ... it could already be a more structured "readme" than the current one.
https://github.com/simbus82/magento-lts/blob/patch-1/README.md

**Comment by seansan** [comment]
Looks good to me; I do see some English that needs to be checked (some
grammar errors already existed no worries)

Maybe some remarks
- If possible add some of the text in the about also in the body?
- If possible add some elements of the about as H2/H1
- Mention Magento where necessary and relevant, also at least some headers
- Maybe utilize some old texts from here:
https://web.archive.org/web/20180207204219/https://magento.com/about (and
add source)

Just some ideas

About

Official OpenMage LTS codebase | Migrate easily from Magento Community
Edition in minutes! Download the source code for free or contribute to
OpenMage LTS | Security vulnerability patches, bug fixes, performance
improvements and more.

**Comment by fballiano** [comment]
I prefered the previous one over the new marketing oriented one. I don't think openmage has the same target of the whole magento1 platform. who's looking into openmage now is not generically looking for "migrate in few minutes". I don't know...

In my opinion openmage will never be magento1, and rightfully and pridefully so, why should it be? it's built on top of the giant but had and needs its own identity, doesn't need to attract people just cause it's easy to migrate or something like that.

But I'm the one also not agreeing on the LTS postfix everywhere, AFAIK we don't know how "log term" is going to be but also that's "openmage lts" is simple a worse name (IMHO) compared to "openmage" (which is beautiful and I love it), so I guess I'm the odd one :-D

Anyway it's done already so...

**Comment by Flyingmana** [comment]
Closing this, as change was done and I think we cant reach much more by changing the Repo Description.

for SEO its probably better to focus on the Website.
Or also indirectly of having other Websites rank on this keywords which refer to us.

Besides that, we currently rank on Position 1 for "Magento LTS"

**Comment by fballiano** [comment]
I would have wrote

`Official OpenMage repository | Migrate from Magento Community Edition easily and get security patches, bug fixes, performance improvements and new features | Download the source code for free and contribute to the project `

**Comment by fballiano** [comment]
> for SEO its probably better to focus on the Website.

then why update the description in a SEO oriented way and ask me to modify https://github.com/OpenMage/magento-lts/pull/1572 checking SEO?

> Besides that, we currently rank on Position 1 for "Magento LTS"

is people in 2021 really seaching for "magento lts"?

**Comment by Flyingmana** [comment]
sorry, should have sayed "focus on the Website from now on for further improvements"
That does not mean we should ignore it from now on or accept any worsening in this area.

and yes, people do:

![image](https://user-images.githubusercontent.com/237319/118397411-132a9d00-b654-11eb-98af-c33c1d730b3d.png)

**Comment by fballiano** [comment]
this query is openmage lts, not magento lts.

also, IMHO, this description is worse than before so to me you're accepting worsening descriptions.

**Comment by Flyingmana** [comment]
ahh sorry, wrong line, thats the magento lts one. A bit less, but still a good position and clickthrough rate

![image](https://user-images.githubusercontent.com/237319/118397679-81239400-b655-11eb-8775-a3dac28735b3.png)
