### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function char() in /var/www/html/lib/Varien/Io/File.php:490

### ISSUE THREAD

**Issue by andthink** [OpenMage/magento-lts#1083]
### Preconditions (*)

Lts 20.0.0

### Steps to reproduce (*)

Loading homepage

### Expected result (*)
pages loads without fatal error

### Actual result (*)
PHP Fatal error:  Uncaught Error: Call to undefined function char() in /var/www/html/lib/Varien/Io/File.php:490

@damien-biasotto

I'm trying to understand where this **char()** function is defined? Maybe it was intended to be **chr()**?

**Comment by andthink** [comment]
https://github.com/OpenMage/magento-lts/pull/1084 I've created a PR with proposed modification

**Comment by damien-biasotto** [comment]
Oh my I feel so ashamed. I'm really sorry :(

**Comment by sreichel** [comment]
Fixed in #1084.
