### ISSUE TITLE
Detect undefined functions on PullRequests

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1087]
With the PR #966 we introduced a function call, to a non defined function by accident.
The error was reported/fixed in #1084

It should be possible to detect this case with a static analyses, and have this triggering an error as one of the Checks running on a PR

possible tools?
https://github.com/vimeo/psalm
https://github.com/phan/phan
https://github.com/phpstan/phpstan

**Comment by Flyingmana** [comment]
Phan is outputting a lot, but it contains:

```
lib/Varien/Io/File.php:490 PhanUndeclaredFunction Call to undeclared function \char() (Did you mean \chr())
```

my config I used:
https://gist.github.com/Flyingmana/484003b1887ae71ce6a96146cc4a73fa

not sure yet how I limit the results to only specific errors

Also it does not know context, so also has false positives like in Mage_PageCache_Model_Control_Zend

Also it finds some cases where I think its not an issue?
```
lib/Cm/Cache/Backend/Redis.php:866 PhanUndeclaredFunction Call to undeclared function \snappy_compress()
lib/Cm/Cache/Backend/Redis.php:868 PhanUndeclaredFunction Call to undeclared function \lz4_compress() (Did you mean \gzcompress() or \gzuncompress())
lib/Cm/Cache/Backend/Redis.php:888 PhanUndeclaredFunction Call to undeclared function \snappy_uncompress()
lib/Cm/Cache/Backend/Redis.php:890 PhanUndeclaredFunction Call to undeclared function \lz4_uncompress() (Did you mean \gzuncompress())
lib/Mage/Connect/Validator.php:411 PhanUndeclaredFunction Call to undeclared function \version_compate() (Did you mean \version_compare())
```

**Comment by sreichel** [comment]
Maybe you want to test phpStan too .... https://phpstan.org/r/940d1f01-5b1e-43e5-9a28-3ec530e1cd9f

- you also need https://github.com/inviqa/phpstan-magento1
- there is my old config (#784) .... After most DOC updates merged it should give a nice result (for now)
PhpStan works too ... https://phpstan.org/r/940d1f01-5b1e-43e5-9a28-3ec530e1cd9f

**Comment by Flyingmana** [comment]
Ahh nice, I did not find thisnrule when I initially searched, so tried out the other first.
Can I limit phpstan to only do this one check?

**Comment by sreichel** [comment]
> 
> 
> Ahh nice, I did not find thisnrule when I initially searched, so tried out the other first.
> Can I limit phpstan to only do this one check?

Linked example uses highest severity level (8) ... but undefined mehtodd are also detected on lowest level (0).

Maybe run phpStan with `level 0` and add all other errors to ignore list (or fix them :P)

**Comment by tmotyl** [comment]
working setup with phpstan: https://github.com/OpenMage/magento-lts/pull/1837

**Comment by tmotyl** [comment]
I believe this can be closed once we got https://github.com/OpenMage/magento-lts/pull/2035 merged, don't you think?
