### ISSUE TITLE
error: .htaccess: patch does not apply

### ISSUE THREAD

**Issue by michaelj000** [OpenMage/magento-lts#1089]
Trying on my production site, getting this when applying patch:

error: patch failed: .htaccess:26
error: .htaccess: patch does not apply

from my .htaccess file: 26

default index file
DirectoryIndex index.php

in the patch file:

diff --git a/.htaccess b/.htaccess
index 63e17295e..4c9cdad1d 100644
--- a/.htaccess
+++ b/.htaccess
@@ -26,13 +26,14 @@

 DirectoryIndex index.php

Tried removing all htaccess changes from patch, then got:

error: corrupt patch at line 82241

**Comment by colinmollenhour** [comment]
Can you describe the exact steps that you are talking about when you say "when applying patch"? Thanks!

**Comment by michaelj000** [comment]
Just following the directions - created the patch in the openmage directory, moved it to the public directory, and:

git apply migration.patch

**Comment by colinmollenhour** [comment]
Ahh, ok. I think at one point we removed .htaccess from the repo and renamed it .htacces.sample.. So we might need to add some extra step to the migration to account for this since the patch probably tries to either delete it or modify it but it is likely to be modified by the end user..

**Comment by michaelj000** [comment]
That seemed to work - replaced my existing htaccess with unedited from one magento 1.9.4.5, made sure .htaccess.sample was there, and it processed with only whitespace error warnings.

**Comment by fballiano** [comment]
Closing since the question has been answered
