### ISSUE TITLE
Cleanup: Remove Mage_Adminhtml_Block_Notification_Survey

### ISSUE THREAD

**Issue by kkrieger85** [OpenMage/magento-lts#1095]
This block and the corresponding template shows a message in Adminhtml which referres to magento survey

![2020-07-06_15-50](https://user-images.githubusercontent.com/4435523/86600606-8b3e2600-bfa0-11ea-9db5-cb7299c6abba.png)

**Comment by fballiano** [comment]
couldn't this be considered duplicate of https://github.com/OpenMage/magento-lts/issues/683 ?
