### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by clockworkgeek** [OpenMage/magento-lts#11]
Would you consider adopting composer and registering with the [Firegento repository](https://github.com/magento-hackathon/composer-repository)?  You already have all versions properly tagged, along with Magento composer installer this could be very useful for a lot of people.

**Comment by LeeSaferite** [comment]
If you want to add one with a pull request, I'll merge it and we can go from there.

**Comment by clockworkgeek** [comment]
It's not as easy as I first thought.  Adding it now won't make old tags available and we know that rewriting the history is a bad thing.

I didn't want to rely on [bragento/magento-core](https://github.com/bragento/magento-core) because of how they map directories but now I have found [magento-core-composer-installer](https://github.com/AydinHassan/magento-core-composer-installer) which works around that.

Thank you anyway.
