### ISSUE TITLE
Apply Patch for Shopping cart price rules - Condition subselection issue

### ISSUE THREAD

**Issue by diglin** [OpenMage/magento-lts#110]
This patch fix issue with Shopping Cart Rule as mentioned here: http://magento.stackexchange.com/questions/46428/magento-1-9-1-shopping-cart-price-rules-condition-subselection-issue

It's old but still actual
https://gist.github.com/piotrekkaminski/54529dadb0bc01a62a2d

**Comment by sreichel** [comment]
Duplicate of #56 ???

**Comment by diglin** [comment]
possible but the solution is provided

**Comment by sreichel** [comment]
@diglin it seems to be fixed in 1.9.3.0 ... can you test it, too?

**Comment by diglin** [comment]
@sreichel sorry, unfortunately I'm not anymore on this topic, it was few months ago I send the feedback.
