### ISSUE TITLE
Deleting reviews leaves orphan data in a database table

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1102]
This issue is related to **review_entity_summary** table in Magento database.

Just delete a review in Backend then check all tables related to review inside the database. All data are deleted except those from review_entity_summary table.

**Comment by fballiano** [comment]
You mean when deleting the last review of a product (or other entity)?

Because the review_entity_summary should just get updated with the count and average or the product ratings.

**Comment by ADDISON74** [comment]
You are correct in my case deleting a review won't update the product ratings. It is a Magento 1 not OpenLTS. I will check more in detail. If it is a bug in Magento 1 I will close the ticket.

**Comment by ADDISON74** [comment]
Please note if you delete ALL reviews **review_entity_summary** table won't be updated. A better implementation would be by deleting all reviews Magento should empty the table review_entity_summary data like starting from scratch.

**Comment by fballiano** [comment]
I've tried to implement a fix.

**Comment by ADDISON74** [comment]
I will close this issue. There is a fix tested by me here #1103.
