### ISSUE TITLE
Mirror the docs

### ISSUE THREAD

**Issue by loekvangool** [OpenMage/magento-lts#1106]
### Description (*)
The technical and user documentation seems to have been removed from Magento's site. Should we host a mirror and pivot it towards OpenMage?

**Comment by Flyingmana** [comment]
We have at least already the Repository.

https://github.com/OpenMage/devdocs-m1

If you can take over the hosting for it, this would be great

**Comment by fballiano** [comment]
I could host this on a small server I have, how would manage a domain/subdomain name?

**Comment by loekvangool** [comment]
S3 hosting might be just fine for this.  I've never done site hosting but looking at the prices, it should be cents per month.

**Comment by Flyingmana** [comment]
If anyone wants to sponsor S3 hosting for this, but please dont do it with private accounts, the cost could explode quite a bit there, especially when we start to change/improve the documentation and its more often uploaded.

a subdomain could be provided I guess, we do this already with https://demo.openmage.org/ which is sponsored bei Nexcess currently.

**Comment by fballiano** [comment]
could we just use https://devdocs-m1.github.io/ then?

**Comment by Flyingmana** [comment]
this could become complicated. the subdomain normally refers to the github organization. And repositories are just paths on this domain, not separate domains. So we only can have one Github Page per domain (which we use for the Website)

But, we do have companies who would sponsor the hosting for things like this.
I will check on one of them

**Comment by splendidinternet** [comment]
@Flyingmana 

o.k. - we'll do the hosting

**Comment by ADDISON74** [comment]
There were a PDF file named User Guide and many other nice things related to Magento 1 which were removed from official website. Disappointing to see how years of work have been thrown in the trash.

BTW I found the last sample database for Magento 1.9 on Nexcess website. We should point it to those who want playing with a full demo version.

**Comment by tmotyl** [comment]
Is the html or pdf version of the docs available somewhere to download already? I have a case where I need to share the REST api docs with the customer.
So if anybody have the rendered version It would be great to attach it here untill we have the domain set up. Thanks

**Comment by jouriy** [comment]
> Is the html or pdf version of the docs available somewhere to download already? 

- **Magento User Guide 1.9** (31.4MB), chapter 63 http://info2.magento.com/rs/magentosoftware/images/Magento_Community_Edition_User_Guide_v.1.9.pdf
- **Magento SOAP API Usage** (730kb) http://info2.magento.com/rs/magentosoftware/images/imagine2012-barcamp-magento-api.pdf
- Magento Community Edition User Guide, v 1.9.1 (11MB)  http://info2.magento.com/rs/magentosoftware/images/Magento_Community_Edition_User_Guide_Latest.pdf

**Comment by jouriy** [comment]
Extracted guides/m1x into https://jouriy.github.io/guides-m1x/

**Comment by dbachmann** [comment]
I've created a repo for the old magento 1 documentation. You can find it here https://dbachmann.github.io/m1-devdocs/
I could upload the documenation to one of my servers if needed.

**Comment by Flyingmana** [comment]
@dbachmann where did you find the source for this?

**Comment by splendidinternet** [comment]
@dbachmann @Flyingmana 

this ist live since september - but we did not wrote it in this issue

https://devdocs-openmage.org/guides/m1x/

**Comment by dbachmann** [comment]
@Flyingmana Well, you need archive.org, archivarix.com and an 10$ investment ;) 
I renamed this repo to m1-userguide. I hope I can recover more than the user guide this way.

**Comment by Flyingmana** [comment]
@dbachmann so was the GPL license part of what you did crawl, or did you add this afterwards?
Because I currently suspect we cant use it as OpenMage because of copyright issues. (the pages directly state copyright belongs to magento)

**Comment by dbachmann** [comment]
@Flyingmana I think the license was added automatically. I've deleted this file. Yes, we can't use it as OpenMage but we can refer to this.

**Comment by kiatng** [comment]
@dbachmann Thanks for the tip on archive.org. I found the [old doc on validation.js](https://web.archive.org/web/20080216073650/http://tetlaw.id.au/view/javascript/really-easy-field-validation/).

**Comment by Flyingmana** [comment]
then I will close this issue for now. as we have a working mirror of the docs
