### ISSUE TITLE
Mirror Magento 1 Marketplace extensions before they are removed from repo.magento.com?

### ISSUE THREAD

**Issue by astleyclarke** [OpenMage/magento-lts#1115]
### Description (*)

Magento 1 extensions were removed from the Magento Marketplace on 7th July 2020. They will be removed from `repo.magento.com` on August 6th 2020. 

Is there a way we can download some or all of them before this happens, and provide a mirror or an archive of them?

### Expected behavior (*)

A copy of all Magento 1 extensions to be available in some form.

### Benefits

Long-term archival of M1 extensions to ensure access to developers who need them after they're removed from Magento Marketplace.

**Comment by Flyingmana** [comment]
We have downloaded all modules which were available via connect to https://github.com/OpenMageModuleFostering

see Blog Post: https://www.openmage.org/2019/08/18/new-home-magento-connect-modules.html

We also have a (zip file) backup of all M1 modules which were available on the marketplace in May, which we will add to this Organization as soon as time allows (or someone has the time to write/extend the script for this)

**Comment by waynetheisinger** [comment]
@Flyingmana As well as the free modules you could also provide Magento module producers an advertising space for their Magento 1 modules that they are still selling and maintaining - you could run a OpenMage Marketplace in the same way that Magento ran Magento Marketplace and take a small commission to a revenue stream to support the project's expenses?

**Comment by Flyingmana** [comment]
@waynetheisinger this would indeed be great to have.
But it may be outside the scope of the project.

My personal opinion here is, its something a person or company from the community could/should step in, and we support them with this.

**Comment by waynetheisinger** [comment]
@Flyingmana perhaps Unirgy could be persuaded to provide a licence for their Marketplace extension and then each vendor could manage their own modules within the marketplace - then only the skin would have to be done by the project collaborators? (let's hope they are community spirited - @unirgy - what do you think?)

**Comment by Flyingmana** [comment]
Closing this, as we do have them mirrored, at least in the form of code.
