### ISSUE TITLE
Unable to place order after canceled order

### ISSUE THREAD

**Issue by drwilliams** [OpenMage/magento-lts#1116]
There is an error when placing an order when using a promo code that has been used on a canceled order. This is because when you cancel an order the times_used in salesrule_coupon_usage becomes zero and it tries to insert a new entry into the database. 

### Preconditions (*)

1. Using OpenMage 19.4.5

### Steps to reproduce (*)

1. Log in to a customer account
2. Place an order and use a promo code
3. Cancel the order
4. Try to place another order with the same promo code and you will get an error when submitting the order

### Expected result (*)

1. Order placed successfully

### Actual result (*)

1. Integrity constraint violation: 1062 Duplicate entry '10961-661' for key 'PRIMARY', query was: INSERT INTO `salesrule_coupon_usage` (`coupon_id`, `customer_id`, `times_used`) VALUES (\?, \?, \?) in /cache/lib/Zend/Db/Statement/Pdo.php:235

**Comment by VincentMarmiesse** [comment]
+1

**Comment by sreichel** [comment]
@all-contributors add @drwilliams bug
