### ISSUE TITLE
Randomly deleted records in catalog_product_link table

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1118]
Last year in September I discovered half of the records stored in **catalog_product_link** table were deleted. I am the only person who is accessing this website and the administrator of the dedicated server. 

I started to check almost every day the content of this table. In February, after 6 months the same thing happened, more than half of the records were deleted. Not a part for X to Y, just randomly. Today the same thing happened from a total of 2.400 records I found only 600. It wasn't a problem because I could restore the table contents from back up (catalog_product_link and catalog_product_link_attribute_int)

I checked the server logs especially mysql and there were no shutdown/restart of the SQL server, no errors on disk, no attempts to run sql injections.

Does anyone know how to approach this issue other than checking daily diff's of dump sql files for this table? Magento logs are enabled but I did not find any issue.

**Comment by kkrieger85** [comment]
First time I read about this problem. 

You could try to log if links will be deleted:
app/code/core/Mage/Catalog/Model/Resource/Product/Link.php:87

Please re-open this issue if you can provide information on how to reproduce this bug.
