### ISSUE TITLE
Uprading to OpenMage v20.x will have some problems with themes by Meigee

### ISSUE THREAD

**Issue by sptm92** [OpenMage/magento-lts#1122]
### Summary (*)

Themes by Meigee have some version checking parameters in frontend layout files, for setting specific templates or adding JS files for corresponding Magento versions.
The issue here is that in 2 of my cases, upgrading to OpenMage v20.0.1, _**/js/varien/product_options.js**_ was not added, so that on configurable product pages, console was full of errors regarding 
```JavaScript
var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
```
in catalog/product/view.phtml

### Examples (*)

in catalog.xml there are parts like this:
```xml
<action check_version="1">
  <if_version method="addJs" is="1.9.3.x">
    <script>varien/product_options.js</script>
  </if_version>
  <default method="setText"><text></text></default>
</action>
```
which fails on OpenMage v20.x, so nothing is added.

generaly in their local.xml of their themes there are some checks but there is a fallback, so i dont think that this will be a problem.. for example:
```xml
<action method="unsetChild"><name>catalog.compare.sidebar</name></action>
<block type="catalog/product_compare_sidebar" after="cart_sidebar" name="catalog.compare.sidebar">
  <action check_version="1">
    <if_version method="setTemplate" is="1.9.3.x">
      <template>catalog/product/compare/sidebar.phtml</template>
    </if_version>
    <if_version method="setTemplate" is="1.9.2.x">
      <template>catalog/product/compare/sidebar.phtml</template>
    </if_version>
    <default method="setTemplate">
      <template>1.9.1.x/catalog/product/compare/sidebar.phtml</template>
    </default>
  </action>
</block>
```

and some
```xml
<reference name="category.products">
  <action check_version="1">
    <if_version method="setTemplate" is="1.9.0.x">
      <template>1.9.0.x/catalog/category/view.phtml</template>
    </if_version>
    <if_version method="setTemplate" is="1.8.x.x">
      <template>1.9.0.x/catalog/category/view.phtml</template>
    </if_version>
    <if_version method="setTemplate" is="1.7.x.x">
      <template>1.7.x.x/catalog/category/view.phtml</template>
    </if_version>
    <default method="setTemplate">
      <template>catalog/category/view.phtml</template>
    </default>
  </action>
</reference>
```

it seems that there is some inconsistency in the logic.. some check if latest then default to old and some check for old and default to latest.. so there are some issues there..

### Proposed solution

The first problem should be solved by replacing the declaration with the default one:
```xml
<action method="addJs"><script>varien/product_options.js</script></action>
```
and for the others, every case may depend of the actual theme of Meigee and/or its version

**Comment by kkrieger85** [comment]
Looks like a typical integration task for a magento developer. 

Did you try to create a child-theme and fix this xml-issues in your own local.xml?

**Comment by sptm92** [comment]
> Looks like a typical integration task for a magento developer.
> 
> Did you try to create a child-theme and fix this xml-issues in your own local.xml?

yes i did fix them, im just reporting for future "known theme issues" etc..

**Comment by sptm92** [comment]
i found out that getVersionInfo() has not changed so it should match with 1.9.4.x.. 
case was that the theme is old..
