### ISSUE TITLE
When upgrading OpenMage via composer maintenance.flag is useless

### ISSUE THREAD

**Issue by ioweb-gr** [OpenMage/magento-lts#1124]
### Preconditions (*)
1. Any version

### Steps to reproduce (*)
1. Execute `touch maintenance.flag`
2. Execute `composer update`

### Expected result (*)
1. The system stays in maintenance mode while the system is updated

### Actual result (*)
1. Since all core files are being removed from the system, the site is showing the default apache/nginx error messages instead of the maintenance page. 

I'm not sure this can be fixed in OpenMage, I think it might require retouching the core composer installer to fix it. I'm opening as a discussion.

**Comment by gkaigk** [comment]
Warning Note: switching to AOEs composer installer will wipe your htdocs folder, it’s not just copying the magento-lts files. If you already symlink local.xml, media and var folder - then just go ahead.

**Comment by ioweb-gr** [comment]
For that reason I'm using https://github.com/Cotya/magento-composer-installer

**Comment by Flyingmana** [comment]
thats more a problem with the install/update methods.
In general I would say its not recommended to execute composer update/install on an environment which is currently served, as the temporary removed htaccess files can also cause security issues. 

But, do you know during which step the maintenance file is actually removed? And which installer you are using?

**Comment by ioweb-gr** [comment]
Actually maybe I explained incorrectly. The maintenance.flag file is not removed. It's the index.php file that's removed which is responsible for rendering the maintenance page after it checks for the flag file. 

So I'm not sure if it's possible to fix this on the installer level

**Comment by Flyingmana** [comment]
I see, it would be possible to ignore this file for the deployment, which on one side means you need to update this file yourself.
But also this file nearly never changes.

see for example: https://github.com/AydinHassan/magento-core-composer-installer#configuration

**Comment by ioweb-gr** [comment]
In some cases it's also modified for multisite installations so I think it would not be a bad idea to keep it there. 

I'm wondering if we could modify the order by which files are deleted or copied to the destinations so that index.php would be deleted last and copied first

**Comment by Flyingmana** [comment]
if you have it already modified, does it come from the core or a module?
the module installer has at least some kind of sort functionality 
https://github.com/Cotya/magento-composer-installer/blob/main/doc/Deploy.md#define-order-in-which-you-want-your-magento-packages-deployed

**Comment by fballiano** [comment]
hmm this is more of a bug of the composer plugin to install the core then something we can fix on our repo, for this reason I'm closing the issue.
