### ISSUE TITLE
Null bytes found in saving the PDF order

### ISSUE THREAD

**Issue by boesbo** [OpenMage/magento-lts#1125]
Null bytes are detected if you try to save the pdf Order. The "Varien_Io_File::_IsValidSource($src)" function blocks the upload because it finds null bytes (strpos($src, chr(0)) === false).

### Preconditions (*)
v1.9.4.x-dev

### Steps to reproduce (*)
```
// Get pdf.
$pdf = Mage::getModel('emailattachments/order_pdf_order')->getPdf([$order]);
$pdfName = 'order.pdf';
$baseDir = Mage::getBaseDir('tmp');
$filePath = $baseDir . DS . $pdfName;

$file = new Varien_Io_File();
$file->write($filePath, $pdf->render());
```

**Comment by maximehuran** [comment]
I have the same problem when I use Image API to create new product image sending the content in base64.

**Comment by sreichel** [comment]
@all-contributors add @boesbo bug
