### ISSUE TITLE
Magento 1.9.4 session error with PHP 7.2

### ISSUE THREAD

**Issue by himanshutecstub** [OpenMage/magento-lts#1127]
Summary
Use magento 1.9.4.2 which is working fine with PHP 7.0 and MySql 5.6 with Cm_RedisSession
Now upgrade PHP version to 7.2.31 and MySql 5.7 with same code. It's slow down and got many session error as below (Redis Version : 6.0.5) and in website shown Out of memory error.

Examples
`PHP Fatal error:  Uncaught Error: __clone method called on
    non-object in
    /app/code/core/Mage/Core/Model/Session/Abstract.php:214`
`Warning: Unknown: Cannot call session save handler in a recursive
    manner  in Unknown on line 0`
`Warning: Unknown: Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions)  in Unknown on line 0`
`Warning: Cannot use a scalar value as an array  in /app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 446`
`Warning: Cannot use a scalar value as an array  in /lib/Varien/Object.php on line 270`

Also use latest Cm_Cache_Backend_Redis version for redis cache and also try to set zend.enable_gc = On.
How resolve that problem. is there any other settings required?

**Comment by seansan** [comment]
We are still seeing this error

2020-09-02T20:02:13+00:00 ERR (3): Warning: Unknown: Cannot call session save handler in a recursive manner  in Unknown on line 0
2020-09-02T20:02:13+00:00 ERR (3): Warning: Unknown: Failed to write session data using user defined save handler. (session.save_path: /tmp)  in Unknown on line 0

/tmp has rights drwxrwxrwt

To move forward on this 
- could we better log the location "where" this goes wrong?
- can we improve logging to know "what" cannot be written?

At least then we are moving forward to identyfing a fix 

Must be some config ... but we dont know `which` config

#156

**Comment by seansan** [comment]
Maybe add "Failed to write session data using user defined save handler" the error to the tile

**Comment by seansan** [comment]
See https://github.com/OpenMage/magento-lts/issues/906
