### ISSUE TITLE
Zend_Locale_Format::isNumber throws notice for float values

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#1134]
### Preconditions (*)

1. OpenMage 1.9.4.5
2. PHP 7.4
3. adding 

### Steps to reproduce (*)

1. call Neuca_Base_Wishlist_IndexController cartAction, which calls `_processLocalizedQty` and then `$this->_localFilter->filter((float)$qty);`

### Expected result (*)

1. OpenMage doesn't throw a notice on PHP 7.4

On one hand Zend should check input variable type and don't process it if its already a number,
on the other hand OpenMage should not pass a float to `filter` in line:
https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Wishlist/Controller/Abstract.php#L62

The casting to float was added in Magento 1.7. This cast made the whole zend filtering obsolete, so it can be removed in my POV.

### Actual result (*)

1. OpenMage throws error when float value is being passed to Zend_Locale_Format::is_number
```
Notice: Trying to access array offset on value of type float  in htdocs/lib/Zend/Locale/Format.php on line 523

#0 htdocs/lib/Zend/Locale/Format.php(523): mageCoreErrorHandler(8, 'Trying to acces...', '..', 523, Array)
#1 htdocs/lib/Zend/Filter/LocalizedToNormalized.php(100): Zend_Locale_Format::isNumber(1, Array)
#2 
```
The notice is being thrown because Zend tries to access float value as array in line:
```
if (!empty($input) && ($input[0] == $symbols['decimal'])) {
```

**Comment by seansan** [comment]
+1

Do we know if there are more php 7.4 bugs? Or could it be he recommended version?

The readme currently advises minimal versions .. but can maybe also show the *advised* and thus last best working version

https://github.com/OpenMage/magento-lts#requirements

**Comment by seansan** [comment]
Is this something to add in 20.0.x release line?

**Comment by sreichel** [comment]
> Is this something to add in 20.0.x release line?

IMHO .... as long there is no clear release strategy, it belongs to 1.9.4.x.

**Comment by colinmollenhour** [comment]
So remove the cast or remove the filter method and just assign the cast value? Seems like in 9 years nobody has used international formats for specifying their wishlist quantity so it's hardly worth discussing.. My guess is that fuzzers caused all sorts of PHP warnings with weird inputs because it tries to parse the input as a date if it is not a number. My vote would be to just remove the filtering and assume the input must be able to be cast since that has worked for 9 years.

**Comment by fballiano** [comment]
Can't create a PR at the moment but I'd fix it this way:

```
--- a/app/code/core/Mage/Wishlist/Controller/Abstract.php
+++ b/app/code/core/Mage/Wishlist/Controller/Abstract.php
@@ -51,15 +51,11 @@ abstract class Mage_Wishlist_Controller_Abstract extends Mage_Core_Controller_Fr
      *
      * @param string $qty
      * @return float|int|null
+     * @deprecated Deprecated since version 20.0.8
      */
     protected function _processLocalizedQty($qty)
     {
-        if (!$this->_localFilter) {
-            $this->_localFilter = new Zend_Filter_LocalizedToNormalized(
-                array('locale' => Mage::app()->getLocale()->getLocaleCode())
-            );
-        }
-        $qty = $this->_localFilter->filter((float)$qty);
+        $qty = (float)$qty;
         if ($qty < 0) {
             $qty = null;
         }
diff --git a/app/code/core/Mage/Wishlist/controllers/IndexController.php b/app/code/core/Mage/Wishlist/controllers/IndexController.php
index 173933bda..708a7002c 100644
--- a/app/code/core/Mage/Wishlist/controllers/IndexController.php
+++ b/app/code/core/Mage/Wishlist/controllers/IndexController.php
@@ -508,8 +508,8 @@ class Mage_Wishlist_IndexController extends Mage_Wishlist_Controller_Abstract
                 $qty = 1;
             }
         }
-        $qty = $this->_processLocalizedQty($qty);
-        if ($qty) {
+        $qty = (float)$qty;
+        if ($qty and $qty>0) {
             $item->setQty($qty);
         }
```

deprecating the _processLocalizedQty method (also removing the filtering, which is useless since there's the cast anyway) and removing the call to _processLocalizedQty from the Mage_Wishlist_IndexController

what do you think?
