### ISSUE TITLE
Github Action Labeler Bot

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#1140]
> @sv3n i remember you did something with github actions recently, github did add something new, which can execute actions on PullRequests from the point of the repository and not from the PullRequest creator. They did solve the security concerns by limiting the executed code to the base from where the branch was forked from.
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

... just a reminder for me to convert #1101 back to #1050 ...

**Comment by sreichel** [comment]
@colinmollenhour closed with 0aec67d5d25b45a3c3f8d30f208c84e3b7c2b4e9?

**Comment by colinmollenhour** [comment]
@sreichel I'm not sure if it is working yet, no new PRs have been pushed since the update.

**Comment by sreichel** [comment]
@colinmollenhour config file name needs to be changed from `labels.yml` to `labeler.yml`

**Comment by colinmollenhour** [comment]
Ahh, thanks @sreichel. Renamed in 1c6ca94b88

**Comment by sreichel** [comment]
@colinmollenhour thansk, seems to work.
