### ISSUE TITLE
Notice: A non well formed numeric value encountered  in Mage/Catalog/Model/Layer/Filter/Price.php on line 212

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1148]
We see a Notice: A non well formed numeric value encountered  in app/code/core/Mage/Catalog/Model/Layer/Filter/Price.php on line 212

I read somewhere that it can be a space after the number? Havent been able to debug this as it occurs only seldom - 

is there anything we can do about it here in the method below? As it does not seem to present errors elsewhere

### Preconditions (*)
?

### Steps to reproduce (*)

2020-08-17T12:03:02+00:00 ERR (3): Notice: A non well formed numeric value encountered  in app/code/core/Mage/Catalog/Model/Layer/Filter/Price.php on line 212
2020-08-17T12:03:06+00:00 ERR (3): Notice: A non well formed numeric value encountered  in app/code/core/Mage/Catalog/Model/Layer/Filter/Price.php on line 212

```
    /**
     * Prepare text of range label
     *
     * @param float|string $fromPrice
     * @param float|string $toPrice
     * @return string
     */
    protected function _renderRangeLabel($fromPrice, $toPrice)
    {
        $store      = Mage::app()->getStore();
        $formattedFromPrice  = $store->formatPrice($fromPrice);
        if ($toPrice === '') {
            return Mage::helper('catalog')->__('%s and above', $formattedFromPrice);
        } elseif ($fromPrice == $toPrice && Mage::app()->getStore()->getConfig(self::XML_PATH_ONE_PRICE_INTERVAL)) {
            return $formattedFromPrice;
        } else {
            if ($fromPrice != $toPrice) {
LINE 212                $toPrice -= 0.01;
            }
            return Mage::helper('catalog')->__('%s - %s', $formattedFromPrice, $store->formatPrice($toPrice));
        }
    }
```

### Expected result (*)
- Log which product? Or what the error values are?

### References
https://stackoverflow.com/questions/51003775/a-non-well-formed-numeric-value-encountered-error-in-php

**Comment by seansan** [comment]
possible fix for this exotic situation is?                 $toPrice = (float)$toPrice;

**Comment by Flyingmana** [comment]
yeah, casting $toPrice to float seems to be the best solution here. The result of the `$toPrice -= .01;` would be a float anyway, so casting it specificly to float before cant do any harm.

**Comment by fballiano** [comment]
I've created a small PR for this

**Comment by fballiano** [comment]
(but I wasn't able to reproduce the problem anyway

**Comment by fballiano** [comment]
fixed thru https://github.com/OpenMage/magento-lts/pull/2225
