### ISSUE TITLE
Running a PHP code sniff against fresh install for PHP compatibility with PHP 7 shouldn't find errors.

### ISSUE THREAD

**Issue by waynetheisinger** [OpenMage/magento-lts#1157]
### Description (*)
In migrating to OpenMage I ran a PHP code sniff for PHP7 compatibility - I was expecting to need to patch third-party modules. However, because PHP7 is the minimum requirement I wasn't expecting core libraries to have errors. 

There were hundreds of Mcrypt warnings but I notice you are using lib/mcryptcompat/mcrypt.php to polyfill mcrypt so this is a false positive.

The link below contains other errors. They are mostly coming from PEAR and Zend. It is possible/probable that the Mage code isn't calling the methods with the problems.

[php7sniffs_core.txt](https://github.com/OpenMage/magento-lts/files/5109246/php7sniffs_core.txt)

#### Feature request
1. If the core code isn't calling the methods with errors, then it would be good to provide a set of custom rules so that PHP code sniff ignores those methods.
2. If the core code is calling the method, then we should either fork the library code, ie the project takes over development of the library for ongoing fixes, or patch the code using something like https://github.com/cweagans/composer-patches

### Expected behavior (*)
Running a PHP code sniff against fresh install for PHP compatibility with PHP 7 shouldn't find errors.

### Benefits
PHP code sniff can be part of a CI/CD pipeline 
Future stability will be more reliable when adding third-party modules

**Comment by Flyingmana** [comment]
by now we got a lot further with php compatibility, and use various tools to check the code statically. Also we have a lot of users with current php versions.

Therefore I close this issue for now, feel free to open a new issue, if you find further issues, (or reopen here, if you want us to also add this specific codesniff)

**Comment by sreichel** [comment]
This is issue is still valid.

We have a PHP compatibility check, but it does not fail on error.

Just check current output from github action workflow.

**Comment by sreichel** [comment]
https://github.com/OpenMage/magento-lts/actions/runs/6429470742/job/17458623872?pr=3582
