### ISSUE TITLE
Use read adapter for describeTable

### ISSUE THREAD

**Issue by joshua-bn** [OpenMage/magento-lts#1158]
### Summary (*)
In many places it does `$this->_getWriteAdapter()->describeTable()`. This causes extra queries to the master. We should expect that DDL changes have propagated to the slaves by the time we are doing something like getting product data.

### Examples (*)
![image](https://user-images.githubusercontent.com/53793523/90909951-914b6300-e3a4-11ea-9cac-70c7d5d8cb99.png)

### Proposed solution
Change `_getWriteAdapter()->describeTable()` calls to `getReadAdapter()->describeTable()`

**Comment by joshua-bn** [comment]
What investigation and feedback is needed @ADDISON74 ?

**Comment by ADDISON74** [comment]
With all due respect, but you probably didn't notice that the whole Issue section went through a triage. You created a post in the past I marked that other opinions are welcome and if changes are needed, it would have been marked with PR requested label.

**Comment by ADDISON74** [comment]
@joshua-bn - I noticed that you had very little activity on GitHub in the last year. Please check this explanation https://github.com/OpenMage/magento-lts/discussions/2374.

**Comment by sreichel** [comment]
@all-contributors add @joshua-bn bug
