### ISSUE TITLE
Set log level from config

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#1163]
### Description (*)

Currently you just can enable/disable logging (system.log/exception.log -  or force logging), without any controll about log level. 

`Mage::log()` uses `Zend_Log` ...

>     const EMERG   = 0;  // Emergency: system is unusable
>     const ALERT   = 1;  // Alert: action must be taken immediately
>     const CRIT    = 2;  // Critical: critical conditions
>     const ERR     = 3;  // Error: error conditions
>     const WARN    = 4;  // Warning: warning conditions
>     const NOTICE  = 5;  // Notice: normal but significant condition
>     const INFO    = 6;  // Informational: informational messages
>     const DEBUG   = 7;  // Debug: debug messages

It would be nice to set a minimum level to get rid of debug infos, but still get warnings/errors logged ...

### Expected behavior (*)

Only log what you're interessted in.

### Benefits

Reduce logs to minimum.

**Comment by elidrissidev** [comment]
I'm taking this!

**Comment by ADDISON74** [comment]
This would be a helpful addition to OM. If anyone will implement it I hope the levels will be changed in Backend.

**Comment by elidrissidev** [comment]
@ADDISON74 Yes, of course! I'm adding them with the other log settings.
