### ISSUE TITLE
Catalog price rule disappears at night

### ISSUE THREAD

**Issue by nicobond** [OpenMage/magento-lts#1166]
### Preconditions (*)

1. OpenMage version 19.4.3
2. PHP 7.x

### Steps to reproduce (*)

1. Add a simple catalog price rule, set rule for any customer group, set a starting date and an ending date and apply it
2. Add a cronjob to apply rule every day (once a day)
3. Check after midnight if rule is applied and product prices are modified as set in the rule

### Expected result (*)

1. I expect that product prices are correctly set in every hour of the day and night (h24)

### Actual result (*)

1. After midnight special prices are not displaying in site and catalog price rules are not correctly applied

**Comment by trabulium** [comment]
Line 121, try changing:

      $timestamp = $coreDate->gmtTimestamp('Today');

to

      $timestamp = Mage::app()->getLocale()->date(null, null, null,true)->get(Zend_Date::TIMESTAMP);

I don't have time to do a PR atm.

**Comment by ADDISON74** [comment]
Did anyone have time to check the solution provided here and push a PR?

**Comment by ADDISON74** [comment]
@nicobond - the solution provided above solved your issue?

**Comment by fballiano** [comment]
I've created PR https://github.com/OpenMage/magento-lts/pull/2189 to fix this
