### ISSUE TITLE
Mage_Core_Model_Abstract is not setting isDeleted flag

### ISSUE THREAD

**Issue by midlan** [OpenMage/magento-lts#1174]
At this moment, there is no way to determine that object has been deleted or not (without accessing database). I would be thankfull if someone can confirm this by testing my example:

### Steps to reproduce (*)
```php
Mage::register('isSecureArea', true); //override to delete from non-admin store

$product = Mage::getModel('catalog/product')->load($productId);

$product->delete();

var_dump($product->isDeleted());
```

### Expected result (*)
I would expect the result to be `true`.

### Actual result (*)
Actually it is `false`.

**Comment by henrykbrzoska** [comment]
Wrong way thinking.
You need set
`$model->isDeleted(true)->save();
`
than in every save() finction is something like:

```
        if ($object->isDeleted()) {
            return $this->delete($object);
        }
```

**Comment by midlan** [comment]
@henrykbrzoska Thank you, I see now it is here: `Mage_Core_Model_Abstract::save`

But my problem is still present. I cannot determine if object was deleted by any other method than trying reload it from database.

**Comment by joshua-bn** [comment]
You would do `$object->isDeleted()` to check if it is deleted.

**Comment by midlan** [comment]
@joshua-bn no `$object->isDeleted()` not work like that, I though that too (my initial post).

**Comment by henrykbrzoska** [comment]
Problematic is name of this field - isDeleted() is wrong
should be toDelete(), but changing things like this will be very problematic

**Comment by midlan** [comment]
@henrykbrzoska I agree. Do not rename something what is working, only because it's wrongly named.

I am wondering about solutions:
1. First what came to my mind is to add call `$this->isDeleted(true)` inside `Mage_Core_Model_Abstract::delete` method, but it won't help, because with that solution I wouldn't know if someone only set the flag from outside, or the object was actually deleted by `delete()` method. Also BC issues. Screw it.
2. Create new flag and method for it, but there is also issue. Since delete is done in fact in resource and resource can work only with public methods of object, someone can call the new public method without actually deleting the object.  Putting the call to the new method inside the `Mage_Core_Model_Abstract::delete` method is not solution either, because someone could go and call `$obj->getResource()->delete($obj);`

At this moment I don!t see any existing solution and even no other way to reliably implement it. I will keep the issue open few weeks, maybe someone can help.
