### ISSUE TITLE
Error in the "_IsValidSource" method in Varien/Io/File.php

### ISSUE THREAD

**Issue by felipegomesdev** [OpenMage/magento-lts#1178]
Hello.

After this change is part of the code (https://github.com/OpenMage/magento-lts/pull/966)

The SOAP API Feature of creating a product image has stopped working. Look [documentation](https://r-martins.github.io/m1docs/guides/m1x/api/soap/catalog/catalogProductAttributeMedia/catalog_product_attribute_media.create.html)

Well, the whole image has a null value. For example:
```php
$src = file_get_contents("https://pbs.twimg.com/media/EelBMRwXsAEcrM9.png");

if (strpos($src, chr(0)) === false){
    echo "success...";
}else {
    echo "error...";
}
```
Therefore, it is not possible to pass the _IsValidSource method in Varien/Io/File.php

Same problem at https://github.com/OpenMage/magento-lts/issues/1125

**Comment by sreichel** [comment]
@all-contributors add @felipegomesdev bug
