### ISSUE TITLE
Install from scratch, ends up in a magento survey for last step - should be eliminated

### ISSUE THREAD

**Issue by ProxiBlue** [OpenMage/magento-lts#1180]
Simply install a brand new instance.

Last step is a survey

![Selection_999(037)](https://user-images.githubusercontent.com/4994260/92120688-f0d95200-ee2b-11ea-8d40-aafc844e1225.png)

**Comment by colinmollenhour** [comment]
Good catch. Can you submit a PR for removing it? Replacing it with a form to sign up for our newsletter would be even better. (same as on the homepage)

**Comment by ProxiBlue** [comment]
Will be in a bit of time.

Have 3 major deadlines for different clients.

**Comment by ProxiBlue** [comment]
Been a while, and I today installed a openmage from scratch, using web installer, and the survey form was not present after that install, so i think someone had handled this.
