### ISSUE TITLE
Can we update all minor and advised version for redis 6? / mysql 8? / php 7.4 in readme?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1188]
### Summary (*)
Can we update all minor and advised version for redis / mysql / php in readme?

I think we should aim at
- Mysql 8
- Redis 6
- Php 7.4

Are we there yet? What are the live examples - people running this?

### Proposed solution
- Mysql 8 or 5.7 latest
- Redis 6
- Php 7.4

Please add PHP tag + core systems / setup tag

**Comment by fballiano** [comment]
question: is redis 6 supported?

i think php/mysql versions are already updated in the read so maybe we can close this issue?

**Comment by colinmollenhour** [comment]
Yes Redis 6 will work. I think any version of Redis since the time the Redis backends were first added.. many years ago at this point. :) I doubt they'll ever break BC until they launch an entirely new protocol.
