### ISSUE TITLE
Fix the "$_FILES array is empty" exception when assiging products to a category or creating a category with the XMLRPC-API..

### ISSUE THREAD

**Issue by digitalpianism** [OpenMage/magento-lts#1190]
### Preconditions (*)

1. 20.0.2
2.

### Steps to reproduce (*)

1. Assign products to a category using the XMLRPC-API
2.

### Expected result (*)

1. No exception thrown.
2. Category updated

### Actual result (*)

1. By looking at the logs we can see the following exception was being thrown:

> exception 'Exception' with message '$_FILES array is empty' in /path/to/magento/includes/src/Varien_File_Uploader.php:461
> Stack trace:
> #0 /path/to/magento/includes/src/Varien_File_Uploader.php(149): Varien_File_Uploader->_setUploadFileId('image')
> #1 /path/to/magento/includes/src/Mage_Catalog_Model_Category_Attribute_Backend_Image.php(57): Varien_File_Uploader->__construct('image')
> #2 [internal function]: Mage_Catalog_Model_Category_Attribute_Backend_Image->afterSave(Object(Mage_Catalog_Model_Category))
> #3 /path/to/magento/includes/src/__default.php(39967): call_user_func_array(Array, Array)
> #4 /path/to/magento/includes/src/__default.php(40958): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterSa...', Array)
> #5 /path/to/magento/includes/src/Mage_Catalog_Model_Resource_Category.php(235): Mage_Eav_Model_Entity_Abstract->_afterSave(Object(Mage_Catalog_Model_Category))
> #6 /path/to/magento/includes/src/__default.php(40434): Mage_Catalog_Model_Resource_Category->_afterSave(Object(Mage_Catalog_Model_Category))
> #7 /path/to/magento/includes/src/__default.php(5593): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Catalog_Model_Category))
> #8 /path/to/magento/includes/src/Mage_Catalog_Model_Category_Api.php(528): Mage_Core_Model_Abstract->save()
> #9 [internal function]: Mage_Catalog_Model_Category_Api->removeProduct(23, '2743')
> #10 /path/to/magento/includes/src/Mage_Api_Model_Server_Handler_Abstract.php(292): call_user_func_array(Array, Array)
> #11 [internal function]: Mage_Api_Model_Server_Handler_Abstract->call('[removed]', 'category.remove...', Array)
> #12 /path/to/magento/includes/src/Zend_Server_Abstract.php(232): call_user_func_array(Array, Array)
> #13 /path/to/magento/includes/src/Zend_XmlRpc_Server.php(599): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
> #14 /path/to/magento/includes/src/Zend_XmlRpc_Server.php(337): Zend_XmlRpc_Server->_handle(Object(Zend_XmlRpc_Request_Http))
> #15 /path/to/magento/includes/src/Mage_Api_Model_Server_Adapter_Xmlrpc.php(105): Zend_XmlRpc_Server->handle()
> #16 /path/to/magento/includes/src/Mage_Api_Model_Server.php(84): Mage_Api_Model_Server_Adapter_Xmlrpc->run()
> #17 /path/to/magento/app/code/core/Mage/Api/controllers/XmlrpcController.php(39): Mage_Api_Model_Server->run()
> #18 /path/to/magento/includes/src/__default.php(13333): Mage_Api_XmlrpcController->indexAction()
> #19 /path/to/magento/includes/src/__default.php(17589): Mage_Core_Controller_Varien_Action->dispatch('index')
> #20 /path/to/magento/includes/src/__default.php(17180): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
> #21 /path/to/magento/includes/src/__default.php(19672): Mage_Core_Controller_Varien_Front->dispatch()
> #22 /path/to/magento/app/Mage.php(640): Mage_Core_Model_App->run(Array)
> #23 /path/to/magento/index.php(80): Mage::run('brillen', 'website')
> #24 {main}

2. Category updated

### Extra information

Source: https://stackoverflow.com/questions/9700611/exception-raised-in-varien-file-uploader-when-using-xmlrpc-to-modify-categories

Official fix from Magento 2 before it was entirely refactored: https://github.com/magento/magento2/blob/d2d10e61db705f30fa1dd7a8842263f0d67aec8a/app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php

I already have a fix for that, will do a PR soon.

**Comment by sreichel** [comment]
@all-contributors add @digitalpianism bug
