### ISSUE TITLE
Fix timestamp not set properly for catalogrule on non GMT install.

### ISSUE THREAD

**Issue by digitalpianism** [OpenMage/magento-lts#1191]
### Preconditions (*)

1. 20.0.2
2. GMT+5 install

### Steps to reproduce (*)

1. Create a catalog rule that applies 15% off all products
2.

### Expected result (*)

1. Works fine.
2.

### Actual result (*)

1. Stops working after midnight.
2.

### Extra information

When Magento displays products on frontend, it checks if there are catalog rules for this date. And the date used for this check is our local, so in our case GMT+5. However, when catalog rules are being applied, it uses GMT date. So that means that we aren't able to apply rules until 5 AM.

Source / fix: https://stackoverflow.com/questions/25280095/magento-catalog-price-rule-disappears-at-night

Fix is ready, will do a PR soon.

**Comment by sreichel** [comment]
https://github.com/OpenMage/magento-lts/pull/1199#issuecomment-1149888889
