### ISSUE TITLE
Using "group by" in a backend grid file will display a wrong count.

### ISSUE THREAD

**Issue by digitalpianism** [OpenMage/magento-lts#1195]
### Preconditions (*)

1. 20.0.2
2. Have a module that implements a "GROUP BY" in a backend grid or a script (see below).

### Steps to reproduce (*)

1. Create the following script and see the result:
```
<?php

require_once 'app/Mage.php';

Mage::app();

$collection = Mage::getResourceModel('sales/order_collection');
$collection->getSelect()->group("customer_group_id");

echo $collection->getSize();
```
2.

### Expected result (*)

1. Number of rows (total count) matches the group by clause (lets say if you have orders from two customer groups, you should get 2 as a result)

### Actual result (*)

1. Number of rows (total count) is wrong: it gives you the total number of entries without taking the group by.

### Extra information

Source: http://ka.lpe.sh/2012/01/05/magento-wrong-count-in-admin-grid-when-using-group-by-clause-overriding-lib-module/

Fix already available, will do a PR soon.

**Comment by dbachmann** [comment]
Well, I fixed this here https://github.com/OpenMage/magento-lts/pull/1404
