### ISSUE TITLE
Merge AOE ClassPathCache into this repo

### ISSUE THREAD

**Issue by digitalpianism** [OpenMage/magento-lts#1196]
### Description (*)

Replace the Varien_Autoloader to be able to cache the exact location of files when they are being looked up.

### Expected behavior (*)

No change in the behavior

### Benefits

Performance improvement

### Additional information

The repo is located here: https://github.com/AOEpeople/Aoe_ClassPathCache

The details about the implementation can be found here: http://fbrnc.net/blog/2012/09/magento-class-path-cache#hello

**Comment by Flyingmana** [comment]
I did look into this years ago, but had the impression activating the opcache.enable_file_override did make this obsolete.
https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.enable-file-override

**Comment by tmotyl** [comment]
From my experience the the way Magento find classes (checks multiple folders for file existance on each request) is still something worth optimizing.
However instead of the classpath cache I think the effort should  first go to to check if this can't  be done by improving composer support, so once composer has run (especially with optimize autolad switch) Magento will not look for files in some folders

**Comment by tmotyl** [comment]
@Flyingmana does enable_file_override helps speeding up cases where script check for a file existence an the file is not there?

**Comment by Flyingmana** [comment]
it does cache the file_exists() call, so yes.

Iam also supporting the case of having composer handling autoloading in the future (together with outsourcing the code in /lib/ into own packages/dependencies )

**Comment by digitalpianism** [comment]
Agreed with both of you.

To be totally transparent, I'm actually using this on my websites to avoid the following Warning being thrown when a file is missing:

`Warning: include(The/Class/To/Be/Loaded.php): failed to open stream: No such file or directory`

As @Vinai explains in this article: https://www.webguys.de/magento-1/tuerchen-11-the-magento-autoloader-and-external-libraries

Magento does not behave correctly in that type of situation, quoting:

> Autoloaders should not trigger errors or exceptions if the class file does not exist.
This was even included as a requirement in the recently released PSR-4 recommendation 

And Magento error handle will thrown an exception on any warning or error if dev mode is enabled.

I strongly suggest looking at Vinai's article. In my case I simply reused the Varien_Autoload class from AOE module (without the rest of it) and it was enough for me.

**Comment by Flyingmana** [comment]
Iam pretty sure we did fix this kind of error in openmage, as it caused issues with all the class_exist calls which possibly happen in libraries.


ok, not really fixed, the official php 7.2 patch did silence it
https://github.com/OpenMage/magento-lts/blame/af99bb3c4b0e2328409a02899b3f50d9e5bbe275/lib/Varien/Autoload.php#L94

**Comment by digitalpianism** [comment]
@Flyingmana haha that almighty @ operator always kills me. Well, I guess once its fixed and if everyone agress we can close this issue.
