### ISSUE TITLE
Replacement of mcrypt and usage of mcryptcompat in Magento 1.9.4.x and 20.x (mcrypt is deprecated)

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#1211]
Getting some mcrypt warnings after I pulled 20.x yesterday we are on php 7.2.33

Am I missing something?

Deprecated: Function mcrypt_module_open() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 74
Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 83
Deprecated: Function mcrypt_create_iv() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 83
Deprecated: Function mcrypt_enc_get_key_size() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 87
Deprecated: Function mcrypt_generic_init() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 94
Deprecated: Function mdecrypt_generic() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 130
Deprecated: Function mdecrypt_generic() is deprecated in public_html/lib/Varien/Crypt/Mcrypt.php on line 130

Funny. I am missing these files and this code in latest 20.x pull ... https://github.com/OpenMage/magento-lts/commit/ce5c2026e4f23add68f5615db3b8839b60e84b4d

https://github.com/OpenMage/magento-lts/commit/ce5c2026e4f23add68f5615db3b8839b60e84b4d

**Comment by seansan** [comment]
OK I have learnt some things and I think it is good to share here; also 1 remaining question then this issue can be closed ;)

**Learnings**

- mcrypt is deprected as of php 7.2; although it can still be loaded via ini files
- to find out if mcrypt via php is used, use this command `php --ini | grep mcrypt`
- it can also be installed via pecl as a module

Since Magento 19.4.x with php 7.2 support the phpseclib lib and mcryptcompat methods have been introduced as a fall back for the deprecation of mcrypt. Important to know is that `mcryptcompat` will only be used if you disable mcrypt via your ini settings and restart php. Otherwise mcryptcompat will not be used. Btw mcryptcompat is required in the header lines of app/mage.php. 

**Fixing it**

- you can stop some of the deprecated messages by adding `error_reporting(0);` to the top of `lib/Varien/Crypt/Mcrypt.php`
- you can start using mcryptcompat by disabling mcrypt via the ini files
- you can install openssl, although this resulted in some encoding/decoding errors with paypal and PSP's https://github.com/OpenMage/magento-lts/pull/506

After disabling mcrypt via the php ini files we saw Magento falls back on mcryptcompat. Mcryptcompat sources can be found here https://github.com/phpseclib/mcrypt_compat and phpseclib3 here https://github.com/phpseclib/phpseclib

**Last problem**

However we are now running into this error which is strange because we can see it is there in phpseclib. How would I go about fixing this error? `Uncaught Error: Class 'phpseclib3\Crypt\Blowfish' not found in lib/mcryptcompat/mcrypt.php:307`

PHP Fatal error:  Uncaught Error: Class 'phpseclib3\Crypt\Blowfish' not found in lib/mcryptcompat/mcrypt.php:307
Stack trace:
#0 lib/mcryptcompat/mcrypt.php(1251): phpseclib_mcrypt_module_open('blowfish', '', 'ecb', '')
#1 lib/Varien/Crypt/Mcrypt.php(77): mcrypt_module_open('blowfish', '', 'ecb', '')
#2 app/code/core/Mage/Core/Model/Encryption.php(174): Varien_Crypt_Mcrypt->init('0d5a5169c64edaa...')
#3 app/code/core/Mage/Core/Model/Encryption.php(198): Mage_Core_Model_Encryption->_getCrypt()
#4 app/code/core/Mage/Core/Helper/Data.php(242): Mage_Core_Model_Encryption->decrypt('FltGPeVKbgKAPZo...')
#5 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(378): Mage_Core_Helper_Data->decrypt('FltGPeVKbgKAPZo...')
#6 app/code/community/Ebizmarts/MailChimp/Helper/Data.ph in lib/mcryptcompat/mcrypt.php on line 307


![image](https://user-images.githubusercontent.com/652395/94733592-4b50ca00-0368-11eb-8916-17c815d3cada.png)

**Comment by joshua-bn** [comment]
@seansan do you find any performance changes between using the two?

**Comment by seansan** [comment]
Not tested. But would be msecs I guess

**Comment by colinmollenhour** [comment]
I think someone tested at some point and of course it depends on how many times you call it but it wasn't insignificant. Could you just disable E_DEPRECATED in production?

**Comment by seansan** [comment]
>> Could you just disable E_DEPRECATED in production?

What do you mean?

**Comment by joshua-bn** [comment]
Use the PECL mcrypt lib and disable E_DEPRECATED

**Comment by colinmollenhour** [comment]
> > Could you just disable E_DEPRECATED in production?
> What do you mean?

Set the `error_reporting` value to not show `E_DEPRECATED`. For example this is the default php.ini:

```
; Development Value: E_ALL
; Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
; http://php.net/error-reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

Stated differently: just because there is a deprecation warning doesn't mean you have to immediately cease using the code, you can just ignore the warning.. :)

**Comment by seansan** [comment]
yeah we did that; but I still saw the error warning sometimes, I think if
certain function calls were made directly in the original php code
