### ISSUE TITLE
Admin not accessible after instaling magento-lts

### ISSUE THREAD

**Issue by bojandavkov** [OpenMage/magento-lts#1212]
After upgrading of my latest 1.9 magento to OpenMage/magento-lts my admin is not accessible. This is the error i`ve got. Is this some know error?

 Fatal error: Uncaught Error: Call to undefined method Mage_Core_Model_App::testCache() in /data/web/public/app/code/core/Mage/Core/Model/Layout/Update.php:252 Stack trace: #0 /data/web/public/app/code/core/Mage/Core/Model/Layout/Update.php(284): Mage_Core_Model_Layout_Update->saveCache() #1 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Action.php(316): Mage_Core_Model_Layout_Update->load() #2 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Action.php(261): Mage_Core_Controller_Varien_Action->loadLayoutUpdates() #3 /data/web/public/app/code/core/Mage/Adminhtml/Controller/Action.php(290): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true) #4 /data/web/public/app/code/core/Mage/Adminhtml/controllers/DashboardController.php(40): Mage_Adminhtml_Controller_Action->loadLayout() #5 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Adminhtml_DashboardController->indexAction() #6 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): in /data/web/public/app/code/core/Mage/Core/Model/Layout/Update.php on line 252

**Comment by bojandavkov** [comment]
not an issue

**Comment by Adel-Magebinary** [comment]
This still happens btw. might need to open this again.

**Comment by fballiano** [comment]
you were probably upgrading from a very old magento version with a "php7 compatibility module" installed or "app/code/local/Mage" overridden files.

**Comment by ADDISON74** [comment]
Inchoo module should be disabled in /app/etc/modules/. Also clear the content for /var/cache/ directory. I did a test for an M1924 and I deleted all application files with a few exceptions then I upload OpenLTS files. Nothing happened and the databases what updated with some columns for some tables.
