### ISSUE TITLE
Admin theme header issues

### ISSUE THREAD

**Issue by AlterWeb** [OpenMage/magento-lts#1214]
### Preconditions (*)

1. OpenMage 19.4.7

### Steps to reproduce (*)

1. Go to the admin
2a. Have design/head/demonotice set to 1 
2b. Resize your screen

### Expected result (*)

1. Everything looks good
2. The menu is fully visible

### Actual result (*)

1. Menu is not lined out properly

![Screenshot from 2020-09-17 16-39-30](https://user-images.githubusercontent.com/12827587/93486396-6f41f380-f904-11ea-9a66-ce68a6e58509.png)

2. Menu items disappear behind search on smaller screens:

![Screenshot from 2020-09-17 16-37-41](https://user-images.githubusercontent.com/12827587/93486382-6c470300-f904-11ea-925b-008808977578.png)

or when there are more menu items:

![Screenshot from 2020-09-17 17-54-13](https://user-images.githubusercontent.com/12827587/93496146-2b082080-f90f-11ea-8e95-ad707174e3e5.png)

There are 2 items behind the search. You can see this when I hide the search:

![Screenshot from 2020-09-17 17-54-26](https://user-images.githubusercontent.com/12827587/93496275-4d01a300-f90f-11ea-89d0-5c1c7568c4a8.png)

**Comment by aterjung** [comment]
thanks again for this report - the demo notice was completely out of my focus :-) Ive never tried it.

**Comment by AlterWeb** [comment]
@aterjung I completely understand that you didn't notice the demo notice. It is not a wide used option I guess. And not really a big deal. We use it as an extra reminder on the test environment that our customers are not working on the live environment. But I think it's also a small problem to solve, so that still would be nice.

The overlapping search is a bigger problem. This is something our customers have actually issues with. For now we can use the old theme for those customers however.

**Comment by aterjung** [comment]
The search is indeed more problematic than i have expected it. There are to many extensions that add an new first level extension... The right way would be to move these to the second or level - but its not our choice. I tend to change the behavior of the search element to show only a magnifying glass icon and overlay the search input after a click. I think the search ist not so important.
A Menu-Font with a smaller width could help to - and at least we have to find a way to handle to long menus. Probably with a scroll button?

**Comment by AlterWeb** [comment]
@aterjung I think the solution could be more easy. The menu is already continuing onto the next page as you can see on my last screenshot. The problem is, it isn't doing that at the right moment. A quick fix in my browser looks like:

![Screenshot from 2020-09-21 13-48-14](https://user-images.githubusercontent.com/12827587/93763121-2abe9c80-fc11-11ea-8b19-244b4f6eb2e7.png)

What I changed is that I added 350px padding to the right of the nav-bar.

**Comment by aterjung** [comment]
thats a short win :-) I will add this to the theme - its not perfect but makes it work. Can be done better later on.
