### ISSUE TITLE
Background color configuration tabs new OpenMage admin theme

### ISSUE THREAD

**Issue by AlterWeb** [OpenMage/magento-lts#1219]
### Preconditions (*)

1. OpenMage 19.4.7

### Steps to reproduce (*)

1. Install PostNL module
2. Go to configuration and look at the PostNL menu item

### Expected result (*)

1. Menu item readable:
![Screenshot from 2020-09-21 11-32-12](https://user-images.githubusercontent.com/12827587/93752100-7156cb80-fbfe-11ea-81c6-a4a5d78441d1.png)

### Actual result (*)

1. Menu item is not readable because background color of `ul.tabs dl`:
![Screenshot from 2020-09-21 11-35-01](https://user-images.githubusercontent.com/12827587/93752152-84699b80-fbfe-11ea-9e8c-b57f3b6a2438.png)

### Solution
I think the fix is as simple as setting the background color of `ul.tabs dl` to white, I don't know for sure if there is a reason it is set to #68666f but I can't think of one.

**Comment by aterjung** [comment]
my last pull request solves this issue. I haven seen any side-effects until now.

**Comment by sreichel** [comment]
Fixed in #1224

**Comment by sreichel** [comment]
@all-contributors add @AlterWeb bug
