### ISSUE TITLE
 Uncaught Error: Undefined class constant 'SCOPE_FILE_PREFIX'

### ISSUE THREAD

**Issue by rafatriolo** [OpenMage/magento-lts#1221]
### Preconditions (*)

1. 19.4.7
2. Hi there, I´m trying to use the compiler on php cli, with the command: php shell/compiler.php --compile. Magento actually compile files and create the include folder with the compile classes, but gives a error: Uncaught Error: Undefined class constant 'SCOPE_FILE_PREFIX'.

### Steps to reproduce (*)

1. To reproduce, please try to run the compile process on php cli.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by Flyingmana** [comment]
Oh, this should not happen, we did remove the compiler a while ago.
https://github.com/OpenMage/magento-lts/tree/1.9.4.x/shell

Reason was lacking benefit thanks to php opcache, big complexity and source of many many problems.

Is there a special reason you need the compiler?

**Comment by rafatriolo** [comment]
Ohh I was not aware! My bad! I will activate php opache instead. I was using the compiler for performance purposes only.
