### ISSUE TITLE
Problems opening system / configuration 

### ISSUE THREAD

**Issue by dgruhn** [OpenMage/magento-lts#1228]
As soon as I open system / configuration the error appears:

Fatal error: Uncaught Error: Class 'Magestore_Magenotification_Helper_Data' not found in /var/www/vhosts/***/httpdocs3/app/Mage.php:593 Stack trace: #0 /var/www/vhosts/***/httpdocs3/app/code/core/Mage/Adminhtml/Block/System/Config/Tabs.php(117): Mage::helper('magenotificatio...') #1 /var/www/vhosts/***/httpdocs3/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(104): Mage_Adminhtml_Block_System_Config_Tabs->initTabs() #2 /var/www/vhosts/***/httpdocs3/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Adminhtml_System_ConfigController->editAction() #3 /var/www/vhosts/***/httpdocs3/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('edit') #4 /var/www/vhosts/***/httpdocs3/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage in /var/www/vhosts/***/httpdocs3/app/Mage.php on line 593

Magento Version 1.9.3.1 to OpenMage LTS 19.4.7

**Comment by kiatng** [comment]
This probably related to corrupted `Magestore_Magenotification` extension and not related to openmage. Try to put this [file](https://github.com/Magestore/Magenotification/blob/master/app/code/local/Magestore/Magenotification/Helper/Data.php) in `app/code/local/Magestore/Magenotification/Helper/Data.php`.

**Comment by dgruhn** [comment]
@kiatng Thanks, the problem is solved, I can open the configuration.
