### ISSUE TITLE
Install using composer failed

### ISSUE THREAD

**Issue by midlan** [OpenMage/magento-lts#1234]
### Preconditions (*)
Composer 1.8.4 2019-02-11 10:52:10
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )

### Steps to reproduce (*)

1. I created empty directory
2. `cd` to it and run `composer require openmage/magento-lts`

### Expected result (*)

I expected to openmage finish the install, but it seems to fail.

### Actual result (*)

Composer successfully downloaded all dependencies, but the after-script seems to fail with error _root/app/Mage.php is not a file._:

```
....
Writing lock file
Generating autoload files
please define your magento root dir [root]
magento root dir "root" missing! create now? [Y,n]
magento root dir "root" created
root/app/Mage.php is not a file.
```
I hit enter twice to confirm defaults. First to set `root` as mage root directory, second to create it. The `root` directory remained empty.

Another weird thing is that the composer exited with exit code `0`.

**Comment by rvelhote** [comment]
I was able to replicate this.

The only way I managed to install was this following `composer.json` and then running `composer install` which is the configuration I use for my deployments.

```
{
	"require": {
	        "aydin-hassan/magento-core-composer-installer": "*",
        	"openmage/magento-lts": "^20.0"
	},
	"extra": {
	        "magento-core-package-type": "magento-source",
	        "magento-deploystrategy": "copy",
	        "magento-root-dir": "root",
	        "magento-force": true
	}
}
```

**Comment by henrykbrzoska** [comment]
`{
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.firegento.com"
    }
  ],
  "minimum-stability": "dev",

  "require": {
    "aydin-hassan/magento-core-composer-installer": "*",
    "openmage/magento-lts": "20.0.x-dev",
    "magento-hackathon/magento-composer-installer": "*",
    "cweagans/composer-patches": "^1.6",
    "n98/magerun": "*",
    "phpoffice/phpspreadsheet": "dev-master"
  },
  "extra": {
    "magento-core-package-type": "magento-source",
    "magento-root-dir": "root",
    "magento-deploystrategy": "copy",
    "magento-force": "true",
    "include-root-package": "true",
    "magento-core-deploy" : {
      "excludes": [
        "app/etc/local.xml",
        "app/etc/config.xml",
        ".htaccess",
        "app/etc/modules/Cm_RedisSession.xml",
        "dev/tests/functional/etc/config.xml",
        "lib/Varien/Image.php"
      ],
      "ignore-directories": [
        "js"
      ],
      "git-ignore-append": false
    }
  }
}
`
this was successful

**Comment by sreichel** [comment]
Run into same problem ... adding `"aydin-hassan/magento-core-composer-installer": "*",` solved it for me.

**Comment by colinmollenhour** [comment]
Closing as the install page already recommends using one of the installer packages and although it leaves a lot to be desired there are many other issues discussing this shortcoming.
