### ISSUE TITLE
Apply patch SUPEE-4755 - Prevent Corrupted Config Cache

### ISSUE THREAD

**Issue by Cieper** [OpenMage/magento-lts#124]
Another [patch](https://github.com/AmpersandHQ/magento-ce-ee-config-corruption-bug/blob/master/PATCH_SUPEE-4755_EE_1.13.1.0_v1.sh#L172) from Magento not included in future versions, for some reason...

**Comment by infabo** [comment]
IMHO this patch addresses config-inconsistency when using EE fullpage-cache. Anyone better/other infos on this?

**Comment by Cieper** [comment]
Sorry, meant to link to https://github.com/AmpersandHQ/magento-ce-ee-config-corruption-bug - It's got an extensive write up of the problem, debugging, and solution.
It's most definately not a problem with EE FPC only, but one that affects a lot of CE sites aswell, as we discovered at https://github.com/ByteInternet - So far it's fixed all the '100 Router Match Iterations' problems we've seen.

**Comment by colinmollenhour** [comment]
Shameless plug: I've not experienced a cache issue since using my "Stampede-resistant Config Cache" patched version here: https://gist.github.com/colinmollenhour/7a91c4a92ccfd2adaeb6
I think it is a more holistic approach to solving the issue and it fixes your site being brought to it's knees during high traffic if you wipe the config cache.

**Comment by seansan** [comment]
We did try this also and did not fix *all* occurences ... I remember there
was some discussion where it also affected cache problems where layered nav
or categories where no longer updating ... sorry dont recall more ... but
we did revert ...

**Comment by seansan** [comment]
>>  fixes your site being brought to it's knees during high traffic if you
wipe the config cache.
this I do recognize

We always had this problem when some cache was flushed and our site was
crawld (FPC warmed)

**Comment by tmotyl** [comment]
related https://github.com/OpenMage/magento-lts/issues/93

**Comment by sreichel** [comment]
Duplicates #422
