### ISSUE TITLE
broken image of paypal logo in checkout payment methods

### ISSUE THREAD

**Issue by empiricompany** [OpenMage/magento-lts#1270]
### Preconditions (*)

OpenMage LTS 20.0.3
PHP 7.3

### Steps to reproduce (*)

1. go to **system->sales->payment methods**
2. **set different merchant location** from United States
3. set **Website Payments Standard (Includes Express Checkout)**
enable this solution => **yes**
sandbox mode => **no**
4. set under **Basic Settings - PayPal Website Payments Standard -> Advanced Settings:**
" Shortcut Buttons Flavor" => "**Dynamic**"
5. go to checkout frontend and show payment methods

### Expected result (*)

the logo is shown in the paypal payment method

### Actual result (*)

paypal payment method show a broken image 
this is the broken url (locale IT):
https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecmark&locale=it_IT

app/design/frontend/base/default/template/paypal/payment/mark.phtml
```
<?php
/**
 * Note: This mark is a requirement of PayPal
 * @see Mage_Paypal_Block_Standard_Form
 */
?>
<!-- PayPal Logo -->
<img src="<?php echo $this->escapeHtml($this->getPaymentAcceptanceMarkSrc())?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Acceptance Mark')) ?>" class="v-middle" />&nbsp;
<a href="<?php echo $this->getPaymentAcceptanceMarkHref()?>" onclick="javascript:window.open('<?php echo $this->getPaymentAcceptanceMarkHref()?>','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=400, height=350'); return false;">
    <?php if($this->getPaymentWhatIs()) {echo Mage::helper('paypal')->__($this->getPaymentWhatIs());} else {echo Mage::helper('paypal')->__('What is PayPal?');} ?>
</a>
<!-- PayPal Logo -->
```

returned by Mage_Paypal_Model_Config::_getDynamicImageUrl() method
```
protected function _getDynamicImageUrl($type, $localeCode, $orderTotal, $pal)
    {
        $params = array(
            'cmd'        => '_dynamic-image',
            'buttontype' => $type,
            'locale'     => $this->_getSupportedLocaleCode($localeCode),
        );
        if ($orderTotal) {
            $params['ordertotal'] = sprintf('%.2F', $orderTotal);
            if ($pal) {
                $params['pal'] = $pal;
            }
        }
        return sprintf('https://fpdbs%s.paypal.com/dynamicimageweb?%s',
            $this->sandboxFlag ? '.sandbox' : '', http_build_query($params)
        );
    }
```

P.S.:
endpoint of sandbox env seems to work:
https://fpdbs.sandbox.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecmark&locale=it_IT

### Additional information and possible solutions

https://stackoverflow.com/questions/16342872/has-paypal-changed-or-stopped-using-the-https-fpdbs-paypal-com-dynamicimageweb

https://github.com/treestonemedia/Magento-Paypal-Dynamic-Images

**Comment by fballiano** [comment]
what was referred as "broken url" it's not working:
https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecmark&locale=it_IT

may paypal fixed it. So it seems this bug autosolved itself.
