### ISSUE TITLE
Github Action "Labeler" failed with "API rate limit exceeded"

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1272]
https://github.com/OpenMage/magento-lts/runs/1283360518?check_suite_focus=true

`
Error: error handling issue comment: Error: could not get PRs: HttpError: API rate limit exceeded for installation ID 5136432.
`

can we somehow split the execution, so it does not try to work on ALL PRs but only the ones which were updates in the last $n Days?

We could also add a delay, but knowing the timeframe for the api limit, we would probably run into the max execution time for an action.

**Comment by sreichel** [comment]
As you mentioned in discord ... or see #1140

PR incoming (till weekend)

**Comment by sreichel** [comment]
Should be fixed with #1140.
