### ISSUE TITLE
Change order of Terms and Conditions

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1288]
This is a known issue in Magento. There is no option to change the order of your **Terms and Conditions** (Backend -> Sales -> Terms and conditions). BTW it should be a capital letter "C" there in the link name, and in other places too (e.g. Reports menu). 

The only way to change the order is by editing the database. In 2017 I reported this issue on magento.stackexchange.com and sreichel who is a nice gentleman and supportive person solve it here: https://github.com/sreichel/magento-Sr-AgreementPosition.

I vote for adding this missing feature to OpenMage.

**Comment by sreichel** [comment]
I'd would make a PR later ... Do you still need the option for content to be optional? Should it be part of the PR?

**Comment by ADDISON74** [comment]
I am using your work with stores in Europe having even 4 checkboxes. It would be great to integrate this missing feature in OpenMage.

**Content** shouldn't be a required field. I analyzed most of the situations and I found that we shouldn't ask for filling it up. For example, in the stores I mentioned there are only checkboxes with text labels but no content. If this field was required I was not able to save the form. 

Do you think we need such of options for Checkbox Text and Content fields?

![Screenshot 2021-03-02 172608](https://user-images.githubusercontent.com/8360474/109671137-7b510300-7b7c-11eb-8915-886098b811b4.png)

**Comment by sreichel** [comment]
> Do you think we need such of options for Checkbox Text and Content fields?

No. And I'm not going to add TinyMCE anywhere ;)
