### ISSUE TITLE
Enable observers for events `save_before` to have the final say

### ISSUE THREAD

**Issue by kiatng** [OpenMage/magento-lts#1295]
### Summary (*)

The placement of `parent::_beforeSave();` in the function `_beforeSave()` are sometimes at the beginning, and sometimes at the end of the function. See [search page](https://github.com/search?q=%22parent%3A%3A_beforeSave%28%29%3B%22+repo%3AOpenMage%2Fmagento-lts+extension%3Aphp+path%3A%2Fapp%2Fcode%2Fcore%2FMage+language%3APHP&type=Code&ref=advsearch&l=PHP&l=).  The placement affects when the events:

```php
// in Mage_Core_Model_Abstract::_beforeSave()
Mage::dispatchEvent('model_save_before', array('object'=>$this));
Mage::dispatchEvent($this->_eventPrefix.'_save_before', $this->_getEventData());
```
are fired. 

I think `parent::_beforeSave();` should be placed at the end so that the events are fired after changes are made to the model. This enables the observer to have the final say.

### Examples (*)

Reference issue #1128, there would be less need of the proposed event `Mage::dispatchEvent('order_status_changed_before_save', ['order' => $this]);`. This is because the order's state can be changed in `$this->_checkState();` and the change is after event `sales_order_save_before`.  If  `parent::_beforeSave();` is placed just before existing the function, then the order's state and status changes can be checked in the observer for  `sales_order_save_before` without the need of new event.

### Proposed solution

Check all occurances of `parent::_beforeSave();` in `protected function _beforeSave()` in models and move it to the end, so that the observer has the final say, and for consistency.

What do you guys think?

**Comment by fballiano** [comment]
I'm closing this since it didn't have any movement in more that a year, please feel free to reopen it if you feel so, or move it to the discussion area, or possibly open a PR :-)
