### ISSUE TITLE
Orphan images related to XML Connect

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1296]
From what I saw you cleaned up the XML Connect code. However, some orphaned files remained that must also be removed. Here is the way:

**/skin/adminhtml/default/default/images/xmlconnect**

**Comment by ADDISON74** [comment]
This should be removed too: 

**/app/locale/en_US/Mage_XmlConnect.csv**

**Comment by sreichel** [comment]
Fixed in #1161 and #1383.
