### ISSUE TITLE
Function libxml_disable_entity_loader() depreciated error in PHP 8.0.0rc1

### ISSUE THREAD

**Issue by bryanveIoso** [OpenMage/magento-lts#1298]
### Preconditions (*)

1. Fresh install of OpenMage LTS 20.0.4

### Steps to reproduce (*)

1. Just visit the homepage or the admin page and you'll see the error

### Expected result (*)

1. For the store to load normally

### Actual result (*)

1. [04-Nov-2020 09:58:34 CST6CDT] PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in app/bootstrap.php on line 33

**Comment by sreichel** [comment]
Closed with #1256
