### ISSUE TITLE
Magento 1.9.3.1 coming? 9.31.x in new naming conv

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#131]
Magento 1.9.3.1 coming? 9.31.x in new naming conv

https://www.reddit.com/r/Magento/comments/592puw/magento_1931_is_coming_soon_reported_magento_in/

**Comment by colinmollenhour** [comment]
If you are referencing my proposed naming convention then it would still be the '9.3x' branch. :)

**Comment by seansan** [comment]
;P

Was 9.31 already imported? I think we can close this isssue too btw.
