### ISSUE TITLE
Dashboard - Top 5 Search Terms link issue

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1310]
**OpenMage LTS 20.0.4**

Go to Dashboard in backend and take a look to the following blocks: **Last 5 Search Terms** and **Top 5 Search Terms**.

Place your mouse pointer over a search term in Last 5 Search Terms list and take a look to the URL. Here is the link in my case: 

https://www.mydomain.tld/index.php/admin/catalog_search/edit/id/41/key/5874688c27ec9781d42bacfd92420f0e/

Now place your mouse pointer over a search term in Top 5 Search Terms list and take a look to the URL. Here is the link in my case: 

https://www.mydomain.tld/index.php/admin/catalog_search/edit/key/5874688c27ec9781d42bacfd92420f0e/

The last link has an issue. Comparing with the first one which redirects correctly to edit the search term this one is opening the page to create a new search query not editing the search term. 

This is happening because the link has missing two parameters id and id_number between /edit/ ... /key/

**Comment by ADDISON74** [comment]
I will close this problem because there is a solution proposed here #1917.

**Comment by elidrissidev** [comment]
FYI issues are closed automatically when the linked PR is merged
