### ISSUE TITLE
RedisSession compression is not disableable by setting threshold to zero

### ISSUE THREAD

**Issue by andrej-schaefer** [OpenMage/magento-lts#1316]
Due to 0 is validated as false, the default threshold is set, but 0 should be possible and further code is checking against 0 to skip compression

https://github.com/OpenMage/magento-lts/blob/73ee43c5557f25b3848af4708b619d574d710f80/app/code/community/Cm/RedisSession/Model/Session.php#L124

PROPOSAL:
`$this->_compressionThreshold =  (((int) $config->descend('compression_threshold')) >= 0 ? (int) $config->descend('compression_threshold') : self::DEFAULT_COMPRESSION_THRESHOLD);`

**Comment by joshua-bn** [comment]
It makes more sense to me to make disable = -1

**Comment by colinmollenhour** [comment]
I believe you are expected to set the 'compression_lib' to 'none' to disable compression.

**Comment by ADDISON74** [comment]
From the last post I understand that the issue has been solved. Are changes needed to the Cm_RedisSession extension?

**Comment by fballiano** [comment]
this issue should be on @colinmollenhour's repository anyway, and we should use is in a composer requirements instead of having it in our repo
