### ISSUE TITLE
Auto return to stock always return qty = 1

### ISSUE THREAD

**Issue by digitalpianism** [OpenMage/magento-lts#1317]
### Preconditions (*)

1. OpenMage 20.0.4
2.

### Steps to reproduce (*)

1. Set "Auto return to stock" to true under System > Config > Inventory
2. Create a configurable product with child products
3. Go to the frontend, add the configurable product with the same option twice to the cart and checkout (so you basically purchase the same item twice).
4. Refund the corresponding order

### Expected result (*)

1. 2 out of 2 items are returned back to stock (the simple product qty is increased by 2)

### Actual result (*)

1. 1 out of 2 items are returned back to stock.

**Comment by digitalpianism** [comment]
This bug is not present in Vanilla Magento. It was introduced by this commit: https://github.com/OpenMage/magento-lts/commit/4347c5894439dbc3bdfbfdb5fe842e8116ba4335#diff-8952b606025d711e94efbff3d7abcd9892780b94bfc13539b96fda83ad763143

**Comment by digitalpianism** [comment]
I should probably tag @JonLaliberte as he's the one who made the commit.

**Comment by JonLaliberte** [comment]
@digitalpianism 

Please also check out the pull request here: https://github.com/OpenMage/magento-lts/pull/275
Someone else recently comment about a problem with this.

I wish I could provide more context here. The patch I submitted back then had been working well, **but** we didn't have many configurable products, whereas we did have many bundle products experiencing the issue I described. I see in my comment there I mentioned it affected/worked with configurable as well, and I vaguely recall testing it at the time, but I don't remember details.

I mostly handed over control of our code (I'm a business owner), so I'm very out of the loop. I'm sorry if this is causing issues on anyone else's installations.

**Comment by elidrissidev** [comment]
Should be fixed by #2186
