### ISSUE TITLE
Currency symbol not saved with fatal PHP error

### ISSUE THREAD

**Issue by jouriy** [OpenMage/magento-lts#1318]
### Preconditions (*)
1. OpenMage v19.4.8

### Steps to reproduce (*)
1. Login to backend and navigate to *System > Manage Currency > Symbols* 
2. Click on *Save Currency Symbols* button
3. Notice fatal error logged in PHP error log, currency symbol is not saved.

### Expected result (*)

1. "Custom currency symbols were applied successfully." success notification message should be shown after saving currency symbol.

### Actual result (*)

1. Fatal PHP error logged:
PHP Fatal error:  Uncaught Error: Call to a member function addSuccess() on bool in app/code/core/Mage/CurrencySymbol/controllers/Adminhtml/System/CurrencysymbolController.php:72
Stack trace:
#0 app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_CurrencySymbol_Adminhtml_System_CurrencysymbolController->saveAction()
#1 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('save')
#2 app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#3 app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#4 app/Mage.php(729): Mage_Core_Model_App->run(Array)
#5 index.php(78): Mage::run('', 'store')
#6 {main}
  thrown in /srv/www/app/code/core/Mage/CurrencySymbol/controllers/Adminhtml/System/CurrencysymbolController.php on line 72

**Comment by jouriy** [comment]
reason is reference to 
`Mage::getSingleton('connect/session')->addSuccess()` call on line 72 in _app/code/core/Mage/CurrencySymbol/controllers/Adminhtml/System/CurrencysymbolController.php_ instead of `Mage::getSingleton('adminhtml/session')->addSuccess()`
PR will follow.

**Comment by ADDISON74** [comment]
This error is pretty strange. I found the same code in Magento CE 1.9.2.4 . When I saved the currency symbols in backend I got the alert message "Custom currency symbols were applies successfully." In PHP log I did not find any error recorded and I set display_errors to E_ALL. 

In my case this function provided the right result based on the alert message:

```
    public function saveAction()
    {
        $symbolsDataArray = $this->getRequest()->getParam('custom_currency_symbol', null);
        if (is_array($symbolsDataArray)) {
            foreach ($symbolsDataArray as &$symbolsData) {
                $symbolsData = Mage::helper('adminhtml')->stripTags($symbolsData);
            }
        }

        try {
            Mage::getModel('currencysymbol/system_currencysymbol')->setCurrencySymbolsData($symbolsDataArray);
            Mage::getSingleton('connect/session')->addSuccess(
                Mage::helper('currencysymbol')->__('Custom currency symbols were applied successfully.')
            );
        } catch (Exception $e) {
            Mage::getSingleton('adminhtml/session')->addError($e->getMessage());
        }

        $this->_redirectReferer();
    }
```
