### ISSUE TITLE
Magento removes old sessions without limit 

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#132]
Session Garbage collector in Magento uses delete query without limit to remove old sessions.
See
https://github.com/OpenMage/magento-lts/blob/1.9.3.0/app/code/core/Mage/Core/Model/Resource/Session.php#L280

On instances with tons of sessions this causes long lasting lock on the session table blocking the whole website rendering.

Magento tries to cleanup old sessions every 50 sessions, so it's very often. So most of the time, Magento will scan the whole session table for nothing. 

I think we should increase the _automaticCleaningFactor to at last 1000, or even disable automatic GC and provide a cron job instead. Another solution would be to add a check to GC to execute it maximum once a day ...

**Comment by tmotyl** [comment]
After thinking about it, setting a limit will not help much when you have long session lifetime, as most of the cases Magento will not find enough records to fulfill the limit, thus it will do a full table scan anyway.

**Comment by colinmollenhour** [comment]
I would think something like an hourly cron job would be appropriate for the MySQL driver.

It seems there should definitely be an index on session_expires. Without an index the whole table is locked using the default "REPEATABLE READ" isolation level. The alternative to avoid locking would be to use "READ COMMITTED" isolation level for this one update, but the full table scan still is going to be bad for performance.

**Comment by seansan** [comment]
Is this still an issue? we added the index.

**Comment by sreichel** [comment]
Quite old ... i'd close to do some cleanup. Please reopen if its still an issue.
