### ISSUE TITLE
Customer cannot reset password

### ISSUE THREAD

**Issue by LuizSantos1** [OpenMage/magento-lts#1327]
### Preconditions (*)

1. OpenMage/Magento LTS 1.9.4.8 - PHP 7.3 (on 7.4 is the same)
2. Customer cannot reset password

### Steps to reproduce (*)

1. Go to: www.yourdomain/customer/account/forgotpassword/
2. Insert e-mail and hit "send"

### Expected result (*)

1. Confirmation of the e-mail sent to reset the password

### Actual result (*)

1. Getting a error: "This page isn’t working www.yourdomain.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by jouriy** [comment]
I can not reproduce this error on clean OpenMage v19.4.8 with RWD theme. Green notice page with "If there is an account associated with johndoe@example.com you will receive an email with a link to reset your password." message is shown after hitting Send button. HTTP response code from page is 200.

As I see in your case HTTP error code 500, which usually mean Internal server error from web-server. Please could you also post the last lines from your web-server error log and PHP error log.

**Comment by LuizSantos1** [comment]
@jouriy I will reinstall Openmage again and test, mine test environment has shown the same error with RWD Theme also. 
Once I do it, I will let you know

**Comment by LuizSantos1** [comment]
@jouriy It might be something related to the upgrade, because on my main site it does not matter if it is my theme or RDW it does not work. In a fresh install with a new database it works...
I will make a copy of my database and test it to see if it is a database issue or something related to files...

I have been searching in foruns and I am seeing a lot of reports about this issue after upgrading...
like: https://magento.stackexchange.com/questions/84605/magento-reset-password-link-not-working-after-upgrade

I have tried using their solution but it did not work

**Comment by jouriy** [comment]
Error logs should contain detailed information on why it is failing to generate page. 
If it is post-upgrade issue, most likely it is related to customer's layout for resetforgotten changed in recent versions:
```diff
--- customer.xml
+++ customer.xml
@@ -153,7 +153,7 @@
         </reference>
     </customer_account_forgotpassword>
 
-    <customer_account_resetpassword translate="label">
+    <customer_account_changeforgotten translate="label">
         <label>Reset a Password</label>
         <remove name="right"/>
         <remove name="left"/>
@@ -172,9 +172,9 @@
             </action>
         </reference>
         <reference name="content">
-            <block type="customer/account_resetpassword" name="resetPassword" template="customer/form/resetforgottenpassword.phtml"/>
+            <block type="customer/account_changeforgotten" name="changeForgottenPassword" template="customer/form/resetforgottenpassword.phtml"/>
         </reference>
-    </customer_account_resetpassword>
+    </customer_account_changeforgotten>
 
     <customer_account_confirmation>
         <remove name="right"/>

**Comment by LuizSantos1** [comment]
@jouriy It is something related to files, because I have made a copy of my database and installed a fresh openmage installation and it is working... 
Could please tell me which patch I need to edit? Is it at: app/design/frontend/base/default/template/customer/form/resetforgottenpassword.phtml

Regards

**Comment by jouriy** [comment]
That's great, than it is definitely have something to do with your theme. You can locate file for your theme with:
```
$ ls -1 app/design/frontend/*/*/layout/customer.xml
app/design/frontend/base/default/layout/customer.xml
app/design/frontend/default/iphone/layout/customer.xml
app/design/frontend/default/modern/layout/customer.xml
app/design/frontend/rwd/default/layout/customer.xml
```
and verify that layout file for your theme have `<customer_account_changeforgotten>` section.

**Comment by LuizSantos1** [comment]
@jouriy 
I have managed to solve it 
I don't really know which one worked, but I have made backup copies of all "customer.xml" files
And copied the "costumer.xml" from here... 

So the path changed were:
 app/design/frontend/rwd/default/layout/customer.xml
 app/design/frontend/base/default/layout/customer.xml
 app/design/frontend/default/iphone/layout/customer.xml
 app/design/frontend/default/modern/layout/customer.xml

And as I did not have customer.xml in my theme, I have created it as well
So it stayed like this:  app/design/frontend/MYTHEME/default/layout/customer.xml

Tested and it worked! Thanks for the help and I am leaving this answer, so someone else might use it!

**Comment by ADDISON74** [comment]
Magento Team changed customer.xml content in 1.9.3 version.

**Here is the one in version 1.9.2.4** 

```
    <customer_account_changeforgotten translate="label">
        <label>Reset a Password</label>
        <remove name="right"/>
        <remove name="left"/>

        <reference name="head">
            <action method="setTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="root">
            <action method="setTemplate">
                <template>page/1column.phtml</template>
            </action>
            <action method="setHeaderTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="content">
            <block type="customer/account_changeforgotten" name="changeForgottenPassword" template="customer/form/resetforgottenpassword.phtml"/>
        </reference>
    </customer_account_changeforgotten>

    <!-- <customer_account_resetpassword translate="label">
        <label>Reset a Password</label>
        <remove name="right"/>
        <remove name="left"/>

        <reference name="head">
            <action method="setTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="root">
            <action method="setTemplate">
                <template>page/1column.phtml</template>
            </action>
            <action method="setHeaderTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="content">
            <block type="customer/account_resetpassword" name="resetPassword" template="customer/form/resetforgottenpassword.phtml"/>
        </reference>
    </customer_account_resetpassword> -->
```

**and here is the one in OpenMage 20.0.4**

```
    <customer_account_forgotpassword translate="label">
        <label>Customer Forgot Password Form</label>
        <remove name="right"/>
        <remove name="left"/>

        <reference name="head">
            <action method="setTitle" translate="title" module="customer"><title>Forgot Your Password</title></action>
        </reference>
        <reference name="root">
            <action method="setTemplate"><template>page/1column.phtml</template></action>
            <action method="setHeaderTitle" translate="title" module="customer"><title>Password forgotten</title></action>
        </reference>
        <reference name="content">
            <!--<block type="core/template" name="forgotPassword" template="customer/form/forgotpassword.phtml"/>-->
            <block type="customer/account_forgotpassword" name="forgotPassword" template="customer/form/forgotpassword.phtml" />
        </reference>
    </customer_account_forgotpassword>

    <customer_account_changeforgotten translate="label">
        <label>Reset a Password</label>
        <remove name="right"/>
        <remove name="left"/>

        <reference name="head">
            <action method="setTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="root">
            <action method="setTemplate">
                <template>page/1column.phtml</template>
            </action>
            <action method="setHeaderTitle" translate="title" module="customer">
                <title>Reset a Password</title>
            </action>
        </reference>
        <reference name="content">
            <block type="customer/account_changeforgotten" name="changeForgottenPassword" template="customer/form/resetforgottenpassword.phtml"/>
        </reference>
    </customer_account_changeforgotten
```

I had the same issue and I had to comment in version 1.9.2.4 the part related to customer_account_resetpassword.

**Comment by LuizSantos1** [comment]
@ADDISON74 Thanks, but my case was related to the customer.xml as @jouriy said.
I have changed/added the file to all theme folders and have created one to my own theme as it did not have and so far everything is working fine. ;)

**Comment by LuizSantos1** [comment]
Hi @sreichel  I hope you can help me...
I have updated it again, but now the solution written by me is not working when I try to retrive the password.
When I use this link: /customer/account/forgotpasswordpost/ 
I put the e-mail, fill up the forms and hit "submit" the 500 error came back after upgrade, the "customer.xml" solution given above by me, does not work anymore... 

I went to the root of the store and commented out this line on "index.php"...
`#ini_set(‘display_errors’, 1);,`

In order to show the errors... 

And it throws this error: 
`Fatal error: Uncaught Error: Call to a member function getBackend() on bool in /public_html/app/code/core/Mage/Eav/Model/Entity/Abstract.php:1538 Stack trace: #0 /public_html/app/code/core/Mage/Customer/Model/Resource/Customer.php(355): Mage_Eav_Model_Entity_Abstract->saveAttribute(Object(Mage_Customer_Model_Customer), 'rp_customer_id') #1 /public_html/app/code/core/Mage/Customer/Model/Customer.php(1545): Mage_Customer_Model_Resource_Customer->changeResetPasswordLinkCustomerId(Object(Mage_Customer_Model_Customer), '45ae2eef5f70478...') #2 /public_html/app/code/core/Mage/Customer/controllers/AccountController.php(772): Mage_Customer_Model_Customer->changeResetPasswordLinkCustomerId('45ae2eef5f70478...') #3 /public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Customer_AccountController->forgotPasswordPostAction() #4 /public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage in /public_html/app/code/core/Mage/Eav/Model/Entity/Abstract.php on line 1538`

Could you tell me if this is a known error and how to solve this?

Regards

**Comment by LuizSantos1** [comment]
Oh yes, 
The error above is shown on this link: customer/account/forgotpasswordpost/

I went to: app/design/frontend/base/default/template/customer/form
And investigated the file: forgotpassword.phtml and I did not find 
`<?php echo $this->getBlockHtml('formkey'); ?>`

I heard this should be there, where should I insert this?

Regards

**Comment by kiatng** [comment]
The error on line 1538 https://github.com/OpenMage/magento-lts/blob/23107336f221c0337f7e0125a5442058e3298462/app/code/core/Mage/Eav/Model/Entity/Abstract.php#L1537-L1538 is probably because something has gone wrong with the attribute `rp_customer_id` as reference in 
> /public_html/app/code/core/Mage/Customer/Model/Resource/Customer.php(355): Mage_Eav_Model_Entity_Abstract->saveAttribute(Object(Mage_Customer_Model_Customer), 'rp_customer_id') #1

and that it cannot instantiate the attribute. I'd check to see if the  attribute `rp_customer_id` exists in the table `eav_attribute`, which should have `attribute_id` 42.

**Comment by LuizSantos1** [comment]
Hi there, @kiatng 
I have checked my database and I see several "eav_attributte" tables, which one I should check?

Regards

**Comment by LuizSantos1** [comment]
@kiatng 
I have found a possible solution for the issue
This is the link: [https://magentary.com/kb/fatal-error-call-to-a-member-function-getbackend-on-a-non-object-in-appcodecoremageeavmodelentityabstract-php-on-line-1536/](url)

Your suggestion was right, it was missing the rp_customer_id attributte 

Clearing the cache and trying to make the setup rebuild this did not work, so the solution was
do it manually using PhpMyadmin query 

Open the database using PhpMyadmin / Make sure you are on "structure" tab, use the filter "Containing the word",
look for "eav_attribute", open this tab and execute the following SQL query: 

`INSERT INTO `eav_attribute` (entity_type_id,attribute_code,attribute_model,backend_model,backend_type,backend_table,frontend_model,frontend_input,frontend_label,frontend_class,source_model,is_required,is_user_defined,default_value,is_unique,note) VALUES  (1,'rp_customer_id',NULL,NULL,'varchar',NULL,NULL,'hidden',NULL,NULL,NULL,0,0,NULL,0,NULL);
`
If you use table prefix, you will need to change "eav_attributte" to "tableprefix_eav_attributte" on the SQL query informed above. 

The link provided talks about inserting more info, but for me it did not work because they were aready there...
Only the first code did the job. 

So, for now I will close this
