### ISSUE TITLE
Bundles - price without tax on frontend

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#133]
Hi. old bug still present. If store uses prices excluding tax on admin area, prices on frontend category are without tax showing "as low as PRICE with tax" instead of including tax. The same appears on product page and cart/checkout bundle product row shows associated product price without tax also
Issue presented in all 1.9 versions, 1.9.3 shows correct price as configured right know - so its a small fix for bundles

**Comment by seansan** [comment]
Is this still an issue in 1939 ? 

@tomekjordan can you provice a fix ... ? Or how are you working with this on your stores

**Comment by sreichel** [comment]
I'd close to do some cleanup. Please reopen if its still an issue.
