### ISSUE TITLE
Please review 1.9.3.1 import via merge

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#136]
I merged the openMage-mirror State/Tag/Commit into a new branch 1.9.3.1 here.
I would like to have someone review it, so we can make it to the new default branch.

**Comment by tschifftner** [comment]
I cannot pull that branch with composer. Any hint?

> "openmage/magento-lts": "1.9.3.1-dev"

**Comment by infabo** [comment]
`"openmage/magento-lts": "dev-1.9.3.1"`?

**Comment by tschifftner** [comment]
Nope
```
  Problem 1
    - The requested package openmage/magento-lts dev-1.9.3.1 exists as openmage/magento-lts[1.8.0.x-dev, 1.8.1.x-dev, 1.9.0.x-dev, 1.9.1.1, 1.9.1.x-dev, 1.9.2.0-dev, 1.9.2.1-dev, 1.9.2.2-dev, 1.9.2.3-dev, 1.9.2.4-dev, 1.9.2.x-dev, 1.9.3.0-dev, dev-Flyingmana-patch-1] but these are rejected by your constraint.
```

**Comment by infabo** [comment]
OK, looks like packagist hasn't updates yet. https://packagist.org/packages/openmage/magento-lts

**Comment by tschifftner** [comment]
Richtig, danke. Lösung ist auch das Repo anzugeben:

```
"openmage/magento-lts": "1.9.3.1-dev“
….
{
  "type": "vcs",
  "url": "https://github.com/OpenMage/magento-lts.git"
}
```

**Comment by Flyingmana** [comment]
thx for the hint with packagist, @drobinson can maybe speed this up a bit.
As people are already using it now, I changed the default branch so we dont get extra work with PRs.

But still, we need a review of the merge :)

**Comment by tschifftner** [comment]
We checked it and it looks pretty good. I hope to get it down a deployment pipeline later this day to test it on live conditions.

**Comment by seansan** [comment]
not very detailed, but highover method. installed and upgraded fom 1.9.2.4
site and works fine. Had some problem with Redis but could also be server
side.

**Comment by drobinson** [comment]
@Flyingmana Did you have to manually resolve any merge conflicts?  Is that what the two file paths in the commit message are referring to?

**Comment by Flyingmana** [comment]
not only, they got automatically added to the message, but there was a bit more because of the file permission changes.

**Comment by tmotyl** [comment]
can we close this issue?

**Comment by Flyingmana** [comment]
as there was enough time and nobody had complaints, yes
