### ISSUE TITLE
Make the email encoding of Zend_Email configurable

### ISSUE THREAD

**Issue by loekvangool** [OpenMage/magento-lts#1366]
### Summary (*)
Make the email encoding configurable.

### Examples (*)
I use the email infrastructure to send custom emails from PHP scripts. I need UTF-8 encoding, but Magento uses `iso-8859-1` (the default of `Zend_Email`). Of course, one can fix things with `utf8_decode()` but it's better to just keep things in a single encoding.  There does not seem to be a setting for this yet.

From the sent email:
>`Content-Type: text/plain; charset=iso-8859-1`

It happens here: https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Core/Model/Email.php#L135

### Proposed solution
There could be a configuration setting for the encoding, and use `iso-8859-1` as a fallback or default.

Also discussed in https://stackoverflow.com/questions/36570050/magento-email-model-encoding-unfortunately-defaults-to-iso-8859-1

**Comment by fballiano** [comment]
I'm closing this one, since now we use zend_mail with utf8 charset
