### ISSUE TITLE
Backups link is not appearing in System -> Tools after enabling the module output

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1368]
OpenMage 2005 just installed from scratch.

In Magento CE 1.9.4.5 by default **Tools** link in System menu has two options: Backups and Compilation. As I know the compilation feature was removed from OpenMage but the code for backup feature is still available.

Checking System -> Configuration -> Advanced section -> Advanced, Mage_Backup module output is set to Disable by default. After enabling it and saving the configuration Backups link is not appearing in Tools menu.

My comments:

1. After enabling Mage_Backup module output we should get Backups section in backend (route system_backup/index) but Magento Team disabled it starting with v1.9.4.0 directly in /app/etc/modules/Mage_All.xml. If anyone need it just edit this file and flush the cache.

2. With Compilation feature removed from OpenMage and Mage_Backup module deactived/disabled by default the link called Tools should not appear in System menu. We cannot remove it but we should find a way to hide it to avoid confusion with a link which is doing nothing.

**Comment by kiatng** [comment]
Some extensions may insert links in the Tools menu. For example:

![image](https://user-images.githubusercontent.com/1106470/103964110-9cf1c780-5195-11eb-99f7-2ac6a961f97e.png)

**Comment by ADDISON74** [comment]
@kiatng: I customized and improved ImaClean extension for cleaning the orphan product images in the filesystem. I put the link for the extension in the Tools submenu too. If there are extensions installed already which are using the Tools menu it won't be any issues. If there are not that link is an orphan one in System menu.

**Comment by ADDISON74** [comment]
This module was disabled in two places by Magento Team starting with 1.9.4 because they considered it a security hole. They did not provide any technical details just statements in post on Internet. Checking the code it is a little bit challenging to remove it completely without creating any issues. It will remain fossilized without any contribution.
