### ISSUE TITLE
installation problem via script

### ISSUE THREAD

**Issue by rr10** [OpenMage/magento-lts#1369]
php 7.2
cpanel
magento 1.9.4.3

I followed the guide below with method 1

https://www.openmage.org/magento-lts/migration-guide.html

but i've this error:
`00102@srv8 public_html]$ curl -fsSL https://migrate.openmage.org | sh
 _____                 ___  ___                   _    _____ _____
|  _  |                |  \/  |                  | |  |_   _/  ___|
| | | |_ __   ___ _ __ | .  . | __ _  __ _  ___  | |    | | \ `--.
| | | | '_ \ / _ \ '_ \| |\/| |/ _` |/ _` |/ _ \ | |    | |  `--. \
\ \_/ / |_) |  __/ | | | |  | | (_| | (_| |  __/ | |____| | /\__/ /
 \___/| .__/ \___|_| |_\_|  |_/\__,_|\__, |\___| \_____/\_/ \____/
      | |                             __/ |
      |_|                            |___/

This script will download the appropriate patch for your Magento installation
and update the core source code to OpenMage LTS v19.4.8.

DO NOT continue if you do not have an easily restorable backup!

DO NOT run this migration on production unless the result has been thoroughly
tested in a development environment for compatibility issues.

Migration will begin in 20 seconds. Press CTRL+C to abort.

Detected that you have installed Magento Commuinity Edition 1.9.4.3
Downloading patch for Magento CE 1.9.4.3 to OpenMage LTS v19.4.8...
wget: unrecognized option '--no-hsts'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.`

**Comment by colinmollenhour** [comment]
Cross-reported here: https://github.com/OpenMage/migrate/issues/4
