### ISSUE TITLE
(?) - What is this? tooltip

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1374]
**OpenMage v20.0.5**

1. Go to Backend -> System -> Configuration
2. On the left side in section "Current Configuration Scope" there a (?) tooltip. See the screenshot attached bellow
3. By clicking on the tooltip a new tab will open with Documentation and Resources for Magento 2.

The link for this tooltip is http://merch.docs.magento.com/ce/user_guide/configuration/scope.html

This should be removed from OpenMage. I did not check for other tooltips, probably there are more.

![screenshot](https://user-images.githubusercontent.com/8360474/103999668-db8f7e00-51a5-11eb-986e-147482e1d29b.jpg)

**Comment by ADDISON74** [comment]
Here are the files:

```
./app/code/core/Mage/Adminhtml/Helper/Data.php: $url = "http://merch.docs.magento.com/{$this->getHelpTargetVersion()}/user_guide/";
./app/code/core/Mage/Adminhtml/etc/config.xml: <url><![CDATA[http://merch.docs.magento.com/ce/user_guide/configuration/scope.html]]></url>
```

Here are other links:

```
<a id="page-help-link" href="http://merch.docs.magento.com/ce/user_guide/order-processing/order-manage.html">Get help for this page</a>
<a id="page-help-link" href="http://merch.docs.magento.com/ce/user_guide/configuration/advanced/admin.html">Get help for this page</a>
<a id="page-help-link" href="http://merch.docs.magento.com/ce/user_guide/configuration/general/general.html">Get help for this page</a>
<a id="page-help-link" href="http://merch.docs.magento.com/ce/user_guide/search_seo/search-terms.html">Get help for this page</a>
```

**Comment by ADDISON74** [comment]
@colinmollenhour, @Flyingmana: Do we have any idea related to this issue?

In case it cannot be implemented I recommend a complete remove from the code.

**Comment by colinmollenhour** [comment]
I think there is a copy of the user docs somewhere but I don't know if they have a permanent home yet.. Will defer to @Flyingmana

**Comment by Flyingmana** [comment]
Will check, but also not sure if this is covered by what we have.

in general I would want to keep it, even if we do not have the documentation at the moment. We could at least use it to check on our documentation page, where people more often look at, to extend the docs there with higher priority.

**Comment by ADDISON74** [comment]
Every page in Backend has a link which is pointing to a dedicated page in former Magento html user manual. Even custom extensions which have pages in Configuration section have ones, dead links of course. After 13 years from its launch I do not expect new people to use this feature, I never used it before because the interface is pretty intuitive. Those who are using Open Mage are already people with experience.

1. My personal opinion is to remove this feature entirely from Magento code. 
2. We can add link(s) to PDF files user manual or other resources in footer which can be downloaded from OpenMage website.

The more OpenMage is detached from external resources the better. These days I have identified two extensions that gave errors because they could no longer obtain information from Internet resources that no longer exist.

**Comment by fitzjohnit** [comment]
Hi I hit an issue with some of  the changes in this commit https://github.com/OpenMage/magento-lts/pull/1536/commits/401314700d2b991507e2ed728711e10ef4e5127f  creating a fatal error on a order view page if have the M2E Pro module installed.  e.g. usage example https://github.com/m2epro/magento1-extension/blob/master/app/code/community/Ess/M2ePro/Observer/Order/View/After.php#L46

I created a pull request above with the Magento specific aspects removed.
