### ISSUE TITLE
Magento 1.9.4.5 Template Compatibility 

### ISSUE THREAD

**Issue by learning101010** [OpenMage/magento-lts#1381]
Hello 

Does Template  from magento 1.9.4.5 to openmage 20.5 compatible  ? does openmage have like template store ?

**Comment by kiatng** [comment]
>Does Template from magento 1.9.4.5 to openmage 20.5 compatible ?

Yes, in general, v20.x does not guarantee backward compatibility. For BC, use OpenMage v19.x.

>does openmage have like template store ?

No.

**Comment by learning101010** [comment]
thank you for you answer
