### ISSUE TITLE
Packagist.org auto-updating/webhook seems to be broken

### ISSUE THREAD

**Issue by rjocoleman** [OpenMage/magento-lts#1385]
### Summary (*)

As per #638 packagist.org seems to be stuck `Last update: 2020-12-29 14:03:16 UTC`, i.e. `1.9.4.x-dev` branch is at commit cbeebfa880cb3a464e6f1a0b7a1ced28cc9bc3c6 from 12 days ago (at the time of writing this issue).

https://packagist.org/packages/openmage/magento-lts#1.9.4.x-dev

https://packagist.org/about#how-to-update-packages lists some ways to resolve, but it perhaps the Packagist.org webhook hasn't been set up by someone with permissions on Packagist.org to publish? 

### Examples (*)

Currently, getting the latest dev version from packagist.org will result in users getting an older version of the code than is in branches of the same on GitHub.

### Proposed solution

@LeeSaferite or @drobinson will need to do something please (as they're the people in control of the packagist.org listing).

**Comment by naderman** [comment]
Just for the record I triggered a manual update on packagist.org yesterday so right now the branches point to the most recent commits, but this package does indeed not seem to update correctly.

**Comment by Flyingmana** [comment]
Also wrote an mail to @LeeSaferite and @drobinson 
with @colinmollenhour and @tmotyl in CC

> Hi you two,
> 
> you are still the only Maintainers on Packagist for OpenMage
> https://packagist.org/packages/openmage/magento-lts
> 
> The github webhook needs to be done by a Maintainer account for the autoupdate to work properly.
> 
> Could you please either do the needed Change for this to work,
> and/or add another Maintainer?
> Adding another Maintainer would also allow us to add eventuel more packages from the Org, should we add Modules or Themes to our Organisation.
> 


In case we do not get a reaction over the next month, I suggest to use our `composer.json` https://github.com/OpenMage/magento-lts/blob/1.9.4.x/composer.json as base for legitimacy to request packagist to add additional Maintainers.

**Comment by sreichel** [comment]
> 
> 
> Just for the record I triggered a manual update on packagist.org yesterday so right now the branches point to the most recent commits, but this package does indeed not seem to update correctly.

Thanks. Thats why it looked correct (#1193)

**Comment by Flyingmana** [comment]
just got added as a maintainer from @LeeSaferite 

payload from the webhook was now delivered

![image](https://user-images.githubusercontent.com/237319/104253595-298dd580-5475-11eb-8225-e1cf1e0d90ab.png)

**Comment by LeeSaferite** [comment]
@naderman Thanks for assist there

**Comment by rjocoleman** [comment]
this appears to be fixed - thanks all! 😀
