### ISSUE TITLE
{{var phone}} vs {{var store_phone}} in Email Templates

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1387]
I have to migrate a customized Magento 1.9.2.4 store to OpenMage 20.0.5. Checking the email templates this website used over the years I found a difference related to the store phone number.

In OpenMage here is the source code for the link which is responsible for making a phone call:

```
{{depend store_phone}}
<b>Call Us:</b>
<a href="tel:{{var phone}}">{{var store_phone}}</a><br>
{{/depend}}
```
As you may see we have two variabiles, one in href and the other one visible in email. **Is this variable called phone set in Magento code or it should be store_phone?**

Here is the list of the files with this issue:

(38) creditmemo_new.html
(37) creditmemo_new_guest.html
(38) creditmemo_update.html
(38) creditmemo_update_guest.html
(39) invoice_new.html
(39) invoice_new_guest.html
(39) invoice_update.html
(37) invoice_update_guest.html
(38) order_new.html
(38) order_new_guest.html
(38) order_update.html
(37) order_update_guest.html
(39) shipment_new.html
(38) shipment_news_guest.html
(39) shipment_update.html
(37) shipment_update_guest.html
(38) account_new.html
(43) account_new_confirmation.html
(33) account_new_confirmed.html

Line number in every file is mentioned between ( ).

**Comment by kiatng** [comment]
The vars are set [here](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Core/Model/Email/Template/Abstract.php#L172):
```php
        $defaultValuesMap = array(
            "logo_width" => self::XML_PATH_DESIGN_EMAIL_LOGO_WIDTH,
            "logo_height" => self::XML_PATH_DESIGN_EMAIL_LOGO_HEIGHT,
            "phone" => Mage_Core_Model_Store::XML_PATH_STORE_STORE_PHONE,
            "store_phone" => Mage_Core_Model_Store::XML_PATH_STORE_STORE_PHONE,
            "store_hours" => Mage_Core_Model_Store::XML_PATH_STORE_STORE_HOURS,
            "store_email" => Mage_Customer_Helper_Data::XML_PATH_SUPPORT_EMAIL,
        );
```

And the function `_addEmailVariables()` that sets the vars is called in several [places](https://github.com/OpenMage/magento-lts/search?q=_addEmailVariables) in the core. So, this is not a bug. Why 2 vars `phone` and `store_phone`? My guess is for BC and not to break custom templates or extensions that reference one of them.

**Comment by ADDISON74** [comment]
I appreciate for your reply. Probably phone variable was used in old versions. I will close this issue.
