### ISSUE TITLE
Missing a few lines in translations

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1389]
The following lines were used in Magento 1.9.2.4 translations.

**[MAGE_CUSTOMER.csv]**
"If there is an account associated with %s you will receive an email with a link to reset your password.", "If there is an account associated with %s you will receive an email with a link to reset your password."
"Your password has been updated.", "Your password has been updated."

**[MAGE_PRODUCTALERT.csv]**
"You will no longer receive stock alerts for this product.", "You will no longer receive stock alerts for this product."

By checking OpenMage source code for every of them there are still PHP files which include them. Here is the list:

```
/app/code/core/Mage/Customer/controllers/AccountController.php
/app/code/core/Mage/Adminhtml/controllers/IndexController.php
/app/code/core/Mage/Customer/controllers/AccountController.php
/app/code/core/Mage/Adminhtml/controllers/IndexController.php
/app/code/core/Mage/ProductAlert/controllers/UnsubscribeController.php
```

**You should put them back.**

The following lines were used in Magento 1.9.2.4 translations but checking OpenMage source code I did not find any PHP files to include them.

**[MAGE_CHECKOUT.csv]**
"Address Billing","Address Billing"
"Address Shipping","Address Shipping"
"Login Registered","Login Registered"
"Product Promotions and Special Offers","Product Promotions and Special Offers"
"Select an option from bellow:","Select an option from bellow:"
"Sign up for our newsletter and price alert", "Sign up for our newsletter and price alert"

**Comment by sreichel** [comment]
Checked all given strings ... (latest OM)

"If there is an account associated with %s you will receive an email with a link to reset your password." -> see `Mage_Adminhtml.csv`
"Your password has been updated." -> see `Mage_Adminhtml.csv`
"You will no longer receive stock alerts for this product." -> see `Mage_ProductAlert.csv`

"Address Billing" -> not used
"Address Shipping" -> not used
"Login Registered" -> not used
"Product Promotions and Special Offers" -> not used
"Select an option from bellow:" -> not used
"Sign up for our newsletter and price alert" -> not used

I dont see anything wrong here. (?)

**Comment by ADDISON74** [comment]
I checked again and here is what I found:

We should add the translation from bellow to **Mage_Customer.csv** as it is used in Customer module in this file ```Customer/controllers/AccountController.php```

"If there is an account associated with %s you will receive an email with a link to reset your password.", "If there is an account associated with %s you will receive an email with a link to reset your password."

Also the translation from bellow to **Mage_ProductAlert.csv** as it is used in PriceAlert module in this file ```ProductAlert/controllers/UnsubscribeController.php```

"You will no longer receive price alerts.","You will no longer receive price alerts"
