### ISSUE TITLE
Magento general speed improvements

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#139]
Magento general speed improvements

Would it make sense to add some or all of the tips mentioned in slide 22+ onwards?

http://www.slideshare.net/ivanchepurnyi/making-magento-flying-like-a-rocket-a-set-of-valuable-tips-for-developers

Some seem a real quick win

**Comment by Flyingmana** [comment]
we already implemented some of them I think, also some were implemented by magento since then, also lead some of them to removed features.

And then you can also implement most of them as an extension like https://github.com/firegento/magento-performance-tweaks

**Comment by seansan** [comment]
thx, did not know that solution. Is that not something we could import? (/w
some settings because I see it disables certain logs)

https://github.com/firegento/magento-performance-tweaks

**Comment by tmotyl** [comment]
+1 for the setting to disable certain logs

**Comment by colinmollenhour** [comment]
Compare should really use session data instead of tables, but I suppose this would be considered breaking BC? Google Analytics or similar is much better for reporting so viewed products reports should be removed entirely IMO but that would definitely break BC. :)

**Comment by Flyingmana** [comment]
Compare is a very interesting piece anyway... I dont know many merchants actually using it...
I personally would accept a BC break on resource/model level.
The log stuff needs a better review, i usual advertise disabling it, but it also kills some of the features magento offers. 
Views on products is also nearly never used actively and probably also very inaccurate. But thats all to much for a single Issue to discuss.

**Comment by SyedMuneebb** [comment]
These are some steps to boost the Magento speed:

- Install and Configure Varnish Cache
- Merge JS and CSS
- Caching Magento
- Flat Catalog Categories and Products
- Magento Compilation

Source: [Improve Magento Performance](https://magenticians.com/improve-magento-frontend-performance/)
