### ISSUE TITLE
Classname wrong

### ISSUE THREAD

**Issue by matteorossi-thespacesm** [OpenMage/magento-lts#1395]
### Preconditions (*)

1. OpenMage LTS 19.4.9

### Steps to reproduce (*)

1. Go to Admin -> System -> Configuration -> General -> Web

### Expected result (*)

1. Configuration page should open ad usual

### Actual result (*)

1. Fatal error: Uncaught Error: Call to a member function toOptionArray() on bool in /mnt/sda/www/riminilambrettacentre.com/htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php on line 463

File name should be Samesite and class name should be Mage_Adminhtml_Model_System_Config_Source_Cookie_Samesite

**Comment by tmotyl** [comment]
fix is in: https://github.com/OpenMage/magento-lts/pull/1390

**Comment by sreichel** [comment]
@all-contributors add @matteorossi-thespacesm bug
