### ISSUE TITLE
All Countries instead of only the configured in checkout when using Country of Manufacturer

### ISSUE THREAD

**Issue by Elfen-Service** [OpenMage/magento-lts#140]
Known bug for several years now ...

http://magento.stackexchange.com/questions/43939/allowed-countries-keeps-resetting-to-all/43961#43961

**Comment by damien-biasotto** [comment]
I tried to replicate the issue first without any luck and I'm not a big fan of blind fixes.

Can someone, confirm it's still happening, or tell me what am I doing wrong?  I created a product with a country of manufacture, restricted the allowed countries to two countries. Then I visited first the product page, then checked-out, and I only see the allowed countries I selected.

**Comment by ADDISON74** [comment]
I would like to know if this issue is still confirmed in OpenMage. Any feedback is welcome.

Please note if there are no posts in 2 weeks from now I will close it.
