### ISSUE TITLE
Wrong field specified when trying to save STORE URL

### ISSUE THREAD

**Issue by stevol2021** [OpenMage/magento-lts#1409]
### Preconditions (*)

1.20.0.6
2.on system > configuration > Web > Base URL  (both) on all stores exept default config.

### Steps to reproduce (*)

1.login > navigate to system > select a store (so no default value) en try to change Base URL
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.Saving the value. 

### Actual result (*)

1. cant save and message ' Wrong field specified.' appears
2.

**Comment by ADDISON74** [comment]
I confirm this bug. And it is not related to your option particularly.

If current [Configuration Scope] is set to "Default Config" everything works as expecting we can save any modification in configuration.

If we choose other options from the list like Main Website or Default Store View the error appears and the configuration is not saved. 

This is not a Magento 1.9.4.5 issue. I checked OpenMage 20.0.5 which is working as expected and OpenMage 20.0.6 which introduced this issue.

In my case I cannot use Template Hints anymore. I recommend from now on a solid stressing testing for every new addition to the code before releasing a new version.

**Comment by ADDISON74** [comment]
I managed to solve this issue. Saving Magento configuration in Backend is working again as expected.

Here is the solution I used: https://github.com/OpenMage/magento-lts/issues/1417#issuecomment-765710454
