### ISSUE TITLE
New OpenMage Admin theme stops working when using a customized template

### ISSUE THREAD

**Issue by dbachmann** [OpenMage/magento-lts#1410]
I switched a shop from a customer to openmage and I had to do some template work. So I added the template package and putted my customizations in a new directory in the template package and added this directory in the themes section. After saving the new openmage theme disappered and switched to the default theme. 

When I removed the directory the new theme appeared again. I think the theme switcher needs own paths to work without issues. You can test it, when you enter "default" in templates, skin and layout and save it. 

![error-with-custom-themes](https://user-images.githubusercontent.com/1921769/105412848-8cc9f580-5c35-11eb-90f8-096e5cc63bf8.JPG)

**Comment by kiatng** [comment]
Not sure if PR #1229 will address this issue. The PR still in _Draft_ and need more volunteers to test it.

**Comment by dbachmann** [comment]
Well, this describes the bug very good. I will close this issue now.
