### ISSUE TITLE
Wrong field specified in system > advanced > system

### ISSUE THREAD

**Issue by dbachmann** [OpenMage/magento-lts#1411]
I have an empty OpenMage installation here which is up tp date. When you go to system > advanced > system and you click on save you get the error "wrong field specified". Even when you change anything and save the configuration the error occurs, The logs are empty. I've tested this with php 7.2.34.
![wrong-field](https://user-images.githubusercontent.com/1921769/105419346-d965fe80-5c3e-11eb-93f0-a6598970792b.JPG)

**Comment by sreichel** [comment]
Same as #1409?

**Comment by ADDISON74** [comment]
I confirm this bug. And it is not related to your option particularly.

If current [Configuration Scope] is set to "Default Config" everything works as expecting we can save any modification in configuration.

If we choose other options from the list like Main Website or Default Store View the error appears and the configuration is not saved.

This is not a Magento 1.9.4.5 issue. I checked OpenMage 20.0.5 which is working as expected and OpenMage 20.0.6 which introduced this issue.

In my case I cannot use Template Hints anymore. I recommend from now on a solid stressing testing for every new addition to the code before releasing a new version.

**Comment by ADDISON74** [comment]
I managed to solve this issue. Saving Magento configuration in Backend is working again as expected.

Here is the solution I used: https://github.com/OpenMage/magento-lts/issues/1417#issuecomment-765710454

**Comment by colinmollenhour** [comment]
Added PR in #1418
