### ISSUE TITLE
Inoffensive changes in .htaccess

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1419]
In .htaccess file I would recommend inoffensive changes to bring the code to our days:

line 8: php5.ini => php7.ini

line 16: php5 settings => php7 settings

```
  
############################################
## GoDaddy specific options

#   Options -MultiViews

## you might also need to add this line to php.ini
##     cgi.fix_pathinfo = 1
## if it still doesn't work, rename php.ini to php5.ini

############################################
## default index file

    DirectoryIndex index.php

############################################
## php5 settings

<IfModule mod_php7.c>
```

**Comment by Flyingmana** [comment]
we should think about something more flexible here, as php8 now gains traction...
For the comments we can just be a bit more verbose and mention the relation to the version and give examples php7.ini, php8.ini

**Comment by ADDISON74** [comment]
@Flyingmana: Do you consider this line should be in .htaccess ```#SetEnv MAGE_IS_DEVELOPER_MODE true```? If someone would like to debug can easy uncommenting the line.

**Comment by ADDISON74** [comment]
There is a PR for this issue here #1554.
