### ISSUE TITLE
hideit field in contact template?

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1421]
This is not a bug report just an investigation. Checking frequently logs and reports in production stores based on OpenMage I found today this error:

```
2021-01-23T10:13:27+00:00 ERR (3): Notice: Undefined index: hideit  in /home/mydomain/public_html/app/code/core/Mage/Contacts/controllers/IndexController.php on line 87
```
The template for contact form has an input tag with this name/id: 
 
```<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />```

I filled up the form and I was able to send the request as usual no errors in logs. I went ahead and activated the Inspector in the browser. I deleted the hideit input tag then I filled up again the form. I was able to send the form without any errors in frontend. This time checking the system.log file I found the same error related to an undefined index named hideit. It is clear a bot or a human played today with the contact form and removed that tag and was able to send the message.

Questions:

1. What is the purpose of this hidden input text box?
2. If this field is important for the form OpenMage should not allow sending the message without it.

**Comment by pianopronto** [comment]
I don't know the specifics on how Magento implements this, but typically those fields are meant to be empty by a human filling out the field. A (probably badly coded bot in this day and age) wouldn't know it was an invisible field, fill it out, and Magento would see it was filled and reject the contact form. 

The check could be codded better to not put that entry into the log though.

**Comment by ADDISON74** [comment]
Investigating this issue I found out that if this hidden field is filled up Magento will not send the form and will display an error message. It is obviously it is an import field for the form. If it is removed from the page or there is no value the same behavior should occur. Magento should not send the message too.

I checked the webserver access log and I found the IP responsible for this issue. Accessing it I got an Apache page. I suspect a bot not a human.

**Comment by ADDISON74** [comment]
I will leave this issue open again. I found today in system.log around 7 lines with this error. I suspect bots  but OM should deal with this error.

**Comment by ADDISON74** [comment]
Here is the webserver access log content:

```
195.181.168.168 - - [08/Jun/2021:05:52:33 +0300] "GET /contacts HTTP/1.1" 200 11432 "https://www.mydomain.tld" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
195.181.168.168 - - [08/Jun/2021:05:52:38 +0300] "POST /contacts/index/post/ HTTP/1.1" 302 586 "https://www.mydomain.tld" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
195.181.168.168 - - [08/Jun/2021:05:52:39 +0300] "GET /contacts/index/ HTTP/1.1" 200 11352 "https://www.mydomain.tld" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.50"
```

Here is the system.log file content:
```
2021-06-08T05:52:38+00:00 ERR (3): Notice: Undefined index: hideit  in /home/mydomain/public_html/app/code/core/Mage/Contacts/controllers/IndexController.php on line 87
```

The IP address is listed in DNSBL.

Obviously the form is sent but the hideit variable does not exist. The situation should be provided in the controller when this variable is not defined. I consider it a logical error in the OM code.

**Comment by ADDISON74** [comment]
More feedback related on this issue. **hideit** is used in the following templates:

```
/app/design/frontend/base/default/template/contacts/form.phtml
/app/design/frontend/rwd/default/template/contacts/form.phtml
```

In /app/code/core/Mage/Contacts/controllers/IndexController.php at line 87 there is the following code: 

```
if (Zend_Validate::is(trim($post['hideit']), 'NotEmpty')) {
    $error = true;
}
```

If I would develop a bot I can skip this input text box because I know its name. The name is hardcoded and only those who edit the code can avoid SPAM. I would recommend in OM Backend an option that allows changing this name. 

Better than that I would recommend using **HoneySpam** extension which is a very powerful one. It allows changing the name in Backend. In this case Magento default templates must be edited to remove hideit and the code from above can be removed.
