### ISSUE TITLE
Warnings when customer add configurable product to cart

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1428]
With OpenMage 20.0.6 and PHP 7.4.6, when a customer add a configurable product to his cart, we encounter the following errors in logs:

_strpos() expects parameter 1 to be string, object given_

![image](https://user-images.githubusercontent.com/31816829/105856108-20f6dc80-5fe9-11eb-9098-9e03730952f7.png)

_Illegal offset type in isset or empty_

![image](https://user-images.githubusercontent.com/31816829/105856181-3409ac80-5fe9-11eb-9629-63e7b02eb102.png)

To fix the problem, [we have revert this change](https://github.com/OpenMage/magento-lts/commit/2fe965826a26bf6cfe36b4edba0d51d5e3f31491).

**Comment by matteorossi-thespacesm** [comment]
I've got the same warning on OpenMage LTS 19.4.10. I've just made two pull requests #1431 and #1432 to fix it.

**Comment by luigifab** [comment]
Also #1429
