### ISSUE TITLE
Mage\Customer\sql\customer_setup\upgrade-1.6.2.0.4-1.6.2.0.5.php doesn't expect: "sample_data"

### ISSUE THREAD

**Issue by Luciferiix** [OpenMage/magento-lts#143]
Installer error in with: magento-sample-data-1.9.2.4-2016-10-11-07-38-13

in:
\app\code\core\Mage\Customer\sql\customer_setup\upgrade-1.6.2.0.4-1.6.2.0.5.php

```
$table = $installer->getConnection()
    ->newTable($installer->getTable('customer/flowpassword'))
    ->addColumn('flowpassword_id', Varien_Db_Ddl_Table::TYPE_INTEGER, null, array(
```

fix:

```
$installer->startSetup();
if (!$installer->getConnection()->tableColumnExists($installer->getTable('customer/flowpassword'), 'flowpassword_id')) {
  $table = $installer->getConnection()
```

**Comment by Luciferiix** [comment]
-dead project-

**Comment by colinmollenhour** [comment]
The project is not dead, we just have limited resources and rely heavily on the community to submit PRs and not just report issues. Please submit a PR instead of an issue, it will take you about the same amount of time and the commit will be attributed to yourself. Thanks!
