### ISSUE TITLE
add pbkdf2 module as recommendation into documentation

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#146]
because a improved password hashing by default is recommended
https://github.com/ikonoshirt/pbkdf2

It also supports Backwards Compatibility, so this module also works with longer existing shops

**Comment by tmotyl** [comment]
shouldn't it be also added in composer as recommended dependency?

**Comment by Flyingmana** [comment]
https://github.com/OpenMage/magento-lts/commit/dd94e6dd5cbd8e1490b20ba6b4422f3922bcf0a1
http://openmage.github.io/magento-lts/suggested_modules.html
