### ISSUE TITLE
Warning in composer.json

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1460]
### Steps to reproduce (*)

```
composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
extra.branch-alias.dev-main : the target branch (1.9.4.x) must end in -dev

```

additionally packagist reports the following:

```

Skipped branch 1.9.4.x, Invalid package information:
extra.branch-alias.dev-main : the target branch (1.9.4.x) must end in -dev
```

the problem was introduced by #1160

### Expected result (*)
no warning

we should probably also check the actions check, to make sure warnings also trigger a failed build.

**Comment by sreichel** [comment]
For composer its just a warnings, but it seems to break packist.org repo completly. I'wasn't able do download any version today.
