### ISSUE TITLE
Offloader Header option in Magento

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1461]
In Magento Backend System -> Configuration -> Web there is an input text box in Secure section called **"Offloader header"**. 

I set up a testing environment with HAProxy as SSL termination in front of Apache. I added in HAProxy configuration a new header called **SSL-Offloaded** and set it to **on**. I set in Magento Backend all Base URL's for Unsecure/Secure to start with https protocol. I checked in browser a basic php script with phpinfo function and $_SERVER['HTTP_SSL_OFFLOADED'] variable was set to on as expected. I copied and pasted **HTTP_SSL_OFFLOAD** text in Magento Backed in "Offloader header" input text box. 

After reloading the frontend nothing happened. I started digging the code and there is no reference in Magento where it uses this value. Going further I found that Magento considers a secured connection if there is a header called **HTTPS** set to **on**. I edited .htaccess and I used the following statement:

```SetEnvIf Ssl-Offloaded on HTTPS=on```

Reloading the frontend I was able to get the page. 

I consider this a bug in source code. Even I set a header value for "Offloader header" to tell Magento there is an SSL termination in front of Apache, Magento never uses this value just its own HTTPS value which is hardcoded in a lot of files. Here is the list:

```
/app/code/core/Mage/Core/Model/Config.php
/app/code/core/Mage/Core/Model/Store.php
/app/code/core/Zend/Controller/Request/Http.php
/errors/processor.php
/lib/Zend/Controller/Request/Http.php
/lib/Zend/Controller/Action/Helper/Redirector.php
/lib/Zend/Amf/Response/Http.php
/lib/Zend/Feed/Pubsubhubbub/CallbackAbstract.php
/lib/Zend/Feed/Pubsubhubbub/CallbackAbstract.php
/lib/Zend/OpenId.php
/lib/Zend/View/Helper/ServerUrl.php
/lib/Zend/View/Helper/Gravatar.php
/lib/Zend/Soap/AutoDiscover.php
```

A normal behavior should be as follows: 
```
1. If $_SERVER['HTTPS']=on => secured connection. In this case the value for HTTPS was set in .htaccess (Apache),

2. If "Offloader header" input box has a value check if there is a value set for $_SERVER['HTTP_ <Offloader_header_value>']. If there a value => secured connection.
```

I will check more in detail what is happening in function isCurrentySecure() in /app/code/core/Mage/Core/Model/Store.php

```
    public function isCurrentlySecure()
    {
        $standardRule = !empty($_SERVER['HTTPS']) && ('off' != $_SERVER['HTTPS']);
        $offloaderHeader = trim((string) Mage::getConfig()->getNode(self::XML_PATH_OFFLOADER_HEADER, 'default'));

        if ((!empty($offloaderHeader) && !empty($_SERVER[$offloaderHeader])) || $standardRule) {
            return true;
        }

        if (Mage::isInstalled()) {
            $secureBaseUrl = Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL);

            if (!$secureBaseUrl) {
                return false;
            }
            $urlParts = parse_url($secureBaseUrl);
            $scheme   = isset($urlParts['scheme']) ? ':' . $urlParts['scheme'] : '';
            $port     = isset($urlParts['port']) ? ':' . $urlParts['port'] : '';
            $isSecure = ($scheme == 'https')
                && isset($_SERVER['SERVER_PORT'])
                && ($port == $_SERVER['SERVER_PORT']);
            return $isSecure;
        } else {
            $isSecure = isset($_SERVER['SERVER_PORT']) && (443 == $_SERVER['SERVER_PORT']);
            return $isSecure;
        }
    }
```

In my case of study $offloaderHeader variable is not empty because I filled up its value in backend and also there is a value for $_SERVER[$offloaderHeader] set to on. Normally the function should return true. I should not change .htaccess in this case.

**Comment by colinmollenhour** [comment]
From a quick read of the code I am guessing that it only works to set this value via XML by placing it in the "default" node. So either that should be fixed so it can be set in any scope (may not be practical since this code might be used before the store scope is determined) or the option should be removed from system.xml to avoid confusion.

**Comment by ADDISON74** [comment]
```if ((!empty($offloaderHeader) && !empty($_SERVER[$offloaderHeader]))```

This evaluation could be a problem. Magento is not using the value I filled up in Backend just the one stored in an XML file $offloaderHeader. I will evaluate the if statement leaving only this variable $_SERVER['HTTP_SSL_OFFLOADED']. I should get a secured connection.

$_SERVER['HTTPS'] variable is used in many files. Without setting it to value **on** loading the pages in browser won't work. I guess this is a relic from old times when we used more unsecured or a mix of unsecure (frontend)/secure (backend) connection. 

When secured websites became a necessity the only way to fix this was by editing Apache/Nginx files to add a header. There are many articles on Internet related to this issue but nobody wondered why this should be fixed. I am fine editing .htaccess file but it is not an elegant solution for a newbie.  I would recommend a solution by setting this variable in /includes/config.php. An average user should not dig the code to understand why secured connections are not working when using a reverse proxy with TLS termination in front of the webserver.

PS - .htaccess needs a little polishing. In section related to Apache module Expires some ExpiresByType should be added or removed (e.g. ExpiresByType application/x-shockwave-flash "access plus 1 month").

**Comment by ADDISON74** [comment]
This part is also interesting to analyze: 

```
$urlParts = parse_url($secureBaseUrl);
$scheme   = isset($urlParts['scheme']) ? ':' . $urlParts['scheme'] : '';
$port     = isset($urlParts['port']) ? ':' . $urlParts['port'] : '';
```

I never filled up in Magento backend the secured URL as https://www.mydomain.tld:443/ just https://www.mydomain.tld/. Based on this in my case the port value was not set to anything and this will generate an unsecured connection.

Not only HTTPS should be set to on but SERVER_PORT should be set to 443 (in case it is not passed by the reverse proxy). I have to admit Magento engineers used many directions to deal with secured connection (e.g. X-Forward-For, X-Forward-Proto required headers).

**Comment by ADDISON74** [comment]
It changed the code in function isCurrentlySecure() to return always true and I was not able to load the frontend. 

In conclusion, it is useless to inform Magento that there is a reverse proxy in front of the webserver by filling in that "Offload Header" value in Backend. Magento source code also processes other headers such as HTTP = on, SERVER_PORT = 443, X_FORWARDED_PROTO=https, as if the webserver terminates TLS connections. 

Obviously, it was not taken into account that a load-balancing could be performed on several webservers or a TLS termination on a reverse proxy.

**Comment by colinmollenhour** [comment]
The most common way I've seen is:

`SetEnvIf X-Forwarded-Proto https HTTPS=on`

Because there is also other Zend library code that is not going to be aware of the Magento config.

But, good observation. It seems that this:

```
                && ($port == $_SERVER['SERVER_PORT']);
```

should be something like this:

```
                && ( ! $port || $port == $_SERVER['SERVER_PORT']);
```

And what is up with prefixing the scheme and port with `':'`? It seems that `$scheme` would be `':http'` or `':https'` and `$port` would be either `':8080'` or empty?

Lastly, it looks like you discovered this [long ago](https://github.com/nexcess/magento-turpentine/issues/981) but the header values in PHP have to be referenced with a 'HTTP_' prefix so 'SSL_OFFLOADED' will never be true, only 'HTTP_SSL_OFFLOADED' would be.

Summary of issues:

- `$scheme` and `$port` incorrectly prefixed with ':'
- scheme detected as https does not work if port not specified
- in general this `offloader_header` config is ill-advised but I see there is a special event observer when it is changed so we probably can't just remove it..

**Comment by ADDISON74** [comment]
Magento considers a secure connection if there is one of these headers set:

- X-Forwarded-Proto=https
- HTTPS=on

By setting X-Forwarded-Proto=https as request header in HAProxy backend I was able to load Magento frontend. It did not work adding HTTPS=on. In this case there is not need to change .htaccess file content for adding HTTPS=on.  My opinion "Offloader header" value set in Backend is useless. 

Indeed I was familiar with Turpentine project and I was able to provide some tips related to Pound configuration in front of Varnish. I abandoned Pound for HAProxy and Envoy.

**Comment by colinmollenhour** [comment]
`HTTPS=on` does not refer to a header, it is a server variable that has to be set from the php engine. For example with nginx it is usually done like so:

```
fastcgi_param  HTTPS              $https if_not_empty;
```

> My opinion "Offloader header" value set in Backend is useless.

Agreed, it appears to be completely broken.. I pushed a fix for it in #1462 if you're interested in trying it out.

**Comment by ADDISON74** [comment]
You are correct. There are two different values one is an environment variable set by the webserver the other one is a value coming from request header set by the reverse proxy (this one starts with HTTP_ prefix). The goal is by setting a header value in reverse proxy then to inform Magento there is a reverse proxy in front of the webserver which is deal with TLS termination (Offloader header value).

In the past I have used the solution letting the webserver to set an environment variable HTTPS=on without asking myself why such a change is necessary that is not available to everyone and especially that it has been omitted from the documentation.

I will implement two scenarios: one when the webserver is dealing with TLS connections and another one when the reverse proxy is dealing with TLS connection and passes unencrypted connection to Magento. I will check what are the $_SERVER[] values in both cases then look into the Magento code. It is strange there are a lot of variable used in many files to achieve a secured connection but setting a header X-Forward-Proto to https is enough. Most of the if statements and "Offloader header" value seem to be useless.

As an immediate solution I am thinking of using the /includes/config.php file where to evaluate the "Offloader header" value. If this value exists in the Backend and if there is a header with this value then we can set all server variables to the values that are used in the if evaluations in Magento code. For example HTTPS = on, X-Forwarded-Proto = https, SERVER_PORT = 443.

**Comment by ADDISON74** [comment]
I finished implementing those 2 scenarios for getting header/server variables when Apache is dealing with SSL and SSL termination is done in HAProxy. Here are the results for $_SERVER['...']:

```
[REMOTE_ADDR] => 192.168.200.1 (Apache) / [REMOTE_ADDR] => 192.168.200.129 (HAProxy)
[SERVER_PORT] => 443 (Apache)           / [SERVER_PORT] => 80 (Haproxy)
                                        / [HTTP_X_FORWARDED_FOR] => 192.168.200.1 (Haproxy)
```

And this is related to Apache SSL only:

```
[SSL_SESSION_RESUMED] => Initial
[SSL_SESSION_ID] => 8e7a4f74acf918d6be405cd721c5bf363bcd26f0cdd8378961d46a21713d907b
[SSL_SERVER_A_SIG] => sha256WithRSAEncryption
[SSL_SERVER_A_KEY] => rsaEncryption
[SSL_SERVER_I_DN] => emailAddress=mydomain@mydomain.net,CN=*.mydomain.net,O=Host default domain
[SSL_SERVER_S_DN] => emailAddress=mydomain@mydomain.net,CN=*.mydomain.net,O=Host default domain
[SSL_SERVER_V_END] => Feb 15 22:01:49 2026 GMT
[SSL_SERVER_V_START] => Feb 16 22:01:49 2021 GMT
[SSL_SERVER_M_SERIAL] => 70484E3D6CC996422ACDFB6489B9753687DCB3A8
[SSL_SERVER_M_VERSION] => 3
[SSL_CLIENT_VERIFY] => NONE
[SSL_CIPHER_ALGKEYSIZE] => 128
[SSL_CIPHER_USEKEYSIZE] => 128
[SSL_CIPHER_EXPORT] => false
[SSL_CIPHER] => TLS_AES_128_GCM_SHA256
[SSL_COMPRESS_METHOD] => NULL
[SSL_SECURE_RENEG] => false
[SSL_PROTOCOL] => TLSv1.3
[SSL_VERSION_LIBRARY] => OpenSSL/1.1.1d
[SSL_VERSION_INTERFACE] => mod_ssl/2.4.38
[SSL_SERVER_SAN_DNS_0] => mydomain.net
[SSL_SERVER_I_DN_Email] => mydomain@mydomain.net
[SSL_SERVER_I_DN_CN] => *.mydomain.net
[SSL_SERVER_I_DN_O] => Host default domain
[SSL_SERVER_S_DN_Email] => mydomain@mydomain.net
[SSL_SERVER_S_DN_CN] => *.mydomain.net
[SSL_SERVER_S_DN_O] => Host default domain
[SSL_TLS_SNI] => www.mydomain.net
[HTTPS] => on
```

As we can see HTTPS=on tells Magento we have a secure connection with Apache. This is the main reason over the years people recommended adding a server variable in .htaccess. X-Forwarded-For is also important as value when setting a reverse proxy server and headers like "Offloaded header" or X-Forwarded-Proto. SERVER_PORT is not relevant.

I will post a new issue related to the chain of IP addresses in Backend -> Orders page when the webserver is behind a reverse proxy server. I am getting 3 IP's instead of one which should be the remote address. I found a quick solution I would like to discuss.
