### ISSUE TITLE
is RELEASE_NOTES.txt useless?

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#1465]
Hi everybody, in the RELEASE_NOTES.txt there are links to the old magento docuementation which doesn't exist anymore (all links are dead).

Unless we switch to openmage doc (but then openmage versions should be added) I suggest to remove the file completely.

**Comment by ADDISON74** [comment]
For a lot of files in Magento root directory I created .htaccess RedirectMatches to 404 in order to stop the visitors looking in files like RELEASE_NOTES.txt. Except index.php all the other files should be hidden. For a potential attacker is a good tip to know what is the version number of Magento.

**Comment by fballiano** [comment]
agree, but it contains old and misleading information so I'd remove it completely

**Comment by colinmollenhour** [comment]
I am in favor of removing all files that are not necessary and are not being maintained.

**Comment by Flyingmana** [comment]
And in case someone needs the actual OpenMage changelog, then we have it in a subdirectory stored already.
https://github.com/OpenMage/magento-lts/tree/20.0/.github/changelog

**Comment by sreichel** [comment]
Fixed with #1469
