### ISSUE TITLE
USPS: Unsecure HTTP Endpoint Retirement

### ISSUE THREAD

**Issue by jouriy** [OpenMage/magento-lts#1493]
### Preconditions (*)

1. Effective June 24 th , 2021, USPS Web Tools will remove support for all unsecure HTTP endpoints. According to the USPS Web Tools API Release Notes <https://www.usps.com/business/web-tools-apis/2021-web-tools-release-notes.pdf> (section 2.6.1 on page 6):
 After this change, all requests to an unsecure HTTP endpoint will fail when attempting to access the Web Tools APIs and integrators may see an error message. To continue using the Web Tools APIs, all requests must be made using the secure HTTPS endpoints listed below. Integrators currently using an unsecure HTTP endpoint should transition as soon as possible to the appropriate secure HTTPS endpoint below to prevent any loss of service. This change will impact only the API endpoints; the API request and response schemas will not change.

Environment | Unsecure | HTTP Endpoint Retirement Date | New Secure HTTPS Endpoint
TEST | http://stg-production.shippingapis.com | 06/24/2021 | https://stg-production.shippingapis.com
PROD | http://production.shippingapis.com | 06/24/2021 | https://production.shippingapis.com

The endpoint is defined in app/code/core/Mage/Usa/Model/Shipping/Carrier/Usps.php https://github.com/OpenMage/magento-lts/blob/75267499f4f8b9f53528b904dff3d48490a3deb1/app/code/core/Mage/Usa/Model/Shipping/Carrier/Usps.php#L115
and app/code/core/Mage/Usa/etc/config.xml https://github.com/OpenMage/magento-lts/blob/75267499f4f8b9f53528b904dff3d48490a3deb1/app/code/core/Mage/Usa/etc/config.xml#L197
### Steps to reproduce (*)

N/A

### Expected result (*)

USPS gateway endpoint URL should be updated to HTTPS schema: https://production.shippingapis.com prior to June 24, 2021.

### Actual result (*)

N/A

**Comment by sreichel** [comment]
@all-contributors add @jouriy bug
