### ISSUE TITLE
Enable legacy Admin Theme

### ISSUE THREAD

**Issue by TangLiang** [OpenMage/magento-lts#1501]
app/code/core/Mage/Adminhtml/Controller/Action.php
if (Mage::getStoreConfigFlag('admin/design/use_legacy_theme')) {
      $theme = Mage::getConfig()->getNode("stores/admin/design/theme/default");
  } else {
      $theme = Mage::getConfig()->getNode("stores/admin/design/theme/openmage");
  }
it will be 
if (Mage::getStoreConfigFlag('admin/design/use_legacy_theme')) {
      $theme = Mage::getConfig()->getNode("stores/admin/design/theme/openmage");
  } else {
       $theme = Mage::getConfig()->getNode("stores/admin/design/theme/default");
  }

**Comment by kiatng** [comment]
Thanks for your bug report. I have reviewed and tested the code in https://github.com/OpenMage/magento-lts/blob/57563fcc40a8702afa7c375ba51a931c7b6295e8/app/code/core/Mage/Adminhtml/Controller/Action.php#L145-L157

The admin theme is behaving as expected for both legacy and the new openmage theme, shown here legacy config:

![image](https://user-images.githubusercontent.com/1106470/111270303-a81c1480-866a-11eb-8fcf-df7828dd2b91.png)

Please follow the template **strictly** when reporting a bug:

![image](https://user-images.githubusercontent.com/1106470/111269474-a4d45900-8669-11eb-849d-29e05c7c5ca1.png)

**You should not remove anything on the template.** Just write brief description under each applicable section. This will help the community to identify the issue.
