### ISSUE TITLE
OpenMage Feed Notifications in Backend

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1507]
OpenMage is using this URL for feeding notifications in Backend:

```
<feed_url>www.openmage.org/Web_Notifications/notifications_v1.rss</feed_url>
```

If you check this page content you will see an item from 2019, "Thank you for installing OpenMage M1 LTS!".

I suggest to use this feature and send periodically notifications related to OpenMage, at least for new releases and features. For example, there is a new feature related to ordering Terms & Conditions in checkout, we improved the speed for X, we fixed the Y.

**Comment by fballiano** [comment]
I'd like to see the adminnotifications dead and buried 😅😅
But if it has to stay it should be used as you propose :-)

**Comment by fballiano** [comment]
But I think this issue is a duplicate of https://github.com/OpenMage/magento-lts/issues/683

**Comment by daboss84** [comment]
This seems to affect Amasty plugins. Due to parsing errors in the logs, I tried to deactivate the whole notifications Plugin in Mage_All.xml and the backed of the store with Amasty Plugins was dead. The other one without those did still work.

**Comment by fballiano** [comment]
I usually just disable admin_notification output, instead of deactivating it, but we could simply create a module that fixes the amasty notification system...

**Comment by daboss84** [comment]
I have the output disabled, but still had the parsing errors in the logfile.
By the way, Wyomind Watchlog also depends on admin notifications:
`
Wyomind_Watchlog_Helper_Data::checkNotification(){
// ...
$notify = Mage::getModel('adminnotification/inbox');
$item = $notify->getCollection()->addFieldToFilter('title', array("eq" => "Watchlog security warning"))->addFieldToFilter('is_remove', array("eq" => 0));
//...
}
`

So I hope OM does not just remove it ;)

**Comment by ADDISON74** [comment]
I close this issue. Please follow the discussions here #1655.
