### ISSUE TITLE
Product qty is incremented when comment is added on a Credit Memo from SOAP API v2

### ISSUE THREAD

**Issue by medgoprot** [OpenMage/magento-lts#1517]
### Preconditions (*)

1. Should be reproducible on Open Mage.

### Steps to reproduce (*)

1. Create a Credit Memo for any order either through the SOAP API v2 or the Admin panel
2. Add a comment on a Credit Memo via the SOAP API v2 and note the qty of the products in the inventory before and after

### Expected result (*)

1. Adding a comment on the Credit Memo should not cause the refunded products' inventory qty to increment again

### Actual result (*)

1. Adding a comment via the SOAP API causes the refunded products' inventory qty to be incremented again

After a long debugging session, it was found that the problem is arising from `Mage_CatalogInventory_Model_Observer#refundOrderInventory` which is observing the `sales_order_creditmemo_save_after` event that is dispatched after *any* `save()` of the Credit Memo, this is because in the event observer method (`refundOrderInventory`), there is no check to see whether the creditmemo object is new or not therefore it keeps adding the qty for all order items on every save.
Thanks

**Comment by fballiano** [comment]
I tested it but couldn't reproduce the error.

<img width="642" alt="Schermata 2021-04-28 alle 17 22 46" src="https://user-images.githubusercontent.com/909743/116438448-5c05e780-a846-11eb-8583-83ccff1c7eba.png">

The qty is always 1, also if the last comment was added via SOAP.

**Comment by fballiano** [comment]
is salesOrderCreditmemoAddComment is method you call?

**Comment by medgoprot** [comment]
@fballiano Yes that's method being called. Are you sure that the inventory qty of the refunded product stays the same when commenting via SOAP API? I updated the issue to make it more clear

**Comment by fballiano** [comment]
the last comment on my screenshot was added via soap but the qty was kept at 1.

**Comment by fballiano** [comment]
another order, with ordered_qty = 10, refunded_qty = 1, created some comments via soap:

<img width="1126" alt="Schermata 2021-04-28 alle 17 54 25" src="https://user-images.githubusercontent.com/909743/116442810-d9335b80-a84a-11eb-9525-b9fd5814960b.png">

i'm on OM 20.0.10 tho

**Comment by medgoprot** [comment]
@fballiano Yes, but can you note the qty of the product in the **inventory** before vs. after adding the comment and see if it changes?

**Comment by medgoprot** [comment]
I'm talking about this qty, it should increment each time after adding a comment from the SOAP API

![Screen Shot 2021-04-28 at 17 02 19](https://user-images.githubusercontent.com/61865721/116443795-9ae66e00-a843-11eb-9a61-95ed8843d5fd.png)

**Comment by fballiano** [comment]
so it's not the refunded_qty but the qty that goes back to stock?

**Comment by fballiano** [comment]
do you have this?

<img width="651" alt="Schermata 2021-04-28 alle 18 17 51" src="https://user-images.githubusercontent.com/909743/116445680-0d5c4b80-a84e-11eb-8b95-3b28fdeab835.png">

**Comment by fballiano** [comment]
oki, understood and reproduced

**Comment by fballiano** [comment]
I just submitted a PR which solves the problem on my local installation.

**Comment by sreichel** [comment]
@all-contributors add @medgoprot bug
