### ISSUE TITLE
Backend hints are now useless

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#1518]
The backend is showing a couple of "hints" linking to the old magento.com documentation, which is no longer available. Those links were useless when the doc was online, they're now more useless.

Screenshots:
<img width="247" alt="Schermata 2021-04-02 alle 17 07 36" src="https://user-images.githubusercontent.com/909743/113433083-7202c280-93d6-11eb-9c1d-a410b1f735e5.png">
<img width="305" alt="Schermata 2021-04-02 alle 17 07 33" src="https://user-images.githubusercontent.com/909743/113433089-7333ef80-93d6-11eb-80d6-5433bcbb68a4.png">

If you agree I'd create a PR removing all that code, for the v20 branch.

**Comment by jouriy** [comment]
ref #1376

**Comment by fballiano** [comment]
oops sorry! I searched for "hints" and didn't find anything, closing this one!
