### ISSUE TITLE
Forward porting of changes in 1.9.3.x to 1.9.4.x

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1526]
Some changes/Pull Requests were merged into 1.9.3.x

please verify no PullRequests are still targeting this branch(or list the ones, which do), and list the changes of 1.9.3.x which are missing in 1.9.4.x

**Comment by Sekiphp** [comment]
https://github.com/OpenMage/magento-lts/commit/d283552ce4650a4b6a914dbb3f54f42e04af1b98
https://github.com/OpenMage/magento-lts/pull/447/files
https://github.com/OpenMage/magento-lts/pull/583
https://github.com/OpenMage/magento-lts/pull/589
https://github.com/OpenMage/magento-lts/pull/1022
https://github.com/OpenMage/magento-lts/pull/575

**Comment by Flyingmana** [comment]
So after mergin the one PR now only these are left missing?
* https://github.com/OpenMage/magento-lts/pull/589
* https://github.com/OpenMage/magento-lts/pull/1022

or were they covered by another PR?

**Comment by elidrissidev** [comment]
@Flyingmana I just did a comparison between `1.9.4.x` and `1.9.3.x` and the changes that show up are all present in `1.9.4.x`

**Comment by ADDISON74** [comment]
Is this still an issue? If not we should close it.
