### ISSUE TITLE
Feature request: sandbox

### ISSUE THREAD

**Issue by midlan** [OpenMage/magento-lts#1528]
### Description (*)
I think this project needs some sandbox, to easily test something.

One of the sanboxes I really like is this one:
https://www.softaculous.com/demos/Magento_1.9

It will start new magento instance and give you unique URL. You can play as you want with the instance. Maybe we can ask the author to migrate it to openmage? This sandbox can also solve the lack of **demo** instance of this project.

Other sandbox I discovered is this one:
https://phpsandbox.io/

It is coding sandbox which launches one of prepared envirnments. It would be nice to have such place where I can put some piece of code and see the actual result.

Anyone also miss such features?

**Comment by colinmollenhour** [comment]
Hi @midlan there actually is a demo here: https://demo.openmage.org/ although I don't know that it is linked from anywhere..

Are you talking about developers or end users? For developers there are multiple ways to quickly setup a test environment, for example this [single command](https://github.com/OpenMage/magento-lts/tree/1.9.4.x/dev/openmage#readme): `dev/openmage/install.sh`

**Comment by midlan** [comment]
Yes thats what I was searching. We should link it from openmage.org website and README.md then?

https://demo.openmage.org/admin

I didn't find admin password. Is the admin area for public testing?

**Comment by Flyingmana** [comment]
the admin area there is not for public testing, as we do not have regular Database Reset implemented.

phpsandbox seems a bit to limited regarding resources, and does not provide a database, so we currently cant run OpenMage there I think.

softaculous looks good, anyone who wants to take over contacting them?

**Comment by Flyingmana** [comment]
@midlan does the new integration with gitpod solve a part of this?

**Comment by fballiano** [comment]
Closing since @midlan (the author) is not providing feedback since 6 months.
