### ISSUE TITLE
Should we mv install.php?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#153]
Should we mv install.php?

Just saw some request being made on our server to install.php - after upgrading via LTS this file is recreated everytime. 

Question: how logic is it that a newby user would use LTS as a first time Magento install? And can we move or rename install.php so it is not executed anymore

Anyone installing from here can anyways read the README and read something like rename file "xxx" to install.php before installing

**Comment by Flyingmana** [comment]
I would keept it for now, because it could cause problems with magento doing patches in this area.
Then later we would need to decide which ways of install we would advertise, and iam not use, but I belive magerun makes use of the install.php?

**Comment by sreichel** [comment]
> Question: how logic is it that a newby user would use LTS as a first time Magento install? And can we move or rename install.php so it is not executed anymore

I had this "problem" during last days ;)

We use LTS and a new colleague had to install a fresh magento (that matches our prod envirement). He's completly new to magento/magerun/composer/git so i told him to just to do `git clone LTS` and follow the installer. Next steps are magerun/composer, but `install.php` was the easiest/fasted solution for now.

I'd close this (non-)issue and keep it as it is ;)

**Comment by drobinson** [comment]
Agreed, install.php being there isn't a bug, nor is it cause for any security concern (that I'm aware of).
