### ISSUE TITLE
sitemap.xml issues with Google Merchant? 

### ISSUE THREAD

**Issue by LuizSantos1** [OpenMage/magento-lts#1546]
### Summary (*)

Hi there,
I am using OpenMage latest version, I have generated sitemap.xml and tried uploading it to Google Merchant but it is 
not working. Google says it is not in the right format or tags. I have tried to investigate it further, but Google
does not give any clue

### Examples (*)

Tried to upload sitemap.xml or use www.mysite.com/sitemap.xml and Google Merchant does not
recognize it. 
I get this message: "The product data you submitted in the feed does not meet the product data specification . As a result, your items have not been approved. Correct and update your feed to display products to customers. To see all errors, go to Diagnostics ." 

Google has recently changed some policies, maybe is that the problem?

### Proposed solution

Make it compatible with Google Merchant or give me some clue of an extension that does that.

Regards

**Comment by pauldpauld** [comment]
Hi, I am just trying to help, look at this;
"To see all errors, go to Diagnostics" 
perhaps you could paste those diagnostics here for us?
Regards, Paul

**Comment by LuizSantos1** [comment]
@pauldpauld 
It does not say much, only "XML formatting error"
I clicked the tab and I got this:
"Our system encountered an error while processing your data feed."
When I hit "know more" I get this link: [https://support.google.com/merchants/answer/160039](url)

It has some more info:
"Error parsing/validating XML feed
Our system encountered an error when processing your XML data feed. Please see the following Help Center topics for more information:

XML tag mismatch

Invalid RSS/Atom document format"

When I hit "XML tag mismatch I get this link: 
[https://support.google.com/merchants/answer/160046#zippy=%2Cstep-see-the-affected-products](url)

I use creare SEO and I have never had problems with feed

I know they have changed something now on April 06, so I am guessing it might be this
I am sending a link of the sitemap.xml. I am not seeing anything different than I used to use. 

See the link: [https://drive.google.com/file/d/1t4q5-mJ-Fmo5XVPS7YyxJjW06dRyqgdS/view](url)

I know that some agencies provide automated Google Product Feed for free but I have forgotten 
the ones that works with Magento 1.9 or Openmage...

**Comment by LuizSantos1** [comment]
@pauldpauld 
Hummm... I guess Magento sitemap.xml is not compatible with Google Shopping and Product feed anymore...
I am trying to find out a free solution that does not make me add mpns and upcs to every products which would be a pain in the ass...

**Comment by pauldpauld** [comment]
It may be that GTIN (or MPN if it doesn't have a GTIN) is what is tripping up your feed.
It does say required in Google specs, but, you might be able to get away with this;
Optional 
<snip>
Use to indicate whether or not the unique product identifiers (UPIs) GTIN, MPN and brand are available for your product.

Example
no [no]

Supported values  

    yes [yes]
    Product identifiers are assigned to the new product by the manufacturer.
    no [no]
    Product lacks a brand, GTIN or MPN (see requirements to the right). If set to no [no], still provide the UPIs that you have.
</snip>

**Comment by LuizSantos1** [comment]
It is not saying that, it is only saying xml tag is not compatible or something like that
in shopping free list, it is saying product lacks review attribute, which does not make any sense since it is there...
I am trying to find a 3rd party free extension feed generator to see if it works...

It looks like Google always changing policies are trying to put the small business out of the way.

**Comment by simbus82** [comment]
Sorry but the sitemap file sitemap.xml is not compatibile with a "product feed" for Google Merchant. They are two really different things.
A sitemap is a list of all url that are in the website.
A products feed for Google Merchant/shopping is a xml very rich in data about products, categories and lot of other "commercial" data about products list, like price, shipping costs, taxes, etc.

![image](https://user-images.githubusercontent.com/1375730/114475842-5d55d400-9bf9-11eb-8b77-a0ce0731a865.png)

**Comment by daboss84** [comment]
I don't think, the build-in sitemap is meant to be used like this. We ended up using Wyomind's Data Feed manager: https://www.wyomind.com/data-feed-manager-magento.html (or cheaper, but less flexible: Simple Google Shopping: https://www.wyomind.com/google-shopping-magento.html)
(But finally, we implemented this functionality on our own because of our "custom" way of handling some product/attribute data).

**Comment by LuizSantos1** [comment]
@simbus82 @daboss84 
I have found this free extension, if anybody is up to develop it further, let me know...
But I guess it should have a free extension for this, at least one.
https://github.com/adampmoss/GoogleShopping

**Comment by yurirn** [comment]
@LuizSantos1 
are you all right? so I saw that you have a problem with your product FEED to send to GOOGLE MERCHANT
I have a free extension that does this, I developed it, the sitemap.xml is to be used in the google search console only and not in the merchant center
call me at yuri@twocommerce.com.br I will help you

tudo bem com você? então vi que esta com um problema no seu FEED de produtos para enviar para o GOOGLE MERCHANT
eu tenho uma extensão gratuita que faz isso, eu desenvolvi, o sitemap.xml é para ser usado no google search console somente e não no merchant center
me chama no yuri@twocommerce.com.br que te ajudo [BR]

**Comment by LuizSantos1** [comment]
@yurirn Te enviei uma mensagem diretamente por e-mail.
Me quebraria um galho essa extensão. Estou usando uma provisória...

**Comment by elidrissidev** [comment]
Closing since `sitemap.xml` isn't meant to be used as a product feed for Google Merchant.
