### ISSUE TITLE
Invoice PDF payment method rendering broken in v19.4.12

### ISSUE THREAD

**Issue by rfeese** [OpenMage/magento-lts#1548]
### Preconditions (*)

1. v19.4.12
2. Pull request that created the issue: https://github.com/OpenMage/magento-lts/pull/1201

### Steps to reproduce (*)

1. Navigate to an existing Sales Order Invoice in admin area.
2. Click Print button
3. Check Payment method section of the invoice, it is corrupted due to applying an HTML template instead of  PDF.

### Expected result (*)

1. The payment method section of the invoice PDF should be rendered using the default PDF template.

### Actual result (*)

1. The payment method section of the invoice PDF is rendered using the HTML template, which breaks the PDF formatting.

Magento-LTS core does not appear to contain PDF email attachment options that the author of the pull request mentioned, so I suspect they may have been using an add-on module which may contain a bug. The PDF payment templates certainly do exist (https://github.com/OpenMage/magento-lts/tree/1.9.4.x/app/design/adminhtml/default/default/template/payment/info/pdf).

**Comment by kiatng** [comment]
The payment block `Mage_Payment_Block_Info` is retrieved from the helper (L322)

https://github.com/OpenMage/magento-lts/blob/d44a8dd66edc2e33b980bab2c1aa0f114ee51553/app/code/core/Mage/Sales/Model/Order/Pdf/Abstract.php#L321-L326

But the function `toPdf()`, due to the PR, now returns the HTML template instead of the PDF template.

**Comment by colinmollenhour** [comment]
Any idea what the fix should be? Should #1201 simply be reverted?

**Comment by kiatng** [comment]
Yes, the PR needs to be reverted.

**Comment by rfeese** [comment]
I agree, the solution is to revert #1201, which I have had to do in a local repo. Is there a way I could help by making a PR that reverts the #1201 PR or is it easier for a maintainer to perform this using the github UI? Sorry, I am a github newb.

**Comment by ADDISON74** [comment]
Did anyone revert PR #1201? If yes we should close this issue.

**Comment by fballiano** [comment]
It wasn't reverted but I created PR https://github.com/OpenMage/magento-lts/pull/2179 to revert it

**Comment by fballiano** [comment]
closing since https://github.com/OpenMage/magento-lts/pull/2179 was merged
