### ISSUE TITLE
Can not select multiple statuses with Prototype 1.7.3 in Reports

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1549]
With the update of Prototype 1.7.3, we can not select multiple order statuses in Reports.

### Steps to reproduce 
1. Go to Reports / Sales / Coupon
2. Select more than one order status
3. Run in console: `Form.serializeElements($$('#sales_report_order_statuses'))`
4. Try to show report
5. Only one status is selected

### Results
1. With prototype 1.7: `"order_statuses%5B%5D=closed%2Ccomplete"`
2. With prototype 1.7.3: `"order_statuses%5B%5D=closed&order_statuses%5B%5D=complete"`\
It break `Mage_Adminhtml_Block_Report_Filter_Form::_initFormValues`.

Perhaps we can fix with:
```php
    protected function _initFormValues()
    {
        $data = $this->getFilterData()->getData();
        foreach ($data as $key => $value) {
            if (is_array($value) && isset($value[0]) && (count($value) == 1)) {
                $data[$key] = explode(',', $value[0]);
            }
        }
        $this->getForm()->addValues($data);
        return parent::_initFormValues();
    }
```

**Comment by ADDISON74** [comment]
I did all your steps except the third. This is an OpenMage 20.0.8 installed from scratch based on the sample package from Magento 1.9. Here are the results:

**Before pressing [Show Report] button**

![before](https://user-images.githubusercontent.com/8360474/114929078-068c0c80-9e3c-11eb-940f-c7c58a78f199.jpg)

**After pressing [Show Report] button**

![after](https://user-images.githubusercontent.com/8360474/114929094-0986fd00-9e3c-11eb-9d0e-eb25bbc0f691.jpg)

**The bug is confirmed!** It does not appear in version 20.0.6 that I am currently working on.

**I suggest immediately replacing the Prototype library with the previous version and carefully checking version 1.7.3 compared to 1.7 before adding to the new versions to avoid any issue.**

@luigifab - I appreciate for your help.

**Comment by Flyingmana** [comment]
Iam also in favor of reverting it for now.
Does it happen on a specific browser, or in general?
Does someone volunteer to submit the issue upstream to prototype?

**Comment by kiatng** [comment]
Ref this commit [Add test and changes for serializing forms with multiple select to a string to work again](https://github.com/prototypejs/prototype/commit/24414bfb1adb83616f7de09266d3eb190a533326) in prototype repo, the serialization of multiple select is supposed to be like this

```js
this.assertEqual("peewee=herman&colors=blue&colors=yellow&colors=not+grey&number=2", form.serialize(false));
```
A use case for array insead of returning comma-delimted string is when the value contains comma, which will be wrongly parsed.

The title of the commit says to make it work again, it so happens we can test that in [version 1.6](http://prototypejs.org/doc/1.6.0/form/serialize.html):

![image](https://user-images.githubusercontent.com/1106470/114971152-599ea780-9eae-11eb-9291-e1064ef97dd1.png)

Note the popup is `hobbies=coding&hobbies=swimming`. Also take a look at the end of the screenshot:

> Keep in mind that "hobbies" multiple select should really be named "hobbies[]" if we're posting to a PHP or Ruby on Rails backend because we want to send an array of values instead of a single one.

For this issue, we can get the values of `order_statuses`  by `$values = $this->getRequest()->getParam('order_statuses');`

So, if that is the case, what do we do? Revert prototype and re-introduce the "bug", or fix OM?

**Comment by ADDISON74** [comment]
If someone makes it quick I suggest fixing OM and checking the new library too. A comparison with the previous version we used in OM for a long time is a must.

**Comment by colinmollenhour** [comment]
I reverted the change to the serialize behavior so it is compatible with the old Prototype without reverting the entire file in #1552

**Comment by ADDISON74** [comment]
Now that we have a quick fix that works maybe we should consider whether the initial form of the Prototype library brings real improvements. I am of the opinion that if it brings improvements then it should be used as such, following that the change will happen in the OpenMage code as suggested @luigifab suggested.
