### ISSUE TITLE
2 problems: minicart generates errors during product cancellation, Openmage does not write error reports 

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#1550]
Platform:
OpenMage updated on April 3rd
PHP7.4
Apache 2
Redis 5.0.x
ubuntu server 20.04

Scenario:
-I purchase a product
-The system adds the product to the minicart and redirects to the cart
-If I am on the page in ../checkout/cart/ and from the mini cart I cancel the working product.
-If I'm on another page and I try to delete the product from the minicart, openmage crashes and generates an error report.

2 problem
Openmage does not write error reports to / var / report when a major error occurs.

sorry for english i use google translate

**Comment by kiatng** [comment]
The error report in `/var/report` is printed here: https://github.com/OpenMage/magento-lts/blob/d44a8dd66edc2e33b980bab2c1aa0f114ee51553/app/Mage.php#L1005
in `public static function printException()`.

When there is no error report in `/var/report`, one possible cause is that the server environment var `MAGE_IS_DEVELOPER_MODE` is set to `true`. If this is not the case, another maybe is PR #1442, as the call to print the report all happen in `catch (Exception $e)`, example:
https://github.com/OpenMage/magento-lts/blob/d44a8dd66edc2e33b980bab2c1aa0f114ee51553/app/Mage.php#L718-L720

In PHP7, `Exception` catches user errors but doesn't catch internal PHP errors.

**Comment by Danieleeffe1** [comment]
Hello everybody.

Update

going by exclusion and disabling the installed plug-ins one by one, I discovered that the minicart error is generated by the Lesti_FPC plug-in.

Disabling this plug-in the system becomes stable again
