### ISSUE TITLE
Exception during cache and session cleaning

### ISSUE THREAD

**Issue by tmccaff** [OpenMage/magento-lts#156]
I get this error every time I try to install an extension through Magento Connect Manager

Cleaning cache

Exception during cache and session cleaning

**Comment by colinmollenhour** [comment]
Probably file permissions but you give so little detail I have no other ideas. Also I doubt this is a bug with magento-lts so other venues for help should be used instead.

**Comment by tmccaff** [comment]
Here is a screenshot;
![screen](https://cloud.githubusercontent.com/assets/11132826/21874946/42f0665a-d846-11e6-876f-8ac4314c134e.jpg)
