### ISSUE TITLE
AddThis_SharingTool not working anymore 

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1569]
If you are using the AddThis_Sharing Tool extension disable it as fast as you can in /app/etc/modules and flush the cache. Since yesterday the service no longer works properly and the loading of the page does not stop. I didn't have the patience to wait until it loads but I can say that after 5 minutes it continues to load.

This is how AddThis block appears in frontend. Instead of a number greater than or equal to zero appearing at the end, a question mark appears.

![Screenshot 2021-04-27 111858](https://user-images.githubusercontent.com/8360474/116210045-2defad00-a74b-11eb-9325-8398207386bb.jpg)

Many themes use this extension. I hope to find a solution as soon as possible. Most likely they changed something in the AddThis script code, I'm not aware of that.

**Comment by pauldpauld** [comment]
I had this happen to my website about a year ago, it was actually a problem with the AddThis server not responding to queries. You might find in a few hours, the server is working again.
(I deleted AddThis from my website, couldn't have that error blocking sales...)

**Comment by ADDISON74** [comment]
Digging after some information nothing changed in AddThis code. There are no announcements yet. Initially I thought the browser or its Ad Blocker extension blocked its content. It seems it is a server error. For the moment I disabled the extension in all stores I manage. If this continue I will remove it too.

Any suggestion for alternatives? If they deal with Magento it will be great.

**Comment by fballiano** [comment]
I strongly suggest you not to use those services (expecially if you're a european company) unless you setup them with cookie prior consent. They will call multiple remote servers to download their stuff (lighthouse will not be happy) and store multiple tracking cookies.

Anyways, do you have an URL where we can see the error happening?

**Comment by ADDISON74** [comment]
@fballiano I am sorry but I am not allowed by contract to provide information about the projects I manage, especially when there are issues.

**Comment by fballiano** [comment]
well... then another environment where it's possible to still see the error...

**Comment by ADDISON74** [comment]
If you have a test environment please download this extension from here:

https://github.com/OpenMageModuleFostering/addthis_sharingtool

I am using the latest version 2.3.0.

**Comment by fballiano** [comment]
it's awful but works perfectly

<img width="729" alt="Schermata 2021-04-27 alle 11 47 51" src="https://user-images.githubusercontent.com/909743/116229454-70ff4f80-a74e-11eb-9ba7-d9c91683ae32.png">

**Comment by ADDISON74** [comment]
@fballiano I appreciate for testing. 

After 1 day of waiting I confirm the things came back to normal. I will revise if I continue using this extension or not. A page which is not stopping from loading is not good for rakings.

Those who are using this extension please pay attention in the future.

**Comment by fballiano** [comment]
please, don't use this module:

<img width="694" alt="Schermata 2021-04-27 alle 11 51 08" src="https://user-images.githubusercontent.com/909743/116229955-faaf1d00-a74e-11eb-8322-1d6257bf5237.png">

also, if possible let's close the issue

**Comment by ADDISON74** [comment]
I will follow your advice. All browsers are blocking that html page.

Closed.
