### ISSUE TITLE
Sendmail "Set Return-Path" vulnerability in zend framework

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#157]
https://magento.com/security/news/new-zend-framework-1-security-vulnerability

**Comment by tmotyl** [comment]
Isn't it already merged in 1.9.3.x ?

**Comment by sreichel** [comment]
Already merged into 1.9.3.0/1.9.3.1/1.9.3.x ...

**Comment by sreichel** [comment]
Fixed with 1.9.3.2

https://github.com/OpenMage/magento-lts/blob/1.9.3.x/lib/Zend/Mail/Transport/Sendmail.php#L122-L134
