### ISSUE TITLE
File differences

### ISSUE THREAD

**Issue by Marx15** [OpenMage/magento-lts#1574]
Hi
I have a question. Why are the files (zip) that I download not the same as the files installed via composer? Missing files.
thanks

**Comment by Flyingmana** [comment]
did you compare the files with the ones in the composer vendor directory, or the target directory after a composer install?
Do you have an example file which is different?

**Comment by Marx15** [comment]
I downloaded the last version via zip and opened it. to do this, I installed the latest version in the "htdocs" directory with composer.
if I now compare the 2, I see, for example, that the .github folder is not there.
the fast one now.
Is definitely not important, but should it be like that?

**Comment by Flyingmana** [comment]
ahh yes, thats intended. we dont copy all the files into the htdocs directory, because some of them are just not needed.
Although Iam not sure about the logic behind this, so I would say we leave this Issue open, till someone did actually check what happens there, and we documented it.

**Comment by Flyingmana** [comment]
I think the questions are answered now, so closing the issue.

For such questions you can also make use of the discussion area: https://github.com/OpenMage/magento-lts/discussions
