### ISSUE TITLE
stop /error/report.php from processing empty reports

### ISSUE THREAD

**Issue by ulbiopro** [OpenMage/magento-lts#1581]
A simple GET request on {BASE_URL}/errors/report.php will trigger processor.php to process an empty report. In case you set up an email report action, you get notified with empty "Store Debug Information" E-Mails.

### Description (*)

Turn off the notification for empty messages. Or even better, if possible, deny webaccess on `report.php` and `processor.php`.

### Benefits

Less junk? ;-)

### Additional information

My question would be following:
Is it possible to suppress empty messages or could this cause trouble?

Like:
https://github.com/OpenMage/magento-lts/blob/cc3eff3ebec46efbcab7ae4c26dd8a754476da18/errors/processor.php#L558-L559
```php
            if(!is_null($this->reportData)) {
                $subject = sprintf('%s [%s]', (string)$this->_config->subject, $this->reportId);
                @mail((string)$this->_config->email_address, $subject, $msg);
            }
```

**Comment by fballiano** [comment]
Hi @ulbiopro, I tried to create a PR for this issue.

**Comment by fballiano** [comment]
@ulbiopro my PR was merged, can you please close the issue?

**Comment by ADDISON74** [comment]
@fballiano - My opinion that if such requests are not answered they should be closed by those who manage the project after a week. There are a lot of hangers who have no feedback from those who have them initially and we must strive for a reduction in the number for visibility and obviously for trust. When we see a limited number of issues we have a feeling that things are still moving forward.

**Comment by fballiano** [comment]
I totally agree but that doesn't happen, that's why I try tagging the original author

**Comment by ulbiopro** [comment]
Sorry for the late response. I had an longer ongoing vacation.
