### ISSUE TITLE
Magento logo in error display

### ISSUE THREAD

**Issue by ProxiBlue** [OpenMage/magento-lts#1589]
### Preconditions (*)

1. 19.4.5

### Steps to reproduce (*)

1. Beak something to thrown an exception

### Expected result (*)

1. OpenMage logo

### Actual result (*)

1. https://github.com/OpenMage/magento-lts/blob/1.9.4.x/errors/default/images/logo.gif is magento logo
2. ![image](https://user-images.githubusercontent.com/4994260/116801821-be5d3180-ab3f-11eb-9575-01688bb20d70.png)
3. Copyright message of Magento in text

**Comment by ADDISON74** [comment]
The /errors directory has not been "brushed" so far. The error reporting pages should also be reviewed in the next OM versions.

**Comment by fballiano** [comment]
@colinmollenhour @Flyingmana is there a high def version of the OpenMage logo? Can't find it anywhere.

Also, the logo on the website is different from the one in the actual source:
<img width="336" alt="Schermata 2021-05-03 alle 20 42 28" src="https://user-images.githubusercontent.com/909743/116924671-197e4980-ac50-11eb-82e9-99a122d61a56.png">
<img width="195" alt="Schermata 2021-05-03 alle 20 42 23" src="https://user-images.githubusercontent.com/909743/116924675-1a16e000-ac50-11eb-93d7-f13528eec683.png">

**Comment by colinmollenhour** [comment]
I don't have the source handy but can get it if needed. However the version on the homepage is svg so you can just zoom way in and take a screenshot. :)

![image](https://user-images.githubusercontent.com/38738/116937154-d2378f00-ac36-11eb-8e74-519409c5ca83.png)

**Comment by fballiano** [comment]
I've donwloaded the SVG logo, embedded the font and converted it to (trimmed and transparent) PNG e GIF (with 4 colors only).

I'm attaching them here for future reference:
![logo](https://user-images.githubusercontent.com/909743/117028089-45073f80-acf5-11eb-9c80-3c95bc6c2419.gif)
![logo](https://user-images.githubusercontent.com/909743/117028093-46386c80-acf5-11eb-9109-a33a0a2596e1.png)

(I wanted to upload the ZIP and SVG but github doesn't allow me).

I'll update the source code with the new version of the logo.

**Comment by fballiano** [comment]
Actually I just found out that the logo is already in the source code: https://github.com/OpenMage/magento-lts/blob/1.9.4.x/skin/adminhtml/default/openmage/images/logo.svg

**Comment by sreichel** [comment]
@all-contributors add @ProxiBlue bug
