### ISSUE TITLE
Magento logo on Demo store notification

### ISSUE THREAD

**Issue by ProxiBlue** [OpenMage/magento-lts#1590]
### Preconditions (*)

1. 19.4.5

### Steps to reproduce (*)

1. Enable demo store notification

### Expected result (*)

1. Openmage logo in top bar with notification

### Actual result (*)

1. Magento logo is shown
2. 
![image](https://user-images.githubusercontent.com/4994260/116837525-684ec380-abfd-11eb-9475-ef40282586f7.png)

**Comment by luigifab** [comment]
Can be closed :)
