### ISSUE TITLE
Wrong Link Twitter Shared Broken

### ISSUE THREAD

**Issue by nihadrekany** [OpenMage/magento-lts#1595]
hi team ,,
i want to share shoes on my twitter but when i click to twitter icon i will redirected to home not to share the link is not check
Step
1- go to https://demo.openmage.org/accessories/shoes/barclay-d-orsay-pump-nude.html?___store=default
2- click to twitter share it is redirect to twitter home not shared .
vuln Link
http://twitter.com/home?status=Barclay+d%27Orsay+pump%2C+Nude+https%3A%2F%2Fdemo.openmage.org%2Fbarclay-d-orsay-pump-nude.html%3F___SID%3DU
removed this link and added this link
https://twitter.com/intent/tweet?url=https://demo.openmage.org/barclay-d-orsay-pump-nude.html?___SID=U
Impact
wrong twitter share

**Comment by fballiano** [comment]
I've just posted PR https://github.com/OpenMage/magento-lts/pull/1598 to fix this.

**Comment by sreichel** [comment]
@all-contributors add @nihadrekany bug
