### ISSUE TITLE
WSDL API does not work in PHP 8.0

### ISSUE THREAD

**Issue by Caprico85** [OpenMage/magento-lts#1602]
### Preconditions (*)
1. OpenMage 20.0.10
2. PHP 8.0

### Steps to reproduce (*)
1. Open http://example.com/index.php/api/v2_soap/index/?wsdl in browser

### Expected result (*)
1. URL can be opened

### Actual result (*)
The URL can't be opened. The error
```
Fatal error: Declaration of Mage_Api_Model_Wsdl_Config_Element::getChildren($source) must be compatible with SimpleXMLElement::getChildren() in [...]/app/code/core/Mage/Api/Model/Wsdl/Config/Element.php on line 179
```
is shown.

This works in PHP 7.4. It only fails since PHP 8.0. I'm not sure if this is caused because PHP 8.0 is more strict towards incompatible method signatures. Or if SimpleXMLElement has got a new method getChildren() in PHP 8.0.

**Comment by Flyingmana** [comment]
Solved by #1613

Thank you a lot for finding this.
