### ISSUE TITLE
Varien_Io_File fatal error after generating sitemap.xml

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#1617]
### Preconditions (*)

1. OpenMage 20.0.10
2. PHP 8.0.3

### Steps to reproduce (*)

In custom PHP script call this to generate sitemap.xml:
```
Mage::getModel('sitemap/sitemap')->load($sitemapId)->generateXml();
```
where $sitemapId is ID of sitemap.
You will get this error:
```
Uncaught TypeError: fclose(): supplied resource is not a valid stream resource in /lib/Varien/Io/File.php:254
Stack trace:
#0 /lib/Varien/Io/File.php(254): fclose()
#1 /lib/Varien/Io/File.php(114): Varien_Io_File->streamClose()
#2 [internal function]: Varien_Io_File->destruct()
#3 {main} thrown in /lib/Varien/Io/File.php on line 254
```

### Solution

change line 113 in /lib/Varien/Io/File.php from:
```
if ($this->_streamHandler) {
```
to
```
if (is_resource($this->_streamHandler)) {
```
Done!

**Comment by fballiano** [comment]
I created a slightly different solution in https://github.com/OpenMage/magento-lts/pull/1623 because I was wondering "why there's a resource there?" and turns out that the streamclose() doesn't reset the $this->_streamHandler variable thus the register_shutdown_function tries to close it again.

**Comment by Flyingmana** [comment]
@S0FTWEX did the related PullRequest fix the issue for you?

**Comment by S0FTWEX** [comment]
Yes, related PR fixed this issue. Closing this issue...
