### ISSUE TITLE
1931 is not using table prefix for customer_flowpassword cleaning by cron

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#162]
Hi. after update from 1924 to 1931 each time cron is trying to clear customer_flowpassword I'm getting exception because this is not using correct db table prefix. I checked db and I have correct table with prefix "ms_customer_flowpassword" but ccustomer/observer::deleteCustomerFlowPassword
is not using prefix producing exception below.

Where to fix it? Thanks a lot

Cron error while executing customer_flowpassword:

exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mg10.customer_flowpassword' doesn't exist' in /home/admin/domains/domain.com/public_html/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /home/admin/domains/domain.com/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /home/admin/domains/domain.com/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `cu...', Array)
#5 /home/admin/domains/domain.com/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `cu...', Array)
#6 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `cu...')
#7 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Customer/Model/Observer.php(231): Zend_Db_Adapter_Abstract->delete('customer_flowpa...', Array)
#8 [internal function]: Mage_Customer_Model_Observer->deleteCustomerFlowPassword(Object(Aoe_Scheduler_Model_Schedule))
#9 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): call_user_func_array(Array, Array)
#10 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(604): Aoe_Scheduler_Model_Schedule->runNow(true)
#11 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#12 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#13 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#14 /home/admin/domains/domain.com/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#15 /home/admin/domains/domain.com/public_html/cron.php(78): Mage::dispatchEvent('default')
#16 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_mg10.customer_flowpassword' doesn't exist, query was: DELETE FROM `customer_flowpassword` WHERE (requested_date < '2017-01-31 00:00:13')' in /home/admin/domains/domain.com/public_html/lib/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /home/admin/domains/domain.com/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/admin/domains/domain.com/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `cu...', Array)
#4 /home/admin/domains/domain.com/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `cu...', Array)
#5 /home/admin/domains/domain.com/public_html/lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `cu...')
#6 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Customer/Model/Observer.php(231): Zend_Db_Adapter_Abstract->delete('customer_flowpa...', Array)
#7 [internal function]: Mage_Customer_Model_Observer->deleteCustomerFlowPassword(Object(Aoe_Scheduler_Model_Schedule))
#8 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): call_user_func_array(Array, Array)
#9 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(604): Aoe_Scheduler_Model_Schedule->runNow(true)
#10 /home/admin/domains/domain.com/public_html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#11 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#12 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#13 /home/admin/domains/domain.com/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#14 /home/admin/domains/domain.com/public_html/cron.php(78): Mage::dispatchEvent('default')
#15 {main}

**Comment by colinmollenhour** [comment]
Not saying the bug shouldn't be fixed, but for your own sake I'd strongly advise avoiding use of table prefixes in favor of separate databases.

**Comment by tomekjordan** [comment]
HI. The problem is that prefixes are by default added by auto-installers like Installatron. so I have no influence on it. Usually 99.9% magento extensions support them without problems. but this time even core files are not correct with prefix

**Comment by sreichel** [comment]
Close? Already merged to 1.9.3.1 branch.
