### ISSUE TITLE
General copyright update

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1620]
To launch 19.5 and 20.1 branches (or not), I propose to create a new copyright in all "Magento" files.

Today we have for example:
```
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magento.com for more information.
 *
 * @category    Mage
 * @package     Mage_ImportExport
 * @copyright  Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Operation abstract class
 *
 * @category    Mage
 * @package     Mage_ImportExport
 * @author      Magento Core Team <core@magentocommerce.com>
 *
 * @method string getRunAt()
 * @method int getScheduledOperationId()
 * @method string getOperationType()
 */

class...
```

I propose to [write a script](https://gist.github.com/luigifab/31aa255499c93d6b7031020d7bf8335e) to replace the previous by something like this:
```
<?php
/**
 * This source file is part of OpenMage, a fork of Magento 1.
 * https://www.openmage.org/
 *
 * It is subject to the Open Software License (OSL 3.0) and Academic Free License (AFL 3.0).
 * Read LICENSE.txt and LICENSE_AFL.txt
 *
 * @category Mage
 * @package  Mage_ImportExport
 * 
 * @method string getRunAt()
 * @method int    getScheduledOperationId()
 * @method string getOperationType()
 */

class...
```

With a short header like this, we will do a better world (reduce files size and reduce network usage).

**Comment by Flyingmana** [comment]
we are not the copyright owners, so thats legally not possible. or at least very risky.
Also removing existing copyright and authorship information is in general seen as very rude.

**Comment by luigifab** [comment]
:'( yes, you are right...
and with a mix of original `@copyright` and `@author` ?

**Comment by fballiano** [comment]
I agree with @Flyingmana, at the same time I'm thinking that we want to respect the original copyright but openmage was born because the original owners said "it's dead to us" and openmage is evolving and changing.
That's more of a philosophical thought because I think we'll never be allowed to change the copyright statements :-(

**Comment by ADDISON74** [comment]
I see the problem legally. OM uses a large percentage of the original Magento code that is protected by copyright. Although I don't like that piece in the code and I could save hundreds of thousands of lines I have to admit that I use a private company solution. In the FOSS community the rule is to take over the work, respect, improve. It is a privilege we can still use this solution as Adobe has an absolutely vicious policy on its products. Newer in Creative Cloud they don't want you to install versions older than two. You even have to uninstall what they no longer provide.

If features are added to the code like new functions then they should reflect the OpenMage team contribution for example:

```
/**
 * Operation abstract class
 *
 * @category    Mage
 * @package     Mage_ImportExport
 * @author      OpenMage Team <https://github.com/OpenMage/magento-lts>
 *
 * @method string getRunAt()
 * @method int getScheduledOperationId()
 * @method string getOperationType()
 */
```

There are a lot of untested PR's and reported issues that require our involvement and unfortunately there are still a handful of people to do this. If we manage to keep the compatibility with the new versions of PHP, MySQL, improving the performance and solving what is wrong in the code would be ideal.

**Comment by colinmollenhour** [comment]
Agreed on only using a new doc block format for new files and leaving all existing ones alone. @Flyingmana should we put the preferred doc block text on the "[what-you-can-do](https://www.openmage.org/partners/what-you-can-do.html)" page or is there a better location? I suppose a "CONTRIBUTING.md" file would be the proper place?

**Comment by luigifab** [comment]
:'( I'm sad.

**Comment by luigifab** [comment]
It seems that _license at magento.com_ is dead: `554 5.4.14 Hop count exceeded - possible mail loop ATTR34 [DM6NAM04FT016....outlook.com]`

**Comment by luigifab** [comment]
For this new year, new ideas?

**Comment by Flyingmana** [comment]
We are still not allowed to change the copyright note without violating the copyright, which is valid for 50years minimum (longer for many countries). So, maybe we should put it on hold till 2070 :/

**Comment by sreichel** [comment]
> For this new year, new ideas?

Keep it, as it is.
