### ISSUE TITLE
Unintentional resetting of attribute values

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#1636]
### Summary (*)

Product attributes with default values are reseted when `save()` a product collection.

### Examples (*)

I run into this again these days and remembered ... https://github.com/flagbit/Magento-ChangeAttributeSet/issues/18#issuecomment-187674464

### Proposed solution

?

**Comment by Flyingmana** [comment]
I remember this issue.
In general I would say its not recommended to save directly from a collection.

Either its specific attributes you want to save, in which case there are special methods on resource models you can use.
Or you need to load the whole product model first before changing values.
