### ISSUE TITLE
Mage_Directory_Helper_Data::getRegionCollection - dependency inside method

### ISSUE THREAD

**Issue by Sekiphp** [OpenMage/magento-lts#1639]
Hello there,

I found some strange in method `getRegionCollection` in class `Mage_Directory_Helper_Data`. In this method is dependency to some undefined method (probably comes from `Varien_Object`). It seems that method `Mage_Directory_Helper_Data::getRegionCollection` is called anywhere.

The body is now very similar to `Mage_Checkout_Block_Onepage_Abstract::getRegionCollection`, but there is `getAddress` method defined.

![image](https://user-images.githubusercontent.com/9967016/119613422-511a8480-bdfd-11eb-905f-5e4ef1f47556.png)

Few suggestions / solutions:
1. Revert code from previous commit 
![image](https://user-images.githubusercontent.com/9967016/119613551-7e673280-bdfd-11eb-8443-e95b042b018c.png)
2. Remove the method without replacement (in branch 20.0)

**Comment by kiatng** [comment]
Related to issue #713 (fixed in PR #718) and PR #773 (reverted to original, probably by mistake). I second @Sekiphp suggestion on reverting the code back to PR #718, but for both branches 19 and 20.  If we keep it in 19, people may start using it and then wanting to migrate to 20.

**Comment by Flyingmana** [comment]
all changes in 19 are merged upstream to 20 regularly, usually on release day

**Comment by Flyingmana** [comment]
should be fixed with next release, please reopen if its not the case
