### ISSUE TITLE
1931 bugs related to special price (and global vs websites scope) + out of stock

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#164]
Hi. I don;t know but after update from 1924 to 1931 I observe strange things.

Product edit SAVE action - M1931 checks if Special Price vs Normal price. if its higher it shows warning. OK. Problem is that it doesn't check correct websites scope and inherited prices from lower scope. Example:
GLOBAL scope: normal price 100
WEBSITE scope: normal price 200
I want to make SPECIAL PRICE 150 for global view - and it shows
Screenshot:
[http://prntscr.com/jh1zsd](http://prntscr.com/jh1zsd)
"The Special Price is active only when lower than the Actual Price."
This buggy special price validation was introduced in 1.9.3.1

When I try to save product on global scope it shows warning and blocks save action, while it should normally save product - because special price is lower on websites scope. Looks like it check current page/scope prices only VS 1924 correct check per scope.

I can bypass this stupid check only with price set with , as float separator :) and it allows me to save the product just like it was normally in 1924
Screenshot: [http://prntscr.com/e3nixh](url)

**Comment by tomekjordan** [comment]
UPDATE:
the only option was to comment lines 659-677 in js/prototype/validation.js

 `    ['validate-greater-than-zero', 'Please enter a number greater than 0 in this field.', function(v) {
            if (Validation.get('IsEmpty').test(v)) {
                return true;
            }
            v = parseNumber(v);
            return !isNaN(v) && v > 0;
        }],

   // ['validate-special-price', 'The Special Price is active only when lower than the Actual Price.', function(v) {
   //     var priceInput = $('price');
   //     var priceType = $('price_type');
   //     var priceValue = parseFloat(v);

        // Passed on non-related validators conditions (to not change order of validation)
    //    if(
    //        !priceInput
    //        || Validation.get('IsEmpty').test(v)
    //        || !Validation.get('validate-number').test(v)
    //    ) {
    //        return true;
    //    }
    //    if(priceType) {
    //        return (priceType && priceValue <= 99.99);
    //    }
    //    return priceValue < parseFloat($F(priceInput));
    //}],
    ['validate-state', 'Please select State/Province.', function(v) {
                return (v!=0 || v == '');
            }],`

Can anybody make this validator to check website scope normal price vs current special price scope ?
Thanks

**Comment by seansan** [comment]
@tomekjordan can you confirm this is still an issue in M1939? 

How are you handling this currently on your webstores ...

**Comment by ADDISON74** [comment]
This issue reported for 1.9.3.1 is almost 4 years old. Is this still in OpenMage?
