### ISSUE TITLE
Open Mage one script migration not working. I am not getting what is the problem.

### ISSUE THREAD

**Issue by Masumisigma** [OpenMage/magento-lts#1661]
### Preconditions (*)

Migrating from Magento CE 1.9.4.5 to Openmage with One Step Migration Script "$ curl -fsSL https://migrate.openmage.org | sh"
1.Magento Community Version - 1.9.4.5
2.PHP Version - 7.2
3. MYSQL Version - 5.7.33

### Steps to reproduce (*)

1.I moved to development build and execute the migration script.

### Expected result (*)

1.Download the patches and apply them.

### Actual result (*)

1. After ruuning the script by the cmd it is giving me this message ''We are sorry,but the edition you have installed is not supported by this migration script.
2. ![Screenshot from 2021-05-28 17-38-35](https://user-images.githubusercontent.com/72392434/119986725-d78fbb80-bfe1-11eb-8e36-2f145490f173.png)

**Comment by fballiano** [comment]
can you post your app/Mage.php file?

cause it seems that this command:
`$(grep '$_currentEdition' app/Mage.php | awk '{print $5}' | sed 's/self:://' | sed 's/;//')`
is somehow failing

**Comment by ADDISON74** [comment]
I closed it because the author did not provide the requested information for too long.
