### ISSUE TITLE
Remove orphan directory and code

### ISSUE THREAD

**Issue by kiatng** [OpenMage/magento-lts#1666]
* Directory `includes` in the root is used by the compiler, which was removed in PR #534.
* Code that reference it should be removed

https://github.com/OpenMage/magento-lts/blob/4d2ce083a9b7a620f085c89183789d890b7eb5ab/index.php.sample#L34-L40

* Line 492
https://github.com/OpenMage/magento-lts/blob/4d2ce083a9b7a620f085c89183789d890b7eb5ab/app/code/core/Mage/Core/etc/config.xml#L486-L498

* Line 492 above also can be removed, since downloader was removed in PR #952.

**Comment by ADDISON74** [comment]
You may close this one if there is already a PR for it.
