### ISSUE TITLE
Canceled order - reuse coupon by the same customer

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#167]
Hi.
Magento problem for ages. 
User is making order, using coupon - one time. Order is canceled due to any problems with payment. Very often.
User tries to reorder - and try to use the coupon again. No luck

Can somebody fix this issue (feature) in Magento that is really annoying. Takes time for custome support, they are asking stuff to help, stuff must regenerate coupons and send them manually.
The goal to allow reuse coupon that was used for canceled order. Nothing more. Key is canceled order state.
Any options to fix this?
Related Stack Exchange topic
http://magento.stackexchange.com/questions/125849/coupon-code-should-apply-once-we-cancel-the-order
Solution to check:
http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions OR [removed bad link]

Thanks
Tomek

**Comment by seansan** [comment]
Some code for a possible fix can be found here

http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions/

**Comment by tomekjordan** [comment]
But Magebase code is very old. It needs to be tuned for Magento 1.9 with
[https://gist.github.com/peterjaap/bf9aa2086f06a1a41fa1](url)
but I think this is important issue - that can be fixed in Magento. I hope this fix - works correctly for 1 coupon sales rules, and for autogenerated codes in bulk.

Tomek

**Comment by sreichel** [comment]
Whats the best way to fix it?

Add an observer or include fix in core files?

**Comment by seansan** [comment]
>> Add an observer or include fix in core files?

@sreichel Seeing how long ago this was logged. And not expecting a fix from Varian, euh Ebay, euh Adobe

I would suggest to fix this in the core as an observer similar to `public function sales_order_afterPlace($observer)` in `app/code/core/Mage/SalesRule/Model/Observer.php`

Btw this code is working fine, we use this extension in production
http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions/.

But seeing this is an easy fix and the code is provided also with the orignal function where the +1 value rule count is set I can imagine we push a fix

The main reason to tackle this is "for the customer" .. we also had this situation many many times where a customer does not understand why is code is "used"

**Comment by seansan** [comment]
+1 is this something we can add? Plz advise on the best solution : as observer or in core? Maybe I can help to get it in ... it is more: lets decide where/how

**Comment by shankar2004nag** [comment]
Links provided above has been closed. Could someone please provide other links or source code .

**Comment by kestraly** [comment]
It’s in the internet archive thankfully 

https://web.archive.org/web/20180115143509/http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions/

**Comment by sreichel** [comment]
@all-contributors add @tomekjordan bug

**Comment by sreichel** [comment]
@all-contributors add @tomekjordan bug
