### ISSUE TITLE
Composer Autoload 

### ISSUE THREAD

**Issue by boesbo** [OpenMage/magento-lts#1673]
Could you develop a customization similar to this: https://github.com/romantomchak/magento-composer-autoload? good for business logic?

It is very useful to be able to use external PHP libraries inside the Magento modules, this adds them to the autoloader.

Seems abandoned, doesn't have Composer 2 support.

**Comment by ADDISON74** [comment]
This is not an OpenMage code issue. Please close it then post it in Discussions section. Thank you.

**Comment by Flyingmana** [comment]
@boesbo Did you check if just adding the "magento-hackathon/magento-composer-installer" does already solve the autoloading?
It should add a patch, which enables this. And it has Composer 2 support.

And having full support for composer autoloading is definitive a feature which should always work for current PHP projects, so please report any related issues here.

**Comment by boesbo** [comment]
> @boesbo Did you check if just adding the "magento-hackathon/magento-composer-installer" does already solve the autoloading?
> It should add a patch, which enables this. And it has Composer 2 support.
> 
> And having full support for composer autoloading is definitive a feature which should always work for current PHP projects, so please report any related issues here.
I noticed the problem yesterday, cleaning a project, removing `romantomchak/magento-composer-autoload` and keeping `magento-hackathon/magento-composer-installer`. I was not loading external libraries downloaded with Composer.

I thought `magento-hackathon/magento-composer-installer` didn't handle this thing, if you say this I'll do a thorough test and let you know.

**Comment by Flyingmana** [comment]
you can find detailed information about this here: https://github.com/Cotya/magento-composer-installer/blob/main/doc/Autoloading.md

Although it may be partially outdated, as we fixed inside openmage the incompatibilities which are mentioned there. (the error if a class is not found)

**Comment by boesbo** [comment]
> you can find detailed information about this here: https://github.com/Cotya/magento-composer-installer/blob/main/doc/Autoloading.md
> 
> Although it may be partially outdated, as we fixed inside openmage the incompatibilities which are mentioned there. (the error if a class is not found)

Thanks so much! I hadn't noticed this.!
