### ISSUE TITLE
Add option to enable/disable cart merge on login

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#168]
Add option to enable/disable cart merge on login

We ended up adding this code. Customers just dont understand why when they go to checkout with 3 items in the cart suddenly have 7 (4 others from previous login). So the cart merge on login should really be an option: code can be found here

https://github.com/jacquesbh/jbh_cartmerge

**Comment by jacquesbh** [comment]
Can we just add a require line in the `composer.json`?

I mean, if it does the job…

Let me know.

**Comment by infabo** [comment]
@seansan Quite nice option/feature. Is this the kick-off to a full-blown magento super-package?

**Comment by jacquesbh** [comment]
Maybe we can just add a recommended package in the `composer.json`?

**Comment by LeeSaferite** [comment]
Honestly, while I see the point being made, I think that addressing this via a modification to the composer.json file is not correct. But then again, I also think we should be going the opposite direction and stripping lots of things out of the core. I'll abstain from voting one way or the other on this and let the other team members sort it out.

@drobinson @colinmollenhour @Flyingmana

**Comment by Flyingmana** [comment]
Thats an interesting "Problem" to solve. But I would preffer to not change it (now).
But there is sure space for a "recommended" meta package of must have extensions, or at least some wiki/website page

**Comment by colinmollenhour** [comment]
I'd consider this a borderline feature and since the upstream is still somewhat active I'm concerned that making too many of such changes could cause merging upstream changes to become increasingly difficult to the point that nobody wants to do it.  So to me if the PR can be done in such a way to just add a couple lines of code like:

```
if (Mage::getStoreConfigFlag('...')) {
    return;
}
```
 and the current behavior continues to be the default, then I wouldn't be opposed.

I am opposed to adding third party modules to composer.json for various reasons.

**Comment by jacquesbh** [comment]
I would love to read these reasons! (@jacquesbh on twitter if you want to
DM)

Yes ok, I'll consider taking time to make a PR with conditions without
changing the default behavior.



Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

**Comment by jtnw** [comment]
Just to put my 2 cents here as I also hate the cart merging: I had written some code that also puts the old items into the wishlist which is nice for the customer. The benefit of making this a module instead of core fix is that we could add that feature if it is needed by others.

**Comment by tomekjordan** [comment]
HI. I don;t know buy you should consider things like abandoned carts marketing. if you move cart quote to wishlist all 3rd party extensions for abandoned carts will stop doing their job....

**Comment by jacquesbh** [comment]
Hum, no, because this feature does the move only if the customer adds
something else in its cart.
Infinite loop in real life.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

**Comment by Flyingmana** [comment]
there are obviously different opinions how to handle this.
Regarding of maintenance I decline to merge this and suggest to work on a "must have meta-package" in a separate repository/project

**Comment by seansan** [comment]
Aren't we making this too complex? I agree with colinmollenhour: if we can make this only a couple lines of extra code then what is the problem?
