### ISSUE TITLE
Plesk environment: I am running into issues with the unserialization and cron

### ISSUE THREAD

**Issue by leganzaro** [OpenMage/magento-lts#1681]
In the list of issues for OpenMage, I didn't find any of these problems so I suspect Plesk as the primary culprit.
I have installed OpenMage **v20.0.10** and **v19.4.13** with **PHP 7.4** and I found two separate problems:

1. I run into an issue with the unserialization.

The exact error happens in:
Warning: unserialize() expects exactly 1 parameter, 2 given in ../app/code/core/Mage/Core/Model/Cache.php on line 503
Warning: unserialize() expects exactly 1 parameter, 2 given in ../lib/Varien/Db/Adapter/Pdo/Mysql.php on line 1567
Warning: unserialize() expects exactly 1 parameter, 2 given in ../app/code/core/Mage/Core/Model/Cache.php on line 614

As a solution for this case, I use @ operator and the notice will no longer be displayed.

2. Cron doesn't execute with no error message. 

Adding `$isShellDisabled = true;` in cron.php allow cron to work but it would be best to run cron.sh and isn't running properly.

Everything was running fine in older releases, ex: **v19.4.2**, **v19.4.1**...

**Comment by kiatng** [comment]
For item 1 on `unserialize()`, see PR #1251, the second parameter was added to improve security. I note that you are running PHP7.4, you need to check again, because the second param was added since PHP7.0.

**Comment by leganzaro** [comment]
I reinstalled both versions **v20.0.10** and **v19.4.13** on a new server with clean installation of Plesk on a Centos 7. One extension was supplementary installed: [Aoe_Scheduler](https://github.com/AOEpeople/Aoe_Scheduler) for the second problem that was mentioned earlier. Current version of PHP is 7.4.18 ([link](https://testss.retrolime.com/phpinfo.php)) but the result is the same with every version (7.0, 7.1...).

With opcache.enable - off (not working as expected) and no custom or additional path to the open_basedir option, there is only one warning active:
ERR (3): Warning: unserialize() expects exactly 1 parameter, 2 given in .../app/code/core/Mage/Core/Model/Cache.php on line 503

The second problem: Cron - doesn't execute with no error message; is present for the last versions of OpenMage ([v20.0.10/v19.4.13](https://testss.retrolime.com/20.0.1.10.png) vs [v19.4.1](https://testss.retrolime.com/19.4.1.png)).
