### ISSUE TITLE
Language switch returns 404

### ISSUE THREAD

**Issue by mbattistini** [OpenMage/magento-lts#1685]
### Preconditions (*)

1. OpenMage LTS 19.4.13
2. php-fpm7.4

### Steps to reproduce (*)

from url: domain.com/it/category/product.html
click on the flag for the English language:

### Expected result (*)

1.  switching to the correct language and the relative localized page.

### Actual result (*)

1. destination url: domain.com/category/product.html
result: 404 page

tested the [VinaiKopp_StoreUrlRewrites](https://github.com/Vinai/VinaiKopp_StoreUrlRewrites) module without success (apparently valid up to magento version 1.8.1)

categories and products do NOT have the same names, in the example url I have simplified
the problem is in both directions, the only way to not have the 404 page is to start from the home in the correct language

**Comment by fballiano** [comment]
Can't reproduce the problem with the default themes, feel free to reopen if you've more info or (better) a PR to fix the problem. Thank you!
