### ISSUE TITLE
OpenMage is not detecting changes in Custom Options section (Product Edit)

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1693]
**This is OpenMage 20.0.10**. Here are the steps to reproduce this issue. 

The product Adidas Women's Shoe has one custom option named Size with a lot of values.

![1](https://user-images.githubusercontent.com/8360474/122653372-a459cb80-d14c-11eb-8600-89d2c006fba1.jpg)

Delete a few values by pressing (x) button and look on the left side where is the tab called **Custom Options**. Normally when there is a change in a section a Save icon appears to inform about and you should press one of the Save buttons to keep the changes. 

![2](https://user-images.githubusercontent.com/8360474/122653418-f7338300-d14c-11eb-9026-7a3de6a0be23.jpg)

Let's reload the page without saving it.  This time we add new rows and fill in the input boxes. Again there is no icon on the left side to inform us there is a change.

![3](https://user-images.githubusercontent.com/8360474/122653445-20ecaa00-d14d-11eb-9347-c57767a0bf73.jpg)

Let's reload the page without saving it. This time we delete the Size option by pressing [Delete Option] button. Again there is no icon on the left side to inform us there is a change.

![4](https://user-images.githubusercontent.com/8360474/122653568-1848a380-d14e-11eb-920f-6a4384e35a9a.jpg)

Let's reload the page without saving it. This time we change option Title value. As you may see the icon appears to inform there is a change in Custom Options section.

![5](https://user-images.githubusercontent.com/8360474/122653572-1c74c100-d14e-11eb-8e9c-2a9ee080a18e.jpg)

As a conclusion, for actions like [Delete Row], [Add New Row], [Delete Option] and changes on SKU and Sort Order columns OpenMage is not detecting the changes. This is bad because if you forget to press the Save buttons you loose your changes.

**Comment by ADDISON74** [comment]
I checked all the other sections and I did not find any issues when changing values. Custom Options is the only section affected. This is inherited from Magento and it is interesting that in so many years it has not been noticed. I discovered it by chance. I made the change without saving the work then I left in front of the computer. When I came back seeing that there are no changes in the sections I switched to other products. Later I discovered that the change made to that product was not operated.

**Comment by elidrissidev** [comment]
I'm taking this issue. Already was able to solve it partially. Will create a PR soon.

**Comment by ADDISON74** [comment]
@elidrissidev - Any updates related to your PR for this issue?

**Comment by elidrissidev** [comment]
Yes, I have made some progress on a branch that I made a while ago. I will try to complete it and create a PR hopefully next week.

**Comment by fballiano** [comment]
I've posted a PR that seems (in my tests) to fix the problem, let's see :-)
