### ISSUE TITLE
add support for gitpod online IDE

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1704]
https://www.gitpod.io/ allows you to checkout code directly from Github into an online IDE, which is also able to run the code.
there are 50 free hours per month and user.

I got it mostly running with our docker setup in https://github.com/OpenMage/magento-lts/tree/1.9.4.x/dev/openmage

I needed to change the port to make use of 8000 instead for the webserver
and I needed to change the url used in the install script to `BASE_URL="https://8000-amber-mule-2ln2y0ot.ws-eu09.gitpod.io/"`
most of the url can be generated from local environment variables:

```
GITPOD_WORKSPACE_ID=amber-mule-2ln2y0ot
GITPOD_WORKSPACE_URL=https://amber-mule-2ln2y0ot.ws-eu09.gitpod.io
```
probably a replace of the url one works best to get the correct url.

Not sure about where to put the .gitpod.yml, for normal usage it should be in the root.

**Comment by colinmollenhour** [comment]
Interesting product!

I added PR #1711 which allows you to set BASE_URL outside the script, so perhaps something like this would work?

```
tasks:
  - name: Install OpenMage
    command: BASE_URL=$GITPOD_WORKSPACE_URL bash dev/openmage/install.sh
```

No idea if that will work though or what you had in mind..

I think adding the `.gitpod.yml` file to the root should be fine. We should probably add a broader "deny" to `.htaccess`  that covers all dot files anyway. For example:

```
<FilesMatch "^\.">
    Order allow,deny
    Deny from all
</FilesMatch>
```

**Comment by colinmollenhour** [comment]
Oh there is a console, so:

`.gitpod.yml`:
```
ports:
  - port: 80
    onOpen: ignore
```

And the user (or maybe a task?) can then run:

```
BASE_URL=$(gp url 80) dev/openmage/install.sh
```
