### ISSUE TITLE
Access denied when connecting via SOAP

### ISSUE THREAD

**Issue by dbachmann** [OpenMage/magento-lts#1723]
A customer used before the update to openmage api calls for some marketing stuff. After the update to openmage, it is not possible to connect via soap. 

For testing I created a new user with full permissions. I tried to connect with the following snippet 

```
<?php 
try {
$client = new SoapClient('https://www.domain.com/api/v2_soap/?wsdl=1');
$session = $client->login('APIUSER', 'APIPASSWORD');

print '<pre>Works: '.print_r($session,1).'</pre>';
}
catch (Exception $e) {
print '<pre>Does not work: '.print_r($e,1).'</pre>';
}
?>
```

As result I get the faultstring "Access denied" with faultcode 2. 
I tested this with enabled and with disabled ws-i conformitiy. Even with enabled and disabled wsdl-cache. I always cleared the caches when I changed anything. Does anyone has an idea what could be wrong?

**Comment by Flyingmana** [comment]
@tmotyl why did you close this?

**Comment by tmotyl** [comment]
sorry, clicked wrong button ;)

**Comment by henrykbrzoska** [comment]
catch exception and log it
ie
app/code/core/Mage/Api/Model/Server/Handler/Abstract.php:228
add there 
Mage::logException($e); 
before
return $this->_fault('access_denied');

**Comment by dbachmann** [comment]
@henrykbrzoska Thank you for your answer. I added the mentioned debug output but the log is empty. 
Yes, I created a new user with and a new role with full access.

**Comment by elidrissidev** [comment]
@dbachmann I tested the SOAP API a few weeks ago in a clean OM installation and it was working fine. So I can confirm to you it's not a problem with OM. Most likely something went wrong during the upgrade process.

Regarding why your log file was empty, make sure you have logging enabled from the Admin in `Configuration > Advanced > Developer > Log Settings > Enabled`

**Comment by dbachmann** [comment]
@elidrissidev I've tested the connection in the latest openmage release. Same error.

**Comment by elidrissidev** [comment]
@dbachmann hmm, are you using the 20.0 or 19.4.x branch?

**Comment by dbachmann** [comment]
@elidrissidev The 19.4.x branch. Before the update to openmage everything worked fine.

**Comment by elidrissidev** [comment]
That's the same branch I was using. I thought maybe you were on 20.0. I'll double-check tonight and let you know.

**Comment by tmotyl** [comment]
@dbachmann you can try adding ‚trace’ option to the soap client (second param of the client) maybe this gives you more insight.

**Comment by elidrissidev** [comment]
@dbachmann Just tested now in a clean OM 19.4.x installation and everything is working perfectly fine. I only get "Access denied" on login if credentials are incorrect or I have no role associated with the SOAP user. Please do what @henrykbrzoska suggested and make sure you have logging enabled as I pointed before and post what you see in the `var/log/exception.log`.

**Comment by dbachmann** [comment]
Does not work: SoapFault Object
(
    [message:protected] => Error cannot find parameter
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => soap.php
    [line:protected] => 60
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => soap.php
                    [line] => 60
                    [function] => __call
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => login
                            [1] => Array
                                (
                                    [0] => apiuser
                                    [1] => apipw
                                )

                        )

                )

        )

    [previous:Exception:private] => 
    [faultstring] => Error cannot find parameter
    [faultcode] => SOAP-ENV:Client
)

**Comment by elidrissidev** [comment]
I think this can be moved to Discussions for further help because it is apparent that it's not an OM bug.

**Comment by Flyingmana** [comment]
@elidrissidev I dont think so, if it worked before the update to OpenMage, there probably was a BC change we did, which is showing effect here.
And the error message "cannot find parameter" does definitive need an improvement here, although its possibly not from OpenMage but PHP itself.

seems random, but have you tried to do `$client->login(['APIUSER', 'APIPASSWORD'])`, so as a single array instead of having them as 2 arguments?

**Comment by kiatng** [comment]
A quick search shows this: https://magento.stackexchange.com/questions/213791/uncaught-soapfault-exception-soap-envclient-error-cannot-find-parameter

Hopefully that helps you to locate the source of your problem.

**Comment by tmotyl** [comment]
Let me sum up common issues which occur when using SOAP:
1) check if the server can connect to itself, e.g. run (`curl -I https://Myhostname/api/soap?wsdl`) from ssh command line, this problem often results in the error "Error WSDL: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://Myhostname/api/soap?wsdl' : failed to load external entity"
2) check if curl i openssl PHP modules are installed
3) is Magento cache enabled?
4) is basic auth removed (htpasswd)
5) isn't default_socket_timeout not too low?
6) check if the soap response body is not 1 char longer than `Content-length` header
7) make sure API url's are without `index.php` (`/api/soap` instead of  `index.php/api`)
8) make sure nginx/apache rewrites are correctly set
apache:
```
RewriteRule ^api/([a-z][0-9a-z_]+)/?$ api.php?type=$1 [QSA,L]
```
nginx:
```
location /api {
        rewrite ^/api/rest /api.php?type=rest last;
        rewrite ^/api/v2_soap /api.php?type=v2_soap last;
        rewrite ^/api/soap /api.php?type=soap last;
    }
```
9) check response from `/api/v2_soap?wsdl=1` an make sure there are no url's with `index.php` inside (if there are, try clearing cache)

10) use the following scripts to debug connection using soap v1:
```
$mage_user = 'soap_user';
$mage_api_key = 'soap_passwd';
$mage_url = 'https://myshop.domain/api/soap/?wsdl';
$ini = ini_set("soap.wsdl_cache_enabled", 0);
$client = new SoapClient( $mage_url ,array('trace' => true));
try {
    print_r($client->__getFunctions());
    $session_id = $client->login($mage_user, $mage_api_key);
    $result = $client->call( $session_id, 'directory_country.list' );
    var_dump($result);
} catch (Exception $e) {
    var_dump($e->getMessage());
    echo "<br>Request Headers:<br>", htmlentities($client->__getLastRequestHeaders()), "<br>";
    echo "<br>Request :<br>", htmlentities($client->__getLastRequest()), "<br>";
    echo "<br>Response Headers:<br>", htmlentities($client->__getLastResponseHeaders()), "<br>";
    echo "<br>Response body:<br>", htmlentities($client->__getLastResponse()), "<br>";
}
```
or for SOAP 2
```
function debugSoap($proxy) {
echo "<br>Request Headers:<br><pre>", htmlentities($proxy->__getLastRequestHeaders()), "</pre><br>";
echo "<br>Request :<br><pre>", htmlentities($proxy->__getLastRequest()), "</pre><br>";
echo "<br>Response Headers:<br><pre>", htmlentities($proxy->__getLastResponseHeaders()), "</pre><br>";
echo "<br>Response body:<br><pre>", htmlentities($proxy->__getLastResponse()), "</pre><br>";
}

ini_set('display_errors', 1);
ini_set("soap.wsdl_cache_enabled", 0);
//ini_set("default_socket_timeout", 3);
  
$user = 'test';
$password = 'test';
$url = 'https://myshop.domain/api/v2_soap?wsdl=1';
$proxy = new SoapClient($url, array('trace' => true));
try {
    echo "trying to login\n";
    $sessionId = $proxy->login($user, $password);
    echo "logged in\n";
 
 
} catch (Exception $e) {
    var_dump($e->getMessage());
    debugSoap($proxy);
}
```

**Comment by dbachmann** [comment]
@kiatng I found this too and I've tested the connection with the mentioned script. Access denied...

@tmotyl 
1. Server can connect
2. curl and openssl are installed
3. Cache is enabled
4. No basic auth
5. default socket timeout is 60
6. How to check the response body?
7. All api urls are without index.php
8. Rewrites are correct

You debug script helped me to get more information. 

Response Headers:

HTTP/1.1 500 Internal Service Error
Date: Thu, 15 Jul 2021 12:27:44 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade, close
Content-Length: 294
X-XSS-Protection: 1; mode=block
Vary: Origin
X-UA-Compatible: IE=edge
Content-Type: text/xml; charset=utf-8

Response body:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>Error cannot find parameter</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

There is an internal server error. My customer servers says nothing and I'm waiting now for a response from the support to get more information about this error. 

On one of my dev servers I get the same response but the error log is empty. That is a very strange behaviour. At first I thought there could be a rewrite or something in the htaccess but I'm working with the default openmage htaccess. The rewrite you mentioned is above is active.

**Comment by elidrissidev** [comment]
> On one of my dev servers I get the same response but the error log is empty. 

@dbachmann Can you please try what I mentioned above and post the result?

**Comment by dbachmann** [comment]
@elidrissidev The logs are the whole time enabled. With @tmotyl s debug script I have another output which I posted above.

**Comment by elidrissidev** [comment]
Sorry if it seemed like I was spamming that question. The first error you reported in the OP was "Access denied". This is coming from Magento so the connection between the SOAP client and server is okay. From this Magento Api code
I can see multiple exceptions that are caught and thrown as one generic exception: "Access denied".

Exceptions are thrown here:
https://github.com/OpenMage/magento-lts/blob/58898f144c39c218fd16726506f11c6e72da4eb1/app/code/core/Mage/Api/Model/Session.php#L112-L138

And are then caught here:
https://github.com/OpenMage/magento-lts/blob/58898f144c39c218fd16726506f11c6e72da4eb1/app/code/core/Mage/Api/Model/Server/Handler/Abstract.php#L212-L232

**Comment by dbachmann** [comment]
Hello, 

I managed to get an output on my customers server 

`Next Zend_Acl_Role_Registry_Exception: Parent Role id 'G1' does not exist in /lib/Zend/Acl/Role/Registry.php:94`

I've found some solutions for login issues to the backend but not for api users.

**Comment by dbachmann** [comment]
It works now. It was a very strange behaviour here because everything worked fine before the migration to OpenMage. So, I deleted all api-users and api-groups and then created a new group and new api users. After flushing the caches I could connect. 
The question is now, what happened here and where did the parent role G1 come from.

**Comment by dbachmann** [comment]
@jacquesbh well, yes, I've found a solution. Delete all soap usergroups and all soap users. Then create new user groups and new users. That's all. Really stupid...

**Comment by jacquesbh** [comment]
@dbachmann I've done that and still have the issue. Damn me 😅.
Nothing else changed?

**Comment by elidrissidev** [comment]
@jacquesbh The fastest way to resolve your problem is to enable logging and check the log files. Did you upgrade to OpenMage recently?

**Comment by dbachmann** [comment]
@jacquesbh Did you delete the user groups completely? Try to clear the caches after deleting the groups and users.

**Comment by jparker1986** [comment]
Hi Guys,

Just thought I would add my fix for this issue.

I added -MultiViews to the .htaccess file and it seemed to resolve the issue.

**Comment by dbachmann** [comment]
@jparker1986 I've tested this too but I my case the issue was caused by the user groups. So if this issue still exist after recreating the users and user groups your mention would be the next step. Thanks for the hint.

**Comment by fballiano** [comment]
Can somebody create a PR for this? It's starting to stagnate since it doesn't have any answer since 2 months

**Comment by elidrissidev** [comment]
> Can somebody create a PR for this? It's starting to stagnate since it doesn't have any answer since 2 months

The OP's issue was already resolved. It was caused by the migration process.

**Comment by fballiano** [comment]
Thanks so much for the update!
