### ISSUE TITLE
Warning: inet_pton(): Unrecognized address *.*.*.*

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#173]
Hi. I'm getting some strange things in M1931 system.log - probably each time user makes an order and is redirected to payment. I have Cloudflare enabled and this is blocking real IP in Magento showing in order page.

Some users warned me about empty white screen (error 500?)
Warning: inet_pton(): Unrecognized address 117.96.232.*7,217.26.232.*7  in /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Helper/Http.php on line 149

do you have any tips how to solve it?

Thanks
Tomek

**Comment by seansan** [comment]
Did you check google? Looks like a server issue
http://magento.stackexchange.com/questions/75104/inet-pton-warning-when-use-webserver-behinds-a-reverse-proxy
https://www.google.nl/search?q=magento+inet_pton()%3A+Unrecognized+address&oq=magento+inet_pton()%3A+Unrecognized+address&aqs=chrome..69i57j69i64l3j69i61.874j0j7&sourceid=chrome&ie=UTF-8
