### ISSUE TITLE
Newsletter lacks CSRF

### ISSUE THREAD

**Issue by mark-netalico** [OpenMage/magento-lts#1738]
The default newsletter signup doesn't have any kind of verification of CSRF so it's possible to automate adding subscribers through javascript or repeatedly POST'ing to that URL.

I think we should add CSRF to the newsletter, but might want it to be disabled by default in 19.x existing installations if any integration/extension is using it so that it doesn't break it.

**Comment by ADDISON74** [comment]
In the past we approached discussions related to this issue. Please take a look here: https://github.com/OpenMage/magento-lts/issues/1287.

**Comment by sreichel** [comment]
@all-contributors add @mark-netalico bug
