### ISSUE TITLE
Magento Imagine Hackathon

### ISSUE THREAD

**Issue by drobinson** [OpenMage/magento-lts#174]
I'm organizing the 2017 Pre-Imagine Hackathon this year (since @fbrnc can't make it :( ) so I think I'll spend my time there working on cleaning up this repo as best as I can.  If you're going to Imagine this year, come a couple days early if you can and join us (either to help with this repo, or work on whatever you choose) - I'll post the sign up link below.

If you can't make it, but want to participate remotely in helping the cleanup effort here, the dates will be April 1-2.  Sorry in advance if you end up getting a lot of emails.

Hackathon sign up link: https://imaginehackathon2017.eventbrite.com

**Comment by tmotyl** [comment]
@drobinson good idea.
I (and also some guys from my team) would like to join remotely. Do we have a communication channel for Magento LTS? e.g. gitter or slack would be awesome

**Comment by drobinson** [comment]
@tmotyl Yes, we could use gitter - that'd be great!

**Comment by tmotyl** [comment]
Just created gitter for openmage, still getting my head around it, but you should get the invitation already

**Comment by seansan** [comment]
What is gitter ? We mainly use slack
(Good idea!)

**Comment by Flyingmana** [comment]
gitter is a simple version of slack/hipchat, which allows auth via github(big plus for easy accessability)

**Comment by Flyingmana** [comment]
Good news, I also got time to join the Hackathon remotely and also have some time reserved for the week before. If I can help with preparation somehow, just ping here. Else I will prepare by finally making TravisCI run for this project.

**Comment by tmotyl** [comment]
@drobinson will you be able to share some of the agenda points through google hangout to enable remote participation? Please also keep communication on gitter for the same purpose.

**Comment by beejhuff** [comment]
I suppose it's a bit late for this reply, but there's an official https://magento-hackathon.slack.com we setup and used for the 2016 Pre-Imagine Hackathon.  It's open and available to any hackathon event and has been integrated with the magento-hackathon repositories here on github.  It's used throughout the year by both docathon and hackathons held across the globe.

@drobinson I've resent your invite and @fbrnc is already setup as an administrator (along with a few others) and as soon as you accept it I'll grant you admin privileges as well (sorry I thought I did this when I granted you the rights to the magento-hackathon twitter account).

You can also bypass the invite system and get automatically granted access using the following link: https://slofile.com/slack/magento-hackathon
