### ISSUE TITLE
Removal of <if> condition in layouts breaks valid use-case

### ISSUE THREAD

**Issue by idmistir** [OpenMage/magento-lts#1748]
### Preconditions (*)

1. v20.0.12

### Steps to reproduce (*)
1. Use this in a theme layout file to load a css file last, after everything
![image](https://user-images.githubusercontent.com/1479170/127440154-719d7af0-cb00-4e1a-8b45-cd40803fd7e7.png)
(Tried adding it as a code block but wouldn't render)

### Expected result (*)

1. test.css file should load last, after everything

### Actual result (*)

1. test.css file loads where it normally would without the if condition

This concerns https://github.com/OpenMage/magento-lts/pull/1073
OpenMage, like M1, does not have a way to load css files last from layouts after everything else, which is very useful in theme development. The above trick with the if condition will force a file to load last in the browser, but since the IE deprecation of that PR that won't happen, causing every upgraded store that relies on this to render horribly due to css ordering. 
Please try to retain existing functionality, or provide an alternative if you really must do this.

I've read the PR and I'd like to note one more thing. I've worked with companies in several countries, and everyone that does B2B in any country and has the government as a client, has the same thing to say: government computers, which can amount to a good chunk of a company's revenue, still use outdated windows versions and IE, with a great deal of them being IE9. So while mainstream statistics will favor deprecation of IE (and by the way,  I'm in the let it die bandwagon too), it doesn't mean that it's necessarily time yet.

**Comment by fballiano** [comment]
I see your point about loading it last, but is there any other way to achieve that? with dependencies or something?

About IE and goverment etc.. they simply should not upgrade to v20, stay on v19 which is still perfectly maintained.

**Comment by fballiano** [comment]
Closing since no feedback since almost a year, anyway it should be possible to solve the issue using module dependancy.
