### ISSUE TITLE
Sponsored Requirement: enhanched Order Editing

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1785]
I did already mention it a while ago, we got a Feature Request by a Company who is willing to sponsor the full work on this.
We are still trying to figure out the best process for this, so please bare with us, if things go not fully smooth. (and please tell us, if you find anything we can/should improve on the process)

The current process is like this:
* I will prepare a set of requirements and group them into multiple Issues
* Anyone who would be willing to take one or multiple over, can write on the Issue, or directly to me with the following information:
  - experience in this area
  - when would a start be possible
  - a rough timeline
  - what additional Information you would need
* I will forward them to my contact in their company
* You would discuss payment with them directly
  - You please keep me posted about the details of this, so iam aware if something sketchy happens.

General Requirements:  
* Code is Part of OpenMage
* works with the latest Version (20.x)
* does not introduce BC breaks
* licensed as MIT

General Plan:
We work on this on a separate Repository at: https://github.com/OpenMage/EnhancedOrderEditing
We will work with one base module, and additional modules grouping some of the features together where needed, so we can use them also separately in OpenMage.
Separate Features can be taken over by separate People.

Feature Requirements : 
* Ability to edit an order instead of having to cancel it out
* Ability to edit order state/status - In the instance that an order was accidentally processed or completed before it should have been. https://github.com/OpenMage/EnhancedOrderEditing/issues/2
* Ability to edit account info - In the instance that the customer accidentally typed in the wrong info or it was pre-populated by the browser incorrectly. https://github.com/OpenMage/EnhancedOrderEditing/issues/3
* Ability to edit qty or replace items in order - If a product is no longer available or oversold, or the accessories purchased are not compatible with main item. https://github.com/OpenMage/EnhancedOrderEditing/issues/4
* Ability to re-authorize payment if new items are added. (We utilized auth.net CIM for this previously) https://github.com/OpenMage/EnhancedOrderEditing/issues/6
* Ability to see what users are making changes to the order (Show in the order log area of Comments History) https://github.com/OpenMage/EnhancedOrderEditing/issues/5

**Comment by Dirtyhair1** [comment]
This is actually a really good feature. As a storeowner I have wanted this many times. Now we have an inventory and shipping system which we use for all the backend processing but I can see how people might want this feature.
