### ISSUE TITLE
Default Shipping method - autoship in the cart

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#179]
Hi. I still cannot understand why Magento cannot present default shipping method costs right in the cart without postcode and manual update.
This is annoying and customers like to see shipping cost right away even wheny this is not desired shipping method at first.
Ajax Add to cart often shows cart contents - but if default method is not calculated - those costs are skewed.
Even more some use fees and other shopping cart rules depending on shipping method. so it should be just standard to choose default method in admin so customer will see shipping cost without manual update (of postcode and quote) or at least use default postcode from store origin.

thanks for considering it

**Comment by sreichel** [comment]
Close ... this can be done with observers/some config only. Working module rdy ... 

... paypal is okay :P
