### ISSUE TITLE
IP whitelist for maintenance mode

### ISSUE THREAD

**Issue by elidrissidev** [OpenMage/magento-lts#1807]
### Description (*)
When maintenance mode is enabled, there is no way to whitelist an IP address to be able to bypass maintenance mode, this was especially useful when we were performing the upgrade to OpenMage this week. We ended up modifying the `if` condition in `index.php` to check if the client IP is ours then let the request continue.

### Expected behavior (*)
We need the ability to specify one or more IP address that will be able to access the website when it's in maintenance. One way would be to include the IPs delimited by a new line in the `maintenance.flag` file itself, but other options can be explored as well.

### Benefits
Just a convenient way to be able to verify that everything is good before disabling maintenance mode.

I can work on this feature myself, just wanted to post it here and see any feedback from the community.

**Comment by Flyingmana** [comment]
I think we just implemented this with the latest release as part of https://github.com/OpenMage/magento-lts/pull/1449

could you check and validate this is working for you?

**Comment by elidrissidev** [comment]
@Flyingmana Oopsie, I just checked the last release now and I saw the bypass code. It's because the release we're using is a couple of months older so It didn't have it. I shall do a better job at searching issues next time.

**Comment by Flyingmana** [comment]
Its ok, one cant know/see everything :)
