### ISSUE TITLE
Search box issue with menus in Backend

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1808]
I installed the latest version of **OpenMage 20.0.13** and I did not make any changes. Go to Backend and resize the browser window. Look at the top to the menus and the search box. 

A positive thing is that the menus are no longer all on one line but we have a second line. A negative thing is that the search box overlaps over 3 - 4 menus. If I'm not mistaken for this issue a PR has already been proposed and has been merged. Because I do not use the full window all the time I had to give up the default theme for Backend due to this issue.

![search](https://user-images.githubusercontent.com/8360474/132136588-5a035a33-4c00-45dc-a2b3-083e6d880f1e.jpg)

**Comment by ADDISON74** [comment]
This issue is one of the many reasons I switch the Backend to legacy Admin Theme.

**With Display Demo Store Notice**. This situation was not taken into account at all.

![with-notice](https://user-images.githubusercontent.com/8360474/173252277-59c53d2f-5e0f-4956-b2a1-976a5cf79ee1.jpg)

**Without Display Demo Store Notice**. "Global Record Search" box covers menus that are no longer accessible.

![without-notice](https://user-images.githubusercontent.com/8360474/173252275-33f6dc3a-facf-48fa-8f96-af593eb3eae2.jpg)

If that hamburger menu is still used, the introduction of the "Global Record Search" box directly in the menu on the first position should be evaluated. Also, the layout issue when the website is in demo must be solved. There are some who use this feature with a different message.

**Comment by ADDISON74** [comment]
With the latest version **OpenMage 19.4.18** this issue seems to be fixed, for both situations, with or without the notification at the top of the page.

![Screenshot from 2022-10-05 12-07-05](https://user-images.githubusercontent.com/8360474/194024182-8bd13831-0042-4a7a-adfd-33379b0c92c2.png)

If I remember well @sreichel fixed this issue recently.

**Comment by sreichel** [comment]
Fixed in #2422
