### ISSUE TITLE
What's the "suggested" way to install this package?

### ISSUE THREAD

**Issue by proxium** [OpenMage/magento-lts#182]
[this is a question, not a bug]

I used to work with firegento/magento package and I need to give openmage/magento-lts a try to test some fixes. Since you'are not using "type": "magento-core", with which composer installer I can install it.

Every time I download the package inside vendor but it was never deployed in src/ folder, any thought?

**Comment by LeeSaferite** [comment]
```
{
    "require": {
        "aoepeople/composer-installers": "*",
        "openmage/magento-lts": "1.9.3.1-dev"
    }
}
```

**Comment by infabo** [comment]
@proxium beware, switching to AOEs composer installer will wipe your htdocs folder, it's not just copying the magneto-lts files into. If you already symlink local.xml, media and var folder - then just go ahead.

**Comment by sreichel** [comment]
https://github.com/OpenMage/magento-lts/wiki/Howto-install

Close?

**Comment by bob2021** [comment]
Alternatively, the latest version of `aydin-hassan/magento-core-composer-installer` lets you specify the core package type (though its only documented in the [release notes](https://github.com/AydinHassan/magento-core-composer-installer/releases/tag/1.4.0))

**Comment by proxium** [comment]
Thank you @bob2021 since aydin-hassan/magento-core-composer-installer is more active than the AOE installer I think it can be a solid alternative

**Comment by Flyingmana** [comment]
I will keep this issue open till I have properly put this on the github page.

**Comment by tmotyl** [comment]
I confirm that aydin-hassan/magento-core-composer-installer can handle Magento LTS.
You just need to:
1. require openmage/magento-lts
2. add following configuration to the  "extra": section:
```
 "extra": {
   "magento-core-package-type": "magento-source"
}
```

**Comment by Flyingmana** [comment]
I added something to the github page, not linked yet
http://openmage.github.io/magento-lts/install.html

**Comment by tmotyl** [comment]
for me is good enough, and we can close the issue :)

**Comment by tmotyl** [comment]
added info to the wiki also. @Flyingmana can you link the github page so it's easier to reach?
