### ISSUE TITLE
XML-RPC product_attribute.options storeview param not working

### ISSUE THREAD

**Issue by nprovoost** [OpenMage/magento-lts#1822]
# Bug report

## Description
versie:  LTS 19.4.14 & LTS 20.0.7 

[host]/api/xmlrpc
Get Product Attribute options specific label storeview
shows only default admin label and no storeview label, when store id/code is given in the params.

$client->call('call', array($session, 'product_attribute.options', array('[attribute_id', '[store_code]'))));

## Expected result
should give array with the correct storeview label but shows the admin label
[0] => Array
  [1] => Array
  (
  [value] => 123
  [label] => Rot
  )
)

## Possible solutions
\app\code\core\Mage\Catalog\Model\Product\Attribute\Api.php
 /**
     * Retrieve attribute options
     *
     * @param int $attributeId
     * @param string|int $store
     * @return array
     */
    public function options($attributeId, $store = null)
    {
line 113 
add >  $attribute->setStoreId($storeId);

will load the correct storeview labels.

Regards Nicky

**Comment by sreichel** [comment]
@all-contributors add @nprovoost bug

**Comment by sreichel** [comment]
@all-contributors add @nprovoost bug
