### ISSUE TITLE
Admin order for new customer - customer group is not working for any rules

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#186]
Hi. There is a bug in Magento - all versions, when admin tries to create new order and there is no customer account.
No matter what group you choose for customer on order creation page - this group has no influence on prices/shipping rules/shopping cart rules.
 It looks like all backorders for new customers are pseudo-assigned to general or non-logged-in group.
This is annoying because it has influence on shipping costs/free shipping rule for certain custom group etc

Screenshot [http://prntscr.com/edzgqv](url)

**Comment by fballiano** [comment]
tested and can't reproduce, the account is created with the selected group
