### ISSUE TITLE
Unused helper class Mage_Index_Helper_Data

### ISSUE THREAD

**Issue by Sekiphp** [OpenMage/magento-lts#1877]
### Summary (*)
In module `Index` is defined helper class `Mage_Index_Helper_Data`, which is used nowhere. There is also missing definition for helpers in related `config.xml` file.

### Proposed solution
1. Remove class `Mage_Index_Helper_Data`
2. Add helper definition to `config.xml`

**Comment by Flyingmana** [comment]
not having this class will error when the module is using any kind of translations (as far as I remember)

**Comment by elidrissidev** [comment]
Translations are indeed being used inside that module, and by looking at `Mage_Core_Model_Config#getGroupedClassName`, it seems Magento infers the class name from the convention even if it's not declared in `config.xml`. So the proper fix is to add it to the config to avoid confusion.
