### ISSUE TITLE
Add CI detection for XML syntax errors

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#1918]
While its mainly about detecting errors at all, we should also more specific be able to detect the error fixed in #1901 

- [ ] detect general xml syntax errors
- [ ] detect error from #1901

**Comment by fballiano** [comment]
@Flyingmana do you have a tool in mind that does xml validation?

**Comment by Flyingmana** [comment]
not a specific one, but xml validation is a generally solved problem.
I would just start with the first tool an online search returns, and see if it would detect the linked error.

**Comment by fballiano** [comment]
I'm running:

` find . -type f -iname '*.xml' | xargs -I '{}' xmllint --noout '{}'`

but it throws errors since a lot of our xml files have this:

```
./app/code/core/Mage/Core/etc/wsi.xml:2: namespace error : xmlns:typens: 'urn:{{var wsdl.name}}' is not a valid URI
<wsdl:definitions xmlns:typens="urn:{{var wsdl.name}}"
```

:-\
