### ISSUE TITLE
PHP8 Compatibility issue implode() legacy signature is being used and is removed in PHP8

### ISSUE THREAD

**Issue by dford-avb** [OpenMage/magento-lts#1937]
### Preconditions (*)

1. v19.4.15
2. PHP 8.0.14

### Steps to reproduce (*)

1. Disable api2.xml caches,
2. Make GET rest api call in browser (to get xml response)

### Expected result (*)

1. Return xml result
2. 
```
<magento_api>
<messages>
<error>
<data_item>
<code>404</code>
<message>Request does not match any route.</message>
</data_item>
</error>
</messages>
</magento_api>
```

### Actual result (*)

1. implode method is using legacy signature which is removed in php 8 -- app/code/core/Mage/Api2/Model/Renderer/Xml.php on line 108: $isAssoc = !preg_match('/^\d+$/', implode(array_keys($data), ''));
2. Fatal error: Uncaught TypeError: implode(): Argument 2 ($array) must be of type ?array, string given in app/code/core/Mage/Api2/Model/Renderer/Xml.php on line 108
6 | 0.1233 | 1754120 | implode( $separator = [0 => 'messages'], $array = '' ) | .../Xml.php:108

**Comment by sreichel** [comment]
@all-contributors add @dford-avb bug

**Comment by sreichel** [comment]
@all-contributors add @dford-avb bug
