### ISSUE TITLE
payment method titles are not translatable

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1956]
It is not possible to select payment methods for individual store views. That means some higher scope configuration is always active for your store view. That means you will never be able to create there a translation, in this specific case the ‘Bank Transfer Payment’ in the checkout.

```

"app/design/frontend/rwd/default/template/checkout/onepage/progress.phtml"

     51             <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
     52             <div id="payment-progress-opcheckout">
     53                 <?php echo $this->getChildHtml('payment.progress') ?>
     54             </div>
     55             <?php endif ?>
```

Solution is to have the getChildHtml('payment.progress') output the payment title via the locales

![banktransfer-admin](https://user-images.githubusercontent.com/13450219/148056680-e1070a3f-9797-4cc8-ab83-06ed3dcecb79.png)
![banktransfer-checkout](https://user-images.githubusercontent.com/13450219/148056686-90ef54fa-0dc5-4bf6-8fe3-fb672ee7e65f.png)

**Comment by luigifab** [comment]
You can set the translation of the title per store view.

You can easily override the system.xml to allow to select payment methods for individual store views.
We have did that on our stores.

**Comment by f1-outsourcing** [comment]
Thanks for the tip! Makes me only wonder why this is not a default.
