### ISSUE TITLE
Part of checkout order review is getting translations from wrong session(?)

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1957]
It looks like part of the order review is getting it’s translations differently than the rest of the checkout page.
If I open in two tabs different store views (with different locale’s configured), the checkout page is fine, except part the order review section. 
![english](https://user-images.githubusercontent.com/13450219/148059487-04429a08-490d-4941-bda8-b7a5e16917dc.png)
![german](https://user-images.githubusercontent.com/13450219/148059495-63e5b371-ec28-4031-9bbb-e58415af2bad.png)

**Comment by fballiano** [comment]
sure, that part gets rendered via an AJAX request, which would use the second session because actually a second session doesn't exist. there's only one session, in the second tab you switched the language and when you re-render the summary of the first tab, it will use the updated locale.
