### ISSUE TITLE
My product reviews are not my but all

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#1965]
From My account / My product reviews, I can access all product reviews, even if the current customer account is not the author of the review.

This is OpenMage 20.0.13 with PHP 8.0.

**Screenshot of the review when customer account is the author:**
![image](https://user-images.githubusercontent.com/31816829/148529536-9e9a32f7-09b3-4a59-a9d5-1cbd5d764a6b.png)

**Screenshot of the review when customer account is NOT the author:**
![image](https://user-images.githubusercontent.com/31816829/148529670-1e86bbd4-4dcb-4264-9d31-9e1bf7792d21.png)

This is not critical, but any customer can get all reviews of any Magento 1 and OpenMage stores by trying all ids from the current url.

**Comment by elidrissidev** [comment]
Can't reproduce this in v1.9.4.x nor v20.0, here is the snippet where the data is coming from and I can only reproduce it if I remove the customer filter line
https://github.com/OpenMage/magento-lts/blob/ff6189ae82f141c13224318241be64d512555c0d/app/code/core/Mage/Review/Block/Customer/List.php#L49-L53

**Comment by luigifab** [comment]
Yes, but to to the detail page, not the list.

**Comment by elidrissidev** [comment]
Do you have to type the URL manually?

**Comment by luigifab** [comment]
Yes, change the id from the url with any existing review.

**Comment by aterjung** [comment]
I am not shure if it is a real issue, cause the reviews are open to everyone via the regular frontend controller:

review/product/view/id/xxx/

but i would prevent it anyway. Probably someone extends the page to edit the review etc. and its no harm.

I have prepared a commit to fix this. But it is a bit bigger. I would expect it to respond with a 404 error - thrown in the controller. The actual review model is loaded in the block class where it should not. This way its too late to throw a 404 error. Bad design :-( 

Intrestlingly its done better in the normal frontend controller.  So i changed the customer review controller and block to match that and added the customer check:

https://github.com/OpenMage/magento-lts/commit/28aceafcc02f8743fb594bdfd3b79535a7550544

I did not tested this - i will do this tomorrow and would create the PR. Would somewone expect this to be a breaking change? Cause it could be security related - i would expect it to go into the 19 branch...

**Comment by ADDISON74** [comment]
In all the stores I started over the years, a table ID never started with a value of 1 because I realized that it provides information to a Magento programmer about the number of orders, customers, reviews. Accessing the controller is as intuitive as in this situation and you can find out how many reviews there are. I did it many times based on a fake account.

I never thought if it would be a solution to run periodically a PHP script that can  change the auto_increment value in certain tables. In this way there would be no continuity in information, especially when trying to obtain it based on a script.

**Comment by aterjung** [comment]
I have to correct myself. This is an security issue. You can access not approved reviews if you know or guess their id.

**Comment by aterjung** [comment]
I have updated and tested my changes and created an PR to fix this issue. Locking forward for comments

**Comment by sreichel** [comment]
@all-contributors add @luigifab bug
