### ISSUE TITLE
VAT number validation is not working

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1971]
I also wonder if the UK VAT numbers are still being send to this VIES, because VIES already dropped support for the UK.

### Steps to reproduce (*)
I am getting this error on a valid VAT number
The VAT ID entered (PL5210088067) is not a valid VAT ID. You will be charged tax.

### Expected result (*)
These numbers are all valid numbers. 
https://nephics.github.io/euvat-direct/batch.html
NL859835832B01
PL5210088067
BE0480694386
DK25283147
DE245335078

### Actual result (*)
There is nothing even being logged, you have no idea what is going on, or how to test it.

**Comment by elidrissidev** [comment]
Hey @f1-outsourcing I tested the VAT ID validation functionality using your provided examples and it seems to work fine for me:


![image](https://user-images.githubusercontent.com/67818913/172003063-6efc456e-4c03-4128-8003-a965ac617638.png)


Note that you don't include the country code with the VAT ID, only the numbers. I'm gonna go ahead and close, but please feel free to open if you have any further questions.
