### ISSUE TITLE
Need to get Rest API Bases on sub store

### ISSUE THREAD

**Issue by himanshutecstub** [OpenMage/magento-lts#1992]
Hello,
In magento 1.9 i used REST API which is working fine with main store as https://store1.magento.com/api/rest/orders
I have another sub store (website) that put on same directory with different domain as https://store2.magento.com/
For that i create new sub directory and put index.php from root and add website code which is working fine
But when i try to access rest API for that as https://store2.magento.com/api/rest/orders which returns 404 error.

Please suggest

**Comment by luigifab** [comment]
You have forgotten configuration of api in web server configuration?

**Comment by elidrissidev** [comment]
Verify your `.htaccess` file if you're using apache2 and make sure that you uncomment the line that rewrites requests to `/api/*` to the `api.php` instead of `index.php`.
