### ISSUE TITLE
EAV Datetime attribute can't save Time when using different Locale

### ISSUE THREAD

**Issue by Hanmac** [OpenMage/magento-lts#2001]
### Preconditions (*)

1. OpenMage LTS 19.4.13
2. Backend Locale "de-DE", timezone "Europe/Berlin"

### Steps to reproduce (*)

1. add a Product EAV Attribute with type=datetime, input=**datetime** and backend and frontend set to the correct datetime classes
2. set the Backend Locale to something else, in my case "de-DE", timezone "Europe/Berlin"
3. use DateTimePicker to set the value for the time, for example today: "03.02.2022 17:00"
4. try to save the product
5. Mage_Eav_Model_Entity_Attribute_Backend_Datetime will fail to parse the Datetime value, try to use Locale but uses getDateFormat instead of getDateTimeFormat.
6. now in the Database there is "2022-02-03 00:00:00"

### Expected result (*)

1. [Screenshots, logs or description]
2. in the Database is "2022-02-03 17:00:00"   (or maybe "2022-02-03 16:00:00" when it would fallback to UTC? )

### Actual result (*)

1. [Screenshots, logs or description]
2. now in the Database there is "2022-02-03 00:00:00"

Also the Frontend should probably differ if it is date or datetime

**Comment by kiatng** [comment]
See PR #2003.
