### ISSUE TITLE
Mage_Core_Model_Locale ::isStoreDateInInterval() has weird logic

### ISSUE THREAD

**Issue by joshua-bn** [OpenMage/magento-lts#2004]
### Summary (*)
`Mage_Core_Model_Locale ::isStoreDateInInterval()`. That logic doesn't make sense. I think what they were trying to do I did below.

However, since this hasn't seemed to a problem, ever, I don't know if it makes sense to fix it. Also, I don't have an OM repo checked out so I won't be submitting a PR for this.

### Examples (*)
See https://github.com/OpenMage/magento-lts/blame/1.9.4.x/app/code/core/Mage/Core/Model/Locale.php#L854

### Proposed solution
```php
    public function isStoreDateInInterval($store, $dateFrom = null, $dateTo = null): bool
    {
        if (!$store instanceof Mage_Core_Model_Store) {
            $store = Mage::app()->getStore($store);
        }

        $storeTimeStamp = $this->storeTimeStamp($store);
        $fromTimeStamp = strtotime($dateFrom);
        $toTimeStamp = strtotime($dateTo);
        if ($dateTo) {
            // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
            $toTimeStamp += 86400;
        }

        return $storeTimeStamp > $fromTimeStamp
            && $storeTimeStamp < $toTimeStamp
            && !is_empty_date($dateFrom ?? '');
    }
```

**Comment by kiatng** [comment]
I think the logic, as it is, is fine:

```php 
        $result = false;
        if (!is_empty_date($dateFrom) && $storeTimeStamp < $fromTimeStamp) {
        } elseif (!is_empty_date($dateTo) && $storeTimeStamp > $toTimeStamp) {
        } else {
            $result = true;
        }

        return $result;
```

I think the equivalent is:

```php
        return !is_empty_date($dateFrom) && $storeTimeStamp >= $fromTimeStamp
            && !is_empty_date($dateTo) && $storeTimeStamp <= $toTimeStamp;
```

**Comment by kiatng** [comment]
My take:

```php
    public function isStoreDateInInterval($store, $dateFrom = null, $dateTo = null)
    {
        if (is_empty_date($dateFrom) || is_empty_date($dateTo)) {
            return false; // Exit right away, save some time.
        }

        $storeTimeStamp = $this->storeTimeStamp($store); // $store is resolved here anyway, no need to check $store instanceof Mage_Core_Model_Store
        $fromTimeStamp  = strtotime($dateFrom);
        $toTimeStamp    = strtotime($dateTo) + 86400;  // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
        
        return $storeTimeStamp >= $fromTimeStamp
            && $storeTimeStamp <= $toTimeStamp;
    }
```

**Comment by fballiano** [comment]
why do you think somebody used "strtotime($dateTo) + 86400"? It doesn't work when there's the daylightsaving switch, right? It could be replaced with 

strtotime($dateTo  . ' + 1day')

**Comment by fballiano** [comment]
> My take:
> 
> ```
>     public function isStoreDateInInterval($store, $dateFrom = null, $dateTo = null)
>     {
>         if (is_empty_date($dateFrom) || is_empty_date($dateTo)) {
>             return false; // Exit right away, save some time.
>         }
> 
>         $storeTimeStamp = $this->storeTimeStamp($store); // $store is resolved here anyway, no need to check $store instanceof Mage_Core_Model_Store
>         $fromTimeStamp  = strtotime($dateFrom);
>         $toTimeStamp    = strtotime($dateTo) + 86400;  // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
>         
>         return $storeTimeStamp >= $fromTimeStamp
>             && $storeTimeStamp <= $toTimeStamp;
>     }
> ```

This doesn't work in all cases, if $dateTo is empty the original function returns true, like eg:

`Mage::getModel('core/locale')->isStoreDateInInterval(0, '2022-01-01');`

while yours returns false

**Comment by fballiano** [comment]
the only thing I'd change is how the return is handled:

```
    public function isStoreDateInInterval($store, $dateFrom = null, $dateTo = null)
    {
        if (!$store instanceof Mage_Core_Model_Store) {
            $store = Mage::app()->getStore($store);
        }

        $storeTimeStamp = $this->storeTimeStamp($store);
        $fromTimeStamp  = strtotime($dateFrom);
        $toTimeStamp    = strtotime($dateTo);
        if ($dateTo) {
            // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
            $toTimeStamp += 86400;
        }
        
        if (!is_empty_date($dateFrom) && $storeTimeStamp < $fromTimeStamp) {
            return false;
        } elseif (!is_empty_date($dateTo) && $storeTimeStamp > $toTimeStamp) {
            return false;
        }

        return true;
    }
```
The rest is fine, and I don't think it's worth only changing the return.

If I'm not mistaken the logic checks that current time is between datefrom and dateto but:
- if datefrom is not provided then only checks that dateto is not passed
- if dateto is not provided then only checks that datefrom is not passed

And from my tests it seems to work correctly
