### ISSUE TITLE
Issue with Registration at Checkout using Paypal Express

### ISSUE THREAD

**Issue by bateaurouge** [OpenMage/magento-lts#2023]
### Preconditions (*)

1. OpenMage LTS 20.0.13 using Paypal Express (tested fresh install)
2. Magento 1.9.4.5 using Paypal Express (tested fresh install)
3. I think this began on version 1.9.3.8

### Steps to reproduce (*)

1.  Add item to cart, proceed to checkout
2.  On checkout page, choose Register to Create an Account
3.  Fill in information, proceed to payment method
4.  Choose Paypal Express
5.  Pay on Paypal
6.  Upon returning to the Magento site from Paypal, the browser Network panel shows a 302 status for /checkout/onepage/success, redirects to homepage, and customer is not logged in
7.  Order and Customer account are created but customer is unable to login. All login attempts result in redirection to homepage until password is reset.

### Expected result (*)

1.  Expect to see success page and logged in customer with working account

### Actual result (*)

1.  Upon returning to the Magento site from Paypal, the browser Network panel shows a 302 status for /checkout/onepage/success, redirects to homepage, and customer is not logged in
2.  There is no error message, no error in Magento log, no PHP error
3.  Order and Customer account are created but customer is unable to login. All login attempts result in redirection to homepage until password is reset.

I looked at the reset password function in the AccountController to see what may be missing from the account creation for Express Checkout.  Adding `$customer->setPasswordCreatedAt(time());` to an override of app/code/core/Mage/Paypal/Model/Express/Checkout.php:993 seems to fix the issue.

**Comment by elidrissidev** [comment]
That's weird. I can't see any relation between the `password_created_at` attribute and customer login, I even deleted it for an existing customer to test as I cannot try the Paypal checkout at this time, and I can login like normal. Did you do any other modification?

**Comment by bateaurouge** [comment]
Thanks for looking. 

I made no other modifications. I tested on clean installs because the site I originally saw the issue on was heavily modified and I wanted to rule out any extensions etc.

You should check `Mage_Core_Model_Session_Abstract_Varien::_validate()`

Also, the non-Paypal Express checkout registration at `Mage_Checkout_Model_Type_Onepage::_prepareNewCustomerQuote()` uses 
`$passwordCreatedTime = $this->_checkoutSession->getData('_session_validator_data')['session_expire_timestamp']
            - Mage::getSingleton('core/cookie')->getLifetime();`
` $customer->setPasswordCreatedAt($passwordCreatedTime);`

I am not sure of the ramifications of using `$customer->setPasswordCreatedAt(time());` like the password reset instead of the above.

It seems like the Paypal Express registration was simply forgotten when adding this validation in SUPEE-10752.
