### ISSUE TITLE
Replace deprecated `strftime` and `gmstrftime` PHP functions

### ISSUE THREAD

**Issue by elidrissidev** [OpenMage/magento-lts#2030]
The PHP functions `strftime` and `gmstrftime` were deprecated starting from PHP 8.1 and will be removed in the next major version, we should consider replacing them with alternatives without changing the behavior.

Ref: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

**Comment by kiatng** [comment]
Duplicate of issue #1812 .

**Comment by elidrissidev** [comment]
@kiatng Sorry, I didn't notice that PR. Although I do prefer small incremental fixes that are easier to review and merge.

**Comment by kiatng** [comment]
Issue #1812 was closed without resolution.
