### ISSUE TITLE
Store view scope product status attribute

### ISSUE THREAD

**Issue by henryhayes** [OpenMage/magento-lts#2036]
Product status attribute is available at website scope only. This should be store_view scope.

This causes a huge problem when you need to have a bundle or configurable product with items across all websites and only have the bundle items or configurable items show up in certain stores?

Why?

When you go to a specific store view when editing the product, the bundle items that are assigned to another website are no longer visible and when you save the product it removes the bundle items.

The only way to make this work properly, is to have all simple items assigned to all websites and have store view scope product status attribute.

My [research so far](https://stackoverflow.com/a/55649394/1439760) finds that the reason is that product status is set as a global attribute. 

My question is doing what's suggested in [this stack answer](https://stackoverflow.com/a/55649394/1439760) seems logical, But what would the wider impact be?

**Comment by fballiano** [comment]
The catalog is intended to be exactly the same within the same website so I think the actual implementation is the correct one. You shouldn't have a different catalog between store_views that should only differ on a translation level.
