### ISSUE TITLE
Product EAV and MultiSelect problem with StoreView and Default

### ISSUE THREAD

**Issue by Hanmac** [OpenMage/magento-lts#2065]
### Preconditions (*)

1. Use a Product Attribute with Multiselect that can be configured in StoreView
2. For Example have a Multiselect using Payment Methods, or any kind of list

### Steps to reproduce (*)

1. First you go into Global Scope and select some value.
2. Then you go into Store or website Scope, disable "use Default" and then choose nothing. (deselect all items)
3. when you try to save the Multiselect, the Form Data was problems, it thinks there is nothing set and it tries saves the values from Global Scope into Store Scope instead.

### Expected result (*)

1. It should save that there is no items selected.

### Actual result (*)

1. The first save does fail because of the form Data.

The Problem is this part in Varien Form Multiselect:
https://github.com/OpenMage/magento-lts/blob/main/lib/Varien/Data/Form/Element/Multiselect.php#L60-L62
https://github.com/OpenMage/magento-lts/blob/24a6c69ccf520c469d803a1735d30d66b2eb9857/lib/Varien/Data/Form/Element/Multiselect.php#L60-L62

When the input is disabled by the `checkFieldDisable`, the hidden input from multiselect is missing which is needed for the form to store empty data.

Possible Solution would be for Varien Form Multiselect to always add the hidden field, just disabled too

**Comment by fballiano** [comment]
I can't reproduce the problem, this is in global scope (with some elements selected):
<img width="821" alt="Schermata 2022-05-04 alle 22 10 16" src="https://user-images.githubusercontent.com/909743/166826509-199cca2f-897f-4297-982c-1bc5676a6a08.png">

and this is the store_view scope (after deselecting everything and save, this screenshot is taken post save):
<img width="799" alt="Schermata 2022-05-04 alle 22 10 25" src="https://user-images.githubusercontent.com/909743/166826593-fa492ce8-f22f-4166-9cb7-9e2528a0743d.png">

**Comment by Hanmac** [comment]
i did checkout current 1.9.4.* branch to check if can reproduce it.

without using any different backend or source model to reduce the error sources, i created a new Attribute in Backend via GUI:

i go to default global scope, selected one or two of them, pressed save, and the attribute is stored.
then i go to store view.

This part is important: because the values are set in global scope, `checkFieldDisable` should have disabled the Select, and "Use Default Value" have been checked. Inspecting the HTML code, the hidden input field should be missing.

so i uncheck the "use default value" checkbox, then the default values should have been selected. I deselect them all. Then I press save. (because the hidden input field is missing, the Controller should not have any form value and the product should still have its values from the global scope, but now they are saved in the store scope)

when the page loads again, the select is not disabled, the "use Default Value" is not checked, and the hidden input field is there.
Now when i deselect them again, and try to save them it works.

**Comment by Piralein** [comment]
The bug is reproducible with latest main.

Unchecking the `Use Default Value/Use Website` and simultaneously removing all selected options results in discarded information for the multi-select, because of the missing hidden input field.
While the state of the `Use Default value` checkbox (product configuration) is saved, the `Use Website` inside the configuration is not.

after save state (removing all selected options and unchecking the checkbox)
![product](https://github.com/OpenMage/magento-lts/assets/48352564/0756921e-7bd9-4d96-9510-41569642a93e)
![config](https://github.com/OpenMage/magento-lts/assets/48352564/ccb64d84-0f51-4553-a05f-33376e60368b)
