### ISSUE TITLE
Backend section headers

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2071]
After almost 12 years in which I did not pay attention to the visual aspects I found out that once I become aware of them I realize that they become annoying. Here is one of them. The headers of the sections in the Backend have a visual issue. At this moment there are several types of headers:

**No icon and with left margin which is looking edge**

![1](https://user-images.githubusercontent.com/8360474/167597020-38ce8ff0-9f78-435b-a930-5dd57a48f111.jpg)

**No icon and no left margin**

![2](https://user-images.githubusercontent.com/8360474/167597057-758ba7a4-ce4e-4784-8a97-8db142dc57a0.jpg)

**With the icon**

![3](https://user-images.githubusercontent.com/8360474/167597078-69b6bbdc-d9fa-4fe6-8a9b-61924426a2b9.jpg)

If I am remembering well In one of the PR's icons have been added to certain sections but many remain without. If it were up to me I would give up the icons, the left margin. I would make the text uppercase and I would give up the gray border below. Here's what the change looks like:

![4](https://user-images.githubusercontent.com/8360474/167596833-e2cc712a-2c04-4054-8f45-a8b62f3fb421.jpg)

**Comment by ADDISON74** [comment]
I have nothing against having icons in each header but as you can see we have an inconsistency and so we have 3 different visual implementations. 

A default icon would be a solution where a distinct one is not possible. Another idea would be to use the same icon for all the headers in each section Sales, Catalog, ..., System. For example in Sales menu {Orders, Invoices, Shipments, Credit Notes, Transactions, ..., Tax} then Tax {Manage Tax, ....} only one icon for all. We would have 8 + Dashboard icons for the default menus in OpenMage.

We already have icons in the skin directory but if you want you can use a dedicated library (e.g. font awesome, bootstrap icons, ...)

**Comment by fballiano** [comment]
Let's not add 3rd party icons set to the core please :-)

**Comment by fballiano** [comment]
I've created a PR for this, let's see
