### ISSUE TITLE
PHP 8 Fatal error:  Uncaught ValueError: imagecolorsforindex() in Varien_Image_Adapter_Gd2

### ISSUE THREAD

**Issue by iamniels** [OpenMage/magento-lts#2185]
### Preconditions

1. OpenMage 20.0.14
2. PHP 8.1, but likely a PHP 8.0 issue
3. [GD Version] => bundled (2.1.0 compatible)

### Steps to reproduce

1. Set the image below as a product image
2. Then execute the code below:
```php
$product = Mage::getModel('catalog/product')->load($productId);
echo (string) Mage::helper('catalog/image')->init($product, 'image')->resize(380,null);
```
![testimage](https://user-images.githubusercontent.com/717126/171580017-8b72a3c8-5365-4ebb-8b28-b527de1f9639.gif)

### Actual result

```
PHP Fatal error:  Uncaught ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range in /var/www/lib/Varien/Image/Adapter/Gd2.php:272
Stack trace:
#0 /var/www/lib/Varien/Image/Adapter/Gd2.php(272): imagecolorsforindex()
#1 /var/www/lib/Varien/Image/Adapter/Gd2.php(410): Varien_Image_Adapter_Gd2->_fillBackgroundColor()
#2 /var/www/lib/Varien/Image.php(155): Varien_Image_Adapter_Gd2->resize()
#3 /var/www/app/code/core/Mage/Catalog/Model/Product/Image.php(486): Varien_Image->resize()
#4 /var/www/app/code/core/Mage/Catalog/Helper/Image.php(367): Mage_Catalog_Model_Product_Image->resize()
```

**Comment by fballiano** [comment]
somebody else talking about it: https://github.com/processwire/processwire-issues/issues/1299

**Comment by ADDISON74** [comment]
There are a lot of discussions on the Internet if you search the error. It seems a lot of people are affected. Here is one resource: https://forums.oscommerce.com/topic/494720-kissit-image-thumbnailer-support/?page=8.

As the bug is confirmed we need a patch for OpenMage too.

**Comment by fballiano** [comment]
tested and can't reproduce the error, I think the image uploaded here by @iamniels is not the right one (because of github compression) because it's not transparent.

could you link the right image please?

**Comment by iamniels** [comment]
The image is correct, I can reproduce it with the gif from this page. It is indeed not transparent. Could you check whether `Varien_Image_Adapter_Gd2::_fillBackgroundColor` is being executed in your setup? It might depend on a config setting.

At first I tried to write a test using `Varien_Image_Adapter_Gd2` without `Mage_Catalog_Model_Product_Image` but then `_fillBackgroundColor` was not executed.
