### ISSUE TITLE
Dates columns in Backend grids need visual improvement

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2198]
In Backend grids have columns where you can filter the data by date.

This is how the columns in the "Catalog Price Rules" section look like now (OpenMage 20.14):

![before](https://user-images.githubusercontent.com/8360474/172199752-9a0ee911-e398-46c1-b51e-00685ea5d5ce.png)

This is how the columns would look like based on my future change:

![after](https://user-images.githubusercontent.com/8360474/172199723-fab41c0f-8361-4b0d-ba2b-aeb2788aba10.png)

**What are the benefits?**

- Those colons used after words To, From and In don't look good at all.

- The icon for calendar popup is placed immediately after the text when in fact it should be placed after the input box.

- The input boxes are a little bit increased. As you can see the date you fill in does not appear completely andit is truncated due to the width limitation set to 50px. In my proposal I changed it to 60px to cover all situations.

This is a visual enhancement. Any opinions are welcome.

**Comment by elidrissidev** [comment]
I agree with this change, it's more natural to have the date selection button to the right of the input.

**Comment by ADDISON74** [comment]
I will take care of this issue. Two PR's will be ready to fix visual issues in filter columns separately.
