### ISSUE TITLE
Inconsistent column width in Backend grids.

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2239]
In the Grid.php files that add columns to the Backend grids I found a mismatch between the width values ​​used for some types of columns that should be fixed. For example, columns in which filter by date should have somewhere at 140px so that the longest date to fit without going to the second row. But there are grids where either the width value is not specified or it is larger than necessary. I personally think that a revision of these grid is necessary.

Here is an example below:

![data_range](https://user-images.githubusercontent.com/8360474/174557132-89ecf5a2-3332-447d-8d8b-d1f63b6beea7.jpg)

As you can see the filter by date column is ridiculously wide. I checked and it should have a minimum width value of 140px. Once this value is set up in boxes.css it is not necessary to specify it in the Grid.php files, except where it is strongly desired not to take up too much space and making the layout look ugly.

After checking all grids I came to the conclusion there is not logic in determining the right widths. There is an inconsistency in setting these values and each programmer chose what he thought would suit, but could choose much better.

I will deal with this issue because it is a visual one and it bothers and becomes tiring when there is no harmony in the presentation of the information in the grids.

**Comment by fballiano** [comment]
closing since the linked PR is merged
