### ISSUE TITLE
PHP 8 is_recurring is enabled by default when creating a new product

### ISSUE THREAD

**Issue by iamniels** [OpenMage/magento-lts#2241]
### Preconditions (*)

1. PHP 8.1
2. MySQL 5.7
3.  OpenMage 19.4.3

### Steps to reproduce (*)

1. Create a new product
2. Go to the tab `Recurring profile`
3. Enable Recurring Profile is set to `yes`

### Expected result (*)

1.  Enable Recurring Profile is set to `no`

**Comment by elidrissidev** [comment]
You listed OpenMage v19.4.3 in the preconditions, but that version doesn't support PHP 8!?

**Comment by ADDISON74** [comment]
The report is vague without logs, screenshots, details about what you're doing.

I was not able to reproduce this issue with OM-20.13/PHP8.1.

**Comment by fballiano** [comment]
can't reproduce on latest OM20 with php8.1.7
