### ISSUE TITLE
Store scope hint points to unexisting old M1 documentation

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#2255]
In the backend, the store switcher has a hint:
<img width="357" alt="Schermata 2022-06-26 alle 00 21 19" src="https://user-images.githubusercontent.com/909743/175793323-8f1eb089-b65c-4a38-bae0-a92886c5a664.png">

and the `?` points to http://merch.docs.magento.com/ce/user_guide/configuration/scope.html which doesn't exist anymore.

Do we have a copy of that url somewhere? I was unable to find it.

**Comment by kiatng** [comment]
[Internet archive](https://web.archive.org/web/20170529192915/http://docs.magento.com/m1/ce/user_guide/configuration/scope.html) to the rescue.

**Comment by ADDISON74** [comment]
In what section are seen this? Here is what I am seeing in Manage Products (OpenMage 20.14):

![help_magento](https://user-images.githubusercontent.com/8360474/175813410-576beb06-ba15-448d-b3a0-8c2c30dde172.jpg)

There were discussions before removing those [?] here [#137](https://github.com/OpenMage/magento-lts/issues/1374) and [here https://github.com/OpenMage/magento-lts/issues/1374](https://github.com/OpenMage/magento-lts/issues/1376). 

Finally they were removed from OpenMage by this PR https://github.com/OpenMage/magento-lts/pull/1536. Are we bringing back the help in OpenMage based on Internet archive? I thought we agreed to get rid off it.

**Comment by fballiano** [comment]
I remembered something like that but I see it in my dev environment on 1.9.4.x branch

**Comment by Sdfendor** [comment]
@fballiano The PR mentioned is for the 20.0 branch so it's expectable to see it still in 1.9.4.x.

**Comment by fballiano** [comment]
@Sdfendor yes I later remembered and written https://github.com/OpenMage/magento-lts/pull/2256#issuecomment-1166518605
