### ISSUE TITLE
setPasswordCreatedAt() leads to PHP Warning

### ISSUE THREAD

**Issue by imaphpdev** [OpenMage/magento-lts#2285]
### Preconditions (*)

1. OpenMage 1.9.4.16

### Steps to reproduce (*)

1. Register while running through the onepage checkout

### Expected result (*)

1. no log inside system.log
2. correct value for customer-attribute "password_created_at" in table "customer_entity_int"

### Actual result (*)

1. "Warning: Trying to access array offset on value of type null  in app/code/core/Mage/Checkout/Model/Type/Onepage.php on line 733" is logged in system.log
2. customer-attribute "password_created_at" in table "customer_entity_int" has a negative value (depends on value for cookie-lifetime)

### Solution
```
$passwordCreatedTime = $this->_checkoutSession->getData('_session_validator_data')['session_expire_timestamp']
            - Mage::getSingleton('core/cookie')->getLifetime();
$customer->setPasswordCreatedAt($passwordCreatedTime);
````
Was added with magento patch SUPEE-10752.

Correct shuold be
```
$customer->setPasswordCreatedAt(time());
````
(see all the other usages of setPasswordCreatedAt())

**Comment by sreichel** [comment]
@all-contributors add @imaphpdev bug
