### ISSUE TITLE
Can't edit special price when mass editing product attributes

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#2286]
### Preconditions (*)

OpenMage 20.0.14 on php7.4

### Steps to reproduce (*)

- Go to backend, catalog -> products, select a product, open the mass action dropbox, select "update attributes".
- Try to modify the special price, without modifying anything else, hit "save"

### Expected result (*)

It should save the special price for the selected attributes.

### Actual result (*)

Whatever price you input the validation will fail with "The Special Price is active only when lower than the Actual Price." and you'll not be able to save.

**Comment by fballiano** [comment]
I think it should be fixed in js/prototype/validation.js

```
    ['validate-special-price', 'The Special Price is active only when lower than the Actual Price.', function(v) {
        var priceInput = $('price');
        var priceType = $('price_type');
        var priceValue = parseFloat(v);

        // Passed on non-related validators conditions (to not change order of validation)
        if(
            !priceInput
            || Validation.get('IsEmpty').test(v)
            || !Validation.get('validate-number').test(v)
        ) {
            return true;
        }
        if(priceType) {
            return (priceType && priceValue <= 99.99);
        }
        return priceValue < parseFloat($F(priceInput));
    }],
```

changing it to 

```
    ['validate-special-price', 'The Special Price is active only when lower than the Actual Price.', function(v) {
        var priceInput = $('price');
        var priceType = $('price_type');
        var priceValue = parseFloat(v);

        // Passed on non-related validators conditions (to not change order of validation)
        if(
            !priceInput
            || !$F(priceInput)
            || Validation.get('IsEmpty').test(v)
            || !Validation.get('validate-number').test(v)
        ) {
            return true;
        }
        if(priceType) {
            return (priceType && priceValue <= 99.99);
        }
        return priceValue < parseFloat($F(priceInput));
    }],
```

actually only adding the "|| !$F(priceInput)" condition, which seems to work fine to me.

I still wonder why blocking the validation when the message is clearly not an error... it seems to me the whole validation shoulnd't even happen.

**Comment by sreichel** [comment]
@all-contributors add @fballiano bug
