### ISSUE TITLE
Uncaught Error: Call to undefined method Mage_Catalog_Model_Resource_Category_Flat::getProductsPosition()

### ISSUE THREAD

**Issue by matteorossi-thespacesm** [OpenMage/magento-lts#2337]
### Preconditions (*)

1. OpenMage 19.4.15 and 19.4.16

### Steps to reproduce (*)

1. Call $category->getProductsPosition();
2.while using Category Flat Table

### Expected result (*)

1. array of products associated to related position in category
2.

### Actual result (*)

1. Fatal error:  Uncaught Error: Call to undefined method Mage_Catalog_Model_Resource_Category_Flat::getProductsPosition() in /mnt/sda/www/xeniosusa.com/htdocs/app/code/core/Mage/Catalog/Model/Category.php:390
2. Method getProductsPosition(9 should be added to Mage_Catalog_Model_Resource_Category_Flat class

**Comment by sreichel** [comment]
@all-contributors add @matteorossi-thespacesm 7 bug
