### ISSUE TITLE
Gender is not translatable

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#237]
... cause values come directly from `eav_attribute_option_value` table.

https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/design/frontend/base/default/template/customer/widget/gender.phtml#L30-L34

```
<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
<?php $value = $this->getGender();?>
<?php foreach ($options as $option):?>
    <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
<?php endforeach;?>
```
Is it enough to change label to `$this->__($option['label'])` or do you have a better idea?

**Comment by Flyingmana** [comment]
I remember I had to face this or a similar issue. I think that is/was the best solution, as most people would first use the normal translation files for this usecase.

Possible problem I see, it could cause some unintended translations if an attribute label (in a non english language) actually matches a translation. But I think thats an  acceptable risk
