### ISSUE TITLE
New admin theme: date fields to small

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#2397]
### Preconditions (*)

1. OM 19.4.17
2. new admin theme

### Steps to reproduce (*)

1. got to catalog price rules

### Expected result (*)

![grid2](https://user-images.githubusercontent.com/5022236/183807754-22627909-0d9d-471a-8418-434dfe4a554a.PNG)

### Actual result (*)

![grid1](https://user-images.githubusercontent.com/5022236/183807741-fb1d7e20-ea0b-4e80-9894-79c05fae6c9f.PNG)

---

Change CSS min-width for `.grid tr.filter .range div.date`?

**Comment by ADDISON74** [comment]
The issue comes from this PR https://github.com/OpenMage/magento-lts/pull/2330. When I created it I didn't test the OpenMage theme, I never used it. The interesting part is that the values I set are the optimal ones, if they change they must be analyzed because I was at the limit with them.

**Comment by ADDISON74** [comment]
It is not the only visual issue, here's another one

![screenshot](https://user-images.githubusercontent.com/8360474/184247571-85a3e1d4-c303-421b-a115-2215fc0c46fd.jpg)

I tried to make changes to look good in the OpenMage theme but the arrangement in the Magento theme is broken.

At first glance I would say that the Magento theme and the OpenMage theme should not share the same boxes.css file.
