### ISSUE TITLE
SOAP heavily broken in 19.4.17

### ISSUE THREAD

**Issue by leissbua** [OpenMage/magento-lts#2399]
### Preconditions (*)

1. 19.4.17

### Steps to reproduce (*)

1. Do Login via https://www.domain.com/api/v2_soap  WS-I Compliant YES or NO

### Expected result (*)

 Login Result given

### Actual result (*)

WS-I Compliant YES

PHP Fatal error: Procedure 'loginParam' not present in /home/cloudpanel/htdocs/[www.domain.com/releases/2022_08_10_4_10_06_branch_master_soapfix/lib/Zend/Soap/Server.php](http://www.gigaset.com/releases/2022_08_10_4_10_06_branch_master_soapfix/lib/Zend/Soap/Server.php) on line 889

WS-I Compliant NO

SOAP-ERROR: Parsing WSDL: Unexpected WSDL element <schema> in /home/cloudpanel/htdocs/www.domain.com/lib/Zend/Soap/Server.php on line 814

**Comment by ADDISON74** [comment]
Does it work in 19.4.16?

**Comment by leissbua** [comment]
Yes - we did a rollback to 19.4.16 on several live instances that failed to handle SOAP. I guess its related to several XML fixes/checks coming in in the recent 19.4.17. Need to do more research tomorrow, was a long day.

**Comment by ADDISON74** [comment]
I'm sorry I can't help you because I can't test SOAP, but if we have confirmation from you that it works in the previous version, we can identify the PR that generated the problem and revert it. On the SOAP side there were not many changes in the code in the last half year. There are good chances that it is the one mentioned by you.

**Comment by fballiano** [comment]
I'll test tomorrow morning and try to find out the problem.

**Comment by fballiano** [comment]
I did a quick test with postman on a vanilla v19 (actually the 1.9.4.x branch) and it worked normally:
<img width="882" alt="Schermata 2022-08-10 alle 19 43 47" src="https://user-images.githubusercontent.com/909743/183992251-f0eb26bf-3434-4b93-969d-c19293e0789b.png">

I could get the login token as usual

**Comment by fballiano** [comment]
and it seems to be working also on the checkout of the 19.4.17 tagged release.

can't check any further at this specific moment.

**Comment by ADDISON74** [comment]
I don't think that PR is to blame. The changes in it would not generate a situation like this. @leissbua could you please revert that PR and see what happens? If not possible just change the content of the file with that from 19.4.16 and flush the cache.

**Comment by elidrissidev** [comment]
It seems I'm able to login properly using the latest tagged version installed with composer.

Do you call the SOAP API in any specific way that we're not aware of (like using some third party tool)?

**Comment by leissbua** [comment]
thanks for adressing my issue. 

```
php --info | grep soap.wsdl_cache_dir

delete the wsdl cache file and the problem starts. Was a bitch in the live site, as the flush happened by script. I am trying to break it locally and report back. But maybe the problem can be reproduced on your side by flushing the tmp dir.

**Comment by elidrissidev** [comment]
I'm able to reproduce now but only with WS-I Compliance Mode enabled.

```php
$client = new SoapClient('http://magento.localhost/api/v2_soap/?wsdl'); 
$client->login((object)array('username' => 'apiUser', 'apiKey' => 'apiKey')); 
// SoapFault with message 'Procedure 'loginParam' not present'
```

**Comment by elidrissidev** [comment]
Also the error doesn't seem to happen if I disable the wsdl cache from the admin panel.

**Comment by fballiano** [comment]
I don't even know how to enable WS-I compliance mode 😅

**Comment by leissbua** [comment]
```
diff --git a/app/code/core/Mage/Api/Model/Wsdl/Config/Base.php b/app/code/core/Mage/Api/Model/Wsdl/Config/Base.php
index b3d21401e6..a142f99e51 100755
--- a/app/code/core/Mage/Api/Model/Wsdl/Config/Base.php
+++ b/app/code/core/Mage/Api/Model/Wsdl/Config/Base.php
@@ -56,7 +56,7 @@ class Mage_Api_Model_Wsdl_Config_Base extends Varien_Simplexml_Config
         // set up default WSDL template variables
         $this->_wsdlVariables = new Varien_Object(
             array(
-                'name' => 'Magento',
+                'name' => 'OpenMage',
                 'url'  => Mage::helper('api')->getServiceUrl('*/*/*', array('_query' => $queryParams), true)
             )
         );
        
``` 
This is what is breaking Magento SOAP. Need to dive in deeper.

**Comment by elidrissidev** [comment]
@fballiano System -> Configuration -> Magento Core Api

**Comment by leissbua** [comment]
Problem was:


```
-<wsdl:definitions xmlns:typens="urn:{{var wsdl.name}}"
+<wsdl:definitions xmlns:typens="urn:OpenMage"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema"
              xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
              xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
              xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
-             name="{{var wsdl.name}}"
-             targetNamespace="urn:{{var wsdl.name}}">
+             name="OpenMage"
+             targetNamespace="OpenMage">

**Comment by elidrissidev** [comment]
The main reason this change was made is because we wanted to introduce a CI workflow to validate XML files syntax, and since `{{var wsdl.name}}` is not a valid namespace it would generate false positive errors. I did spend a good amount of time trying to find a way to suppress these errors because I wasn't sure if this many changes may introduce unexpected issues in the future, but I never tested with WS-I mode enabled. I guess you can never be too cautious.

**Comment by leissbua** [comment]
This (changing the wsdl) has a tremendous impact on current installations, as most ERP-Systems cache the wsdl on there side. Just saying.

**Comment by sreichel** [comment]
@all-contributors add @leissbua bug
