### ISSUE TITLE
composer.json type value

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#24]
is there a specific reason why the `type` is set to `magento-source`? Other projects choose `magento-core` which is supported by at least 2 composer installers

**Comment by drobinson** [comment]
Not that I'm aware of - other than "it works".  Do you know what compability we gain/lose by going with another type?

**Comment by infabo** [comment]
I like this core installer: https://github.com/AydinHassan/magento-core-composer-installer
It uses `magento-core`

**Comment by tmotyl** [comment]
you can use both core installers
https://github.com/AydinHassan/magento-core-composer-installer
and 
aoepeople/composer-installers

See instructions here:
http://openmage.github.io/magento-lts/install.html

**Comment by tmotyl** [comment]
@LeeSaferite can you shed some light why magento-lts is using different type then other forks?

So if there is no good reason to keep different type I would opt for changing it. If there is, I would close the pull request and issues asking for the change as wont fix.

**Comment by LeeSaferite** [comment]
Well, historically, 'magento-source' came before 'magento-core'.

https://github.com/AOEpeople/composer-installers/commit/163aa5194e9b8b0bc864637260920304034a05ca

https://github.com/magento-hackathon/magento-composer-installer/commit/e61b4e4088fd4751d6f8f6eb1bdadf9b296a764d

**Comment by drobinson** [comment]
I think the question should be *is there a good reason to change it* since it will break backwards compatibility.  I would prefer to err on the side of not forcing anyone to update their config.

**Comment by tmotyl** [comment]
ok, lets leave it as it is
