### ISSUE TITLE
Cursor icon changes from pointer to wait even the page was fully loaded

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2420]
Go to **Backend > Catalog > Manage Products** and edit any product. After the product editing page is loaded press the [Save and Continue Edit] button and do not move the mouse. After the page is loaded by AJAX suddenly the mouse changes its icon from pointer to wait. It will stay like this if the mouse is not moved.

![cursor](https://user-images.githubusercontent.com/8360474/184504041-fb61437b-02ef-4185-8a7e-6eb786b93837.jpg)

**Comment by fballiano** [comment]
It seems not to happen to me, on chrome/macos

**Comment by ADDISON74** [comment]
I will also check in Linux to see what happens. If it is specific to Windows, it is not worth wasting our time.

**Comment by elidrissidev** [comment]
I tried this when I first saw it on Linux and couldn't see any change in the cursor.

**Comment by elidrissidev** [comment]
Tried this on Windows 11 and can't reproduce it. I think we should close as it may be related OS / browser version specific?

**Comment by ADDISON74** [comment]
I will close this issue in the next days if it is related to Windows 10 only.

**Comment by ADDISON74** [comment]
Here are test results from today:

- Fedora 36 + Chrome = no issue
- Arch 2022.10.01 + Chrome = no issue
- Ubuntu 22.04.1 + Chrome = no issue
- Windows 10 Pro 21H2 + Chrome latest = **issue** (two different desktops) 
- Windows 10 Pro 21H2 + Firefox latest = no issue (the same desktops)

Therefore, it is an issue identified only in Windows 10 Pro and which cannot be replicated in other operating systems. I don't consider it is a major problem to require detailed investigation, so I will close the report.
