### ISSUE TITLE
Add re-order button

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#244]
Currently the RE ORDER button only appears for customers **with** an account 

![image](https://cloud.githubusercontent.com/assets/652395/23855482/16d4119a-07f6-11e7-9a4a-3d971df3e771.png)

Extensions exist to create a dummy account for every customer using observer/batch

But would it not be possible to show the button also for guest checkout? (or at least create an option to do so). 

If someone has experience with this or seen similar code on the web then let us know; maybe we can create a simple pull and at least add som functionality

*business sense: re-typing data is just a lot of work and leads to errors ....

**Comment by tomekjordan** [comment]
Its really pain, when you must input all guest data to make 2nd order. A lot of mistakes can be made. During manual work. Reorder button should capture the same data or Magento should have register guest as customer option in admin area.

**Comment by tomekjordan** [comment]
I just found that, orderes Holded cannot be reordered. Button Reorder is missing for admins. It could be showed as usual, because orders On hold should have option to reorder.

**Comment by sreichel** [comment]
This should be possible w/o rewrites.
