### ISSUE TITLE
OM is not detecting draggable changes in Backend in Associated Products tab

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2454]
Go to **Backend > Manage Products** and edit any configurable product. In my case Black Nolita Cami.

Go to **Associated Products** tab. Drag "Color" over the "Size", which is a change in the Frontend if you save the product. This action is not detected, no save icon warning appears. Here is a screenshot for details:

![draggable](https://user-images.githubusercontent.com/8360474/185575372-117856d0-d6ac-4884-a38a-015febf03da1.jpg)

I hope I managed to discover all the actions that are not detected when a product is edited in Backend. The lack of that change/save warning icon is extremely important. If it doesn't warn, you risk making changes you don't know about, especially when you are distracted from work.

**Comment by fballiano** [comment]
this is being tricky to fix, let's see if i find a solution

**Comment by ADDISON74** [comment]
The ultimate test. Maybe it was not accidental that it remained at the end. With how many users Magento 1 had in its heyday, I am surprised that such apparently small and easy to notice issues were not reported and resolved.
