### ISSUE TITLE
Not able to add tags to products

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#2469]
### Preconditions (*)

1. 1.9.4.x-dev
2. php8.1

### Steps to reproduce (*)

1. cant add tags to products (new admin theme)
2. ...

Do I miss something?

**Comment by fballiano** [comment]
mmmm there's no button to add them (legacy theme), not even hidden. was it possible before?

**Comment by ADDISON74** [comment]
Is the module disabled in XML or in Backend? I have attached screenshots from Magento 1.9.4.5. I did not check in OpenMage 19 or 20.

![screenshot_1945](https://user-images.githubusercontent.com/8360474/185898827-6d04e99d-b18e-45ea-922c-7537f880411e.jpg)
![screenshot_1945-2](https://user-images.githubusercontent.com/8360474/185898832-3043ce9f-0e24-4fb6-8df7-71978a2fd67c.jpg)

**Comment by sreichel** [comment]
> Is the module disabled in XML or in Backend?

Thanks. Why is this disabled from backend in SampleData pack???

**Comment by ADDISON74** [comment]
I don't know how to answer you, but make sure you activate all the ones you want to test/use.
