### ISSUE TITLE
Catalog price rules core bug in Magento CE 1.9.1 and EE 1.14.1.0 

### ISSUE THREAD

**Issue by real34** [OpenMage/magento-lts#25]
See http://firebearstudio.com/blog/catalog-price-rules-core-bug-in-magento-ce-1-9-1-and-ee-1-14-1-0-array-to-string-conversion-error-and-incorrect-price-rules-behavior.html for further information and a patch

So far the issue is still "In progress" on magento bug tracker: http://www.magentocommerce.com/bug-tracking/issue/index/id/278
Is this the kind of things that you'd like to include? What would be the process then?

**Comment by Flyingmana** [comment]
Yes, that is a thing we would want to include.
We are still in a process to create a CI setup, so we can also add additional tests to reproduce the Bugs and validate the fixes are working.

Till then I think an accept from two members of the team is what it needs. In this case could it need a little longer, as they need to find the time trying it out and reviewing it.

**Comment by drobinson** [comment]
@real34 I know this is old, but if you'd like to include this patch will you submit a PR?

**Comment by seansan** [comment]
@real34 any update on this?

**Comment by tomekjordan** [comment]
will it be fixed?

**Comment by sreichel** [comment]
Was fixed in 1.9.2.0.

**Comment by tmotyl** [comment]
@sreichel I assume you've tested the issue with newer magento and found it's fixed. I'm closing the issue.

**Comment by sreichel** [comment]
Yep. Tested on 1.9.3.1 and looked where code hasr changed .

**Comment by sreichel** [comment]
@all-contributors add @real34 bug
