### ISSUE TITLE
"is not" filter in price rules not working as expected

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#252]
"is not" filter in price rules not working as expected

as I understand a known bug and reported to M. Waiting for a possible fix or link to the bug report

(will post later)

![image](https://cloud.githubusercontent.com/assets/652395/24650751/7e5a5c0c-192b-11e7-9d95-7895871ac709.png)

**Comment by sreichel** [comment]
Please reopen with some more information.
