### ISSUE TITLE
The locale is not displayed.

### ISSUE THREAD

**Issue by hgati** [OpenMage/magento-lts#2521]
OpenMage v20.0.15
Some of the selectable locales are not displayed at the bottom of the admin screen.
country name is blank.

![2022-08-30 23 20 15](https://user-images.githubusercontent.com/6913728/187463199-3b2053c9-1fc8-437a-ad83-b05999368264.png)

![aaa](https://user-images.githubusercontent.com/6913728/187463770-fa5e5136-00cf-42b2-a553-c9f7773a736c.png)

I tried the default theme not custom theme. It is also same. (not displayed)

**Comment by fballiano** [comment]
I've tested branch 1.9.4.x, 20.0 and tag v20.0.15 but I can't reproduce the problem, I always see this:

<img width="869" alt="Schermata 2022-08-30 alle 17 03 49" src="https://user-images.githubusercontent.com/909743/187485945-66d61d62-da13-45bc-938c-5d6cb3726ae5.png">

**Comment by hgati** [comment]
There is something issue on Mage::app()->loadCache($cacheId)
Some locales are missing.

![2022-08-31 01 17 31](https://user-images.githubusercontent.com/6913728/187490737-8e023ea6-93e4-4b52-99c0-130e0e7313e4.png)
![2022-08-31 01 24 34](https://user-images.githubusercontent.com/6913728/187490741-5bd4fdc2-ba1d-4099-9c0f-e302600cfcb4.png)

**Comment by fballiano** [comment]
mmm but that's not the code that's in the release:

https://github.com/OpenMage/magento-lts/blob/cf82b8f623e754e63c9a64dbf3c21adaf46ddc56/app/code/core/Mage/Adminhtml/Block/Page/Footer.php#L62

**Comment by hgati** [comment]
> mmm but that's not the code that's in the release:
> 
> https://github.com/OpenMage/magento-lts/blob/cf82b8f623e754e63c9a64dbf3c21adaf46ddc56/app/code/core/Mage/Adminhtml/Block/Page/Footer.php#L62-L81
> 
> you can check this link: https://github.com/OpenMage/magento-lts/blob/v20.0.15/app/code/core/Mage/Adminhtml/Block/Page/Footer.php#L62

Ahh, d($html) is my debugging code. 
d() is shortcut Kint::dump() using for [PHP debug](https://kint-php.github.io/kint/)
For testing return value of loadCache()

It seems to be related with cache.
It is displayed with cache disable.
![2022-08-31 01 51 17](https://user-images.githubusercontent.com/6913728/187494716-99c58cb6-c9f2-41be-8adf-e7dc7fa927ac.png)
![2022-08-31 01 40 34](https://user-images.githubusercontent.com/6913728/187494758-db1f430b-0bf7-4b73-aca6-34cb786e8b58.png)

**Comment by fballiano** [comment]
I've enabled all caches (on file, not redis) but still can't reproduce

**Comment by hgati** [comment]
Sometimes it didn't show up several times, but now I found that the reason was a cache problem.

**Comment by ADDISON74** [comment]
I was not able to reproduce this issue. 

Here is the latest OM cloned from repository with **cache enabled**:

![screenshot_cache_enable](https://user-images.githubusercontent.com/8360474/187546354-3e02ea81-b825-43ea-a3c4-47b629e6fffd.png)

Here is the latest OM cloned from repository with **cache disabled**:

![screenshot_cache_disable](https://user-images.githubusercontent.com/8360474/187546378-e830edae-1865-4754-8773-a6b1c06dfdce.png)
