### ISSUE TITLE
SOAP Api Connection Errors after upgrade to 19.4.17

### ISSUE THREAD

**Issue by Dirtyhair1** [OpenMage/magento-lts#2539]
### Preconditions (*)
1.Previously had OpenMage 19.4.15 installed with no issues. We updated to 19.4.17 on Wednesday and straight away have had issues connecting by SOAP to our inventory system. We have also been notified that Klaviyo cannot connect to our store either. 
2.

### Steps to reproduce (*)
1.Update to Openmage 19.4.17 from Openmage 19.4.15

### Expected result (*)
1. We should have a clean update with no issues, we tested the site on our staging setup before pushing live and didn't notice anything. On the staging site we don't have these platforms connected though so only found out once pushed to production/live site.

### Actual result (*)
1. Dear Systems - inventory system - cannot pull any orders from Magento store into Dear Systems, nor can it push any inventory updates to our Magento store. When we try to force it to do one of these actions, an error comes up which is in the image below:
![dear system error](https://user-images.githubusercontent.com/62090700/188043885-40d5ab01-4331-4453-9cdf-38a6b933bbd3.png)
"Unexpected WSDL element"
2. Klaviyo - email marketing platform - same issue but mainly refers to order/customer data, it is not syncing with Klaviyo and comes up with similar error:
"Invalid WSDL file at website. Received error message: "<unknown>:8:37: not well-formed (invalid token)."

Anyone else seeing anything like this?

**Comment by fballiano** [comment]
It could be this one btw:
https://github.com/OpenMage/magento-lts/pull/2405

**Comment by ADDISON74** [comment]
Check this file ```/app/code/core/Mage/Api/etc/wsi.xml```. 

If you have in line 8 the following statement targetNamespace="OpenMage" then change it to targetNamespace="urn:OpenMage".

**Comment by Dirtyhair1** [comment]
Hey guys, thanks for your feedback, fix mentioned above has been applied.

Klaviyo - can sync now so all good, no problems there.

Dear Systems - still having problems but changed message, please see below:

![E944D108-B7AE-4351-B051-7F60172E5A35](https://user-images.githubusercontent.com/62090700/188249409-be209256-c271-46e9-83d9-f4da221fd748.png)

“Failed to load orders: SOAP-ERROR: Parsing Schema: can't import schema from 'http://schemas.xmlsoap.org/soap/encoding/'”

So will have to look further.

Appreciate all you guys are doing but did the change that caused this need to be implemented in OpenMage 19.4.x?

I have gone through #2399 and #2405 

Just wondering if these kinds of changes should be kept in OpenMage 2.0.x

**Comment by sreichel** [comment]
> Dear Systems - still having problems but changed message, per below:
> 
> “Failed to load orders: SOAP-ERROR: Parsing Schema: can't import schema from '[http://schemas.xmlsoap.org/soap/encoding/'”](http://schemas.xmlsoap.org/soap/encoding/'%E2%80%9D)

This URL works for me. I just found this ... https://community.oracle.com/tech/apps-infra/discussion/648011/schemas-xmlsoap-org-is-not-working.

> Just wondering if these kinds of changes should be kept in OpenMage 2.0.x?

This issue/error/bug is not related to 19.4 or 20.x versioning at all. This change was made to validate XML files, that would be okay for 19.x too, but we just have not tested it properly.

My question is, why it takes so long to bring a new release. This problem is known for 3 weeks and i dont know when next release is planned. If we break something in latest release, we should be possible to fix it quickly.

**Comment by Dirtyhair1** [comment]
@sreichel ok got you. Sorry if that came across wrong, but what I meant was, this change has caused issues in previously fine Magento/OpenMage stores. Anyway, didn’t mean to be rude, just commenting.

Further, I have run the process again and now the error message is changed:

“ Failed to load orders: CommunicationException: Error in deserializing body of reply message for operation 'salesOrderList'.”

I understand what you were saying and I wonder how many other stores have been affected like this. One thing to note is we DON’T have “WS-I Compliant” enabled which was mentioned in #2399 

I’m sure this will be an easy fix, but yeah, unexpected issue for sure.

**Comment by sreichel** [comment]
There was nothing wrong or rude :) This problem exists since some days an should be fixed asap.

**Comment by ADDISON74** [comment]
From what someone said in another post, the cache must be deleted and it still lasts until it is deleted on the other side.

**Comment by fballiano** [comment]
@sreichel let's merge https://github.com/OpenMage/magento-lts/pull/2546, then I'll update https://github.com/OpenMage/magento-lts/pull/2416 and we merge that too and then I'll do a release.

In the meanwhile let's not merge anything else, at least we get that done!

**Comment by Dirtyhair1** [comment]
> From what someone said in another post, the cache must be deleted and it still lasts until it is deleted on the other side.

Yes sorry I went back through those other issues. Have reached out to them to ask for them to clear the cache on their side…who knows how long that will take. Will update once resolved.

**Comment by sreichel** [comment]
> In the meanwhile let's not merge anything else, at least we get that done!

Good idea. This is why i set all my PRs on draft (except from admin css fix an php7.3/intl)

**Comment by elidrissidev** [comment]
> Dear Systems - still having problems but changed message, per below:
> 
> “Failed to load orders: SOAP-ERROR: Parsing Schema: can't import schema from 'http://schemas.xmlsoap.org/soap/encoding/'”
> 
> So will have to look further.

Just thought I'd share that we also get similar errors from time to time since a few months ago (running an 19.4.14), might be a problem from upstream.

**Comment by fballiano** [comment]
@elidrissidev if you've a lot of traffic on the API you'll reach the rate limit of calls to the schema.org domain and sadly I think that's nothing we can do about that :-\

**Comment by fballiano** [comment]
@Dirtyhair1 did it solve?

**Comment by elidrissidev** [comment]
@fballiano yeah I know, just thought I will mention since he posted he was receiving the same error.

**Comment by Dirtyhair1** [comment]
@fballiano thanks for checking in. Not good here unfortunately. It's turning into a right royal disaster. We have contacted our inventory system support team numerous times but they have not flushed the wsdl cache, who knows how long it is set to. All our product stock levels are incorrect. All our products are synced in the backend using a "bill of materials" structure, so selling one item affects stock levels of different items. Anyway, I am sure we will get it resolved I am just not sure how the system will handle it when all these orders from 5 days come in and then what that will do to the stock levels of items we have been selling via our storefront and wholesale. Currently we are manually managing things and hoping for the best. Will keep you updated when I know more.

**Comment by sreichel** [comment]
Maybe this helps ... https://stackoverflow.com/questions/323561/force-re-cache-of-wsdl-in-php

**Comment by Dirtyhair1** [comment]
> Maybe this helps ... https://stackoverflow.com/questions/323561/force-re-cache-of-wsdl-in-php

Cheers. Reason this is still on-going is I am not a developer, I am the humble store owner, I wish I could implement the actions in the above line. I will get our developers to check it out once they are online.

**Comment by Dirtyhair1** [comment]
Right, so the inventory guys have replied they don't cache wsdl data and anyway it would have cleared over the weekend. Will have the developers keep digging.

**Comment by fballiano** [comment]
they may not cache it actively but (for example) php does it anyway:

`php --info | grep soap.wsdl_cache_dir`

that dir has to be checked for wasdl cache files and cleaned

**Comment by luigifab** [comment]
We have the same problem, but with another solution.
One of our installed module use a fixed targetNamespace:

```
app/code/community/Fooman/Surcharge/etc/wsdl.xml
              name="{{var wsdl.name}}" targetNamespace="urn:{{var wsdl.name}}">
 
     <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
             <import namespace="http://schemas.xmlsoap.org/soap/encoding/" schemaLocation="http://schemas....
             <complexType name="salesOrderEntity">
                 <all>
```

This produce:

```
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL:
  Unexpected WSDL element <schema> in testapi/soap-sales.php:58
Stack trace:
#0 testapi/soap-sales.php(58): SoapClient->__construct()
#1 {main}
  thrown in testapi/soap-sales.php on line 58
```

So the solution is to replace `urn:Magento` by `urn:OpenMage`.

**Comment by ADDISON74** [comment]
A warning related to this modification is required in the README file. 

If there are still extensions that use ```targetNamespace ="urn:Magento"``` or ```wsdl.name``` , they must be changed ASAP.

**Comment by Dirtyhair1** [comment]
Yes @ADDISON74 and @luigifab are spot on. 

Looks like some of the extensions we had installed were causing this issue due to them using the older targetNamespace.

I am surprised that this was only mentioned in this issue and also #2399, must be a lot of stores out there affected.

**Comment by ADDISON74** [comment]
I would not revert, but change from OpenMage to Magento, possibly in both versions.

**Comment by elidrissidev** [comment]
> I would not revert, but change from OpenMage to Magento, possibly in both versions.

Yes, exactly what I meant

**Comment by fballiano** [comment]
I wouldn’t change it back cause people may already have fixed it and we’ll break it again, let’s push a backend notification, modify the release notes and add a line in readme (imho)

**Comment by Dirtyhair1** [comment]
> I wouldn’t change it back cause people may already have fixed it and we’ll break it again, let’s push a backend notification, modify the release notes and add a line in readme (imho)

I think backend notification is best, I also thought that originally. Just like the “free Ukraine” one that is hard to miss.

**Comment by ADDISON74** [comment]
Both a notification in the README file and one in the Backend are fine. The latter must be approved quickly, if I'm not mistaken in that repository we have an open PR that should have been merged for a long time (I have no rights there).

**Comment by ADDISON74** [comment]
Here is the repository https://github.com/OpenMage/Web_Notifications. I think that the major changes that are in progress should be announced through this feature that exists in OpenMage. For example, the minimum requirement for PHP as being 7.3, but also others.

**Comment by fballiano** [comment]
> We have the same problem, but with another solution. One of our installed module use the old targetNamespace:
> 
> ```
> app/code/community/Fooman/Surcharge/etc/wsdl.xml
> 
> <definitions xmlns:typens="urn:{{var wsdl.name}}" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
>              xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas..."
>              xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/"
>              name="{{var wsdl.name}}" targetNamespace="urn:{{var wsdl.name}}">
>  
>      <types>
>         <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
>              <import namespace="http://schemas.xmlsoap.org/soap/encoding/" schemaLocation="http://schemas....
>              <complexType name="salesOrderEntity">
>                  <all>
> ```
> 
> This produce:
> 
> ```
> PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL:
>   Unexpected WSDL element <schema> in testapi/soap-sales.php:58
> Stack trace:
> #0 testapi/soap-sales.php(58): SoapClient->__construct()
> #1 {main}
>   thrown in testapi/soap-sales.php on line 58
> ```
> 
> So the solution is to replace `urn:Magento` by `urn:OpenMage`.

you could also have replaced with `{{var wsdl.name}}"`, probably cleaner

**Comment by fballiano** [comment]
I've updated the release notes (in the release page here on github) and created a PR for an update to the README https://github.com/OpenMage/magento-lts/pull/2559

**Comment by sreichel** [comment]
I hope it's okay to close this.

**Comment by prafullkachhadiya** [comment]
This is still an issue with latest version 19.4.18.
We are getting same issue with Klaviyo as mentioned in this issue's description.
I checked the file app/code/core/Mage/Api/etc/wsi.xml and seen that `targetNamespace` is set to correct value `urn:OpenMage`.
Is there a way to fix this?

**Comment by prafullkachhadiya** [comment]
I found that we have wsdl.xml files in our couple of custom plugins we are using.
Fix suggested by @fballiano for replacing `urn:Magento` with `urn:OpenMage` all wsdl.xml files of custom or any 3rd party plugins worked for us and fixed the issue with WSDL error.
