### ISSUE TITLE
Duplicate product keys in rewrite table in CE

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#255]
Duplicate product keys in rewrite table in CE

Is this still applicable?

https://www.atwix.com/magento/duplicated-product-url-keys-in-community-edition/

**Comment by andreasemer** [comment]
No, this is already fixed in CE Core...

**Comment by seansan** [comment]
OK thanks ;) .... I'll close it. .... we are facing however multi 1000-en rows of simple products under configurable products (simple products that are not viewable individually) .... was this also in the fix?

**Comment by andreasemer** [comment]
I think this issue was fixed in 1.9.3.1, maybe you have a older CE version? Using the Magento Standard Indexer with a lot of products, especially with Conf/Simple products is not the best idea ;-)

**Comment by seansan** [comment]
>> Using the Magento Standard Indexer with a lot of products, especially with Conf/Simple products is not the best idea ;-)
OK we use 1931 - but what do you mean with the "Magento Standard Indexer" yes we use this and yes we have many Conf/Simple products ... whats the alternative? (really appreciate your help here)

**Comment by andreasemer** [comment]
Here are issues with conf/simple products and the url indexer in Magento:
* You are creating also URLs for simples, but you don't need or use them
* You are creating "category URLs" for every category which is assigned to a product, even if are have disabeled this option in the backend. So if a product is in category "a", "b" and "c" there is a url for this ("a/product1", "b/product1" and "c/product1")
* The reindex is very slow and messes up the db

We have started to use http://www.dnd.fr/2012/09/magento-patch-how-to-optimize-re-index-processing-time-for-url-rewrite/ but then ended up with our own solution for the url indexer.

**Comment by seansan** [comment]
Thanks Andreas. We do use DND (Phew!)
