### ISSUE TITLE
Not load search widget in header searh

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#2568]
### Preconditions (*)
Last version

### Steps to reproduce (*)
copy source file in root folder
start composer

### Actual result (*)
Not load Search widget in header-serch

**Comment by ADDISON74** [comment]
If you had posted this issue in Magento 2, it would have been closed immediately for lack of detailed information. 

Honestly speaking, I would like to see all steps described, screenshots, to immediately understand what it is about and to be able to allocate a little time to the investigation to determine if it is an issue or not.

**Comment by Danieleeffe1** [comment]
Thanks for the reply

I don't know how to describe it differently as I did exactly as described above

I can give you more information

starting magento 1.9.4.5

updated with openmage 20.0.13

copied and pasted openmage source in the magento root

updated openmage from 20.0.13 to 2.0.16

copied and pasted openmage source in the magento root

started composer update

the template is based on RWD

in the folder design frontend / rwd / my template / etc I have copied the original files of RWD default.

php7.4
apache 2

magento cache and Lesti_FCP disabled

**Comment by ADDISON74** [comment]
I am sorry but I don't have the patience to test such a description.

**Comment by Danieleeffe1** [comment]
No, magento/openmage v20.0.16. not is the last version?

Il mer 7 set 2022, 10:39 ADDISON ***@***.***> ha scritto:
