### ISSUE TITLE
Note: add tax amount column to sales_order_grid

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#257]
As a simple improvement 

add tax amount column to sales_order_grid

**Comment by sreichel** [comment]
I think there are so many different use cases/requirements that adding additional columns to any grid should be handled with events/observers.

**Comment by colinmollenhour** [comment]
I agree, everyone needs different columns and if they are all added to grid then the grid table will become as large as the base table.

**Comment by infabo** [comment]
larger than the base table.
