### ISSUE TITLE
Problem adding product to cart

### ISSUE THREAD

**Issue by roby255** [OpenMage/magento-lts#2584]
### Preconditions (*)

1. migrate from v1.9.4.5 whit script
2. update to v19.4.18

### Steps to reproduce (*)

1. Cache disabled, enable log
2. I made the migration with OpenMage Migration Script, with no error
3. Updated to v19.4.18 (the problem appared also before the update)
4. Without login, i put a product in the cart (the porto ajax cart work, in quote table in database the product appeared)
5. Go to the cart
6. I found nothing in the cart

### Expected result (*)

I must find the product in the cart

### Actual result (*)

Sometime you find the product, but most of the time you don't find nothing

The problem seem don't appen when logged
I checked the log and the console but no error append.
I undestend that could be a cookie problem, but my setting in the backend seem ok!

What to check?

I dont' know if it's the right place to write, if i'm wrong, sorry in advance.
Thank you in advance for the help

**Comment by ADDISON74** [comment]
I tried to reproduce this issue without luck. Here are my steps.

1. I installed Magento 1.9.4.5 + Sample Data Pack (from Nexcess)
2. I downloaded the OpenMage v19.4.18 archive from this repository
3. I did not use the upgrade script and I did not delete the Magento files, but I copied the contents of the archive over the existing files replacing them.
4. I flushed the cache and the sessions. I loaded the Frontend and added a product to the basket. Below screenshot.

![addtocart](https://user-images.githubusercontent.com/8360474/189453946-d01badef-7df3-4c72-973d-e938a7728c30.png)
