### ISSUE TITLE
Checkout options config not available in storeview scope

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#259]
https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/code/core/Mage/Checkout/etc/system.xml#L38-L55

_Group_ is set to `<show_in_store>0</show_in_store>`, but some _Fields_ are set to `<show_in_store>1</show_in_store>`

_Group_ should be visible in storeview scope too. PR coming later ...

**Comment by LeeSaferite** [comment]
If you are feeling ambitious, I'd say the *real* fix is that a group should have the visibility of the union of the children. So, as soon as a single child setting is a store level setting, the group gets the store level flag.

**Comment by sreichel** [comment]
> Edit: Really, the whole menu system should auto-show based on the child items.

... AND it should also work in the opposite direction, so that you can define visibility on `section`/`group` level w/o defining it on _lower_ levels.
