### ISSUE TITLE
check if SUPEE-389 needs to be applied (Every time the catalog URL is rendexed, a new custom rewrite is created)

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#26]
SUPEE-389: Every time the catalog URL is rendexed, a new custom rewrite is created
https://gist.github.com/piotrekkaminski/c348538ca91ba35773be

**Comment by drobinson** [comment]
Doesn't look like this has been included in the core yet, do you want to apply it or wait and see if we get it with a new version?

**Comment by seansan** [comment]
Would Wait now if it is only 1 week. But I know many sites where this is a problem. SO if not included I would suggest to add it immediately

**Comment by drobinson** [comment]
It looks like this was built into the original `getUnusedPath` method - circa v 1.13.1

**Comment by sprankhub** [comment]
@drobinson could you share details? In my experience, Magento 1.9.3.4 still creates more and more rewrites with each reindex.

**Comment by sreichel** [comment]
@all-contributors add @tmotyl bug
