### ISSUE TITLE
Backend Customer Grid filter issue with filter_condition_callback

### ISSUE THREAD

**Issue by prafullkachhadiya** [OpenMage/magento-lts#2645]
### Preconditions (*)

1. OpenMage version 19.4.18 upgraded from Magento community edition 1.9.4.2

### Steps to reproduce (*)

1. Have the custom customer attribute and add that attribute to Customer grid inside backend.
2. While defining column in Customer grid add the attribute `filter_condition_callback` and configure the class of the callback function which is not inside Grid block itself i.e. call back function you are providing for this attribute must not be inside Mage_Adminhtml_Block_Customer_Grid. This callback function must be outside in some other class instance.
3. For example add column by using Event Observer like below code.
Event definition in `config.xml`
`<core_block_abstract_prepare_layout_before><observers><vendor_custommodule_customer_grid><class>custommodule/observer</class><method>prepareCustomerGrid</method></vendor_custommodule_customer_grid></observers></core_block_abstract_prepare_layout_before>`

Event Function definition in Observer class `Vendor_Custommodule_Model_Observer` with file `Observer.php`

`public function prepareCustomerGrid($observer)
{
$block = $observer->getBlock();
$customerGridClass = Mage::getConfig()->getBlockClassName('adminhtml/customer_grid');
if ($customerGridClass != get_class($block)) {
return $this;
}
$block->addColumn('custom_attribute', [
'header' => Mage::helper('custommodule')->__('Custom Attribute),
'index' => 'custom_attribute',
'filter_condition_callback' => [$this, 'filterCustomAttributeCallback'],
]);
}`

Here `filter_condition_callback` defined with value `[$this, 'filterCustomAttributeCallback']` which means `$this` reference to Observer `Vendor_Custommodule_Model_Observer` instance instead of original Custom grid class. Filter callback function already defined inside Observer class like below:

`public function filterCustomAttributeCallback($collection, $column)
{
$value = $column->getFilter()->getValue();
if (empty($value)) {
return;
}
$condition = $collection->getConnection()->prepareSqlCondition('custom_attribute.sometext', $value);
if (empty($value["from"])) {
$condition .= "OR custom_attribute.sometext IS NULL";
}
$collection->getSelect()->where($condition);
}`

### Expected result (*)

1. When we filter customer grid with this custom attribute it should filter the grid with the given callback function.

### Actual result (*)

1. Throws Mage_Eav exception with message Invalid attribute name: custom_attribute

### Solution (*)
1. I found that this happening because addition conditions add in function _addColumnFilterToCollection in class  `Mage_Adminhtml_Block_Widget_Grid` in file `app/code/core/Mage/Adminhtml/Block/Widget/Grid.php` in line number 496 and the code is `if ($column->getFilterConditionCallback() && $column->getFilterConditionCallback()[0] instanceof self) {`
2. Inside Magento community edition same function same file and same class has code on line number 467
`if ($column->getFilterConditionCallback()) {`

In OpenMage additional condition `$column->getFilterConditionCallback()[0] instanceof self` added to IF for checking whether the callback function is from same class instance or not. And if that condition gets failed it will not allow filter and throws the exception with the filter callback.

So, as to allow custom plugins to add custom attribute columns to any admin grid, this additional condition needs to remove.

**Comment by kiatng** [comment]
I can confirm that this is not a bug, the code was part of [patch SUPEE-11219](https://devdocs-openmage.org/guides/m1x//ce19-ee114/ce1.9_release-notes.html#ce19-1943).

You can try the solution in this [StackExchange](https://magento.stackexchange.com/a/306941/3506).

Basically, you can extend your observer class to `Mage_Adminhtml_Block_Widget_Grid`, which will then satisfy `$column->getFilterConditionCallback()[0] instanceof self`. I hope this helps with your issue.
