### ISSUE TITLE
Editing orders in Backend - Actions are not working

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2646]
OpenMage 19.4.18
Magento Sample Data

1. Go to ```Backend > Sales > Orders```. Search for **Order # 100000055** which has 4 items ordered.
2. Click [Edit] button. Select on the **Action** column "Remove" for the last two items in the grid. Click [Submit Order].
3. **Order # 100000055-1** was created. 

Take a look to the **Items Ordered** grid bellow. The last two items we removed in step 2 are still there. Let's edit this new order, this time by removing the first two products (Ann Ankle Boot and A Tale of Two Cities). Order # 100000055-2 is created and in the grid we see the same items ordered.

In conclusion, **Actions** are not working when editing orders.

![screenshot](https://user-images.githubusercontent.com/8360474/193938016-60ee80b9-6a12-46fd-9d39-3a4a88a17b7c.jpg)

It came to my attention today when an administrator told me that he received an order of 5 items, but he was able to send only 3. He wanted to create a new order by editing the first one and remove the items unavailable. After submitting the order the items he removed were still in the new order. My test confirms the issue.

If I remember well from the past this worked great in Magento 1.9.3. I will check it with the last version of Magento too.

**Comment by elidrissidev** [comment]
Did you click "Update Items and Qty's" after selecting the "Remove" action?

**Comment by ADDISON74** [comment]
Not yet. Did it work for you?

**Comment by elidrissidev** [comment]
I'm not on my computer to try now. But only selecting the Action from the dropdown won't do anything to my knowledge. You have to click Update.

**Comment by ADDISON74** [comment]
In my installation, pressing that button kept the changes made in the order, but not in his case. I thought I would get away easily, but it will take me time to identify the issue, it is an installation with many extensions. He never used order editing before, because he would have reported the problem since then.

Considering that it is not an issue in OpenMage but a particular one, I will close the report. I deleted two of our short messages that were not relevant to keep the clarity of the conversation.
