### ISSUE TITLE
/dev/openmage/install.sh - Script issue when installing

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2647]
@colinmollenhour - Please take a look to the screenshot bellow. 

![screenshot](https://user-images.githubusercontent.com/8360474/193903533-96aa511f-a6b5-4657-90dd-2598fe2604db.png)

It is from a (Ubuntu 22.04 + Docker) without anything else installed. You can see the steps I followed until I run ```install.sh```. Those directories I don't have permissions for are from an OpenMage installation.

I took a look at the installation file and I commented line 39:

```sh
echo "Preparing filesystem..."
chmod 777 ../../app/etc ../../media
#$dc run --rm --no-deps cli mkdir -p var/cache var/log var/locks var/session
```

Below is what happened by running the installation file again:

![screenshot2](https://user-images.githubusercontent.com/8360474/193905750-e6fb9089-eca3-4dd5-a6fa-b72ea296aef1.png)

As I see line 39 and other changes were added recently in this commit https://github.com/OpenMage/magento-lts/commit/4b1282d12775eb7da09ce4b30f0330b35a6bebe5.

**Comment by ADDISON74** [comment]
@elidrissidev - You are correct, it was changed 2 hours ago. I am glad @colinmollenhour found this opened issue so fast. 

I encourage both the DDEV and Colin's variants to quickly create a test environment for OpenMage. At first glance, the reported issue was solved, but I would like to test it before stating this.

**Comment by colinmollenhour** [comment]
Hey I saw this message and just had a few minutes to test and push a fix.. Another issue I noticed is it seems the docker images I used are no longer being maintained so there is probably more work to do on this (e.g. PHP should be updated) but wanted to push a quick fix to avoid wasting any more dev time if anyone ran into the same issue.
