### ISSUE TITLE
Indexers shouldn't reindex disabled storeviews

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#2650]
I was doing some tests in a multiwebsite environment and I notices that reindexing the EAV was creating records in the `catalog_product_index_eav` table also for disabled store views.

I think this should be avoided if possible, so I was checking the `Mage_Catalog_Model_Resource_Product_Indexer_Eav_Source` and it only filters out store_view 0, but always processes all other store views:

<img width="854" alt="Schermata 2022-10-10 alle 12 56 03" src="https://user-images.githubusercontent.com/909743/194860910-48952115-3f7d-4407-b900-35227ddc7f84.png">

should we get the list of enabled store_views and replace the `where('s.store_id != 0')` with a where store_id IN (list of all enabled storeviews)?

opinions?

**Comment by elidrissidev** [comment]
Do you know if other product indexes do the same? like price and stock indexes, if they do then it would make sense to do it to stay consistent and also reduce table size for big stores.

**Comment by fballiano** [comment]
Price index should be only global/website and there's no way to disable a website at the moment, so I think this "problem" shouldn't apply to the price index.

Stock, if I'm not mistaken, is only global.

**Comment by elidrissidev** [comment]
You're right my bad, both of them are global. In this case I personally can't find another reason to keep indexing them, you can open the PR and wait for others' opinions.
