### ISSUE TITLE
WYSIWYG editor doesn't open on product admin page

### ISSUE THREAD

**Issue by hansgv** [OpenMage/magento-lts#2656]
Under the admin UI's Catalog > Manage Products > Edit page, the WYSIWYG Editor for the Description or Short Description fields on the General tab doesn't open. Instead I see a series of errors in my browser console (not sure which one's are related to this specifically)

SyntaxError: Unexpected token ';' (this is from a javascript snippet where `var LOADING_TIMEOUT = ;`)
ReferenceError: Can't find variable: BLANK_IMG (this is from a javascript snippet where `Ext.BLANK_IMAGE.URL = BLANK_IMG;`)
Failed to load resource: the server responded with a status of 404 (Not Found) http://extjs.com/s.gif
Can't find variable FORM_KEY (I think this is the error that pops up when actually trying to open the editor)

I can reproduce this only after upgrading my Openmage 19.4.17 site to 19.4.18.

**Comment by sreichel** [comment]
Cant reproduce with 19.4.x-latest

**Comment by ADDISON74** [comment]
I tried to reproduce the error in OM 19.4.18 cloned today from the repository, but without success. Below is a screenshot from the Backend. In Console there are no messages and two issues appear related to prototype.js and tiny.mce.js, but they are not related to the reported issue.

![screenshot](https://user-images.githubusercontent.com/8360474/195817426-e8899cf5-29ed-452f-92cf-a2a6b44a3682.png)

After any upgrade the OpenMage cache must be cleaned, also the browser cache. In a test environment disable both caches.

**Comment by hansgv** [comment]
@elidrissidev I did empty Magneto's cache as well as browser's.

What additional info can I provide to help debug this?

I upgraded my site by extracting the 19.4.18 tar package to my root directory. None of the errors appear pre-upgrade. Everything else seems to work es expected both pre and post upgrade.

**Comment by elidrissidev** [comment]
Can you post the content of the first `<script>` tag in the `<head>` of the product edit page? it should look like this:
```html
<script type="text/javascript">
    var BLANK_URL = 'http://magento.localhost/js/blank.html';
    var BLANK_IMG = 'http://magento.localhost/js/spacer.gif';
    var BASE_URL = 'http://magento.localhost/index.php/admin/index/index/key/7a18a1ef53f5ed89b706dd61538e420d/';
    var SKIN_URL = 'http://magento.localhost/skin/adminhtml/default/default/';
    var FORM_KEY = 'QPBwweNxDvA7KaXZ';
    var LOADING_TIMEOUT = 200;
</script>
```

All of the errors seem to be related to some of these variables missing.

**Comment by hansgv** [comment]
@elidrissidev 

Looks like this:

```
    <script type="text/javascript">
        var BLANK_URL = 'https://mydomain.com/js/blank.html';
        var BLANK_IMG = 'https://https://mydomain.com/js/spacer.gif';
        var BASE_URL = 'https://https://mydomain.com/index.php/hallinta/index/index/key/613fe4ceec22a7df08f7305ae1d31357/';
        var SKIN_URL = 'https://https://mydomain.comi/skin/adminhtml/default/openmage/';
        var FORM_KEY = 'm07aQdv3hHfaAJxq';
        var LOADING_TIMEOUT = ;
    </script>
```

I think the FORM_KEY error points to this method in `loader.js`.

```
Ajax.Request.addMethods({
    initialize: function($super, url, options){
        $super(options);
        this.transport = Ajax.getTransport();
        if (!url.match(new RegExp('[?&]isAjax=true',''))) {
            url = url.match(new RegExp('\\?',"g")) ? url + '&isAjax=true' : url + '?isAjax=true';
        }
        if (Object.isString(this.options.parameters)
            && this.options.parameters.indexOf('form_key=') == -1
        ) {
            this.options.parameters += '&' + Object.toQueryString({
                form_key: FORM_KEY
            });
        } else {
            if (!this.options.parameters) {
                this.options.parameters = {
                    form_key: FORM_KEY
                };
            }
            if (!this.options.parameters.form_key) {
                this.options.parameters.form_key = FORM_KEY;
            }
        }
```

**Comment by elidrissidev** [comment]
I am able to reproduce your issue, but only if I make the method `Mage_Adminhtml_Block_Page_Head::getLoadingTimeout()` return an empty string or null.

Please check the `app/code/core/Mage/Adminhtml/Block/Page/Head.php` file and make sure the content was copied correctly. You can also run the following snippet from a PHP file and see if it's gonna return something (should return a number):
```php
<?php
require_once 'app/Mage.php';
Mage::app();
var_dump((new Mage_Adminhtml_Block_Page_Head)->getLoadingTimeout());
```

**Comment by hansgv** [comment]
@elidrissidev It returns a int(200).

**Comment by sreichel** [comment]
Is there any rewrite for `Mage_Adminhtml_Block_Page_Head`?

**Comment by hansgv** [comment]
@sreichel I don't understand your question. Can you elaborate?

**Comment by sreichel** [comment]
Can you please add `var_dump(get_class($this))` to app/design/adminhtml/default/default/template/page/head.phtml to verify its not rewritten?

**Comment by hansgv** [comment]
@sreichel @elidrissidev Where in `app/design/adminhtml/default/default/template/page/head.phtml` should I add `var_dump(get_class($this))`? I tried adding it to the bottom but that doesn't seem right.

**Comment by elidrissidev** [comment]
You may wanna keep that extension enabled if you're actually using it, and instead just copy `getLoadingTimeout` method from `Mage/Adminhtml/Block/Page/Head.php` to `Fooman/SpeedsterAdvanced/Block/Adminhtml/Page/Head.php`.

**Comment by kiatng** [comment]
It'll be good to create this issue in https://github.com/fooman/speedsteradvanced

**Comment by sreichel** [comment]
> It'll be good to create this issue in https://github.com/fooman/speedsteradvanced

Just wait a minute .... ;)
