### ISSUE TITLE
composer validate is failing now (locked version mismatch of php-cs-fixer)

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#2665]
Since few commits the composer.json and composer.lock are not aligned.

I remember there was an CI check for it 
see
https://github.com/OpenMage/magento-lts/commit/feb7f060e44553bfd741d7fd3477aa795db17e0a

but seems it's not running any more?

### Steps to reproduce (*)

1. run `composer validate`

### Expected result (*)

Validation is OK

### Actual result (*)

```
./composer.json is valid but your composer.lock has some errors
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
- Required (in require-dev) package "friendsofphp/php-cs-fixer" is in the lock file as "v3.4.0" but that does not satisfy your constraint "^3.11".
- Required (in require-dev) package "phpstan/phpstan" is in the lock file as "1.8.8" but that does not satisfy your constraint "^1.8.10".
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require

```

**Comment by sreichel** [comment]
Seems it was removed in #2410

**Comment by elidrissidev** [comment]
Might be worth adding back the validation to existing workflows where composer is used.

**Comment by fballiano** [comment]
so "composer install" in all the workflows (like https://github.com/OpenMage/magento-lts/blob/1.9.4.x/.github/workflows/phpstan.yml) doesn't validate?

**Comment by elidrissidev** [comment]
> so "composer install" in all the workflows (like https://github.com/OpenMage/magento-lts/blob/1.9.4.x/.github/workflows/phpstan.yml) doesn't validate?

no it installs normally.
