### ISSUE TITLE
Page Head for Adminhtml throws JS Error - 

### ISSUE THREAD

**Issue by pisc-software** [OpenMage/magento-lts#2668]
### Preconditions (*)

1. OpenMage 20.0.16
2. Update store from older OpenMage release

### Steps to reproduce (*)
1. Upgrade from an older OpenMage release by updating store files
1. Enter Admin area
2. Apply filter to any grid

### Expected result (*)
1. Grid performs action

### Actual result (*)
1. JS error in browser: Uncaught SyntaxError: Unexpected token ';'
2. JS error in browser: Uncaught ReferenceError: FORM_KEY is not defined

### The Issue corrected:
Mage_Adminhtml_Block_Page_Head has added a new function ''getLoadingTimeout()".
Templatefile "adminhtml/default/default/page/head.html has the following line:

    var LOADING_TIMEOUT = <?php echo $this->getLoadingTimeout() ?>;

This line expects a number value, however the config string "admin/design/loading_timeout" does return an empty string / null value as there is no default value defined in the "config.xml".

Adding a default value to "config.xml" of Mage_Adminhtml will resolve this, otherwise use '' to ensure that empty values are correctly handled:

   	<default>
   		<adminhtml
	  		<admin>
	  			<loading_timeout>2000</loading_timeout>

**Comment by elidrissidev** [comment]
Hey, thanks for your report! This seems to be the same issue as #2656, please refer to that thread for the solution.
Thanks.

**Comment by elidrissidev** [comment]
Just to clarify, the return statement of `getLoadingTimeout()` casts the value of the config to an `int`, so if it's`null` it becomes 0, which is the default because there's no timeout in Magento.

**Comment by kiatng** [comment]
I think there should be a fix for this, we should expect there will be plenty more override of `Mage_Adminhtml_Block_Page_Head`.

**Comment by justinbeaty** [comment]
Hi, (sorry I’ve been away for some time, been very busy!)

I think we can just use a null coalesce operator in the phtml file so it defaults to zero there, too.

I can PR tomorrow in case no one else does it sooner.

**Comment by kiatng** [comment]
There is already a fix for this in issue #2661, however, it is yet to be merged to branch 20. I'm not sure how it can be merged sooner. @fballiano ?

**Comment by justinbeaty** [comment]
Ah, okay yes the cast works too. 

When making the original PR, I guess I didn’t consider that 3rd party code might not have extended the base classes. I suppose someone could have also overwrote the file in code/local too, but there’s probably lots of cases in OpenMage where doing that would break things.

**Comment by pisc-software** [comment]
Thats OK. We have overriden the "head.phtml" for the admin area with an intermediate fix for that, so the customers store is working. Thanks for the efforts to continue Magento 1.9 with this.
