### ISSUE TITLE
clearStoreProductsInvalidRewrites doesn't return any items for cleanup due to select structure

### ISSUE THREAD

**Issue by PFortin93** [OpenMage/magento-lts#2743]
### Preconditions (*)

1. 1.6-
2. 20.0.7

### Steps to reproduce (*)

In [app/code/core/Mage/Catalog/Model/Resource/Url.php](https://github.com/OpenMage/magento-lts/blob/2afbba93b23fda237029473c4bdcbce6889328bb/app/code/core/Mage/Catalog/Model/Resource/Url.php#L1156-L1171  `clearStoreProductsInvalidRewrites()` contains L1160 a join `WHERE (...) AND website.website_id = :website_id', ` but later in the function, L1169 appends `$select->where('website.website_id IS NULL');. `How would this ever return data if it's filtering to where the website_id is set but also where the website ID is null? See SQL statement pulled from database here:

```sql
SELECT `rewrite`.`url_rewrite_id` 
FROM `core_url_rewrite` AS `rewrite`
LEFT JOIN `catalog_product_website` AS `website` 
  ON rewrite.product_id = website.product_id AND website.website_id = '1' 
WHERE (rewrite.store_id = '1') 
  AND (rewrite.category_id IS NULL) 
  AND (rewrite.product_id IS NOT NULL) 
  AND (website.website_id IS NULL)
```

This query is poorly performing (returning in 3 seconds with a 1.3 million row table scan) to return no data.
### Expected result (*)

The query should be formatted in a way in which data would be returned for cleaning. I think the extra  `$select->where('website.website_id IS NULL');` shouldn't be there.

### Actual result (*)

Data is never returned.

**Comment by kiatng** [comment]
Tested @elidrissidev reasoning by adding a new entry in the table `core_url_rewrite`. The select statement indeed returns the newly added row.
