### ISSUE TITLE
Problem during checkout with paypal express after upgrade from 19.4.16 to 19.4.19

### ISSUE THREAD

**Issue by sprippen-it** [OpenMage/magento-lts#2756]
### Preconditions (*)

1. OpenMage 19.4.19

### Steps to reproduce (*)

1. Place order during checkout with method payment PayPal Express

### Expected result (*)

1. Go to paypal webite to place payment

### Actual result (*)

1. stay on website with error "you don't have permission to make this api call error 10002"
![paypal-openmage](https://user-images.githubusercontent.com/88031901/203591819-48fbe5a5-dd4f-4a4b-b725-eca09cc3ec39.png)

**Comment by sprippen-it** [comment]
I restored the app/code/core/Mage/Paypal/Model/Config.php file from version 19.4.18 and now it works

**Comment by elidrissidev** [comment]
The only difference in `Mage/Paypal/Model/Config.php` between `v19.4.18` and `v19.4.19` is the addition of public properties in #2554:
```diff
+    public $allow_ba_signup;
+    public $api_cert;
+    public $api_password;
+    public $api_signature;
+    public $api_username;
+    public $apiAuthentication;
+    public $apiPassword;
+    public $apiSignature;
+    public $apiUsername;
+    public $business_account;
+    public $businessAccount;
+    public $buttonFlavor;
+    public $buttonType;
+    public $cctypes;
+    public $debug;
+    public $lineItemsEnabled;
+    public $lineItemsSummary;
+    public $paymentAction;
+    public $paymentMarkSize;
+    public $requireBillingAddress;
+    public $sandboxFlag;
+    public $solutionType;
+    public $transferShippingOptions;
+    public $verifyPeer;
+    public $visible_on_cart;
+    public $visible_on_product;
```

Dropping this here in case someone else can check why this is happening, sorry I haven't time to check any further right now.

**Comment by falkone** [comment]
I can confirm it. Removing these properies fix the problem - can also be tested on sandbox mode.
It seems the Problem is the camel case and Mage magic getter / setter.
One Problem is the business account the other the sandbox flag:
```
...
public $business_account;
public $businessAccount;
...
public $sandboxFlag;
...
```
Removing or uncomment fix the problem.

**Comment by elidrissidev** [comment]
> the Problem is the camel case and Mage magic getter / setter.

Can you elaborate please? What does magic getters/setters have to do with this issue?

**Comment by elidrissidev** [comment]
Nevermind I understood the problem. Thanks @falkone for digging in!

**Comment by dimdimich** [comment]
This issue is still present in 19.4.20. So we were forced to use app/code/core/Mage/Paypal/Model/Config.php from 19.4.18 also.

**Comment by elidrissidev** [comment]
@dimdimich How's that!? To my understanding the problem was with the introduction of properties to that class which caused a problem because it was using magic __get. Can you check if any of the config properties are returning the correct value or just `null`?
