### ISSUE TITLE
SUPEE-9767

### ISSUE THREAD

**Issue by cundd** [OpenMage/magento-lts#277]
Maybe I've overlooked something: Is SUPEE-9767 applied to the `1.9.3.x` branch, or is it blocked by the known issues mentioned here: https://magento.com/security/patches/supee-9767

**Comment by Flyingmana** [comment]
we instead wanted to directly update to the new version, which already includes the bugfixes.
see #276

**Comment by sreichel** [comment]
Just for information .... [Security Patch SUPEE-9767 - Possible issues?](https://magento.stackexchange.com/a/176958/46249)

**Comment by infabo** [comment]
ambitious goal - 19 days ago.

**Comment by seansan** [comment]
V2 released: https://magento.com/tech-resources/download?mkt_tok=eyJpIjoiTkRRMU16RXpOMll6WkdZNCIsInQiOiJqUzJLWGpQRVF4ZU1kM1dCbEJKVHBJXC9FMDVsRGw0R2ZCYldSWjErRDlvT2JiWllTY2lWREN2WUg2bDVGUmRGXC9oSDJ3dXRZSXk4T0MwSk9BZ1UyN0FrTWVJMGF0QWt6aHg3T3UxUFdFZ2FZMFFTT1BaRWdzWFN1NEJcL1wvNGxPVHgifQ%3D%3D#download2034

**Comment by Flyingmana** [comment]
also there is a new magento release, so I would say, just merge the new release into the openMage mirror and then pull this into Mage-LTS

**Comment by Flyingmana** [comment]
the newest version 1.9.3.4 was merged, so the content of this patch should be includes.

**Comment by seansan** [comment]
just to be sure. and this is in 1.9.3.x ... ?


[image: Inline image 1]

**Comment by sreichel** [comment]
@seansan Yes :)
