### ISSUE TITLE
Magento defaultsort in category not showing default config value from backend

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#278]
Magento defaultsort in category not showing default config value from backend

In main backend config we have set default sortby NAME

![image](https://user-images.githubusercontent.com/652395/26964014-feb895ce-4cef-11e7-911c-d77f4f23b669.png)

In category this is not reflected (catalog_category/index)

Actual result in category (with default config flag): Best value
Expected result in category (with default config flag): Name

![image](https://user-images.githubusercontent.com/652395/26963833-dd2431d0-4cee-11e7-930e-c81e00b68ac3.png)

We never realized because it was always best value, which is the first value of the array .... but now when we changed to to a different version we suddenly see this is not working as expected

Not sure if the lgoci is here. https://github.com/OpenMage/magento-lts/blob/1.9.3.x/app/code/core/Mage/Catalog/Model/Category.php

But maybe for someone of more knowledge of the backend models/templates this is a quick fix

**Comment by sreichel** [comment]
Think this is only a display issue. Can you please check if sorting works as expected in frontent? (For me it does)

**Comment by seansan** [comment]
Seems only display in adminhtml

**Comment by seansan** [comment]
Still an issue isn’t it?

**Comment by sreichel** [comment]
It just displays 1st attribute from available sortable attributes. Not perfect, but it works ...

**Comment by seansan** [comment]
I know. Probably a quick fix.

**Comment by sreichel** [comment]
No, its not soo quick ... ;)

**Comment by fballiano** [comment]
I've submitted PR https://github.com/OpenMage/magento-lts/pull/2062 to fix this issue and, since this one doesn't get any comment since 3 years, I'm closing it.
