### ISSUE TITLE
Credis symlinks wrong?

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#2781]
### Preconditions (*)

1. latest 19.4.x (with composer modules added)

### Steps to reproduce (*)

1. added this to `composer.json`
```
    "magento-deploystrategy": "copy",
    "magento-deploystrategy-dev": "symlink",
    "magento-force": true,
```
2. run `composer install` ... symlinks for CM_ are created
3. delete `vendor`
4. run `composer install --no-dev`

### Expected result (*)

1. symlinks should be replaced by files

### Actual result (*)

1. Credis copy fails

![credis](https://user-images.githubusercontent.com/5022236/205515035-e1c7061f-0cf0-4cc1-96c6-63dac532e3e7.PNG)
![credis2](https://user-images.githubusercontent.com/5022236/205515259-b67630fd-d3f4-4cdd-b1e3-596f0408cd5e.PNG)

**Comment by fballiano** [comment]
when I do the `composer install --no-dev` I get:

```
In Copy.php line 133:
                                                                                                                                                                                                                                                           
  copy(/Users/fab/Projects/openmage/vendor/colinmollenhour/cache-backend-redis/lib/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis/Credis): failed to open stream: Invalid argument   
```

I think the problem is with the "magento-force" option

**Comment by sreichel** [comment]
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/issues/65 is not fixed `lib/Credis` is empty.

**Comment by AGelzer** [comment]
Info: [magento-composer-installer](https://github.com/Cotya/magento-composer-installer) has problems with change deploy strategy symlink to copy


 See: [Pull request #208](https://github.com/Cotya/magento-composer-installer/pull/208)

**Comment by sreichel** [comment]
@AGelzer thank you.

@Flyingmana your're maintainer there ... have you time to review this?

**Comment by Flyingmana** [comment]
For this I first need to know if the same happens when using modman, as we tried back then to copy the behavior (which included bugs like these if directories were already existing)
Also changing without removing is more or less undefined behaviour.
