### ISSUE TITLE
Bug: Block core/list defined outside any layout handle

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#279]
See: https://magento.stackexchange.com/questions/689/block-core-list-defined-outside-any-layout-handle

It's still there in 1.9.3. It does only affect `base/default` template. RWD is correct.

**Comment by sreichel** [comment]
This line can be deleted. It's not called in the `onepage_checkout_failure` template ...

**Comment by nintenic** [comment]
@sreichel Seems to be correct.

**Comment by colinmollenhour** [comment]
Fixed in c760e367a06188e63d42f6f50738d5dbf5b21eaf (forget to add "Fixes #279" to commit message until it was too late..)
