### ISSUE TITLE
Add a Redis cache "dashboard" for 19.x and 20.x

### ISSUE THREAD

**Issue by simbus82** [OpenMage/magento-lts#2792]
### Description (*)
Sometimes it's needed to check the status of redis cache or refresh only parts of cache.
So i think could be useful add a feature like https://github.com/steverobbins/Magento-Redismanager

### Expected behavior (*)
A dashboard to check, manage and flush redis caches.

### Benefits
- Manage different cache in load balanced environments
- Flush all redis cache databases directly from admin panel: it's possibile to clear sessions, or execute flushdb and flushall commands for true cache purging.
- Delete cache keys by matched strings
- View redis usage statistics

### Additional information
The proposed utility is tested and working with latest good old Magento 1.9.4.x, but i don't know if it works well with latest Openmage changes.

**Comment by ADDISON74** [comment]
This is not an issue in OpenMage but a solution to an extension that we already want to outsource using Composer. personally, I would have proposed this extension for discussion in the Discussions section. If it is an active project, the solution is agreed by everyone, it can be added with Composer by those who use Redis.

**Comment by simbus82** [comment]
> This is not an issue in OpenMage but a solution to an extension that we already want to outsource using Composer. Personally, I would have proposed this extension for discussion in the Discussions section. If it is an active project, the solution is agreed by everyone, it can be added with Composer by those who use Redis.

Sorry, i have clicked this in Github issues :-) It was probably better if I asked in the discussion area first.
![image](https://user-images.githubusercontent.com/1375730/206261999-b44356c0-af57-42d1-bcca-0b7bd85f6f66.png)

I thought that since Redis has become "recommended", it would be a good idea to include its management in the core as a default module (if the third party agrees, since they haven't updated it for years).
But I guess keeping everything optional is much cleaner.
