### ISSUE TITLE
Call to undefined function rray_key_exists() in lib/Magento/Db/Adapter/Pdo/Mysql.php

### ISSUE THREAD

**Issue by hansgv** [OpenMage/magento-lts#2793]
### Preconditions (*)
OpenMage 19.4.20

### Steps to reproduce (*)
Attempt to save a product

### Expected result (*)
Saving works

### Actual result (*)
Error PHP Fatal error:  Uncaught Error: Call to undefined function rray_key_exists() in /var/www/vhosts/idlounge.fi/lib/Magento/Db/Adapter/Pdo/Mysql.php:135

I presume it's because it should be array_key_exists(). Fixing the typo seems to fix the issue.

**Comment by elidrissidev** [comment]
I believe this was already fixed in #2780
