### ISSUE TITLE
"Bug": Typo in Mage_HTTP_Client_Curl

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#281]
See: https://magento.stackexchange.com/questions/158818/bug-in-magento-curl-php

I know this class isn't/shouldn't be used, but it doesn't hurt to fix this to:

    /**
     * Set curl options array directly
     * @param array $array
     */
    protected function curlOptions($array)
    {
        curl_setopt_array($this->_ch, $array);
    }

**Comment by Flyingmana** [comment]
its part of the downloader... but yes, thats a fair thing to fix
