### ISSUE TITLE
protected function _isApplicableAttribute

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2829]
I am running in a test environment with DDEV the latest OM 20 + PHP 7.3 (requested by Composer). I installed an old extension which worked great with PHP 7.0 to update it to 8.2 but OM is not loading some sections that this extension adds to the Backend. 

In the browser window I am getting a fatal error like this: 

```php
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Abstract.php:70 

Stack trace: 
#0 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(622): Mage_Catalog_Model_Resource_Abstract->_isApplicableAttribute(Object(Ave_SizeChart_Model_Chart), Object(Ave_SizeChart_Model_Resource_Eav_Attribute)) 

#1 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1618): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterLo...', Array) 

#2 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(952): Mage_Eav_Model_Entity_Abstract->_afterLoad(Object(Ave_SizeChart_Model_Chart)) 

#3 /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Abstract.php(743): Mage_Eav_Model_Entity_Abstract->load(Object(Ave_SizeChart_Model_Chart), 1, NULL) 

#4 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(291): Mage_Catalog_Model_Resource_Abstract->load(Object(Ave_SizeChart_Model_Chart), 1, NULL)
 
#5 /var/www/html/app/code/community/Ave/SizeChart/controllers/Adminhtml/Sizechart/ChartController.php(42): Mage_Core_Model_Abstract->load(1) 

#6 /var/www/html/app/code/community/Ave/SizeChart/controllers/Adminhtml/Sizechart/ChartController.php(86): Ave_SizeChart_Adminhtml_Sizechart_ChartController->_initChart() 

#7 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(429): Ave_SizeChart_Adminhtml_Sizechart_ChartController->editAction() 

#8 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch('edit') 

#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(190): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) 

#10 /var/www/html/app/code/core/Mage/Core/Model/App.php(373): Mage_Core_Controller_Varien_Front->dispatch() 

#11 /var/www/html/app/Mage.php(739): Mage_Core_Model_App->run(Array) 

#12 /var/www/html/index.php(71): Mage::run('', 'store') 

#13 {main} thrown in /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Abstract.php on line 70
```

Based on the error I checked the **/app/code/core/Mage/Catalog/Model/Resource/Abstract.php** file on line 70. Here is the PHP code:

```php
    /**
     * Check whether the attribute is Applicable to the object
     *
     * @param Varien_Object $object
     * @param Mage_Catalog_Model_Resource_Eav_Attribute $attribute
     * @return boolean
     */
    protected function _isApplicableAttribute($object, $attribute)
    {
        $applyTo = $attribute->getApplyTo();
        return count($applyTo) == 0 || in_array($object->getTypeId(), $applyTo);
    }
```

If I change it as follows

```php
        $applyTo = array($attribute->getApplyTo());
```

the fatal error disappears and there are no more errors in /var/log/system.log file from now on like I got with PHP 7.3.

As you may see I am editing an OpenMage file to make this extension working properly. Do you consider this an issue into the OM code related to new PHP versions we need to take in consideration? Maybe PHPStan could solve this mystery but I am not an expert, honestly speaking I never used it.

**Comment by sreichel** [comment]
Can you share code of Ave/SizeChart?

**Comment by ADDISON74** [comment]
Unfortunately, the developer is from Ukraine, the official website is down, no replies. I hope he is alive. It is a paid extension and I am posting only the parts of code that appear in error.

**/app/code/community/Ave/SizeChart/controllers/Adminhtml/Sizechart/ChartController.php**

```php
    protected function _initChart()
    {
        $this->_title($this->__('Size Chart'))
             ->_title($this->__('Manage Charts'));

        $chartId  = (int) $this->getRequest()->getParam('id');
        $chart    = Mage::getModel('ave_sizechart/chart')
            ->setStoreId($this->getRequest()->getParam('store', 0));

        if ($chartId) {
            $chart->load($chartId); ***** THIS IS LINE 42 *****
        }

        Mage::register('current_chart', $chart);
        return $chart;
    }
```

```php
    public function editAction()
    {
        $chartId  = (int) $this->getRequest()->getParam('id');
        $chart    = $this->_initChart(); ***** THIS IS LINE 86 *****
        if ($chartId && !$chart->getId()) {
            $this->_getSession()->addError(
                Mage::helper('ave_sizechart')->__('This chart no longer exists.')
            );
            $this->_redirect('*/*/');
            return;
        }

        if ($data = Mage::getSingleton('adminhtml/session')->getChartData(true)) {
            $chart->setData($data);
        }

        $this->_title($chart->getName());
        Mage::dispatchEvent(
            'ave_sizechart_chart_edit_action',
            array('chart' => $chart)
        );
        $this->loadLayout();
        if ($chart->getId()) {
            if (!Mage::app()->isSingleStoreMode() && ($switchBlock = $this->getLayout()->getBlock('store_switcher'))) {
                $switchBlock->setDefaultStoreName(Mage::helper('ave_sizechart')->__('Default Values'))
                    ->setWebsiteIds($chart->getWebsiteIds())
                    ->setSwitchUrl(
                        $this->getUrl(
                            '*/*/*',
                            array(
                                '_current'=>true,
                                'active_tab'=>null,
                                'tab' => null,
                                'store'=>null
                            )
                        )
                    );
            }
        } else {
            $this->getLayout()->getBlock('left')->unsetChild('store_switcher');
        }

        $this->getLayout()->getBlock('head')->setCanLoadExtJs(true);
        $this->renderLayout();
    }
```

**Comment by ADDISON74** [comment]
I am starting to consider that it's not the extension that's to blame for the error but the OpenMage code related to the PHP version used.

**7.0**: is running fine. no errors appear in the system.log and in the browser window
7.2, 7.3, 7.4: all are running but errors appear in the system.log
```php
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Abstract.php on line 71
```
8.0: is not running. the fatal error appears in the browser, nothing in the system.log

I wanted to find out the value of the **$applyTo** variable. I insert var_dump()and this is what it displays in browser

Frontend: array(0) { }
Backend: NULL

It is obvious that using the count() function in these conditions will generate an error. Searching the Internet for the fatal error I found a lot of pages where the solution is to convert the type to array. Once done in the OpenMage code, the error disappear and extension works without issues.

**Comment by ADDISON74** [comment]
Here is what appears now in system.log with PHP 8.2 after I converted the variable to array:

```php
2022-12-21T10:41:32+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view/media.phtml on line 42
2022-12-21T10:41:32+00:00 ERR (3): Warning: count(): Parameter must be an array or an object that implements Countable  in /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view/media.phtml on line 53
```
It seems this error is a known one. I certainly wouldn't have found out about it if I hadn't tested this extension. There are a lot of people asking for help in the last year in different PHP forums. Here is one resource 

https://stackoverflow.com/questions/53020833/count-parameter-must-be-an-array-or-an-object-that-implements-countable-in-lar

**Comment by ADDISON74** [comment]
I ran the code bellow in DDEV changing PHP version from 7.0 to 8.2

```php
$varTest = null;
var_dump(count($varTest));
```
It produces on output with PHP 7.2 - 7.4 "Warning: count(): Parameter must be an array or an object that implements Countable in … on line 2". Starting with version 8.0 it is a fatal error.

Because the minimum requirements of the OM are already for PHP set to version 7.3 I would propose to modify the OpenMage code in the case of the count() function to deal specifically with the situation when a variable has the value NULL.

Using array($variable) is not quite suitable as a solution but one just to see an immediate effect, although if it is NULL it becomes an empty array. Also, the replacement with !empty($variable) or isset($variable) doesn't seem right to me.

In PHP 7.3 the **is_countable()** function was introduced. I would propose that the change be as follows

count($admin) => count((is_countable($admin)?$admin:[]))

We can also check the variable directly in an if condition with !is_null($variable).

**Comment by fballiano** [comment]
maybe some module is overriding the getGalleryImages() method or something like that?

**Comment by ADDISON74** [comment]
At this moment the extension is disabled by editing its module file. I was able to reproduce this issue pretty simple, by renaming the media directory then creating an empty one. OM thinks the products have images but there are not physically accessible. This issue is not related to the one reported here, I discovered it by chance.

Using count function with NULL values is really an important issue. Even we fix this one there a lot in the code. Now I realize that many do not upgrade the operating system and for this reason we do not have reports, but when they will do it we will definitely identify others count related issues.

**Comment by sreichel** [comment]
> I was able to reproduce this issue pretty simple, by renaming the media directory then creating an empty one. OM thinks the products have images but there are not physically accessible.

Cant reproduce it with 1.9.4.x / PHP8.1

When media directory is empty and i go to product page, placeholder images are added.

**Comment by ADDISON74** [comment]
No problem. I will spend some time on this issue. I have in plan more tests.

**Comment by sreichel** [comment]
> I wanted to find out the value of the **$applyTo** variable

Can you add a xdebug breakpoint there an post stacktrace? (or share code?)

**Comment by ADDISON74** [comment]
In DDEV with PHP 7.4 / OpenMage 19.4.21 installed from scratch + AveRun SizeChart extension

If I change in /app/code/core/Mage/Catalog/Model/Resource/Abstract.php line 71 from

```php
return count($applyTo) == 0 || in_array($object->getTypeId(), $applyTo);
```

to 
```php
return is_countable($applyTo) == 0 || in_array($object->getTypeId(), $applyTo);
```

there are no errors in browser window and system.log file.

Going further to PHP 8.2 this time the extension works correctly in Frontend/Backend but I am getting warnings in system.log that I need to investigate 

```php
 Warning: setValue(): Argument #3 ($keys) must be passed by reference, value given  in /var/www/html/app/code/community/Ave/SizeChart/controllers/Adminhtml/Sizechart/ChartController.php on line 551
```

I wouldn't say that I have yet formed an opinion but I think the change in the OpenMage code is required from count() to is_countable() to be compatible with PHP 8.2.

**Comment by ADDISON74** [comment]
With PHP 8.2 these errors appear in exception.log file

```php
2022-12-21T23:53:03+00:00 ERR (3): 
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view/media.phtml:53
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include()
#1 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#2 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#3 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#4 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(650): Mage_Core_Block_Abstract->toHtml()
#5 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(594): Mage_Core_Block_Abstract->_getChildHtml('media', true)
#6 /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view.phtml(51): Mage_Core_Block_Abstract->getChildHtml('media')
#7 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include('/var/www/html/a...')
#8 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#9 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#10 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#11 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(42): Mage_Core_Block_Abstract->toHtml()
#12 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Text_List->_toHtml()
#13 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(650): Mage_Core_Block_Abstract->toHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(594): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#15 /var/www/html/app/design/frontend/rwd/default/template/page/1column.phtml(46): Mage_Core_Block_Abstract->getChildHtml('content')
#16 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include('/var/www/html/a...')
#17 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#18 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#19 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#20 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(580): Mage_Core_Block_Abstract->toHtml()
#21 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(397): Mage_Core_Model_Layout->getOutput()
#22 /var/www/html/app/code/core/Mage/Catalog/Helper/Product/View.php(149): Mage_Core_Controller_Varien_Action->renderLayout()
#23 /var/www/html/app/code/core/Mage/Catalog/controllers/ProductController.php(128): Mage_Catalog_Helper_Product_View->prepareAndRender(448, Object(Mage_Catalog_ProductController), Object(Varien_Object))
#24 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(428): Mage_Catalog_ProductController->viewAction()
#25 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('view')
#26 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(188): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /var/www/html/app/code/core/Mage/Core/Model/App.php(371): Mage_Core_Controller_Varien_Front->dispatch()
#28 /var/www/html/app/Mage.php(738): Mage_Core_Model_App->run(Array)
#29 /var/www/html/index.php(71): Mage::run('', 'store')
#30 {main}
2022-12-21T23:53:13+00:00 ERR (3): 
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view/media.phtml:53
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include()
#1 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#2 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#3 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#4 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(650): Mage_Core_Block_Abstract->toHtml()
#5 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(594): Mage_Core_Block_Abstract->_getChildHtml('media', true)
#6 /var/www/html/app/design/frontend/rwd/default/template/catalog/product/view.phtml(51): Mage_Core_Block_Abstract->getChildHtml('media')
#7 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include('/var/www/html/a...')
#8 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#9 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#10 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#11 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(42): Mage_Core_Block_Abstract->toHtml()
#12 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Text_List->_toHtml()
#13 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(650): Mage_Core_Block_Abstract->toHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(594): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#15 /var/www/html/app/design/frontend/rwd/default/template/page/1column.phtml(46): Mage_Core_Block_Abstract->getChildHtml('content')
#16 /var/www/html/app/code/core/Mage/Core/Block/Template.php(257): include('/var/www/html/a...')
#17 /var/www/html/app/code/core/Mage/Core/Block/Template.php(291): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#18 /var/www/html/app/code/core/Mage/Core/Block/Template.php(304): Mage_Core_Block_Template->renderView()
#19 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(932): Mage_Core_Block_Template->_toHtml()
#20 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(580): Mage_Core_Block_Abstract->toHtml()
#21 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(397): Mage_Core_Model_Layout->getOutput()
#22 /var/www/html/app/code/core/Mage/Catalog/Helper/Product/View.php(149): Mage_Core_Controller_Varien_Action->renderLayout()
#23 /var/www/html/app/code/core/Mage/Catalog/controllers/ProductController.php(128): Mage_Catalog_Helper_Product_View->prepareAndRender(378, Object(Mage_Catalog_ProductController), Object(Varien_Object))
#24 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(428): Mage_Catalog_ProductController->viewAction()
#25 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('view')
#26 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(188): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /var/www/html/app/code/core/Mage/Core/Model/App.php(371): Mage_Core_Controller_Varien_Front->dispatch()
#28 /var/www/html/app/Mage.php(738): Mage_Core_Model_App->run(Array)
#29 /var/www/html/index.php(71): Mage::run('', 'store')
#30 {main}
````

**Comment by sreichel** [comment]
> return is_countable($applyTo) == 0 || in_array($object->getTypeId(), $applyTo);

This looks wrong to me. Before it checked if array-size is zero. Now it checks only for being contable.

To me it seems this extenson was not made for php8.0. Without code its hard to check.

**Comment by ADDISON74** [comment]
When I last checked the extension it was in PHP 7.0.33 and it was functional, but since then almost 1 year has passed and the developer from Ukraine no longer responds. I hope with all my heart that he is in good health because surely the war started by an idiot either created problems for him or led him to war.

**Comment by sreichel** [comment]
If you want, pls send extension to my.name at hotmail dot com.

**Comment by sreichel** [comment]
> I hope with all my heart that he is in good health because surely the war started by an idiot either created problems for him or led him to war.

:heart: 

@Flyingmana https://github.com/OpenMage/Web_Notifications/pull/4 ... not?

**Comment by ADDISON74** [comment]
Are you using the email address listed into your GitHub account? The one attached to your PRs?

**Comment by sreichel** [comment]
Yes.

**Comment by ADDISON74** [comment]
Good. I will delete our posts related to your request.

**Comment by ADDISON74** [comment]
I used XDebug together with the extension and the value of the **$applyTo** variable is null. Using the null value in the count() function creates trouble starting with PHP 7.2 (warnings in system.log) and PHP 8.0 (fatal error in browser). For this reason I would insert a line before return to prevent this particular case, if the value is null then I set it to an empty array.

In the OM file **/app/code/core/Mage/Catalog/Model/Resource/Abstract.php** in the _isApplicableAttribute method (line 68) here is the change

```php
    protected function _isApplicableAttribute($object, $attribute)
    {
        $applyTo = $attribute->getApplyTo();
        if(is_null($applyTo)) $applyTo = [];
        return count($applyTo) == 0 || in_array($object->getTypeId(), $applyTo);
    }
```

The use of the is_countable() function is not appropriate in this case. With my change the extension works, there are no more warnings or errors.

**Comment by sreichel** [comment]
Thanks for sharing code. [under NDA :sunglasses: ]

IMHO ... this problem comes from that extension.

This error pops up on install ...

`Error in file: "/var/www/html/app/code/community/Ave/SizeChart/data/ave_sizechart_setup/data-install-0.0.4.php" - Warning: count(): Parameter must be an array or an object that implements Countable  in /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Abstract.php on line 71`

If `$attribute` is instance of Mage_Catalog_Model_Resource_Eav_Attribute `$attribute->getApplyTo()` would return an array in any case, but this extension use its own entites ...

`class Ave_SizeChart_Model_Resource_Eav_Attribute extends Mage_Eav_Model_Entity_Attribute`

This looks wrong, it should extend an resourecec class?!?

**Comment by sreichel** [comment]
After some investigation ...

IMHO ... this problem comes from this extension.

`$attribute->getApplyTo()` return `null` b/c `$attribute` is not `Mage_Catalog_Model_Resource_Eav_Attribute` as docs say. In this case `getApplyTo()` would return an array, but for this extension `$attribute` is ...

`class Ave_SizeChart_Model_Resource_Eav_Attribute extends Mage_Eav_Model_Entity_Attribute`, not having `getApplyTo()` method and calling Varien_Object getter.

Adding this to `Ave_SizeChart_Model_Resource_Eav_Attribute` seems to fix it (stopped here with testing, at least install works for now)

```
    /**
     * @return array
     */
    public function getApplyTo(): array
    {
        return [];
    }
```
