### ISSUE TITLE
CM_RedisSession module in OM 20?

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2865]
In OM 19 in the **/app/code/** there is only one directory /core.

In OM 20 in the same directory there are two directories, one related to /community/Cm/RedisSession.

Somehow no change was made in OM 20? If I remember both versions were recently updated with the same content.

**Comment by fballiano** [comment]
I think it's just because https://github.com/OpenMage/magento-lts/pull/2766 is not merged yet

**Comment by ADDISON74** [comment]
It is great you know about it.
