### ISSUE TITLE
Image background color gets black instead of transparent

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#288]
During last days (after last patch) this came up serveral times on magento.stackexchange ...

https://magento.stackexchange.com/questions/177005/watermark-get-black-background-when-transparent

If confirmed, i'll create PR.

**Comment by leek** [comment]
I've confirmed this issue in standard CE Magento 1.9.3.3.

**Comment by tomekjordan** [comment]
It may be related to GD library and PNG image format. I had similar things in M1702....

**Comment by leek** [comment]
**@tomekjordan:** Maybe... However - the fix from the Stack Exchange link provided by @sreichel corrects the issue for me.

**Comment by onlinebizsoft** [comment]
I have confirmed issue on 1.9.3.3 too

**Comment by sreichel** [comment]
Fixed in 1.9.3.4.
