### ISSUE TITLE
Change behavior of modules <depends> node

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#291]
https://magento.stackexchange.com/questions/179280/change-behavior-of-modules-depends-node-any-downsides

**Can you please review this?** 

If this looks OK, is a PR accepted?

---

__Current sitution:__

If one of you extensions depends on another, that isn't active or not installed it breaks page load and you'll see error report page.

    <?xml version="1.0"?>
    <config>
        <modules>
            <My_Module>
                <active>true</active>
                <codePool>local</codePool>
                <depends>
                    <Non_Existing />
                </depends>
            </My_Module>
        </modules>
    </config>

__Desired behavoir:__

If dependency is missing, just do not load the extension, but load the page correctly.

The related code is this: https://github.com/OpenMage/magento-mirror/blob/magento-1.8/app/code/core/Mage/Core/Model/Config.php#L835-L881

I played around a bit and modified code that it does not load the extension:

    /**
     * Sort modules and check depends
     *
     * @param array $modules
     * @return array
     */
    protected function _sortModuleDepends($modules)
    {
        foreach ($modules as $moduleName => $moduleProps) {
            $unset = false; // added
            $depends = $moduleProps['depends'];
            foreach ($moduleProps['depends'] as $depend => $true) {
                if ($moduleProps['active'] && ((!isset($modules[$depend])) || empty($modules[$depend]['active']))) {
                    // replaced Mage::throwException
                    Mage::log(
                        Mage::helper('core')->__('Module "%1$s" requires module "%2$s".', $moduleName, $depend)
                    );
                    // added
                    unset($modules[$moduleName]);
                    $unset = true;

                }
                if (!$unset) { // added
                    $depends = array_merge($depends, $modules[$depend]['depends']);
                }
            }
            if (!$unset) { // added
                $modules[$moduleName]['depends'] = $depends;
            }
        }
        $modules = array_values($modules);

        $size = count($modules) - 1;
        for ($i = $size; $i >= 0; $i--) {
            for ($j = $size; $i < $j; $j--) {
                if (isset($modules[$i]['depends'][$modules[$j]['module']])) {
                    $value       = $modules[$i];
                    $modules[$i] = $modules[$j];
                    $modules[$j] = $value;
                }
            }
        }

        $definedModules = array();
        foreach ($modules as $key => $moduleProp) { // added $key
            $unset = false; // added
            foreach ($moduleProp['depends'] as $dependModule => $true) {
                if (!isset($definedModules[$dependModule])) {
                    // replaced Mage::throwException
                    Mage::log(
                        Mage::helper('core')->__('Module "%1$s" cannot depend on "%2$s".', $moduleProp['module'], $dependModule)
                    );
                    // added
                    unset($modules[$key]);
                    $unset = true;
                }
            }
            if (!$unset) { // added
                $definedModules[$moduleProp['module']] = true;
            }
        }

        return $modules;
    }

---

__Question:__ it seems to work as intended, but did i've missed something or can I use this safly in production?

**Comment by colinmollenhour** [comment]
I don't see a compelling reason to change the behavior that if a module lists a dependency there is a fatal error if the dependency is not met.. A looong time ago I proposed a sort of "soft dependency" just so that modules could have a specified load order when they exist but not necessarily a strict dependency but I guess this never went anywhere. However, if this is what you're looking for in my opinion it should be added as a new feature and the existing functionality should remain unchanged.

**Comment by Flyingmana** [comment]
the module config is like the backbone of your store. If there is a dependency not there(anymore) this is a crack in your backbone. You should instantly notice this, else you would operate with a partially disabled shop for possible weeks without noticing(I have experience with the inability of people to notice something important is broken)

**Comment by sreichel** [comment]
Thanks for replies ... fully understad your concerns. :) Still playing arround with this and until now found nothing that hurts (me), but a colin said "the existing functionality should remain unchanged".
