### ISSUE TITLE
Upgrade to openmage from 1.9.2.4

### ISSUE THREAD

**Issue by bylli79** [OpenMage/magento-lts#2921]
Hi,
I have a version of magento 1.9.2.4.
I would like to switch to openmage.
Can I update magento from 1.9.2.4 to 1.9.4.5 or do I have to go through the intermediate versions?

Thank you

**Comment by fballiano** [comment]
it's not necessary to do the intermediate upgrades

**Comment by fballiano** [comment]
closing since it's not really an issue

**Comment by ADDISON74** [comment]
I am moving this post to Discussions. I will provide some ideas.
