### ISSUE TITLE
Error after upgrade: Uncaught Error: Class 'Pelago\Emogrifier\CssInliner'

### ISSUE THREAD

**Issue by djixas** [OpenMage/magento-lts#2925]
### Preconditions (*)

1. Upgraded from Magento 1.9.4 to MageLTS 19.4.21
2. The issue appears in PHP 7.4 and PHP 8.0

### Steps to reproduce (*)

1. Upgrade Magento and try to reset admin password
3. The following error will be shown

### Expected result (*)

1. It should reset password

### Actual result (*)

1. It throws error, and every email since then is just HTML code instead of "HTML code converted to data"

```
Fatal error:  Uncaught Error: Class 'Pelago\Emogrifier\CssInliner' not found in /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template/Abstract.php:200
Stack trace:
#0 /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template.php(354): Mage_Core_Model_Email_Template_Abstract->_applyInlineCss('\n\n\n\n\n\n<!DOCTYPE...')
#1 /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template.php(328): Mage_Core_Model_Email_Template->getPreparedTemplateText('\n\n\n\n\n\n<!DOCTYPE...')
#2 /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template.php(402): Mage_Core_Model_Email_Template->getProcessedTemplate(Array, true)
#3 /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template.php(518): Mage_Core_Model_Email_Template->send('MYEMAIL@GMAIL...', Array, Array)
#4 /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(78): Mage_Core_Model_Email_Template->sendTransactional('admin_emails_fo...', 'general', Array, Array, Array, 0)
#5 /home/xxxxxxxxxx in /home/xxxxxxxxxx/public_html/app/code/core/Mage/Core/Model/Email/Template/Abstract.php on line 200
```

Line 200 -                 `$emogrifier = \Pelago\Emogrifier\CssInliner::fromHtml($html)`

**Comment by ADDISON74** [comment]
The repository no longer has the /lib/Pelago directory, but the release version contains it. Download the archive and put it there or use Composer. You face this issue because you used the git command and what you had local was synchronized with remote.

**Comment by ADDISON74** [comment]
Here you go https://github.com/OpenMage/magento-lts/releases/tag/v19.4.21

**Comment by fballiano** [comment]
how did you upgrade? git a git pull from a development branch? IMHO don't use development branches, use a release tag, better if with composer.

anyway `composer install` will fix that error

**Comment by fballiano** [comment]
mmm i've never seen that script, i'll look for it, maybe it broke because our development branches are very different from the released ones.

**Comment by djixas** [comment]
> mmm i've never seen that script, i'll look for it, maybe it broke because our development branches are very different from the released ones.

Yes, they've since decided to drop it https://github.com/OpenMage/migrate/issues/6

Anyhow, I'll probably create another ticket for HTML issue, thank you for your help

**Comment by fballiano** [comment]
@ADDISON74 @djixas I've created this PR to discontinue the migration script, vote for it if you feel it's correct ;-)

**Comment by fballiano** [comment]
@ADDISON74 @djixas I've created this PR to discontinue the migration script, vote for it if you feel it's correct ;-)

https://github.com/OpenMage/migrate/pull/7

**Comment by djixas** [comment]
> ah, weird I'm not subscribed to that repo, BTW it seems very outdated, I wouldn't use it

Yeah, sadly, this is how "they got me", as it's still the top recommendation at https://www.openmage.org/magento-lts/migration-guide.html

**Comment by fballiano** [comment]
can I ask you where is that page linked? cause I can't find a link to it.

that page, to me, should be complete redone, i woulnd't use (and i didn't when i migrated my shops) any of those methods.

**Comment by fballiano** [comment]
> I'm fairly new to Github, sorry, do I just +1 with comment or?

that's enough at the moment :-)
