### ISSUE TITLE
Configuration 'depends' with front and backend model

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#294]
Run into same problem as described here: https://magento.stackexchange.com/questions/15500/configuration-depends-with-front-and-backend-model

Solution with adding DIV to `_toHtml()` works, but I think this isn't correct behavior.

    public function _toHtml()
    {
        return '<div id="' . $this->getElement()->getId(). '">' . parent::_toHtml() . '</div>';
    }

 Any ideas where to start to fix this?

**Comment by fballiano** [comment]
@sreichel what solution would you implement?
