### ISSUE TITLE
Slow query with MySQL 5.7

### ISSUE THREAD

**Issue by infabo** [OpenMage/magento-lts#295]
After upgrading from MySQL 5.6 to 5.7 on my devbox, I have experienced a massive performance drop on Magento's homepage. After some investigation (profiling, ...) I have quickly determined a single database query to be responsible for it (at least it had the biggest impact).
Can't remember exactly, but was 45sec pageload and with the "hack" I got down to 11 secs.
Seems like there are several other fuckups due to MySQL 5.7, because on 5.6 the Magento instance is/was rocking fast. (maybe those visitor logs, etc. are not optimized too).

http://itstickers.besthw.net/en/magento-mysql-5-7-slow-queries/

So....I'd like to ask here: does or should magento-lts accept patches like these?

**Comment by tomekjordan** [comment]
is Maria DB 5.7 also suffering the same problem?

**Comment by colinmollenhour** [comment]
This is exactly the kind of patch this project should accept with substantial proof there are no regressions.
