### ISSUE TITLE
MySql disable/enable key statements during index processing

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#296]
I noticed its a common part of magento to to disable keys on an index table, while performing the index process, even if it is only for single entries.

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Index/Model/Indexer.php#L296

Why I looked into it: I just had a case where the disable keys statement did run for 65 seconds according to a NewRelic trace.

I understand the initial idea behind it, to improve the performance of batch processing. I just wonder if thats maybe a problem, which already got solved by now on side of MySql so this "workaround" is not needed anymore.

I did a bit of research

https://stackoverflow.com/questions/8210608/mysql-disable-enable-keys
https://serverfault.com/questions/291100/with-mysql-how-long-does-an-alter-table-disable-keys-statement-last

I learned, that disable keys only works for MyIsam, and that you need to use a different method to disable them. But as the MyIsam is an alter table, it is global, while the one for InnoDB seems to be limited to the current connection, which seems like a better deal.

My question is now.
Does it make sense to remove the disable keys complete, or only for the code paths which get triggered by the updateOnSave paths.
And, would it be a good idea to move this tables from MyIsam to InnoDB?

Edit:

found http://binary-data.github.io/2017/04/05/magento-mysql-crash-deadlock-when-index-under-highload/
and they are right, this table is already InnoDB, so the disable Keys does not even have a positive impact

**Comment by tmotyl** [comment]
@Flyingmana haven't we already merge the patch which removed calling disabled keys?

**Comment by bob2021** [comment]
Have you seen #188 & #152?

**Comment by Flyingmana** [comment]
my fault, I really need to work on this overview list with all the patches we have. Seems there is a good set of patches I did not notice :D
Also I should push my current project to use the LTS fork
