### ISSUE TITLE
Gitpod deployment fails with class Zend_Cache not found

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#2961]
I guess we did not add a composer install to the gitpod setup, so it fails now since we depend on it.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

`Fatal error: Uncaught Error: Class 'Zend_Cache' not found in /var/www/html/app/code/core/Mage/Core/Model/Cache.php on line 132`

**Comment by sreichel** [comment]
I guess you did not add a `composer install` to the gitpod setup?

**Comment by elidrissidev** [comment]
I'm guessing the same thing for docker compose file.

**Comment by ADDISON74** [comment]
If someone uses DDEV with cloned OM repository, he must use the "ddev composer install" command to be able to run the online store, otherwise the first error is related to the missing of the Zend library.

**Comment by fballiano** [comment]
I can't manage to install composer on gitpod without building a new dockerimage 😅

**Comment by sreichel** [comment]
I tried githubs built-in gitpod with a minimal config and it worked. https://github.com/OpenMage/magento-lts/pull/1836#issuecomment-1329760430
