### ISSUE TITLE
attribute title localization does not work

### ISSUE THREAD

**Issue by mbattistini** [OpenMage/magento-lts#2963]
### Preconditions (*)

1. OpenMage 19.4.21
2. PHP 8.0

### Steps to reproduce (*)

1. installed new version of magento-lts
2. created 2 storeviews
3. created attribute with correct localization for storeview
4. created the product with the attribute set with the new attribute
5. verified the product the attribute titles remain the "admin" ones not the localized ones

### Expected result (*)

1. the product also keeps the attribute titles correctly localized

### Actual result (*)

1. the attribute titles remain the "admin" ones not the localized ones

**Comment by elidrissidev** [comment]
Are the attributes not localized in the frontend or backend or both? I tried with the same version and I got the expected result in frontend, but not the admin in product view page.

**Frontend:**

![Screenshot_20230117_085744](https://user-images.githubusercontent.com/67818913/212999758-8944859f-74a6-413c-8d0d-cb3335dcb88e.png)

**Backend:**

![Screenshot_20230117_090023](https://user-images.githubusercontent.com/67818913/212999766-de5ac656-5cb5-4cec-ba03-bcc02e6412e8.png)
![Screenshot_20230117_085809](https://user-images.githubusercontent.com/67818913/212999764-db098681-4c5e-463b-b9c5-fe6884fc5165.png)

**Comment by sreichel** [comment]
> I got the expected result in frontend, but not the admin in product view page.

What do you expect on admin edit page?

**Comment by elidrissidev** [comment]
> What do you expect on admin edit page?

I don't remember if the labels are supposed to be localized when selecting a store view in admin or not.

**Comment by sreichel** [comment]
from memories ... in admin it always uses "admin value"

**Comment by fballiano** [comment]
> from memories ... in admin it always uses "admin value"

exactly

**Comment by mbattistini** [comment]
> Are the attributes not localized in the frontend or backend or both? I tried with the same version and I got the expected result in frontend, but not the admin in product view page.

the problem is in the frontend, in the backend everything is as it should be.
I will do further verification.

Thank you.

**Comment by mbattistini** [comment]
It took me a while to figure out but I found a check I had never paid attention to, under "Super product attributes configuration" in creating the simple products linked to the configurables, there is a "use default" that is not checked.

I noticed this because with simple products the problem wasn't there.

Thanks again.
