### ISSUE TITLE
/w catalog price rules admin html order view shows original_price as discounted price

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#299]
In adminhtml order view I suddenly see the discounted price instead of the original_price. I found a link referencing this as 'default' but I dont agree. The column should show the original_price as the header explains, the data retrieval shows (original_price) and is stored in mysql (original_price)

Possible bug? 

Sorry for the short note: more info is found here

(ahum dont have solution yet; but will get there.  Maybe someone else knows too/faster)

https://magento.stackexchange.com/questions/182973/magento-1-9-3-3-order-grid-shows-original-price-column-but-contains-discounted

**Comment by Romz** [comment]
Subscribe

**Comment by ADDISON74** [comment]
The link provided by the author is not working anymore. This issue has 5 years from its report. I will close it.
