### ISSUE TITLE
Cannot upload favicon in Windows ICO format (.ico)

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#3001]
### Preconditions (*)

1. OpenMage 20.0.19
2. PHP 8.1.14

### Steps to reproduce (*)

1. Go to Configuration -> Design section and select Windows .ico format to upload as website favicon

### Actual result (*)

1. You will get an error: Invalid image format.
2. There's an error in system.log:
```
Warning: imagecreatefromstring(): one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully
  in /app/code/core/Mage/Core/Model/File/Validator/Image.php on line 103
Warning: imagecreatefromstring(): Passed data is not in &quot;WBMP&quot; format  in /app/code/core/Mage/Core/Model/File/Validator/Image.php on line 103
Warning: imagecreatefromstring(): Couldn't create GD Image Stream out of Data  in /app/code/core/Mage/Core/Model/File/Validator/Image.php on line 103
```
In previous versions of OpenMage this error doesn't appear.

**Comment by fballiano** [comment]
bug is confirmed only with .ico files, the other filetypes work ok

**Comment by fballiano** [comment]
since GD doesn't handle .ico files, should we add a 3rd party library to do so like https://github.com/lordelph/icofileloader?

**Comment by elidrissidev** [comment]
> In previous versions of OpenMage this error doesn't appear.

Which version were you using before the upgrade?

I suspect it may have something to do with #2629.

**Comment by fballiano** [comment]
ye it seems a bit overkill to add a library just to process ico files but then we can't apply the security "process and re-save images" procedure to those files (maybe they can't even be vehicle for malicious code, IDK)

**Comment by elidrissidev** [comment]
We could introduce Imagick adapter under `lib/Varien/Image/Adapter` and then use it there, but that has the drawback of requiring another PHP extension. Magento 2 applied a [similar fix](https://github.com/magento/magento2/pull/34883), but I think they have the image adapter configurable in the backend.

**Comment by empiricompany** [comment]
why not just skip like this?
`app\code\core\Mage\Core\Model\File\Validator\Image.php`
```
 /**
     * Validation callback for checking if file is image
     * Destroy malicious code in image by reprocessing
     *
     * @param  string $filePath Path to temporary uploaded file
     * @return null
     * @throws Mage_Core_Exception
     */
    public function validate($filePath)
    {
        list($imageWidth, $imageHeight, $fileType) = getimagesize($filePath);
        if ($fileType) {
            if ($this->isImageType($fileType)) {
                if ($fileType == IMAGETYPE_ICO) {
                    return null;
                }
```
