### ISSUE TITLE
password creation/reset from backend does not work

### ISSUE THREAD

**Issue by mbattistini** [OpenMage/magento-lts#3033]
### Preconditions (*)

1. 19.4.23
2. PHP 8.0

### Steps to reproduce (*)

1) account creation from backend or 
2) password reset from backend 

### Expected result (*)

account creation from backend or password reset from backend have to send an email with the new password.

### Actual result (*)

return an email that says "Password: (the password you set when creating your account)" instead of the new password.

**Comment by justinbeaty** [comment]
See #1205 and #1283

**Comment by mbattistini** [comment]
I had also searched for the issue without success.... Thank you!
