### ISSUE TITLE
PDOStatement deprecation for PHP8.1

### ISSUE THREAD

**Issue by daboss84** [OpenMage/magento-lts#3034]
### Preconditions (*)
OM 20.0.20 running on PHP 8.1

### Steps to reproduce (*)
Switch to PHP 8.1

### Expected result (*)
Everything works fine :)

### Actual result (*)
The system.log runs full of a PDOStatement deprecation in the Zend-Lib:
`PDOStatement::fetch(): Passing null to parameter #2 ($cursorOrientation) of type int is deprecated/var/www/vhosts/xyz.de/xyz/lib/Zend/Db/Statement/Pdo.php`
`2023-02-06T22:23:04+00:00 DEBUG (7): PDOStatement::fetch(): Passing null to parameter #3 ($cursorOffset) of type int is deprecated/var/www/vhosts/xyz.de/xyz/lib/Zend/Db/Statement/Pdo.php`

### Possible solution (or workaround)
As a quick hack, I checked these params for null and set them to their defaults. Still have to wait and see if this is good or still sub-optimal... Maybe you know more about this one?
This is a screen of the Pdo.php
![grafik](https://user-images.githubusercontent.com/18015530/220166883-a85d945f-49de-4248-85a2-79637dec6a0a.png)

... sorry I am a bit in a hurry right know, but want to post this bug despite it.

**Comment by fballiano** [comment]
lib/Zend was removed from our repository lately so I think this should get fixed already in 19.5.0 and 20.1.0 ;-)

**Comment by elidrissidev** [comment]
Already fixed in the latest rc releases
