### ISSUE TITLE
Frontend "Template Path Hints" set to YES not working  - OM 19.5.0-rc1

### ISSUE THREAD

**Issue by LuizSantos22** [OpenMage/magento-lts#3058]
### Preconditions (*)

1. OpenMage 19.5.0-rc1
2. Cpanel - Litespeed Hosting PHP 7.4 (it does not matter changing it to higher versions)

### Steps to reproduce (*)

1. Install OpenMage 19.5.0-rc1 and the Magento legacy library/extensions that is provided with it
2. Go to system/config/advanced/developer/FRONTEND - Template Path Hints/Yes

### Expected result (*)

1. Seeing the path hints at frontend 
2. I have tested with default and my custom theme to make sure it is not working

### Actual result (*)

1. Nothing happens
2. If we set Admin Template Path Hints and Add Block Names to Hints to YES it works fine at the backend
3. If we set Translation in Line for both Frontend and Backend, it works fine as well.
4. So I guess that the issue is only with FRONTEND - Template Path Hints

**Comment by ADDISON74** [comment]
I am trying to reproduce this issue without any luck. I am using for testing OpenMage 19.5.0.rc-2, Magento Sample Pack, DDEV (Apache FPM, PHP 8.2). Here are the results in the Frontend after changing the "Configuration Scope" between **Default Config / Main Website / English**.

![Backend](https://user-images.githubusercontent.com/8360474/222681322-909cd688-e2d7-4531-81a3-558ec1359759.png)

**[Default Config]**

![Default](https://user-images.githubusercontent.com/8360474/222681896-5cfcc5ef-a821-4fe4-be49-88b87f1ea63f.png)

**[Main Website]**

![Main Website](https://user-images.githubusercontent.com/8360474/222682367-717845ca-b9f0-4b11-8dbb-69649259fe48.png)

**[English]** => Switching in Frontend to French and German it works as expected.

![English](https://user-images.githubusercontent.com/8360474/222682789-1921a50a-ea08-4d0e-a42c-a9fa277fa3db.png)

**Comment by elidrissidev** [comment]
Also unable to reproduce the issue, my guess is that the problem could be the value of the config in "Website" or "Store View" scope is overriding the "Default" config therefore it's still reading the "No" value.

**Comment by LuizSantos22** [comment]
@elidrissidev 
You are right, I have investigated it further and followed your advice and now it is working on frontend to a specific store
"No" values was set by default to those specific stores and changing it to "Yes" using "all stores" scope does not affect them.

I am still with the thinking that "all stores" is a "master" that overrides all the "slavers" (speficit stores)

@ADDISON74 
Consider it as closed as it was not really a "bug", bud a "feature", what was "strange" is the fact that "translation" even when activated using "all stores" works fine at any frontend.
