### ISSUE TITLE
Use most recent Credis/Client.php for compatibility with PHP 8.2

### ISSUE THREAD

**Issue by pisc-software** [OpenMage/magento-lts#3061]
### Preconditions (*)

1. OpenMage 20.0.20 on PHP 8.2
2. lib/Credis/Client.php from OpenMage source zip.

### Steps to reproduce (*)

1. Use CRedis as cache backend.

### Actual result (*)

1. System.log is showing deprecation notice. Please see linked issues below.

Please refer to these fixed issues, will become relevant for PHP 8.2+ compatibility of OpenMage in future:
[Credis: #170 PHP 8.2 Use of self in callables is deprecated](https://github.com/colinmollenhour/credis/issues/170)
[Credis: #177 Use of "self" in callables is deprecated in Credis/Client.php](https://github.com/colinmollenhour/credis/issues/177)

Whoever is reading this and wants a quick work around:
1. Download the latest CRedis code from: [Colin Mollenhour - Credis](https://github.com/colinmollenhour/credis)
2. Copy "Client.php" from source package to "app/code/local/Credis/Client.php" to override "lib/Credis/Client.php" with the most recent version. Update save with future OpenMage updates.

This as feedback and contribution to the OpenMage team on PHP 8.2+ compatibility. Thanks everyone for the efforts on this project.

**Comment by fballiano** [comment]
this was solved in 20.1.0-rc1 since everything is managed via composer :-)
