### ISSUE TITLE
Unsupported operand types: string * int during cronjob 'sales_clean_quotes'

### ISSUE THREAD

**Issue by darinda** [OpenMage/magento-lts#3064]
### Preconditions (*)

1. OpenMage 20.1.0-rc1 or any other
2. PHP 8.1

### Steps to reproduce (*)

1. Run the cronjob [`sales_clean_quotes`](https://github.com/OpenMage/magento-lts/blob/20.0/app/code/core/Mage/Sales/etc/config.xml#L1715)

### Expected result (*)

1. Cronjob works ;)

### Actual result (*)

1. PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in [...]app/code/core/Mage/Sales/Model/Observer.php:51

**Comment by sreichel** [comment]
@all-contributors add @darinda bug
