### ISSUE TITLE
Better Dashboard graph in OpenMage Admin theme

### ISSUE THREAD

**Issue by elidrissidev** [OpenMage/magento-lts#3121]
### Description (*)

This is a feature request created from a [discussion](https://github.com/OpenMage/magento-lts/discussions/3105) to make the Dashboard graph in OpenMage's own admin theme match what's on the website screenshots.

![](https://user-images.githubusercontent.com/7250950/226338239-f57603bb-238b-48d3-9d3c-3c7a923852bb.png)

**Comment by m-overlund** [comment]
Maybe something like a https://www.chartjs.org/ implementation could do it
