### ISSUE TITLE
Invalid report date

### ISSUE THREAD

**Issue by kyrena** [OpenMage/magento-lts#3122]
Go to Reports > Sales > Invoiced, set _Period_ to _Month_, set _From_ to _01/01/2023_ and _To_ to _20/03/2023_.

Result is something like that (**1/1970**):
![image](https://user-images.githubusercontent.com/78410399/228529960-858bba44-f68f-4635-b80c-b9bbcbba7cae.png)

Tested with OpenMage 19.5.0-rc2 and 20.1.0-rc2, with PHP 8.0.

**Comment by m-overlund** [comment]
Tested on 19.4.23 and PHP 8.1 with no issues

**Comment by elidrissidev** [comment]
This issue was introduced in #2861, the `Zend_Date` override in `app/code/core/Zend` had a few additional lines that made the date parsing work.

**Comment by elidrissidev** [comment]
Yeah it was a different one, updated comment.

**Comment by sreichel** [comment]
> This issue was introduced in #2827, the `Zend_Date` override in `app/code/core/Zend` had a few additional lines that made the date parsing work.

Could you track it to a specific line?

**Comment by elidrissidev** [comment]
> Could you track it to a specific line?

Somewhere in these lines https://github.com/OpenMage/magento-lts/blob/v19.4.23/app/code/core/Zend/Date.php#L2080-2085

Either they were removed in zf1-future, or they were added by the magento team to support a specific usecase.

**Comment by sreichel** [comment]
This has been added to Zend ... https://github.com/Shardj/zf1-future/commit/c7a5cf6dcd36bffefd7dd30e68db49b35966bee1

```
                // (T)hh:mm
                if (empty($timematch)) {
                    preg_match('/[T,\s]{0,1}(\d{2}):(\d{2})/', $tmpdate, $timematch);
                }
                // (T)hhmm
                if (empty($timematch)) {
                    preg_match('/[T,\s]{0,1}(\d{2})(\d{2})/', $tmpdate, $timematch);
                }
```

**Comment by sreichel** [comment]
@all-contributors add @kyrena bug
