### ISSUE TITLE
TypeError: Unsupported operand types: int * string

### ISSUE THREAD

**Issue by m-overlund** [OpenMage/magento-lts#3135]
You can crash the admin product page, by filtering for Price from: NULL to: NULL

__TypeError: Unsupported operand types: int * string__
https://bmb-import.sentry.io/share/issue/7fb970b852054849b8f142c3baeaecdb/

PHP 8.1
OpenMage 19.4.23

(Happens with and without TBT_EnhancedGrid)

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by fballiano** [comment]
would it be possible to test with the latest github version?

**Comment by m-overlund** [comment]
i don't have the greatest dev setup atm. - but will try to prioritize this :)

**Comment by elidrissidev** [comment]
Filtering by `NULL` is a new feature added by #1203, and I don't think it supports custom column filter classes.

**Comment by sreichel** [comment]
@elidrissidev it happens for all strings - not only `null`.

**Comment by elidrissidev** [comment]
Yeah but it wouldn't make sense to filter by a string in a Price column...

**Comment by ADDISON74** [comment]
From an engineering point of view, filtering by any value, other than numerical, must be avoided. As it is now in Backend the error appears and I get the popup with the animated loader and "Please wait..." message. If I refresh the page, all the content under the navigation menu disappears. Obviously such a situation must be prevented and we should not rely on the honesty of the user to use only numerical/dates values when filtering the grid columns.

**Comment by sreichel** [comment]
@all-contributors add @m-overlund bug
