### ISSUE TITLE
SOAP Api Warnings - PHP8.1

### ISSUE THREAD

**Issue by m-overlund** [OpenMage/magento-lts#3166]
I'm getting multiple errors from SOAP Api on OpenMage 19.4.23 / PHP 8.1 (with selected php 8.1/8.2 patches).

Not sure if others are experiencing the same issues.
Glad to open multiple issues if it's issues that OpenMage should handle.

## Klaviyo ESP
`Return type of Varien_Data_Tree_Node_Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`
from SOAP: `urn:Mage_Api_Model_Server_V2_HandlerAction` (Klaviyo ESP)
lib/Varien/Data/Tree/Node/Collection.php L29

```
class Varien_Data_Tree_Node_Collection implements ArrayAccess, IteratorAggregate, Countable
```

## WMS - add tracking to shipment

`substr(): Passing null to parameter #1 ($string) of type string is deprecated`
lib/phpseclib/Crypt/Base.php
From SOAP: `urn:Mage_Api_Model_Server_V2_HandlerAction`

Request:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Magento" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:salesOrderShipmentAddTrack><sessionId xsi:type="xsd:string">xxxxxxxxxxxxxxxxxxxxx</sessionId><shipmentIncrementId xsi:type="xsd:string">[ORDERNUMBER REMOVED]</shipmentIncrementId><carrier xsi:type="xsd:string">custom</carrier><title xsi:type="xsd:string">Tracking</title><trackNumber xsi:type="xsd:string">[TRACKING NUMBER REMOVED]</trackNumber><weight xsi:nil="true"/></ns1:salesOrderShipmentAddTrack></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

![image](https://user-images.githubusercontent.com/504236/231681960-7440be9d-e463-46c5-bd52-213605a3340a.png)

## SOAP - Pricing robot API Warning
`strlen(): Passing null to parameter #1 ($string) of type string is deprecated`
/lib/Unserialize/Reader/Str.php

(Stack trace includes Amasty/Magpleasure Tierprice module)
SOAP: `urn:Action`

SOAP request:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><q1:catalogProductInfo xmlns:q1="urn:Magento"><sessionId xsi:type="xsd:string">xxxxxxxxxxxxxxxxxxxxx</sessionId><productId xsi:type="xsd:string">[PRODUCT SKU REDACTED]</productId><storeView xsi:type="xsd:string">[STORE ID REDACTED]</storeView><attributes href="#id1"/><identifierType xsi:type="xsd:string">sku</identifierType></q1:catalogProductInfo><q2:catalogProductRequestAttributes id="id1" xsi:type="q2:catalogProductRequestAttributes" xmlns:q2="urn:Magento"><additional_attributes href="#id2"/></q2:catalogProductRequestAttributes><q3:Array id="id2" q3:arrayType="xsd:string[1]" xmlns:q3="http://schemas.xmlsoap.org/soap/encoding/"><Item>price_position</Item></q3:Array></s:Body></s:Envelope>
```

![image](https://user-images.githubusercontent.com/504236/231683409-f59cd4cc-84a3-472e-a178-0678363056b3.png)

## Klaviyo Cart API

`Array to string conversion /lib/Zend/Soap/Server.php `

Soap Action: `urn:Mage_Api_Model_Server_V2_HandlerAction`

Soap Call:
```
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns0="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns2="http://www.w3.org/2001/XMLSchema" xmlns:ns3="urn:Magento" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Header/><ns1:Body><ns3:shoppingCartInfo><sessionId xsi:type="ns2:string">xxxxxxxxxxxxxxxxxxxx</sessionId><quoteId xsi:type="ns2:int">[QUOTE ID REDACTED]</quoteId><storeId xsi:type="ns2:string">[STORE ID REDACTED]</storeId></ns3:shoppingCartInfo></ns1:Body></SOAP-ENV:Envelope>
```

**Comment by m-overlund** [comment]
Thanks a lot - will try the patches.
You mean v19.5.0 RC2?

v19.4.23 should be newest v19 release?

**Comment by kiatng** [comment]
I defer to @fballiano on the right version.

**Comment by ADDISON74** [comment]
@m-overlund - Did the recommendations that were made to you solve the issue? If yes, then we can close this ticket.

**Comment by m-overlund** [comment]
@ADDISON74 
kiang's recommandations only partially solves this issue.
Waiting to confirm if rc1 or rc3 solved the last issues.

I can close and reopen, if that serves the project better :)

**Comment by ADDISON74** [comment]
@m-overlund - Let's close it when you consider the problem solved.
