### ISSUE TITLE
Configurable product attribute specific label does not have "Use default" by default

### ISSUE THREAD

**Issue by mmenozzi** [OpenMage/magento-lts#3167]
### Preconditions (*)

1. OpenMage 1.9.4.10 (but I think the issue applies also for other versions)
2. PHP 7.4
3. MySQL 5.7

### Steps to reproduce (*)

1. Install OpenMage with sample data
2. Log in admin
3. Start creating a configurable product for any attribute set (for example Clothing) and any attribute (for example Color)
4. Go into the "Associated Products" tab

### Expected result (*)

The "Use default" checkbox in the "Super product attributes configuration" should be checked by default (at least in my opinion).

### Actual result (*)

The "Use default" checkbox in the "Super product attributes configuration" is not checked by default.

![Screenshot 2023-04-13 alle 11 23 56](https://user-images.githubusercontent.com/1199914/231720452-a56a7070-f9da-42aa-ba74-1894a80ab989.png)

### Additional comments

The "Use default" checkbox should be checked by default, in my opinion, because it's much more likely that the user wants to use the attribute label rather than a custom label for that single product. If the attribute label changes after the configurable product creation it's likely that the user wants to show the new label in the product pages. Moreover if we have multiple store views and the attribute label has been translated for each of them, having "Use default" not selected forces the user to translate that product label for each store view after the product creation.

**Comment by elidrissidev** [comment]
A similar issue was reported in #2963, so yeah I think it's better to make it checked by default.

**Comment by sreichel** [comment]
@all-contributors add @mmenozzi bug
