### ISSUE TITLE
Outdated guides and documents

### ISSUE THREAD

**Issue by djixas** [OpenMage/magento-lts#3192]
### Preconditions (*)

1. I was looking for info how to setup cron jobs and what cron jobs to use while came across system requirements, which are broken

### Steps to reproduce (*)

1. Load https://devdocs-openmage.org/guides/m1x//system-requirements.html
2. Click on memcached, gives 404

### Expected result (*)

1. Should load something

### Actual result (*)

1. Error 404

**Comment by ADDISON74** [comment]
I suggest you to find the Magento 1 user manual. In the Discussion section we have identified several resources on the Internet where you can find information about Magento 1. @fballiano collected this information and has a list in his repository.

Regarding the OpenMage website, it has not been updated for a long time and is a minus for this project. Even the web_notification feature is not valued as it should be. I doubt that anyone will solve the issue reported by you. Anyway, it is not a bug in the source code.

**Comment by fballiano** [comment]
https://github.com/fballiano/awesome-openmage ;-)
