### ISSUE TITLE
Modules using Zend_Mail stopped sending emails (PHP 8.1)

### ISSUE THREAD

**Issue by m-overlund** [OpenMage/magento-lts#3196]
## Issue
After upgrading to PHP8.1 our modules using Zend_Mail seems to have stopped sending emails.

In this case Xtento OrderExport.
The module does not return an error.

## Patch
Is it related to this patch - should it be applied to solve it?
https://github.com/Shardj/zf1-future/pull/344/files

## Tech
OpenMage 19.4.23
PHP 8.1

**Comment by ADDISON74** [comment]
Please try the solution proposed in that PR and check if you solve the Issue, although it concerns the content of the message and not its non-sending. If you don't succeed, then activate all PHP, OpenMage logs and check what errors appear in these files.

**Comment by ADDISON74** [comment]
Follow these steps:
https://support.xtento.com/wiki/Magento_Extensions:Magento_Order_Export_Module#Potential_issues:_No_emails_are_sent

**Comment by m-overlund** [comment]
Yes it is, and the they ran successfully.

Applied the patch, but didn't get it to work.
Changed from cron to event based trigger afterwards, and it is now sending mails.

So dunno the exact reason at this moment.

**Comment by ADDISON74** [comment]
I am going to close this PR. If the problems reappear it can be opened again.
