### ISSUE TITLE
Missing mod_php section in .htaccess for PHP8 settings

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3252]
If I remember well we discussed an improved version for the .htaccess file last year. Then a section for PHP8 settings was proposed. Today when I looked in the content of the file we only have specific settings for PHP7, not for PHP8.

Here is what we have at this moment in the file

```
############################################
## php7 settings

<IfModule mod_php7.c>

############################################
## adjust max execution time

    php_value max_execution_time 18000

############################################
## disable automatic session start
## before autoload was initialized

    php_flag session.auto_start off

############################################
## enable resulting html compression

    #php_flag zlib.output_compression on

###########################################
# disable user agent verification to not break multiple image upload

    php_flag suhosin.session.cryptua off

</IfModule>
```

**Comment by fballiano** [comment]
I chcked the history of the .htaccess file but I don't see any change that removed that section, probably we never added it at the end. unless it was in a commit on some branch that got lost.

**Comment by fballiano** [comment]
it was this PR https://github.com/OpenMage/magento-lts/pull/2306 anyway

**Comment by ADDISON74** [comment]
The exchange of ideas in that PR showed that improvments are needed in .htaccess. We did the changes for PHP8 in other directories such as media, skin, but not in the root file. We can add a few lines with some important settings.
