### ISSUE TITLE
GitHub Actions - `check-files` job fails in case of large number of changed files

### ISSUE THREAD

**Issue by gorbunovav** [OpenMage/magento-lts#3275]
### Summary (*)
E.g. in #3120 8K files were updated.
In the current form `check-files` tries to calculate number of changed files of different types. To achieve this the full list of changed files is emitted into each bash expression. 
Expressions are all listed in one step of the job, which leads to too large template size.

### Examples (*)
#3120 

### Proposed solution
We can split job into several steps - this way template for each step will be not that large.

**Comment by ADDISON74** [comment]
This problem does not concern the source code of OpenMage, but is a proposal for a certain situation in the case of PRs where many files are modified. the most appropriate place to discuss the proposal would be Discussions > Ideas.

**Comment by gorbunovav** [comment]
@ADDISON74 Workflow specs for GitHub actions are part of this repo. 
I've created a PR with the fix proposed - it doesn't contain any specific logic branches for large PRs: the same approach is used for all cases.

Do you want me to additionally create a discussion?

**Comment by ADDISON74** [comment]
Since you created a PR there will be discussions. I don't consider it necessary to create another topic on this topic. I appreciate your work.

**Comment by sreichel** [comment]
@all-contributors add @gorbunovav bug
