### ISSUE TITLE
Deprecation notices on NULL to empty string conversion on PHP 8.2

### ISSUE THREAD

**Issue by pisc-software** [OpenMage/magento-lts#3291]
### Preconditions (*)

1. OpenMage 20.0.20
2. PHP 8.2.6

### Steps to reproduce (*)

1. Has shown in production store on XMLRPC API use

### Expected result (*)

1. NULL to string empty auto conversion was performed on PHP < 8.2, now throws deprecation notice in log files.

### Actual result (*)

1. Deprecation notice: Passing null to string parameter is deprecated

### FIX: Add string type casting to parameters to convert null values to empty string:
In this case we have identified following files that need type casting on string parameters:

```
File: app/code/core/Mage/Core/Model/Translate.php (261)
    /**
     * @param string $string
     * @return string
     */
    protected function _prepareDataString($string)
    {
        // FIX: type casting null to string results in empty string (DEPRECATION on PHP 8.2)
        return str_replace('""', '"', (string)$string);
    }
```

```
File: app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php (618)
    /**
     * Get attribute backend table name
     *
     * @return string
     */
    public function getBackendTable()
    {
        if ($this->_dataTable === null) {
            if ($this->isStatic()) {
                $this->_dataTable = $this->getEntityType()->getValueTablePrefix();
            } else {
                // FIX: Deprecation message on passing NULL to trim: Casting value to string resolves null to empty string
                $backendTable = trim((string)$this->_getData('backend_table'));
                if (empty($backendTable)) {
                    $entityTable  = [$this->getEntity()->getEntityTablePrefix(), $this->getBackendType()];
                    $backendTable = $this->getResource()->getTable($entityTable);
                }
                $this->_dataTable = $backendTable;
            }
        }
        return $this->_dataTable;
    }
```

The Zend Framework has also an error in this file, where the default value is an empty string, but is reset to null at another position in the code:

```
File: lib/Zend/Validate/File/Extension.php (135)
    /**
     * Sets the file extensions
     *
     * @param  string|array $extension The extensions to validate
     * @return Zend_Validate_File_Extension Provides a fluent interface
     */
    public function setExtension($extension)
    {
        // FIX: Set _extension to empty string instead of null
        $this->_extension = '';
        $this->addExtension($extension);
        return $this;
    }
```

Sorry, we do not use GIT in our workflow, so pull requests for these changes are not available from us.
We want to point out the fixes, it is also a question on how to update the Zend Framework to have that fix included. We have also posted the ZF related issue to the ZF1 Future repo at [](https://github.com/Shardj/zf1-future)

As we support that particular production store with additional related fixes needed we will add these in this thread.
Thank you.

**Comment by pisc-software** [comment]
File: app/Mage.php (407)

    /**
     * Retrieve config flag for store by path
     *
     * @param string $path
     * @param mixed $store
     * @return bool
     */
    public static function getStoreConfigFlag($path, $store = null)
    {
        // FIX: null does not automatically convert to empty string on PHP 8.2:
        $flag = strtolower((string)self::getStoreConfig($path, $store));
        if (!empty($flag) && $flag !== 'false') {
            return true;
        } else {
            return false;
        }
    }

**Comment by sreichel** [comment]
Mage.php is fixed in [v20.1.0-rc1](https://github.com/OpenMage/magento-lts/releases/tag/v20.1.0-rc1)

**Comment by pisc-software** [comment]
Ok, so that may be excessive, as all string functions need a (string) cast (such as "trim" or "strlen") to overcome that deprecation. As notice here another item.
I think it needs a team decision as how the correction approach may look like on your end.

File: app/code/Mage/Core/Helper/Abstract.php

```
    /**
     * Escape html entities
     *
     * @param   string|array $data
     * @param   array $allowedTags
     * @return  mixed
     */
    public function escapeHtml($data, $allowedTags = null)
    {
        if (is_array($data)) {
            $result = [];
            foreach ($data as $item) {
                $result[] = $this->escapeHtml($item);
            }
        } else {
            // process single item
			// FIX: casting null to empty string
            if (strlen((string)$data)) {
                if (is_array($allowedTags) && !empty($allowedTags)) {
                    $allowed = implode('|', $allowedTags);
                    $result = preg_replace('/<([\/\s\r\n]*)(' . $allowed . ')([\/\s\r\n]*)>/si', '##$1$2$3##', $data);
                    $result = htmlspecialchars($result, ENT_COMPAT, 'UTF-8', false);
                    $result = preg_replace('/##([\/\s\r\n]*)(' . $allowed . ')([\/\s\r\n]*)##/si', '<$1$2$3>', $result);
                } else {
                    $result = htmlspecialchars($data, ENT_COMPAT, 'UTF-8', false);
                }
            } else {
                $result = $data;
            }
        }
        return $result;
    }

```

**Comment by kiatng** [comment]
All the E_DEPRECATED's raised in this issue were already fixed in the `main` branch, except for this `app/code/core/Mage/Core/Model/Translate.php`, which is fixed in PR #3294.

**Comment by thakilla** [comment]
Is there a reason why it was not merged in v19?

**Comment by kiatng** [comment]
@thakilla There has been a very long discussion on v19, v20, and v21. The consensus is that v19 is security upgrade only, all users are encouraged to migrate to v20, which is the main branch. v21 is the next branch after v20. See RFC on [Release Schedule](https://github.com/Flyingmana/rfcs/blob/2031563b15017a7354b45643bb8b6cc26f2b04de/proposed/0002-release-schedule.md)

**Comment by thakilla** [comment]
Alright that's fine for me. I was just irritated because yesterday i tried to upgrade an old 1.7 instance and in the docs / readme the first sentence related to v19 is that its php 8.2 compatible.

![Bildschirmfoto 2024-06-05 um 09 28 31](https://github.com/OpenMage/magento-lts/assets/449411/aae21014-f800-49a8-b23f-0d21298928af)

But thanks, i will try my luck with v20.

**Comment by kiatng** [comment]
@thakilla v19 should run fine with PHP8.2, depending on your error settings, you may have PHP deprecation notices on null. IMHO, the amount of works required to upgrade from 1.7 to v19 or v20 are about the same, which ever path you choose, it's a lot of works. You need to ensure the database is updated correctly. Once that done, you need to ensure the 3rd-party plugins play nicely. I hope that you have a smooth update.

**Comment by fballiano** [comment]
@thakilla v19 works perfectly fine on 8.2. also, this is a community project, instead of getting irritated at somebody who's dedicating time for free, feel free to participate and help.
