### ISSUE TITLE
Paypal express returns fullname as firstname, instead of first+last separately

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#332]
Paypal express returns fullname as firstname, instead of first+last separately

https://magento.stackexchange.com/questions/99884/paypal-express-firstname-and-lastname-instead-of-shiptoname/99892#99892

**Comment by ADDISON74** [comment]
5 years have passed since this report and the author has not been active on GitHub for a long time. I don't use the PayPal component so I can't express an opinion. Is this still an issue in OpenMage?
