### ISSUE TITLE
Deprecated notice when saving product attribute set

### ISSUE THREAD

**Issue by kyrena** [OpenMage/magento-lts#3325]
With OpenMage 20.x and PHP 8.1/8.2: `trim(): Passing null to parameter #1 ($string) of type string is deprecated`

![image](https://github.com/OpenMage/magento-lts/assets/78410399/a4c316fe-d907-4110-8dde-abdda211b6e8)

Without any changes (PHP 8.0), the query after the `foreach` is: `SELECT eav_attribute.* FROM eav_attribute WHERE (attribute_code='') AND (entity_type_id='4') AND (attribute_id!='1559')`

Possible solution?

```php
if (is_array($unique['field'])) {
    foreach ($unique['field'] as $field) {
        $select->where($field . '=?', trim((string)$data->getData($field)));
    }
} else {
    $select->where($unique['field'] . '=?', trim((string)$data->getData($unique['field'])));
}
```

It's weird.

**Comment by fballiano** [comment]
solved by https://github.com/OpenMage/magento-lts/pull/3535
