### ISSUE TITLE
Merge #319 causing PHP error on line 247

### ISSUE THREAD

**Issue by Quazz** [OpenMage/magento-lts#334]
syntax error, unexpected '', product'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /home/user/public_html/app/code/core/Mage/Checkout/Model/Cart.php on line 247

https://github.com/OpenMage/magento-lts/commit/0adfff595485d744e0b02803ddc6e056ea68a588

I think 

`Mage::dispatchEvent('checkout_cart_product_add_before', array('request' => $request', product' => $product));`

Should be 

`Mage::dispatchEvent('checkout_cart_product_add_before', array('request' => $request, 'product' => $product));`

**Comment by LeeSaferite** [comment]
I really miss having a fully automated test suite to catch things like this.

@colinmollenhour would you have time to add a simple linter on all of the php files to catch simple syntax errors like this in the future before we merge a PR?

**Comment by colinmollenhour** [comment]
@LeeSaferite  PHP lint functionality added!
