### ISSUE TITLE
Migration Bucket not found on AWS S3

### ISSUE THREAD

**Issue by gattieri** [OpenMage/magento-lts#3343]
### Preconditions (*)

1. try to migrate from Magento 1.9.4 to OpenMage last version
2. go to Magento root directory

### Steps to reproduce (*)

1. call the command "curl -fsSL https://migrate.openmage.org | sh"
2.

### Expected result (*)

1. Migration starts

### Actual result (*)

1. AWS S3 openmage.migrationpatches  Bucket doesn't exists
https://openmage.migrationpatches.s3.amazonaws.com/magento-ce-1.9.3.4-openmage-lts-v19.4.8.patch.gz
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>openmage.migrationpatches</BucketName>
<RequestId>AETMTKP1GMWYWJD0</RequestId>
<HostId>WjlaKRUVNiPYursw/Fgo34KD6S3M64WJnVTctONgHbK4Vs6E1HFx7hmNnvaRYOnPBginvMbK28o=</HostId>
</Error>

**Comment by fballiano** [comment]
the migration script was discontinued https://github.com/OpenMage/migrate/ but nobody updated the website, sorry for that :-( please refer to the https://github.com/OpenMage/magento-lts#installation to continue

**Comment by gattieri** [comment]
> the migration script was discontinued https://github.com/OpenMage/migrate/ but nobody updated the website, sorry for that :-( please refer to the https://github.com/OpenMage/magento-lts#installation to continue

Thank you.
so there is no longer a migration tool?
should openmage be installed in the old magento folder?

On your link i only find installation instruction.
I'm trying to go live today after migrating in test with the "old" tool
I lost the morning time... is there a chance to use the old migration?

I also have another project that will go live the next week and i will have the same problem

thanks

**Comment by fballiano** [comment]
I've never used the migration tool and I've not written it so I've no idea sorry

**Comment by gattieri** [comment]
I'm sorry if I'm insistent: in any case, would the migration concern only the files or are there also changes to the DB?

I would have found a workaround but I should check that the DB is "migrated" but I don't know how to check.

Can I check if there is a specific field on a table of the db that is created only for OpenMage or is the DB the same as Magento 1.9?

I'm talking about OpenMage v.19

thanks and sorry

**Comment by fballiano** [comment]
no reason to be sorry, I'd still reinstall openmage on top of the previous files, just to be sure.

if you login to the backend, in the footer there's gonna be written what version you're running.

my workflow:
- extract openmage on the previous folder
- reset cache
- login to backend
at this point all upgrade script ran

**Comment by ADDISON74** [comment]
In such situations you can clone the database and copy OpenMage files in another directory. Test it for a week and if you have no errors in the logs, with your own extensions and custom changes you launch it into production. Thus you have a backup of the current, functional version.

Remember that using the migration script was not a guarantee. moreover, I do not recommend migrating to production, so the version shown before is the safest way for an upgrade. I know that it is convenient to do everything with one order and quickly like in Magento 2, but there is still a long way to go and it will not be done soon because it depends on too many particularities of each OM installation.

So far I haven't identified any problems in OM using the current database, only there were problems with extensions and newer PHP versions.

**Comment by gattieri** [comment]
Thanks.
We tried openmage for a month in staging and making some theme and plugin changes.

Today was "The Day" and we get a strange error 500 without log errors.

But using the staging file with the production DB it works.

The fear is that some field in db are missing and we will get problem in the future.

Now i will try from clean db and Magento 1 file, using @fballiano procedure.

**Comment by fballiano** [comment]
the error 500 are logged by the webserver directly, so you should have something in the apache logs or the nginx logs

**Comment by gattieri** [comment]
i know but i found the 500 error log on access.log

i will start again from vhost and on...

thanks
