### ISSUE TITLE
Ebizmarts\Sagepaysuite expects ^v2.0 phpsec (20.1.0-rc5)

### ISSUE THREAD

**Issue by evensis** [OpenMage/magento-lts#3353]
### Preconditions (*)
1. 20.1.0-rc5
2. Opayo (sagepaysuite).

### Steps to reproduce (*)
1. Update to 20.1.0-rc5.
2. Add product to basket and navigate to cart page.
2. Attempt to navigate to checkout with Ebizmarts Sagepaysuite (Opayo) extension installed.
3. White screen crash.

### Expected result (*)
1. The checkout to load and display.

### Actual result (*)
1. White screen crash.

The issue is due to the Ebizmarts module relying upon version `^v2.0 phpsec` and `^v1.0 phpsec_mcrypt_compat`. So the composer changes of this release has broken this due to the newer version introducing breaking changes. This is using the most recent release of the Sage pay suite extension. Rolling back the version in composer.json to the aforementioned versions, resolved this issue, however, there was one more issue causing the crash:

The second issue revolves around Sagepaysuite expecting:

 `Mage::getSingleton('core/session')->getVisitorData();`

to return an array, with the session id as a key and value pair.  It seems this function or the data setter, has disappeared. I have overridden the Sagepaysuite extension to use `getSessionId();` instead to workaround this in the meantime.

Just a note that there a few breaking changes, so reporting as not sure if intended. Thanks!

**Comment by fballiano** [comment]
I think sage should update their module ;-)

**Comment by sreichel** [comment]
Or allow to install both versions?

Or share this extension to provide a patch?

**Comment by fballiano** [comment]
@evensis did you find a solution?

**Comment by fballiano** [comment]
@evensis do you have any updates in this report?
