### ISSUE TITLE
Scroll to first selected option in multiselect dropdown lists in the admin

### ISSUE THREAD

**Issue by loekvangool** [OpenMage/magento-lts#3357]
### Description (*)
In the admin, if selected values come into scroll focus on page load, the user does not need to scroll to the value, or ask whether any value is set at all. I find it tiring to scroll through sometimes hundreds of items.

### Additional information
I'm not a JS guy, but it might be something like:

```javascript
function scrollToSelected() {
  list = document.querySelectorAll('[multiple]');
  for (var i = 0; i < list.length; i++) {
    var select = list.item(i);
    var opts = select.getElementsByTagName('option');
    for ( var j = opts.length -1; j > 0; --j ) {
      if ( opts.item(j).selected == true ) {
        select.scrollTop = j * opts.item(j).offsetHeight;
        return;
      } 
    }
  }
}

window.onload = function() {
  scrollToSelected();
}
```

Adapted from https://stackoverflow.com/questions/71307437/how-do-i-scroll-an-html-multiple-selection-select-box-to-the-first-selected-opti

Or, something like https://harvesthq.github.io/chosen/ could improve the UX around multiselects.

**Comment by loekvangool** [comment]
Anyone with some input on how this could be done? Or is this a good way?

As far as performance impact is concerned: I have dozens of `multiselect` fields and the fire all at page load in the Product Edit screen, on all tabs at the same time, and it had no noticeable impact.

**Comment by fballiano** [comment]
Since nobody acted on this in a year, my personal opinion is that I wouldn't add a JS to override this default behavior by the browsers.

If anybody is willing to provide a PR, feel free
