### ISSUE TITLE
Loading the cart page takes 1 minute

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3358]
**My configuration**

Windows 10
WSL + Ubuntu 20
DDEV
Apache + PHP 8.2
OpenMage - latest main branch cloned
Magento Sample Pack

All pages are loading super fast on a powerful system except this URL **https://openmage.ddev.site/checkout/cart/**. 

It takes 1 minutes to load the cart page on a very powerful system. All action See the screenshot bellow

![screenshot](https://github.com/OpenMage/magento-lts/assets/8360474/16c6b52b-a547-4dfb-99d9-b0654bc2cf32)

The same issue is happening when adding any type of products to the cart. Does this issue happen to others?

**Comment by fballiano** [comment]
openmage "main", php8.2 on macos + brew, I don't see the issue:

<img width="1633" alt="Screenshot 2023-07-02 alle 20 01 54" src="https://github.com/OpenMage/magento-lts/assets/909743/53bb3fd8-3732-44c7-99b3-8981d9e20935">

**Comment by ADDISON74** [comment]
Please use the **Estimate** feature in the cart page and let me know what happens. In my case after clicking on the link the issue appears. The page loads in almost 45 seconds and after that the cart page loads always around 1 minute when adding a product or accessing it.

**Comment by fballiano** [comment]
the issue is there, but interestingly

<img width="1151" alt="Screenshot 2023-07-02 alle 20 59 30" src="https://github.com/OpenMage/magento-lts/assets/909743/736455b6-91d9-49e1-9718-127eb1a9711b">

it seems to be UPS fault somehow

**Comment by fballiano** [comment]
if you checkout https://github.com/OpenMage/magento-lts/pull/3287 you'll see the issue is not there anymore, it seems to be caused by the shut down UPS API that I asked to remove a month ago ;-)

**Comment by ADDISON74** [comment]
You are right, very good observation. Such relics if not removed quickly can have immediate consequences.
