### ISSUE TITLE
can't modify or create customer in admin

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#3375]
OpenMage 20.1.0-rc5

I am unable to reproduce the steps.
it is a test installation performed by 0 following the tutorials.

I have installed many plugins.

The same plug-ins are installed in other OpenMage installations without problems.

i upgrade to rc6 and tried to disable the plug-ins and the FPC but the problem remains

i want to add a client from the backend part
when I try to add a customer the page stays blank.

serverubuntu 20.04
php 7.4

**Comment by fballiano** [comment]
you can't see this page?

<img width="939" alt="Screenshot 2023-07-11 alle 15 46 54" src="https://github.com/OpenMage/magento-lts/assets/909743/968725cb-da43-4496-acf2-555b591e76d7">

**Comment by Danieleeffe1** [comment]
no

**Comment by fballiano** [comment]
I tested on php7 (usually use php8) but I can see that page with no problems.

**Comment by Danieleeffe1** [comment]
I changed the php version now I'm at 8.1, nothing has changed, if I check the page with the developer tools I only see the completely empty hrad and body html tags

**Comment by fballiano** [comment]
the only way is to enable developer mode and start disabling modules until you narrow it down

**Comment by pquerner** [comment]
Is this rc5 or rc6 related? You kinda said both versions and 'only' upgrades are failing?
What does the php error log say?

**Comment by ADDISON74** [comment]
I was not able to replicate this issue with the latest OpenMage + Sample Data. 

What I would do quickly would be to rename all the files of the installed extensions from /app/etc/modules, then I would flush the cache, it is impossible for the page not to load in the browser. Once confirmed, I would activate each extension in turn until I identify the one that causes trouble.

If the problem persists, I would check if the OpenMage instance is complete, that is, if it has all the files in their place. The URL for that page is /customer/edit/id/ look for the file /app/code/core/Mage/Adminhtml/controllers/CustomerController.php. Is it there?

**Comment by pquerner** [comment]
OpenMage made some changes regarding object deserialization, maybe that could be a thing. See https://github.com/OpenMage/magento-lts/pull/1251

**Comment by elidrissidev** [comment]
Do you see any error in the logs? You could also set `error_reporting = E_ALL` setting in `php.ini` and see if anything is displayed on the page.

**Comment by Danieleeffe1** [comment]
I'm currently reinstalling everything from scratch to check if the problem with my plug-ins comes back, give me some time and I'll try to update you

**Comment by fballiano** [comment]
closing, feel free to reopen in case you've more updates :-)
