### ISSUE TITLE
Deleting a website causes fatal error

### ISSUE THREAD

**Issue by m-overlund** [OpenMage/magento-lts#3380]
### Preconditions (*)

1. Multistore OpenMage
2. PHP 8.1
3. OpenMage 19.4.23

### Steps to reproduce (*)
1. Create multiple websites
4. Delete one website

### Expected result (*)
No errors - website deleted

### Actual result (*)
All sites crashes - backend and frontend, with HTTP 500.
```
[14-Jul-2023 08:52:50 UTC] PHP Fatal error:  Uncaught TypeError: Mage_Core_Model_Store::setWebsite(): Argument #1 ($website) must be of type Mage_Core_Model_Website, null given, called in /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/App.php on line 657 and defined in /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/Store.php:481
Stack trace:
#0 /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/App.php(657): Mage_Core_Model_Store->setWebsite()
#1 /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/App.php(483): Mage_Core_Model_App->_initStores()
#2 /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/App.php(366): Mage_Core_Model_App->_initCurrentStore()
#3 /var/www/xyz.com/public_html/app/Mage.php(736): Mage_Core_Model_App->run()
#4 /var/www/xyz.com/public_html/index.php(165): Mage::run()
#5 {main}
  thrown in /var/www/xyz.com/public_html/app/code/core/Mage/Core/Model/Store.php on line 481
```

### Fix used
1. Had to change function in app\code\core\Mage\Core\Model\Store.php to accept null.
`public function setWebsite(Mage_Core_Model_Website $website)`
to
`public function setWebsite(Mage_Core_Model_Website $website = null)`
to get past HTTP 500 on all pages.

2. Save base website again
5. Optionally remove edit again

**Comment by ADDISON74** [comment]
Here is my test result using a DDEV (Apache, PHP 8.2, MariaDB) + Magento Sample Data instance from scratch. OpenMage version 20.1.0-rc7.

**I created two more websites as follows**

![screenshot_1](https://github.com/OpenMage/magento-lts/assets/8360474/0a3b70ef-48b5-4d5e-b6f4-192ef9bf2950)

**I deleted the last one created**

![screenshot_2](https://github.com/OpenMage/magento-lts/assets/8360474/6a618ca5-5830-4333-b99b-11174038cbe9)

As you can see it was deleted without any issues. Backend/Frontend are working fine.

Is there something i didn't follow?

**Comment by m-overlund** [comment]
I don't know exactly what causes it.
Our multistore is from 2013, so there could be many factors.

Maybe it's only a thing, if you come from xx version or such.

**Comment by m-overlund** [comment]
There's only the multistore standard switch/case server_name in index.php 
Will test on dev to see what actually happened, some time soon.

**Comment by fballiano** [comment]
do we have any updates on this?

**Comment by m-overlund** [comment]
Did a quick test on dev and cannot reproduce.
Closing
