### ISSUE TITLE
Possibly still there? Catalog price rules core bug in Magento CE 1.9.1

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#340]
Possibly still there? Catalog price rules core bug in Magento CE 1.9.1

https://firebearstudio.com/blog/catalog-price-rules-core-bug-in-magento-ce-1-9-1-and-ee-1-14-1-0-array-to-string-conversion-error-and-incorrect-price-rules-behavior.html

**Comment by sreichel** [comment]
Duplicate of #25

**Comment by seansan** [comment]
agree - seems closed/fixed then?
