### ISSUE TITLE
Poor Image Quality for Some WebP Images on Product Page

### ISSUE THREAD

**Issue by hirale** [OpenMage/magento-lts#3400]
### Preconditions (*)

1. dev-main, fresh install with sample data
2. php 8.1, libwebp-dev 1.2.4-0.2, libwebp7 1.2.4-0.2, libwebpmux3 1.2.4-0.2, libwebpdemux2 1.2.4-0.2
![image](https://github.com/OpenMage/magento-lts/assets/22028058/9839598d-7a8c-47c9-9ebb-8448bd036413)

### Steps to reproduce (*)

1. upload some WebP images
![image](https://github.com/OpenMage/magento-lts/assets/22028058/1a4a8c25-32cb-4e85-9d64-8c40fe9fe76f)
here are original images
![image](https://www.gstatic.com/webp/gallery/1.webp)
![image](https://www.gstatic.com/webp/gallery/2.webp)
![image](https://www.gstatic.com/webp/gallery/3.webp)
![image](https://www.gstatic.com/webp/gallery/4.webp)
![image](https://www.gstatic.com/webp/gallery/5.webp)
2. flush cache

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. Poor quality for some images
![image](https://github.com/OpenMage/magento-lts/assets/22028058/8898f0fb-24d0-4dec-8e75-cbfa4a9d202e)
![image](https://github.com/OpenMage/magento-lts/assets/22028058/2e64ca53-fcd9-4b0b-a0ad-972aad86e24f)
![image](https://github.com/OpenMage/magento-lts/assets/22028058/a4245985-4cb7-44f7-8986-578435b198ce)
![image](https://github.com/OpenMage/magento-lts/assets/22028058/79d1f2da-0d45-42ca-ba21-060f61fa3851)
![image](https://github.com/OpenMage/magento-lts/assets/22028058/ab01eaf3-256f-456f-ad9d-c1585c24bf90)
2. WebP files in the screenshots cannot be uploaded directly here, so I made a zip.
[webp.zip](https://github.com/OpenMage/magento-lts/files/12138084/webp.zip)

**Comment by fballiano** [comment]
mmm probably the GD2 based resizing is screwing the images?

**Comment by sreichel** [comment]
+1 for untested new features.

**Comment by fballiano** [comment]
@sreichel I just makes me sad that you choose to only participate only when you can uselessly criticize what other people are trying, within their limits, to bring to this wonderful project. Do you want to break the game you don't want to play anymore? I wonder what happened to the person I was working together just a few months ago. Have a good week.

**Comment by fballiano** [comment]
@hirale interesting, on my machine I can't see the images you provided (in the zipfile) correctly, they look very odd:

<img width="1398" alt="Screenshot 2023-07-24 alle 08 44 06" src="https://github.com/OpenMage/magento-lts/assets/909743/03f13b2a-72d5-4633-9a20-811f624eddfd">

I don't know if that's possible but, could they have some specific colorspace or color profile or something I that?

I mean, not even my finder renders them correctly:
<img width="1465" alt="Screenshot 2023-07-24 alle 08 46 26" src="https://github.com/OpenMage/magento-lts/assets/909743/c600fad3-84d3-4ed2-87e5-79cb42f52f2f">

**Comment by fballiano** [comment]
if I download the test image from google I can render it correctly, while the one in the zip looks bad:

<img width="1500" alt="Screenshot 2023-07-24 alle 08 53 44" src="https://github.com/OpenMage/magento-lts/assets/909743/2f952263-8cfa-4fed-9452-00fb32b32385">

**Comment by fballiano** [comment]
ok now I think I understand the problem, this image is "correct" to use as a source image: 
[4.webp.zip](https://github.com/OpenMage/magento-lts/files/12143214/4.webp.zip)

then I upload it:
<img width="948" alt="Screenshot 2023-07-24 alle 08 57 09" src="https://github.com/OpenMage/magento-lts/assets/909743/9b4d0c0c-3db4-42ae-8e94-346c5538d40e">

at a first glance it looks ok on the frontend:
<img width="870" alt="Screenshot 2023-07-24 alle 08 55 23" src="https://github.com/OpenMage/magento-lts/assets/909743/8d940148-15e0-4a77-8c68-33bd080d34d4">

but then, click the thumbnail:
<img width="989" alt="Screenshot 2023-07-24 alle 08 58 06" src="https://github.com/OpenMage/magento-lts/assets/909743/ada015c8-5401-4df1-bfce-89c331f0bdcb">

so, the resizing routines for sure break the image somehow.

**Comment by ADDISON74** [comment]
It could be an issue with images resized by OpenMage. I added one of the images in the product description and as expected it is displayed correctly, see the result below

![webp-1](https://github.com/OpenMage/magento-lts/assets/8360474/99e5f578-79cf-4f6c-b912-4fe963bd1d5d)

If I open one of the thumbnails in a new browser window, here is what is displayed in Chrome, and nothing is displayed in Firefox

![webp-2](https://github.com/OpenMage/magento-lts/assets/8360474/5c1a9333-b9cc-4565-bd2b-cf29683ba8b9)

I will check what happens with a TIFF image saved from Photoshop in WebP format and one saved through an online converter.

**Comment by ADDISON74** [comment]
I took a TIFF image and saved it in Photoshop (latest version) in 3 formats: JPEG, PNG and WebP. By resizing the WebP format, the thumbnail (the one on the right) has a big loss of quality.

![Thumbnail](https://github.com/OpenMage/magento-lts/assets/8360474/1e54df80-1584-4e30-a40f-e78199ae5923)

If in the Backend the thumbnail is opened in a new window, which is actually the unsized image, this is what is displayed

![browser](https://github.com/OpenMage/magento-lts/assets/8360474/089c0033-66e8-4917-bb89-44dbaf0eb0db)

The highlight, if I drag the image saved on the Desktop into the browser, it is displayed correctly.

**Comment by fballiano** [comment]
please give a test to https://github.com/OpenMage/magento-lts/pull/3403, it solves for me

**Comment by ADDISON74** [comment]
@sreichel - In PR #3384 the feature to use images in WebP format was added to OpenMage. That PR solved 90% of the change and it was not mandatory to make a revert. A problem was identified yesterday and today it was confirmed, at this moment there is a solution that needs to be tested. If it is fine, then the problem is completely solved, We can state there is a new feature added. In addition, by merging that PR we did not affect the users, there is no release to contain it.

Only two people from those with "green approvals" participated in that PR. I would call them the last of the Mohicans who attach daily importance to OpenMage. For my part, I did a test, but I admit that I missed checking the quality of thumbnails and product images when they are used. I don't mind the reproaches in any way, but I would like not to see them, especially coming from people who abandoned the contribution because of personal vendetta.

**Comment by sreichel** [comment]
> @sreichel I just makes me sad that you choose to only participate only when you can uselessly criticize what other people are trying, within their limits, to bring to this wonderful project. Do you want to break the game you don't want to play anymore? I wonder what happened to the person I was working together just a few months ago. Have a good week.

As said, ive no time to work on OM (nor Magerun), but i was able to reproduce this issue with my first try.  My conclusion was, it was not properbly tested and got merged.

After spending tons of time to improve code quality it feels wrong to me to merge everything ASAP just to lower the number of issues or PRs.

You are one of the most active user here, but not found time to share your oppion about #2748? (Same for some other of my PRs.) Using type hints would be great improvement to avoid additional checks and make code clear. Since latest release a lot of new code has been added, w/o carring about this. Changing this later may cause more troube, so i asked for re-checking newly added methods.

btw ... it seems you ignore all my concerns ... e.g. showing deprecation errors with enabled debug-mode broke a few projects and is something i had to revert.

**Comment by fballiano** [comment]
what part of "we do what we can" you don't get? you've behaved very poorly to me personally, yet I've fixed quite some of your PRs that you purposely left unmaintained. The ones I thought were helpful.
I'm not commenting anything I don't believe in, you're not my boss hence you don't get to decide what I have to do on not.

I still think you comment only when you create problems just to ruin the environment for everybody. I gave you my full trust in the past and you treated it

**Comment by fballiano** [comment]
What part of "we do what we can" you don't get?
You've behaved very poorly to me personally, yet I've fixed quite some of your PRs that you purposely left unmaintained. The ones I thought were helpful.
I'm not commenting anything I don't believe in, you're not my boss hence you don't get to decide what I have to do on not.

I still think you comment only when you create problems and to ruin the environment for everybody.
I gave you my full trust in the past and you behaved and behave like it's worth zero, I won't make the same mistake again.

If github had a "block user", like whatsapp, I wouldn't be ruining my evenings every time you decide to write one of your messages.

**Comment by sreichel** [comment]
Got it, You're the boss. I will not criticize anything more ...

**Comment by fballiano** [comment]
wow

**Comment by sreichel** [comment]
Why "wow"? I frequently take a look at the PRs, but due to the lack of time i cant test it, so i can only mention things that feel wrong to me.
