### ISSUE TITLE
Underline active links in Backend menu (Next only)

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3452]
Please note this issue is only in the NEXT branch. I did not check when the change occurred in /skin/adminhtml/default/default/menu.css line 64.

**Steps to reproduce it**

1 - Go to Backend.

2 - From the menu select any section, for example Catalog > Manage Products.

3 - After the page loads, go to the menu again. The active page link is underlined. See the image bellow.

![menu_underline](https://github.com/OpenMage/magento-lts/assets/8360474/bc946b0f-64cf-4280-bbf8-146daf2c500b)

**Comment by fballiano** [comment]
it's coming from https://github.com/OpenMage/magento-lts/pull/2737 and I like it this way actually

**Comment by ADDISON74** [comment]
It doesn't look good at all

**Comment by ADDISON74** [comment]
It doesn't look good at all.

Underlining the active link has not been done for a long time. I consider that it is enough for the menu header to get a different color (orange), but no distinguishing elements are necessary for the submenu. I am sorry I approved that PR I missed the underline part.

**Comment by fballiano** [comment]
I don't think it can be considered a bug anyway, it's a preference that we can change in case

**Comment by ADDISON74** [comment]
It's a visual bug, it looks very bad and unprofessional. I immediately noticed it after seeing this interface for 15 years. It must be fixed, that underlining of the active link must be removed from both in the legacy theme and in openmage.

If you still like to highlight the active link of the menu, then a better option would be not to underline the link but to give it the hover background. Please make the change in the Inspector and you will see that it looks much better.

```#nav ul li a.active { /*! text-decoration:underline; */ background-color: #d0dfe2;}```

**Comment by ADDISON74** [comment]
This behavior introduced in PR #2737 must be removed at once. Even if we replace the underlining of active links with a colored background in the menu, there are issues I did not know before. Not all active links are underlined. Visit ```CMS > Widgets``` and after the page loads go to the menu, **Widgets** is not underlined. It is not the only case, visit the sections of the Reports, some are underlined, others are not. Problems in submenus. If you take every section accessible from the menu there are around 35% active link having this issue.

**Comment by fballiano** [comment]
the "widgets" bug is for sure due to the widgets mask, not the PR itself

**Comment by fballiano** [comment]
I think that having "something" to show that the menu is "active" is a good thing, maybe the underlining could be not the best? that's debatable I think, but to have an active state I think it's a good thing.

**Comment by sreichel** [comment]
@ADDISON74 any suggestions to make it look better - w/o underline. Different background color e.g.?

**Comment by ADDISON74** [comment]
This one is related to the legacy theme. The change should be

```css
#nav ul li a.active { /*! text-decoration:underline; */ background-color: #d0dfe2;}
```

Any active link will be highlighted in the menu, being easy to know which one is. Underlining is not a suitable visual solution in my opinion, valid for both Backend themes.
