### ISSUE TITLE
Uncaught Error: Class "Zend_Controller_Request_Http" not found in get.php

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#3453]
### Preconditions (*)

Using OpenMage version 20.1.0 & PHP8.2

### Steps to reproduce (*)

1. Hit the URL of non-existent image, e.g.: https://www.domain.tld/media/catalog/category/blankx.jpg
2. Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "Zend_Controller_Request_Http" not found in get.php:62

### Solution (*)

I suggest to move the piece of code in get.php - from lines 78-84:
```
$mageFilename = 'app/Mage.php';

if (!file_exists($mageFilename)) {
    echo $mageFilename . ' was not found';
}

require_once $mageFilename;
```

to move above the line 62:
`$request = new Zend_Controller_Request_Http();`

**Comment by fballiano** [comment]
I get a 404:

<img width="916" alt="Screenshot 2023-08-20 alle 23 46 16" src="https://github.com/OpenMage/magento-lts/assets/909743/62914a45-0cf2-46b8-9185-21b384eefafd">

do you need developer mode or something else in order to trigger the error?

**Comment by kiatng** [comment]
I cannot replicate, I get a 404 as well on the OM 20.1.0 PHP8.2.

**Comment by S0FTWEX** [comment]
> I get a 404:
> <img alt="Screenshot 2023-08-20 alle 23 46 16" width="916" src="https://user-images.githubusercontent.com/909743/261879862-62914a45-0cf2-46b8-9185-21b384eefafd.png">
> 
> do you need developer mode or something else in order to trigger the error?

My OpenMage was installed manually (extracting openmage-v20.1.0.zip file). Class `Zend_Controller_Request_Http` is defined only in vendor/shardj/zf1-future/library/Zend/Controller/Request/Http.php but 'vendor' is not mentioned in included paths in get.php (lines 32-35). So my question is: How can manually installed OpenMage load the Zend_Controller_Request_Http class in this file (get.php) if 'vendor' is not include path?

**Comment by ferdiusa** [comment]
This issue can be replicated if the .htaccess inside the media/ directory is properly parsed. (this actually redirects all request through get.php)
Some apache configurations skip this (and use the /.htaccess instead of /media/.htaccess for files in subdirectories). Try accessing 
http://openmage.test/media/missingfile.jpg
This should result in error 500 instead of 404 due to the missing class (due to missing autoloader patch in get.php)

**Comment by ADDISON74** [comment]
@ferdiusa - that is a good observation. I tested this reported before and I got error 500, without anything in the webserver logs. Some testers reported above getting 404 error.

**Comment by S0FTWEX** [comment]
Error 500 can be fixed by adding 
```
<IfModule mod_php8.c>
    php_flag engine 0
</IfModule>
```
in `media/.htaccess`. This fix actually redirects all request through get.php, but there is still problem with missing class `Zend_Controller_Request_Http`.

**Comment by fballiano** [comment]
I hope https://github.com/OpenMage/magento-lts/pull/3476 fix this problem ;-)

**Comment by S0FTWEX** [comment]
> I hope #3476 fix this problem ;-)

Yes, this PR fixes the problem.

**Comment by fballiano** [comment]
@S0FTWEX could you leave a review with the green button on the top-left https://github.com/OpenMage/magento-lts/pull/3476/files? thanxxxx
