### ISSUE TITLE
Deprecated functionality: imagecolorallocate()

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3463]
DDEV (Apache 2.4.56 + Maria DB 10.5.19 + PHP 8.2.8)
OpenMage 20.1.0 + Sample Pack (fresh install)

**Steps to replicate the issue**

1 - Enable the log files in the Backend. Both system.log and exceptions.log must be empty.

2 - Use two windows placed next to each other. On the left side open a Terminal then go to ```/var/log/``` directory and execute the command ```tail -f system.log```. On the right side, open the Frontend and browse product and category pages that contain swatches.

3 - At some point, around 6 - 7 visited pages, the **system.log** file starts to fill up with errors like bellow

```
2023-08-21T21:51:37+00:00 ERR (3): Deprecated functionality: imagecolorallocate(): Passing null to parameter #2 
($red) of type int is deprecated  in /var/www/html/lib/Varien/Image/Adapter/Gd2.php on line 282
2023-08-21T21:51:37+00:00 ERR (3): Deprecated functionality: imagecolorallocate(): Passing null to parameter #3 
($green) of type int is deprecated  in /var/www/html/lib/Varien/Image/Adapter/Gd2.php on line 282
2023-08-21T21:51:37+00:00 ERR (3): Deprecated functionality: imagecolorallocate(): Passing null to parameter #4 
($blue) of type int is deprecated  in /var/www/html/lib/Varien/Image/Adapter/Gd2.php on line 282
```

It happens also in the NEXT branch. I recommend everyone to open a Terminal window for watching in real time the log files and to check if other errors will be listed by visiting the Frontend and the Backend.

![error+](https://github.com/OpenMage/magento-lts/assets/8360474/762ba85e-d058-4055-a3a0-6d5e2b64c660)

**Comment by ADDISON74** [comment]
That function call needs a fix in two places. All three parameters get null values.

**File /lib/Varien/Image/Adapter/Gd2.php**
```
266 $transparentColor = imagecolorallocate($imageResourceTo, $r, $g, $b);
267 }
 
281 list($r, $g, $b) = $this->_backgroundColor;
282 $color = imagecolorallocate($imageResourceTo, $r, $g, $b);
283 if (!imagefill($imageResourceTo, 0, 0, $color)) {
```

**Comment by Flyingmana** [comment]
huh, did it see them as 0 before in case of this error? and makes it sense to do this?
Might be 2 issues, first what you see in the log, second that it gets into a situation where it is not set.
