### ISSUE TITLE
Uncaught TypeError: Mage_Sales_Model_Quote::setCouponCode()

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#3472]
### Preconditions (*)

1. OpenMage 20.1.0
2. PHP 8.2

### Steps to reproduce (*)

1. Place an order with no coupon code.
2. Run this PHP script to create quote from the order:
```
$orderId = XXXXX;
$order = Mage::getModel('sales/order')->load($orderId);
$quote = Mage::getSingleton('sales/convert_order')->toQuote($order);
```

### Expected result (*)

1. Quote has to be created.

### Actual result (*)

```
Fatal error: Uncaught TypeError: Mage_Sales_Model_Quote::setCouponCode(): Argument #1 ($couponCode) must be of type string, null given, called in /lib/Varien/Object.php on line 394 and defined in /app/code/core/Mage/Sales/Model/Quote.php on line 2102
TypeError: Mage_Sales_Model_Quote::setCouponCode(): Argument #1 ($couponCode) must be of type string, null given, called in /lib/Varien/Object.php on line 394 in /app/code/core/Mage/Sales/Model/Quote.php on line 2102
```

**Comment by fballiano** [comment]
mmm interesting, the setCoupon method is:

```php 
    public function setCouponCode(string $couponCode)
    {
        return $this->setData('coupon_code', $couponCode);
    }
```

so it requires a string, but the `toQuote()` method is copying filling the quote data using `copyFieldset()`

```php
public function copyFieldset($fieldset, $aspect, $source, $target, $root = 'global')
    {
        if (!(is_array($source) || $source instanceof Varien_Object)
            || !(is_array($target) || $target instanceof Varien_Object)
        ) {
            return false;
        }
        $fields = Mage::getConfig()->getFieldset($fieldset, $root);
        if (!$fields) {
            return false;
        }

        $sourceIsArray = is_array($source);
        $targetIsArray = is_array($target);

        $result = false;
        foreach ($fields as $code => $node) {
            if (empty($node->$aspect)) {
                continue;
            }

            if ($sourceIsArray) {
                $value = $source[$code] ?? null;
            } else {
                $value = $source->getDataUsingMethod($code);
            }

            $targetCode = (string)$node->$aspect;
            $targetCode = $targetCode == '*' ? $code : $targetCode;

            if ($targetIsArray) {
                $target[$targetCode] = $value;
            } else {
                $target->setDataUsingMethod($targetCode, $value);
            }

            $result = true;
        }

        $eventName = sprintf('core_copy_fieldset_%s_%s', $fieldset, $aspect);
        Mage::dispatchEvent($eventName, [
            'target' => $target,
            'source' => $source,
            'root'   => $root
        ]);

        return $result;
    }
```

which has the directive to copy the coupon_code and it does it calling the `$target->setDataUsingMethod('coupon_code', null);` because when loading an order with the model, it has a null coupon_code property in its `data` array because it's null on the database.

@kiatng how do you think we can solve it? either we change the setCouponCode method signature... or I don't see how we can initialize the model to '' when it's null in the database...

**Comment by S0FTWEX** [comment]
> I would remove the method `setCouponCode()` in the target model. It seems unnecessary. I'll review the code again after I get back from traveling.

The getter and setter for coupon code were added recently in #2825, so check this PR. For now, as a quick fix, I changed the method paramater signature to: `public function setCouponCode(?string $couponCode)`

**Comment by kiatng** [comment]
I agree with @S0FTWEX `public function setCouponCode(?string $couponCode)`. Reasons:

1. `coupon_code` column in the quote and order tables accepts `null`.
2. Setting `coupon_code` to empty string would change the default value in the table.

**Comment by kiatng** [comment]
Ref description in #2825, the function `setCouponCode()` was added as a test

> Added first getter/setter for test ... should make some changes to templates obsolete.

It seems we shouldn't add it. Is it best to simply remove the **test**, i.e., remove the function? @sreichel, your thought?

**Comment by fballiano** [comment]
I'd remove the method but let's see if we have other opinions

**Comment by sreichel** [comment]
@kiatng i prefer real methods over magic ones, so i think `?string` is the better way to allow `null` - to "unset"/not set a coupon code.

**Comment by kiatng** [comment]
@S0FTWEX Would you like to make a PR? 

Regardless of my personal preference, PHP is moving towards strict typing and there's no turning back. Magic methods was once loved, now it's frowned upon.

**Comment by fballiano** [comment]
OM will always have magic methods, so adding it was a test and maybe not a successful one, so Im still for removing it.

**Comment by elidrissidev** [comment]
We could simply change the type for the setter to `?string`, and the getter will keep returning an empty string so not affecting anything.

**Comment by elidrissidev** [comment]
Please share your thought in #3492.

**Comment by sreichel** [comment]
@all-contributors add @S0FTWEX bug
