### ISSUE TITLE
Use subfolder for setup

### ISSUE THREAD

**Issue by xf-** [OpenMage/magento-lts#348]
### Issue:
Trying to replacing firegento/magento with OpenMage/magento-lts. Current setup works with composer and puts magneto into a subfolder `src`.
Missing index.php in src is missing after replacing the packages.  `src/vendor` includes openmage/magento-lts .

```composer.json
{
  "name": "xy/yx",
  "require": {
    "magento-hackathon/magento-composer-installer": "~3.0",
    "aydin-hassan/magento-core-composer-installer": "~1.4",
    "riconeitzel/german-localepack-de-de": "~1.9",
    "phpoffice/phpexcel": "1.8.0",
    "firegento/performance-tweaks": "dev-master",
    "openmage/magento-lts": "1.9.3.x-dev"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.firegento.com/"
    }
  ],
  "config": {
    "vendor-dir": "src/vendor"
  },
  "extra": {
    "magento-root-dir": "src",
    "auto-append-gitignore": false,
    "magento-deploystrategy": "copy",
    "magento-force": "true",
    "magento-core-deploy" : {
      "excludes": [
        "app/etc/local.xml",
        "app/etc/config.xml",
        ".htaccess",
        "app/etc/modules/Cm_RedisSession.xml",
        "dev/tests/functional/etc/config.xml"
      ]
    }
  }
}
```

Note: If i clone the repo and throw it into`src` -> it works.

**Comment by tmotyl** [comment]
Hi,
In my working composer setup I have few differences:
- `remove "vendor-dir": "src/vendor"` from config section
- add   `"magento-core-package-type": "magento-source"` to "extra" section

**Comment by xf-** [comment]
THX - i never removed the vendor-dir - i added "magento-core-package-type" but no effect.
