### ISSUE TITLE
Change TItle of project

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#349]
Currently is

A fork of Magento that is accepting bug fixes

Make it

Magento LTS 1.x - A Magento Fork Accepting Bug Fixes (with Long Time Support)

This makes it a lot better to find in Google and of people interested. Now youo really have to add +github to the query sstring -- whilst if we rename it like above + add this string to the readme etc too -- then it will be indexed a lot better

**Comment by tomekjordan** [comment]
HI. nobody knows whot is LTS. So for better searching & SEO, I would opted for just: Magento 1.x Bug Fixes - with Long Time Support

**Comment by seansan** [comment]
The suggestion is the suggestion made
It actually explains LTS to the user ;) 
And its only a quick win

**Comment by Quazz** [comment]
Because github adds a prefix, that title would be truncated off, just as it is now. 

I don't have a problem finding this github page with "magento long term support", though.  (even in incognito)

**Comment by Flyingmana** [comment]
We have a different repository for "organizatorial" tasks
https://github.com/OpenMage/organizational/issues

please move such topics there, so they are not mixed with technical topics.
