### ISSUE TITLE
Missing files fusty-flow.js and -factory.js

### ISSUE THREAD

**Issue by simkea** [OpenMage/magento-lts#3546]
### Preconditions (*)
Version: 20.1.1
PHP 8.1

### Steps to reproduce (*)
1. Clone Repo magento-lts and install
2. after full setup go to > catalog > article > edit/new article
3. Try to Upload an Image 

### Expected result (*)
1. JS Console : Error fusty missing
![image](https://github.com/OpenMage/magento-lts/assets/612913/da6a01dd-293a-4d72-be34-8a5a81207021)

### Solve the Problem
i placed the files from https://github.com/flowjs/fusty-flow.js/tree/master in the js folders:
![image](https://github.com/OpenMage/magento-lts/assets/612913/3dc28480-850b-4190-a5c3-0467c8a06182)
add "fusty-flow.js" and "fusty-flow-factory.js" to the folder "/js/lib/uploader/"

**Comment by justinbeaty** [comment]
> after full setup go to > catalog > article > edit/new article

This page sound like it is from an extension, correct? The extension should be modified to remove reference to this library.

We removed fusty flow because it’s very old and only for Internet Explorer:

> [What is Fusty-Flow.js ?](https://github.com/OpenMage/magento-lts/issues/3546#what-is-fusty-flowjs-)
>
> A JavaScript library which extends Flow.js and allows to use not resumable uploads for older browsers, such as IE7, IE8 and IE9.

**Comment by simkea** [comment]
I pulled the code here from Github. And no extension installed!!! Only code from your repo of version 20.1.1.

Why is the uploader broken then?

**Comment by simkea** [comment]
Sorry, plz delete this Problem! solved, Browser-Cache Problem
