### ISSUE TITLE
Performance improvement for WYSIWYG editor

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#355]
Read here: https://www.ctidigital.com/blog/fixing-magento-improving-performance-of-the-wysiwyg-editor/

See: https://github.com/ctidigital/magento-wysiwyg-fix

Looks good. Just need to test if there are some sideeffects ...

Addresses same like #261

**Comment by sreichel** [comment]
#261 is the same approach as mentioned there (https://www.ctidigital.com/blog/fixing-magento-improving-performance-of-the-wysiwyg-editor/), just without fixed `Mage_Cms_Helper_Wysiwyg_Images::getBaseUrl()`

... however ... 1.9.4 broke it again. Details and possible fix here: https://magento.stackexchange.com/questions/279596/1-9-4-breaking-broken-features-what-is-mage-core-model-file-uploadergetcorre

PR as soon as confirmed.

**Comment by jahnni** [comment]
hi there, do you have any news on that :) ? tnx!

**Comment by sreichel** [comment]
Closed with #984
