### ISSUE TITLE
Revert PR - comments format

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#3555]
Ref #3552 

Please check https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_phpDocumentor.howto.pkg.html#basics.docblock

**Comment by fballiano** [comment]
ah ok so this is the documentation (I searched for that before creating the PR and couldn't find):
<img width="645" alt="Screenshot 2023-09-27 alle 16 17 15" src="https://github.com/OpenMage/magento-lts/assets/909743/808e2a3a-4a34-43c0-8b60-92e431c628c2">

In short, it duplicates the doc in the template for all the "vars".

I'd agree to revert if the doc had types but it seems to me that it only has descriptions (https://github.com/OpenMage/magento-lts/pull/3552/files) so I don't see the point of having a template just for a generic description of multiple constants, which don't even explain what the constant does :-\

eg:
<img width="480" alt="Screenshot 2023-09-27 alle 16 20 51" src="https://github.com/OpenMage/magento-lts/assets/909743/7f6ad51a-d6b0-491e-9b8c-dcfac1e7dbcf">
it seems not very useful to me to have a duplicate "names" description for those constants, actually it seems worse than just not having the description at all.

But if people think it's important let's revert it.

**Comment by ADDISON74** [comment]
The arguments offered are in favor of a revert. I have no idea how useful will be those comments in the future.

**Comment by fballiano** [comment]
> The arguments offered are in favor of a revert. I have no idea how useful will be those comments in the future.

@ADDISON74 actually I said the opposite 😅 and from the emoj reaction I think @elidrissidev agree. @pquerner just asked a question. so let's see if somebody else participates in the discussion.

**Comment by elidrissidev** [comment]
I do not oppose reverting the PR as @sreichel's point is completely valid, but the comments that were removed are not adding much value anyways and the description of the constants as well as their type can be easily inferred from their names. Anyways I'll approve it if someone creates it.

**Comment by fballiano** [comment]
I don't think there's any value in reverting so I'll not participate, but I'll not oppose, obviously

**Comment by Flyingmana** [comment]
What I see its a functionality to copy comments onto multiple variables? My first question would be, is it supported by phpstan for type informations? (or phpstorm?)
But even then I would prefer not having it, as its an uncommon notation many will not understand the meaning of.
But it means we would need to modify the changed files again, as we lost some type and some deprecated annotations (which were intended for multiple entries.
And its a bit odd to have the comments in plural, when the comment is copied into each entry.

Its also documented in their code, although not in their documentation https://github.com/phpDocumentor/ReflectionDocBlock/blob/7b217217725dc991a0ae7b995041cee1d5019561/src/DocBlock.php#L98-L117

**Comment by fballiano** [comment]
I can create a PR in like 15 minutes to convert those few "real" tags that we lost (1 deprecated and a couple of "mixed" types) if wanted

**Comment by sreichel** [comment]
> Does OpenMage/Magento have a public phpDocumentor archive or why is that important to keep?

There is no public one, but maybe private?

> My first question would be, is it supported by phpstan for type informations? (or phpstorm?)

It is supported by phpstorm. So i'm pretty sure it's also supported by phpstan/psalm/...

---

With #3552 phpDocumentor looses some descriptions - for absolutly no reason.

I am also pretty sure we had a similar PR years ago, that was closed for same reason. (cant find it)

**Comment by sreichel** [comment]
Closed with #3558
