### ISSUE TITLE
UPS API Change Request

### ISSUE THREAD

**Issue by sebadiginet** [OpenMage/magento-lts#3556]
### Description (*)

Starting from June 3, 2024, UPS no longer support WDSL and authentication to UPS API. UPS is going to change to use Oauth 2.0.
Here is request for Magento2 : https://github.com/magento/magento2/issues/37534
So integration with UPS for openmage will be not available after that date.

### Expected behavior (*)

Hope to create solution for openmage integration with UPS OAuth2.

### Benefits

That will allow to continue use UPS online live rates for openmage.

**Comment by fballiano** [comment]
I'm already trying to port that patch to OM ;-)

**Comment by sebadiginet** [comment]
Great im not programmer but if i can help any way give me info.
Also when we are talking your extension magento-full-catalog-translate im still using.

**Comment by fballiano** [comment]
hahah nice!

**Comment by elidrissidev** [comment]
@fballiano any progress on this? I've been working with the new UPS API recently, if you need any help let me know.

**Comment by fballiano** [comment]
@kiatng I did something on a branch, I can publish it if you want to take a look or add stuff, there's nothing tested because it's not even finished

**Comment by kiatng** [comment]
@fballiano I am not familiar with shipping, but I can take a look when you publish it.

**Comment by elidrissidev** [comment]
@kiatng I think he meant to mention me instead 😅

**Comment by elidrissidev** [comment]
@fballiano You can push it to your fork, I'll take a look once I get some time.

**Comment by fballiano** [comment]
it seems M2 is about to release an updated patch for this, so I'll wait for that one before pushing my branch (which probably will have to me re-built anyway ;-))

**Comment by perryholden** [comment]
@fballiano - Do you have any updates on your branch / PR? I appreciate it! Thanks!

**Comment by Franciscof-Serfe** [comment]
Hi Everyone, 
 On this note, I leave my last notes regarding this update https://github.com/magento/magento2/issues/37534#issuecomment-2018491122
 
 I hope it is useful to you to be able to move forward with this.
Regards,
Francisco

**Comment by fballiano** [comment]
check 20.7.0

**Comment by mark-ligon** [comment]
Looking for the OpenMage 19.4.8 solution or information. New to github and understanding how to navigate to see the solutions by members.

**Comment by mark-ligon** [comment]
> @mark-ligon there's no solution for v19 unless you want to extract the mage_usa module from v20 and try to run it on v19

Thank you for the reply, can you point me in the direction of the v20 solution? I'm trying to learn the ropes of github and still get confused on locating things.

**Comment by fballiano** [comment]
OM 20.9 has our latest version of the UPS module, which is called Mage_Usa by the way ;-)
