### ISSUE TITLE
Implement Improved Hashing and 2FA into core 

### ISSUE THREAD

**Issue by damienwebdev** [OpenMage/magento-lts#357]
Referencing #307  there was discussion about adding 2FA into Magento 1.X as a core feature alongside an improved hashing algorithm for customer passwords.

There are two well-known libraries that already exist that discuss this: 

https://github.com/ikonoshirt/pbkdf2
https://github.com/magento-hackathon/Magento-Two-factor-Authentication

We should consider these.

Additionally, it may be prudent to consider some Social Identity providers via OAuth.

**Comment by kkrieger85** [comment]
References:

#690 #689

**Comment by kkrieger85** [comment]
Close this issue, as both mentioned modules have their own issue ;)
