### ISSUE TITLE
Error in extension NWD Themes Revolution Slider 6.1.1.6

### ISSUE THREAD

**Issue by matteotestoni** [OpenMage/magento-lts#3572]
### Preconditions (*)

1. OpenMage 20.1.1
2. NWDthemes Revolution Slider - https://nwdthemes.com/extensions/slider-revolution/

### Steps to reproduce (*)

1. upload a new image 
2. openmage logout

### Expected result (*)

1. upload image to a slide
2. save slide

### Actual result (*)

1. in prototype.js parsejson redirect to login page and openmage is now logged out from admin

Maybe cookie change in openmage?
Extension also search for fusty-flow.js, fusty-flow-factory.js ext-all.css removed from openmage 20.1 rc2

**Comment by matteotestoni** [comment]
this is uploadfile of the extension

    /**
     * Upload and resize new file
     *
     * @param string $targetPath Target directory
     * @param string $type Type of storage, e.g. image, media etc.
     * @throws Mage_Core_Exception
     * @return array File info Array
     */
    public function uploadFile($targetPath, $type = null)
    {
        $uploader = new Mage_Core_Model_File_Uploader('image');
        if ($allowed = $this->getAllowedExtensions($type)) {
            $uploader->setAllowedExtensions($allowed);
        }
        $uploader->setAllowRenameFiles(true);
        $uploader->setFilesDispersion(false);
        $result = $uploader->save($targetPath);

        if (!$result) {
            Mage::throwException( Mage::helper('cms')->__('Cannot upload file.') );
        }

        // create thumbnail
        if ($this->getUploadType() == 'image') {
            $this->resizeFile($targetPath . DS . $uploader->getUploadedFileName(), true);
        }

        $result['cookie'] = array(
            'name'     => session_name(),
            'value'    => $this->getSession()->getSessionId(),
            'lifetime' => $this->getSession()->getCookieLifetime(),
            'path'     => $this->getSession()->getCookiePath(),
            'domain'   => $this->getSession()->getCookieDomain()
        );

        return $result;
    }

**Comment by matteotestoni** [comment]
maybe getSession() to _getSession()?

**Comment by kiatng** [comment]
> maybe getSession() to _getSession()?

That would depends on the parent classes. But this should work:
```php
      $session = Mage::getSingleton('core/session');
      $result['cookie'] = array(
            'name'     => session_name(),
            'value'    => $session->getSessionId(),
            'lifetime' => $session->getCookieLifetime(),
            'path'     => $session->getCookiePath(),
            'domain'   => $session->getCookieDomain()
        );
```

**Comment by matteotestoni** [comment]
Not resolve because the problem is before.
NWD revolution slider extend Mage_Cms_Model_Wysiwyg_Images_Storage to create a custom uploader and maybe something is changed in session for 20.1.1
Maybe something in javascript

I think media storage can have a custom menu like media library of wordpress.

Maybe someone can resolve this problem with a paid work?

**Comment by ADDISON74** [comment]
I have created a new category in Discussions for those interested in solving their problems quickly by paying a developer

https://github.com/OpenMage/magento-lts/discussions/categories/hire

**Comment by matteotestoni** [comment]
submitted
