### ISSUE TITLE
Create backorder - shows only store view name instead of website name

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#358]
Hi. as a merchant many times I need to create backorder, but order making screen shows only store view (which is usually language name) and gives nothing to admin. Many times I needed to cancel and start again because I wasn't sure this is correct website.

Screen: [http://prntscr.com/h0fy3b](http://prntscr.com/h0fy3b)

BTW: it would be great to change website during order creation process (something similar is done in IWD Order Manager)

Thanks

**Comment by sreichel** [comment]
Added website name in PR, but IMHO

> BTW: it would be great to change website during order creation process (something similar is done in IWD Order Manager)

... is out of scope. (would like to have it in too, so maybe feature request for "later"?)
