### ISSUE TITLE
Deprecated functionality: mb_strtolower()

### ISSUE THREAD

**Issue by gkopec** [OpenMage/magento-lts#3580]
OpenaMage 19.5.1

`app/code/core/Mage/ConfigurableSwatches/Helper/Data.php::79`

```Deprecated functionality: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated```

**Comment by Flyingmana** [comment]
was fixed as part of https://github.com/OpenMage/magento-lts/pull/3155 and is available since [v20.1.0](https://github.com/OpenMage/magento-lts/releases/tag/v20.1.0)

Do you need it to get backported?

**Comment by kiatng** [comment]
https://github.com/OpenMage/magento-lts/blob/758b01c959057c9f44eb003c27cbf1a6af2504d1/app/code/core/Mage/ConfigurableSwatches/Helper/Data.php#L75-L84

Thanks for the report, but as you can see, it's fixed.

**Comment by sreichel** [comment]
It's seems not to be fixed for 19.5.1.

**Comment by kiatng** [comment]
My apology. My mistake to close this.

**Comment by fballiano** [comment]
I'd merge https://github.com/OpenMage/magento-lts/pull/3592 and then create a new release, seems about time ;-)
