### ISSUE TITLE
Create backorder + new customer gives customer associated to admin

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#359]
Hi. anytime order is created with new customer on the fly, this customer is not assigned by default to the websites where the order is made, but to "Admin" fake website.

It makes problems with customer login after order is made, even when you send this customer random password or he tries to reset it.

**Comment by colinmollenhour** [comment]
Agreed this is a bug.

**Comment by sreichel** [comment]
Can't reproduce. Customers website is correct when create order from backend with new customer.

> BTW: it would be great to change website during order creation process (something similar is done in IWD Order Manager)

Do you use this extenion? Maybe a bug there?

**Comment by sreichel** [comment]
@tomekjordan 

Is it still reproducable? (tested and worked for me)

**Comment by tomekjordan** [comment]
Hi, it works so we can close. but it would be great o check mark as defsult on Save Adress. to avoid accidental address loss after order is made (it will no save customer's address in his profile)

**Comment by sreichel** [comment]
> Agreed this is a bug.

@colinmollenhour Tested or from reading?

@tomekjordan do you mean your other ticket? Already checked, but not enough time for PR :)

**Comment by tomekjordan** [comment]
I test it everyday. I have a lot admin orders.no bug there. false alarm, or at least 1931 have fixed it
