### ISSUE TITLE
Odd conversion from string to number - multiply by one

### ISSUE THREAD

**Issue by m-overlund** [OpenMage/magento-lts#3623]
Had a integer field (postcode) added to sales order grid, which gave me errors (due to lack of input validation).

Found this line in the Number renderer:
https://github.com/OpenMage/magento-lts/blob/main/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Renderer/Number.php#L36

Isn't it just an odd way of converting a variable that may be a string to int?

It crashed my order grid due to postcode containing non int characters, as int was expected (in our country it's only integers).

`TypeError: Unsupported operand types: string * int in app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Renderer/Number.php:36`

### Preconditions (*)

1. OpenMage 20.2.0
2. PHP 8.2.1

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by kiatng** [comment]
If your postcode is not a number, why do you set `'type'  => 'number'`?

**Comment by m-overlund** [comment]
I do expect postcode to be a number :)
(I do use number to be able to search from/to postcodes)

There was cases of whitespace included in value, customers who had written postcode in city and vice versa, in customer profile address (my fault).
But that isn't my point with this issue.

To my knowledge, the only reason to multiply the value with 1, is to make sure a string is converted to a number?
So i believe that either it should expect a number or convert in a better way, or handle an exception?

**Comment by kiatng** [comment]
Can you do a PR?

**Comment by kiatng** [comment]
There are many places:

https://github.com/OpenMage/magento-lts/blob/7c44d695b499689c1885a5b3fd56b2ef79bd8585/app/code/core/Mage/Tax/Model/Resource/Calculation.php#L121

https://github.com/OpenMage/magento-lts/blob/7c44d695b499689c1885a5b3fd56b2ef79bd8585/app/code/core/Mage/Adminhtml/Block/Report/Grid/Column/Renderer/Blanknumber.php#L28

app\code\core\Mage\Adminhtml\Block\](https://github.com/OpenMage/magento-lts/blob/7c44d695b499689c1885a5b3fd56b2ef79bd8585/app/code/core/Mage/Adminhtml/Block/Sales/Order/Create/Items/Grid.php#L89-L107

**Comment by m-overlund** [comment]
> Can you do a PR?

Yeah, I'll have a go at it and submit a PR :)

**Comment by sreichel** [comment]
Please do not change.

You can add a custom column renderer, observe _before_save or _after_load, validate input ...  no need to change core for some wrong input.

**Comment by m-overlund** [comment]
I don't want to change core due to wrong input - i found the odd number conversion code due to wrong input handling.
If the mentioned core code is not an issue, i'll just close it.

**Comment by kiatng** [comment]
You can try: https://onlinephp.io?s=s7EvyCjg5VIpLilSsFVQN1S35uUqSyyKTynNLdAAi2orGGhaAwA%2C&v=8.2.12

```php
$number = '1' * 1; // int(1)
$number = '1.01' * 1; // float(1.01)
$number = 'str' * 1; // Fatal error: Uncaught TypeError: Unsupported operand types: string * int
```

Is it wrong to throw the last error? It depends on the use case. For 

https://github.com/OpenMage/magento-lts/blob/0ac3f19a23eed02fbb27cc5586254a5eb7d30af9/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Renderer/Number.php#L36-L36

In the core, type number is used for column of type `int` as defined in the DB. So it's probably ok to throw an error, I think. So I changed the label to "bug unconfirmed".

**Comment by m-overlund** [comment]
Sounds right.
I'll close it up.
