### ISSUE TITLE
New TinyMCE 6 removes script and style tags

### ISSUE THREAD

**Issue by empiricompany** [OpenMage/magento-lts#3651]
### Preconditions (*)

1. OpenMage 20.2.0
2. php 7.4

### Steps to reproduce (*)

1. open some content that contains `<script>` or `<style>` tag with wysywyg editor (example content below)
2. hide editor and return to html 

### Expected result (*)

1. `<script>` / `<style>` tag not removed

### Actual result (*)

1. `<script>` / `<style>` tags removed from html 

**Example Content to Test out**
```
<script>
console.log("This message should not appear when tinyMCE is active, as it means that it is executing JavaScript, exposing security issues");
</script> 
<script type="text/javascript>
console.log("This message should not appear when tinyMCE is active, as it means that it is executing JavaScript, exposing security issues");
</script> 
<script type="text/javascript>// <![CDATA[ 
console.log("This message should not appear when tinyMCE is active, as it means that it is executing JavaScript, exposing security issues");
// ]]></script> 
<script type="text/javascript">// <![CDATA[ 
console.log("This message should not appear when tinyMCE is active, as it means that it is executing JavaScript, exposing security issues");
    jQuery(function($){ 
        $("#carousel").owlCarousel({autoPlay:3500,lazyLoad:true,stopOnHover: true,pagination: false, autoPlay: true,navigation: true,navigationText:["<i class='icon-left-open-big'></i>","<i class='icon-right-open-big'></i>"],slideSpeed : 1900,paginationSpeed : 900,singleItem:true,transitionStyle:"fade"}); 
  }); 
// ]]></script> 
<style><!-- 
.owl-bottom-narrow .owl-controls{width:95%;} 
  .owl-bottom-narrow .owl-controls .owl-buttons .owl-prev{color:#fff; float:left;} 
  .owl-bottom-narrow .owl-controls .owl-buttons .owl-next{color:#fff; float:right;} 
    .hidden-xs{display:block;} 
    .visible-xs{display:none;} 
    @media(max-width:540px){ 
        .hidden-xs{display:none;} 
      .visible-xs{display:block;} 
      .owl-carousel.owl-theme .owl-controls.clickable .owl-buttons div i{visibility:visible; vertical-align:middle;} 
      .owl-banner-carousel.owl-middle-narrow .owl-controls .owl-buttons div.owl-prev, .owl-banner-carousel.owl-middle-narrow .owl-controls .owl-buttons div.owl-next{visibility:visible;opacity:1; width: 50px; 
        height: 50px; padding:10px 10px; border-radius:50px; line-height:20px; background: rgba(0,0,0,0.3); color:#fff;} 
      .owl-middle-narrow .owl-controls{display:block!important;} 
  } 
  --></style> 

<div class="hide-mob hidden-xs">
	<div class="owl-carousel owl-theme owl-bottom-narrow owl-banner-carousel" id="carousel" style="border-bottom: solid 5px #0c06f7;">

		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		<div class="item">
			<a href="{{store direct_url='link'}}"><img alt="altImg" src="{{media url="wysiwyg/banner/test.jpg"}}" style="width: 100%;" /></a>
		</div>
		
	</div>
</div>
```

Themes like Porto include <script> and <style> tags in CMS content. However, when our customers modify this content using TinyMCE, they lose all the included scripts and styles.

It seems quite urgent because I had to restore the content from a backup.

Same resource to deal with:
[TinyMCE 6 Docs - Content Filtering](https://www.tiny.cloud/docs/tinymce/6/content-filtering/)
[stackoverflow](https://stackoverflow.com/questions/38165362/tinymce-stripping-style-tags)

**Comment by empiricompany** [comment]
common content of static block of Porto
![example](https://github.com/OpenMage/magento-lts/assets/5071467/3d179d0e-a109-4a41-ae49-ed208f19d5c4)

**Comment by empiricompany** [comment]
strip also alpinejs like
`x-data="carousel()"`

**Comment by ADDISON74** [comment]
Good observation. All HTML tags that need protection must be identified and thus remain unaffected after saving. 

You mentioned <script> and <style> for now. The Tiny documentation is clear in this direction, at first glance I would go for adding the protected block to tinymce.ini

https://www.tiny.cloud/docs/configure/content-filtering/#keep_styles

Clearly, a quick solution is needed because this will create big problems. I haven't upgraded, but I have CMS pages that contain the two HTML tags.

**Comment by empiricompany** [comment]
I am doing several tests with different configurations, it seems that there is no simple solution. 
This issue also occurs in Magento 2 with TinyMCE 4.

**Comment by empiricompany** [comment]
@ADDISON74 we can add some labels like HELP WANTED to this issues?

**Comment by empiricompany** [comment]
I have spent a lot of time conducting various tests, and for now, the best solution seems to be this:

![tinymce-settings](https://github.com/OpenMage/magento-lts/assets/5071467/02737ac1-e643-483c-9406-e10b8ccb98af)

But when I switch from the editor to the HTML text, it adds `</p>` like this:
![tinymce-insertp](https://github.com/OpenMage/magento-lts/assets/5071467/d2d132cc-0fbb-450e-99b4-de2e5679b22c)

**Comment by ADDISON74** [comment]
I changed the labels in "bug confirmed" and "help wanted".

A solution must be found that covers all situations, by no means only the particular ones, as shown on the Stackoverflow. No one should add anything in the configuration file. In addition we prevent in advance until the problem is identified by the user and it is too late, because the changes have already occurred irreversibly, if there is no backup.

I checked in several installations that do not have this update to TinyMCE 6, based on Magento 1.9.4. I have not encountered any issue with tags such as <script> and <style>, they remain in the form after saving the page.

**Comment by ADDISON74** [comment]
@empiricompany - if my memory serves me right, the addition of the <p> tag also happened before TinyMCE 6. Activating the editor and saving the whole content got the tags. I had to delete outside the editor then save again the page. This would be a separate problem, but I have not analyzed what the solution would be.

**Comment by empiricompany** [comment]
@ADDISON74 No, this didn't happen with the old tinymce 3 editor. I have tested it on other clients.
