### ISSUE TITLE
Importing magento-lts 1.9.3.x as upstream via git / how?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#366]
Hi, we run our own repo with dev / master etc. 

Now I am doing the following
- goto branch myrepo/dev
- sync/fetch all
- import  magento-lts/1.9.3.x where magento-lts/1.9.3.x overwrites local files (as being the core)
- git add and commit
- git push to myrepo/dev
(TEST)
- then git pull to myrepo/master

My question is how does one import the 3rd step correctly? so it takes the magento-lts/1.9.3.x as leading (I was trying git pull -X theirs magento-lts 1.9.3.x)

Any help appreciated

**Comment by Flyingmana** [comment]
A very good question and I think a very common usecase which needs to get a good documented solution.
But this needs a bit more time and effort, so first a bit of advice and some ideas.

The first part is, having a common base with both repos/branches. This is easier, if you already started the project from the openMage mirror or lts repo. If this is not given, we need to simulate one.
For this its best to take the specific version of the openMage/mirror you use, and merge it into your project with the "ours" strategy. You use the -s `-s <strategy>, --strategy=<strategy>` argument for this, dont mix this up with the merge options of the "recursive" strategy, which has a "ours" and a "theirs" option (and some more).
The "ours" strategy creates a merge point, but does not change anything in your branch.

Afterwards you can do real pulls and merges of the lts repository, and probably produce conflicts.
This is the point where you then can use the "theirs" option of the "recursive" strategy, and it should either work or produce some errors which we need to look into.
But actually I would do a proper merge conflict resolution for this step, as just taking the changes of the lts repository, could lead to cases, where only half of a modification is removed.

I can also offer to look myself into a specific case and prepare a dedicated manual how to do it properly for your case. Just contact me via mail.

**Comment by seansan** [comment]
@Flyingmana PM sent - maybe prep a little together and then post herre

**Comment by pepijnblom** [comment]
I'm interested in this too 👍

**Comment by tmotyl** [comment]
@seansan @Flyingmana can you elaborate a little bit how your project is structured?
Now we use composer to fetch mage-lts, as well as other packages, but before we used modman to keep Magento core clean and separate from modules and other data (magento was added to the git repo as a git submodule).

**Comment by seansan** [comment]
We added LTS as upstream and merge

Sometimes we run into this https://github.com/OpenMage/magento-lts/issues/880

@Flyingmana is writing an upgrade doc I understand. Maybe add something there .... 

then close this issue?

**Comment by fballiano** [comment]
I guess this issue can be closed now
