### ISSUE TITLE
`Undefined array key 0` warning at console Installation

### ISSUE THREAD

**Issue by akunzai** [OpenMage/magento-lts#3672]
### Preconditions (*)

1. OpenMage 20.2.0
2. PHP 8.2

See my [gist](https://gist.github.com/akunzai/8a14d7ee7b7a567f1d424f612477f08c)

### Steps to reproduce (*)

```sh
# start containers
docker compose up -d

# install OpenMage
bash ./install.sh
```

### Expected result (*)

Install success without errors

```sh
Checking database...
Installing OpenMage...
SUCCESS: ef6481244432fb89d109db9017743b1e
```

### Actual result (*)

```sh
Checking database...
Installing OpenMage...
ERROR: Error in file: "/var/www/html/app/code/core/Mage/Customer/sql/customer_setup/mysql4-data-upgrade-1.4.0.0.7-1.4.0.0.8.php" - Warning: Undefined array key 0  in /var/www/html/app/code/core/Mage/Core/Model/App.php on line 1006
```

Workaround: change `php.ini` to ignore warnings

```ini
error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING
```

I wrote some simple code to reproduce exception at [App.php](https://github.com/OpenMage/magento-lts/blob/main/app/code/core/Mage/Core/Model/App.php#L1006).

```php
<?php
function mageCoreErrorHandler($errno, $errstr, $errfile, $errline)
{
  $errno = $errno & error_reporting();
  if ($errno == 0) {
    return false;
  }
  throw new Exception($errstr);
}
set_error_handler('mageCoreErrorHandler');
error_reporting(E_ALL);
$website = 1;
$websites = [];
$id = false;
$code = null;
$websites[$code] = $website;
echo $websites[$code], "\n"; # [''] => 1
echo $websites[$id], "\n"; # [0] => Undefined array key 0
print_r($websites);
```

**Comment by fballiano** [comment]
I've tested a clean installation without seeing your problem, can you provide a install.php script with all the parameters for a quick check?

**Comment by sreichel** [comment]
I remember this error.

Can you test https://github.com/OpenMage/magento-lts/pull/3248 or install via n98-magerun?

**Comment by akunzai** [comment]
@fballiano https://gist.github.com/akunzai/8a14d7ee7b7a567f1d424f612477f08c#file-install-php

**Comment by sreichel** [comment]
@akunzai its nothing about your env ...

For some reason `false` is passed to `Mage_Core_Model_App::getWebsite($id = null)`, but `false` isnt an expeccted input ... and not handled.

**Comment by akunzai** [comment]
@sreichel 

false as index key will cast to 0 and should be fine, I notice the websites array was initialized with NULL key, and NULL cast to empty string as the index key

**Comment by akunzai** [comment]
the `false` was return by [Store::getWebsite](https://github.com/OpenMage/magento-lts/blob/1151717c034567f31722eb5d4666e0949977f80b/app/code/core/Mage/Core/Model/Store.php#L457)

and the warning only becomes exception in Developer mode(`MAGE_IS_DEVELOPER_MODE=1`)

I'll try to fire a PR to handle the `false` value
