### ISSUE TITLE
CM_Redis does not work with copy deploy strat?

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#3684]
As soon i change 

```
        "magento-deploystrategy": "copy",
        "magento-deploystrategy-dev": "symlink",
```

to "copy" or run composer install with `--no-dev` i get symlink errors every time.

- deleted community
- deleted vendor

It does nor work with copy!? @colinmollenhour can you please check this?

**Comment by colinmollenhour** [comment]
May be helpful to know so please clarify, when you say CM_Redis are you referring to the cache module or the session module?

This sounds like an issue with Composer more than any given module? I don't use Composer in this capacity and have never looked at the code for the magento-related Composer plugins so not sure I am the best person to report this to.. @Flyingmana would you be more familiar with this or know who to ask about it?

**Comment by sreichel** [comment]
Maybe related to undeleted symlinks?

Can you please test symlink strat and change it to copy and visa verse? (with and without cleaning vendor and symlinks)

**Comment by fballiano** [comment]
I recall that it was already discussed that if you switch between symlink and copy it doesn't work, but it's not CM_Redis fault, it should be the magento module

**Comment by sreichel** [comment]
> This sounds like an issue with Composer more than any given module?

It only happens to CM_Redis for me. Guess into the wild ... (or something that came accross years ago?)

modman
```
Cm/Cache/Backend/*                 app/code/community/Cm/Cache/Backend/
```

@colinmollenhour can you please test it w/o astrix `*`?

```
Cm/Cache/Backend/                  app/code/community/Cm/Cache/Backend/
```

**Comment by colinmollenhour** [comment]
The reason for the asterisk is Backend is not supposed to be a symlink, but rather a directory because there are other backends as well like Cm_Cache_Backend_File and Cm_Cache_Backend_Mongo so the intent was to avoid conflicts.

**Comment by sreichel** [comment]
> as well like Cm_Cache_Backend_File

I can remember problems symlinking multiple modules to one directoy ...  is it possible t to link files one by one? Or by sub-directories?

**Comment by colinmollenhour** [comment]
That's what the asterisk is for, but I suppose it could be specified one file per line.

https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/commit/d403f4473e1b3cc616fa59d187e817543b6620c1
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/releases/tag/1.17.1
