### ISSUE TITLE
Fatal error on saving a magento product

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#3692]
Try to create a simple product with add and remove "Tier Price". Then click on "Save". It is throwing "Fatal error".

`Fatal error: Uncaught TypeError: Unsupported operand types: string * int in \src\app\code\core\Mage\Catalog\Model\Product\Attribute\Backend\Tierprice.php:54 Stack trace: #0 \src\app\code\core\Mage\Catalog\Model\Product\Attribute\Backend\Groupprice\Abstract.php(290): Mage_Catalog_Model_Product_Attribute_Backend_Tierprice->_getAdditionalUniqueFields(Array) #1 \src\app\code\core\Mage\Eav\Model\Entity\Abstract.php(640): Mage_Catalog_Model_Product_Attribute_Backend_Groupprice_Abstract->afterSave(Object(Mage_Catalog_Model_Product)) #2 \src\app\code\core\Mage\Eav\Model\Entity\Abstract.php(1640): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterSa...', Array) #3 \src\app\code\core\Mage\Catalog\Model\Resource\Product.php(181): Mage_Eav_Model_Entity_Abstract->_afterSave(Object(Mage_Catalog_Model_Product)) #4 \src\app\code\core\Mage\Eav\Model\Entity\Abstract.php(1092): Mage_Catalog_Model_Resource_Product->_afterSave(Object(Mage_Catalog_Model_Product)) #5 \src\app\code\core\Mage\Core\Model\Abstract.php(379): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Catalog_Model_Product)) #6 \src\app\code\core\Mage\Adminhtml\controllers\Catalog\ProductController.php(751): Mage_Core_Model_Abstract->save() #7 \src\app\code\core\Mage\Core\Controller\Varien\Action.php(421): Mage_Adminhtml_Catalog_ProductController->saveAction() #8 \src\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch('save') #9 \src\app\code\core\Mage\Core\Controller\Varien\Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #10 \src\app\code\core\Mage\Core\Model\App.php(358): Mage_Core_Controller_Varien_Front->dispatch() #11 \src\app\Mage.php(740): Mage_Core_Model_App->run(Array) #12 \src\index.php(60): Mage::run('', 'store') #13 {main} thrown in \src\app\code\core\Mage\Catalog\Model\Product\Attribute\Backend\Tierprice.php on line 54`

**Comment by fballiano** [comment]
I could save a product with a tier price without the error

<img width="891" alt="Screenshot 2023-12-06 alle 10 10 45" src="https://github.com/OpenMage/magento-lts/assets/909743/3e4a0294-b417-4ee4-a502-8c74dd35d9ff">

do you have developer mode on?
