### ISSUE TITLE
1eaada92863d70274033ef6fd9a998a0bac941eb is breaking Admin Panel

### ISSUE THREAD

**Issue by PapaDragonov** [OpenMage/magento-lts#370]
Just in case that issues are recognized earlier than commit comments:

The named commit (Pull Request #317) is breaking the Admin Panel because of a missing comma in line 525.

@sreichel @colinmollenhour

**Comment by tomekjordan** [comment]
confirmed issue

**Comment by sreichel** [comment]
@all-contributors add @PapaDragonov bug

**Comment by sreichel** [comment]
@all-contributors add @PapaDragonov bug
