### ISSUE TITLE
Magento Admin: Input fields text and select drop-downs are different widths in "Attribute Information" page

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#3716]

**Comment by kiatng** [comment]
It'll be nice to include a screenshot in your description. Also, please explain why this is a bug. Other nice info to include: which version. which admin theme, and navigation steps to get to the screen.

**Comment by ADDISON74** [comment]
This is from Magento legacy theme

![Screenshot 2024-01-20 172654](https://github.com/OpenMage/magento-lts/assets/8360474/7b8dcabf-ea75-417a-bb0c-0e45a0f24e56)

**Comment by kiatng** [comment]
@dev-venkatesh Please review PR #3740 and provide your feedback/approval.

**Comment by kiatng** [comment]
@dev-venkatesh Thanks, but you need to finish your review by approving it for it to count:
![image](https://github.com/OpenMage/magento-lts/assets/1106470/fdf9e5e2-f49f-43bd-ae54-7eb0918cdc35)

It's a community and we desperately need more reviewers.

**Comment by ADDISON74** [comment]
This is the PR that fixes this issue https://github.com/OpenMage/magento-lts/pull/3850. 

I don't remember if it was released in version 20.5.0.

**Comment by fballiano** [comment]
#3850 was merged 1 day after 20.5.0, it will be included in the next release
