### ISSUE TITLE
Online refund (credit) always 0.00 and order complete instead of closed

### ISSUE THREAD

**Issue by steve18tech** [OpenMage/magento-lts#3720]
### Preconditions (*)

1. Version 20.3.0 (and 20.2.0 / 20.1.1)
2. Installed extentions for payments are Mollie and Pay.nl (both Netherlands)

### Steps to reproduce (*)

1. Place and pay an order so i get status processing and invoice is made.
2. Create an online refund by clicking on invoices > open the invoice > click on Credit Nota > click Refund. 

### Expected result (*)

1. A complete credit nota with the total amount of whole order instead of a 0.00 credit

### Actual result (*)

1. message 'Refunded amount of € 0,00 online.' should be in my example € 10,93
2. The right amount is passed to the payment provider, that works as expected only the credit nota itself is zero and the order is not closed but its complete.

**Comment by steve18tech** [comment]
Update: on other installation with Openmage 20.3.0 and only Mollie its working. So maybe a setup or conflicting thing?

**Comment by luigifab** [comment]
I suppose that your refund is right.

Try to find the culprit:
- I suggest to check the [refund method of your payment module](https://github.com/paynl/magento-plugin/blob/6437bbf223dea1ae46b878476659bb59a0e76c98/app/code/community/Pay/Payment/Model/Paymentmethod.php#L150) with `Mage::log($amount);`.
- Then check occurrences of `Refunded amount of` in your code.
- Perhaps try to `Mage::log($baseAmountToRefund);` [here](https://github.com/OpenMage/magento-lts/blob/11eca9d518be7e8073556b64ba36cf2178b276fb/app/code/core/Mage/Sales/Model/Order/Payment.php#L706).

**Comment by steve18tech** [comment]
Issue found! It was an older version of Fooman Surcharge whitch was causing the problems. Nothing to do with OpenMage. Now solved!
