### ISSUE TITLE
Can't upgrade from v20.2.0 to v20.3.0 

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#3737]
I am not sure on how to upgrade from v20.2.0 to v20.3.0.

I executed the below command to upgrade to the latest version in my OpenMage (Magento) root directory.
`composer update`
But the above command not upgraded to the latest version v20.3.0.

Please suggest the commands how to upgrade from v20.2.0 to v20.3.0 via composer.

**Comment by ADDISON74** [comment]
I will move this post where it belongs in Discussions section.
