### ISSUE TITLE
Escape strings in grids by default.

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/magento-lts#375]
It is obvious that user input should always be escaped when it is rendered to prevent various attacks. In the Text renderer it is escaped by default, but in the Longtext renderer which is actually used for a lot of columns it is optional and disabled by default. This could break some columns although I can't really imagine in which case database text should not be escaped when rendered in an admin grid but I think this will go a long way to prevent attacks in core code as well as third-party extensions. If for some crazy reason the escaping is not desired it can be disabled by explicitly requesting `'escape' => false`.

Examples: Search "Stored XSS" here, all of these attacks could be prevented.

**Comment by sreichel** [comment]
Lowercase `false`?
+1
