### ISSUE TITLE
Unable to save customer in admin console with DOB set to empty

### ISSUE THREAD

**Issue by massa-man** [OpenMage/magento-lts#3751]
### Preconditions (*)

1. OpenMage 19.5.2
2. PHP 7.4.33
3. MAGE_IS_DEVELOPER_MODE=true

### Steps to reproduce (*)

1. Open a customer record in Admin
2. Leave the date of birth field in the "Account information" section empty and click "save and continue edit"

### Expected result (*)

1. The contact information should be saved
2.

### Actual result (*)

1. The AJAX validation gets stuck, and the server responds to the ajax validation call with this:

```
<pre>Warning: A non-numeric value encountered  in /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php on line 97

#0 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php(97): mageCoreErrorHandler(2, 'A non-numeric v...', '/var/www/html/v...', 97, Array)
#1 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(387): Zend_Locale_Math_PhpMath::Sub('0', '', 0)
#2 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(666): Zend_Locale_Format::toNumber('', Array)
#3 /var/www/html/vendor/shardj/zf1-future/library/Zend/Filter/NormalizedToLocalized.php(110): Zend_Locale_Format::toFloat('', Array)
#4 /var/www/html/lib/Varien/Data/Form/Filter/Date.php(72): Zend_Filter_NormalizedToLocalized->filter('')
#5 /var/www/html/app/code/core/Mage/Eav/Model/Attribute/Data/Abstract.php(191): Varien_Data_Form_Filter_Date->inputFilter('')
#6 /var/www/html/app/code/core/Mage/Eav/Model/Attribute/Data/Date.php(35): Mage_Eav_Model_Attribute_Data_Abstract->_applyInputFilter('')
#7 /var/www/html/app/code/core/Mage/Eav/Model/Form.php(355): Mage_Eav_Model_Attribute_Data_Date->extractValue(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(623): Mage_Eav_Model_Form->extractData(Object(Mage_Core_Controller_Request_Http), 'account')
#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(422): Mage_Adminhtml_CustomerController->validateAction()
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch('validate')
#11 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(182): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/html/app/Mage.php(742): Mage_Core_Model_App->run(Array)
#14 /var/www/html/index.php(55): Mage::run('', 'store')
#15 {main}</pre>
```

I also tested this with the same version of **OpenMage but with PHP 8.1** and the error still happens, but in this case the error raised is not a warning, but a fatal error:

```
<pre>
    <br/>
    <b>Fatal error</b>
    :  Uncaught TypeError: Unsupported operand types: string - string in /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php:97
Stack trace:
#0 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(387): Zend_Locale_Math_PhpMath::Sub('0', '', 0)
#1 /var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(666): Zend_Locale_Format::toNumber('', Array)
#2 /var/www/html/vendor/shardj/zf1-future/library/Zend/Filter/NormalizedToLocalized.php(110): Zend_Locale_Format::toFloat('', Array)
#3 /var/www/html/lib/Varien/Data/Form/Filter/Date.php(72): Zend_Filter_NormalizedToLocalized-&gt;filter('')
#4 /var/www/html/app/code/core/Mage/Eav/Model/Attribute/Data/Abstract.php(191): Varien_Data_Form_Filter_Date-&gt;inputFilter('')
#5 /var/www/html/app/code/core/Mage/Eav/Model/Attribute/Data/Date.php(34): Mage_Eav_Model_Attribute_Data_Abstract-&gt;_applyInputFilter('')
#6 /var/www/html/app/code/core/Mage/Eav/Model/Form.php(355): Mage_Eav_Model_Attribute_Data_Date-&gt;extractValue(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(623): Mage_Eav_Model_Form-&gt;extractData(Object(Mage_Core_Controller_Request_Http), 'account')
#8 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(422): Mage_Adminhtml_CustomerController-&gt;validateAction()
#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(256): Mage_Core_Controller_Varien_Action-&gt;dispatch('validate')
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(182): Mage_Core_Controller_Varien_Router_Standard-&gt;match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front-&gt;dispatch()
#12 /var/www/html/app/Mage.php(742): Mage_Core_Model_App-&gt;run(Array)
#13 /var/www/html/index.php(55): Mage::run('', 'store')
#14 {main}
  thrown in <b>/var/www/html/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php</b>
    on line <b>97</b>
    <br/>
</pre>
```

Doing a bit of debugging, the issue is raised in the form filters for the dat filters, here:

```
Varien_Data_Form_Filter_Date::inputFilter()
Varien_Data_Form_Filter_Date::outputFilter()
```

These functions should exit eraly if the $value is empty.

I also found this issue had been raised in Magento2 and was patched in these PR: https://github.com/magento/magento2/commit/799199e149b749890a8ed15b27d751cc7c57dade

Linked to this issue in magento2: https://github.com/magento/magento2/issues/12146

Happy to provide a patch.

**Comment by fballiano** [comment]
Hi, wasn't it fixed by https://github.com/OpenMage/magento-lts/pull/3374 (which I think was released only in v20)

**Comment by massa-man** [comment]
I don't think so. The issues seem different. This is an issue with the core form Date & DateTime filters in Admin (used internally by the EAV from components - such as the customer EAV models - and other forms), while the issue you mentioned seem to be specific to the customer registration form in the frontend which uses three different elements for DD, MM, and YYYY

**Comment by kiatng** [comment]
Following the steps described, I cannot replicate with ver20.3.0 and PHP8.2.

**Comment by massa-man** [comment]
I found this old PR https://github.com/OpenMage/magento-lts/pull/1457 and related bug which is the exact same as I am experiencing. This does not appear to happen on new installations, but it does happen with older/upgraded installations (in my case we migrated to OpenMage 19.5.2 from Magento CE 1.9.4.5, but or original magento installation - and DB - comes from 1.4).

It is clear from the issues reported both in OpenMage as well as Magento2 repos, that this is an issue which impacts quite a few people upgrading, and the fix in my view is quite simple and logical, there is no need to filter a Date when the input is empty, if anything this should also make for better and more performant code.

**Comment by fballiano** [comment]
does it happen on OM 20.3.0?

**Comment by massa-man** [comment]
Not sure, I have not upgraded to OM 20.x yet, we are still on 19. It will require quite a bit of work for me to move to OM 20 since we have in-house and community modules that need to be upgraded

**Comment by pquerner** [comment]
Maybe its the database settings?
Can you show a DESCRIBE of that table?

**Comment by sreichel** [comment]
See https://github.com/Shardj/zf1-future/pull/402

**Comment by massa-man** [comment]
Sure, the Customer DOB is stored in magento's EAV model for the customer, in table `customer_entity_datetime`

```
mysql> DESCRIBE customer_entity_datetime;
+----------------+-------------------+------+-----+---------------------+----------------+
| Field          | Type              | Null | Key | Default             | Extra          |
+----------------+-------------------+------+-----+---------------------+----------------+
| value_id       | int               | NO   | PRI | NULL                | auto_increment |
| entity_type_id | smallint unsigned | NO   | MUL | 0                   |                |
| attribute_id   | smallint unsigned | NO   | MUL | 0                   |                |
| entity_id      | int unsigned      | NO   | MUL | 0                   |                |
| value          | datetime          | NO   |     | 0000-00-00 00:00:00 |                |
+----------------+-------------------+------+-----+---------------------+----------------+
5 rows in set (0.01 sec)
```

I see the @sreichel  provided a patch in zf1-future to fix this in the parent class `Zend_Locale_Math_PhpMath`, but that PR has not been merged yet, and even if it does, it might take sometime to be released and then we would need to upgrade OM 19.x to the new version of zf1-future which might have other implications.

I still think the patch I provided should be merged even if this is fixed elsewhere, it makes no sense to me to try and filter a date and/or datetime input doing time consuming conversions to and from internal locale and application locale when the input is empty.

**Comment by sreichel** [comment]
@massa-man the PR targets main branch and has to be backported. I'm okay with it, but i remember that the v19.x branch is abandoned.

If you use composer, you can patch this file until the next zf1 release (that hopefully comes within next days)

However, +1 for the PR.

**Comment by sreichel** [comment]
@massa-man  The PR has been merged. With composer you can dev-master until next release.
