### ISSUE TITLE
Use rebase instead of merge for PRs

### ISSUE THREAD

**Issue by edannenberg** [OpenMage/magento-lts#385]
I find the current git history really hard to work with due to all the pointless merge commits. Picasso would have been proud. ;) Ideally the history for any given branch should be a straight line. 

Proposal: Come up with a git strategy that prevents those issues in the future and gives users a clean view of what changed.

For starters:

* PR should always get rebased so a FF merge can be used which eliminates those pesky merge commits, the Github interface has options for that so the time impact for maintainers should be minimal
* Strict rules regarding commit messages
  * Should be rather verbose for fixes
  * Maybe use starting tags like [fix] or [bug], etc, so the git history can be scraped to generate a, sorely needed, changelog for this repo

If a middle ground for this can be found I can offer to unfuck the current history of the 1.9.3.x branch.

**Comment by blopa** [comment]
+1 for rebasing

**Comment by tomekjordan** [comment]
I dream about Changelog file...

**Comment by tmotyl** [comment]
I'm all for it. But please also see discussion here https://github.com/OpenMage/magento-lts/issues/155

**Comment by edannenberg** [comment]
@tmotyl I see, this can be closed then.
