### ISSUE TITLE
Customer information missing after 19.5.3 -> 20.5.0 upgrade

### ISSUE THREAD

**Issue by hansgv** [OpenMage/magento-lts#3883]
### Preconditions
- OpenMage 20.5.0 upgraded from 19.5.3
- PHP 8.1.27
- Nginx 1.25.4
- Ubuntu 22.0.4 LTS
- Aurora MySQL 2.10.2 (compatible with MySQL 5.7.40)

### Steps to reproduce
1. Upgraded functioning OpenMage 19.5.3 store to 20.5.0 by downloading and extracting the tar package to site root
2. Cleared Openmage's caches
3. Created a new order as a guest

### Expected result
1. After creating a new order for a new customer, the new customer should be created to `customer_entity` table, be visible under admin UI's Customers > Manage Customers, etc.
4. Customer information should also be visible in orders, etc. Sales > Orders

### Actual result
1. New customers are not created
2. Orders are missing customer details

No errors in PHP error log or Openmage's var/log/system.log or exception.log

On a related note, is it okay to downgrade to 19.5.3 or are there breaking db changes?

**Comment by ADDISON74** [comment]
Until we investigate this bug report, it would be good to go back to a backup that I hope you made before the upgrade.

**Comment by hansgv** [comment]
For what it's worth, downgrading back to 19.5.3 seems to fix the problem.

**Comment by ADDISON74** [comment]
For testing this issue I am using (OpenMage 20.5.0 + Magento Sample Data).

In the **Backend > Sales > Orders** I click on the **[Create New Order]** button. 

In the "Create New Order" page there are two buttons **[Create New Customer]** and **[Create Guest Order]**. I click on the first one. I select the English Store. 

For a new customer named Marlon Brando, I fill in the required fields in the "Billing Address" form, I add a product and select the "Shipping Method".

After I submit the order Mailpit is catching two emails, one for the order and one for the new account.

![mailpit](https://github.com/OpenMage/magento-lts/assets/8360474/175bc6b1-7e03-449c-95d6-cb7d330e90cb)

This is the order confirmation page, you can see the customer name is orange which means it is a link to the new account.

![order](https://github.com/OpenMage/magento-lts/assets/8360474/e6c6e593-38a3-4e8a-ae1d-13b1d9a0d7d9)

If I click the orange name it loads the customer page.

![customer_page](https://github.com/OpenMage/magento-lts/assets/8360474/98047a28-560b-4bc6-b1e5-bce8827b62ae)

This is the confirmation from the table **customer_entity** that the customer was created succesfully.

![customer_entity](https://github.com/OpenMage/magento-lts/assets/8360474/821d8f1d-98be-490e-a2b2-94f0c2ffa5b3)

Unfortunately, after testing, I cannot confirm the reported error.

**Comment by pquerner** [comment]
@ADDISON74 its unclear which PHP version you were running or if you did use the upgrade path (or started with a fresh 20.5.0).

@hansgv Can you add your database information? Anything out of the order? MySQL? Which version? Something in the my.cnf or somewhere else?

**Comment by hansgv** [comment]
My db is Aurora MySQL 2.10.2 (compatible with MySQL 5.7.40).

If there's a scenario I can test, I'm happy to help. My hunch is that the issue is related to the version upgrade path I took.

**Comment by ADDISON74** [comment]
@pquerner - I am using DDEV with any PHP version I want. For this test I used PHP 8.3. 

I didn't do one thing, to look in the OpenMage logs, even Magento Developer Mode was enabled.

**Comment by ADDISON74** [comment]
@hansvg - when I test a report, I do it in an unchanged OpenMage. Always I am using the latest version from its repository. If the issue is confirmed then it must be fixed, if not then we close the case. You did an upgrade, but I can't evaluate what actually happened there, It's just a particular case.

**Comment by fballiano** [comment]
I'm pretty sure this is caused by 3rd party modules, not the core
