### ISSUE TITLE
Customers on online not showing

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#3915]
I recently upgraded to the **OpenMage** **20.5.0** version. After that it effects on the online customers in Admin area.

**Steps to Reproduce:**
Login into a customer account .
Login into admin panel.
    Go to Customers -> Online Customers, here the logged in customer record is not showing.

**Comment by fballiano** [comment]
on my test installation, on the main branch, it works as expected, I had an empty page, then opened the website and my session if showed correctly:

<img width="1225" alt="Screenshot 2024-03-29 alle 12 27 34" src="https://github.com/OpenMage/magento-lts/assets/909743/f479a1f9-06d0-40bc-884d-38c800838cdc">

**Comment by fballiano** [comment]
you've to enable this and it works:

<img width="888" alt="Screenshot 2024-03-29 alle 17 15 32" src="https://github.com/OpenMage/magento-lts/assets/909743/5d7a10d1-2d40-4372-ab13-72b4fe1add32">
