### ISSUE TITLE
In backend, add "click to copy text" feature

### ISSUE THREAD

**Issue by pauldpauld** [OpenMage/magento-lts#3952]
### Description (*)

I transfer new customer details into my accounting program, always using tedious "copy 'n paste", I have noticed that eBay and other websites have a "click to copy" button, or simply, click on a field which copied the text content.

![image](https://github.com/OpenMage/magento-lts/assets/1549372/9b2bda13-12df-47ac-af69-e3ac4e018cb2)

The above is my freight company page with a tracking number, clicking on the graphic copies the tracking number.

### Expected behavior (*)

Clicking on a customer name and/or address fields on the order page will copy that text to the clipboard.

### Benefits

It would make it much quicker and efficient for admin staff to copy many of the customer details (and or product details) if they don't already use a linked method.

### Additional information

Here is a sample from W3schools

```
` Step 1) Add HTML:
Example
The text field
<input type="text" value="Hello World" id="myInput">
<input type="text" value="Hello World" id="myInput">

The button used to copy the text
<button onclick="myFunction()">Copy text</button>
<button onclick="myFunction()">Copy text</button>

 <!-- The text field -->
<input type="text" value="Hello World" id="myInput">

<!-- The button used to copy the text -->
<button onclick="myFunction()">Copy text</button>
```
Step 2) Add JavaScript:
Example
function myFunction() {
  // Get the text field
  var copyText = document.getElementById("myInput");

  // Select the text field
  copyText.select();
  copyText.setSelectionRange(0, 99999); // For mobile devices

   // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.value);

  // Alert the copied text
  alert("Copied the text: " + copyText.value);
} 
`

**Comment by luigifab** [comment]
So good idea! See also #2774.
With Linux you can select any text to copy it :)
