### ISSUE TITLE
Not valid template / Mage_Paypal_Block_Payment_Info

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#396]
Hi, not certain that related to LTS. But did log it here because since recently we started using the Paypal Express button in the cart. And it is clear that Paypal Express was/is not a top priority. Several fixes need to be done. 

Now we see this error in logging. However it is not clear to my why the themplate is being looked for in "base/default" instead of default/default

Not valid template file:adminhtml/base/default/template/payment/info/pdf/default.phtml class: Mage_Paypal_Block_Payment_Info

**Comment by colinmollenhour** [comment]
I don't know anything about the Paypal modules, but perhaps the code did not set the correct "area" (frontend vs adminhtml)?

**Comment by sreichel** [comment]
Used default template w/o problems ...

I'd close to do some cleanup. Please reopen if its still an issue.
