### ISSUE TITLE
Admin filters and sorting not working after upgrader to v20.6.0 and v20.7.0

### ISSUE THREAD

**Issue by starnetwork** [OpenMage/magento-lts#3993]
### Preconditions (*)

1. OpenMage v20.7.0

### Steps to reproduce (*)

1. Login to admin, go to products and try to sort by Type / SKU or price

### Expected result (*)

1. sort should be changed by selected value, nothing happen

### Actual result (*)

1. sort of products should be changed by selected value, nothing happen
![Screenshot 2024-05-14 115552](https://github.com/OpenMage/magento-lts/assets/626945/5850b975-714e-4d10-a132-c1f93e6b25d2)

**Comment by fballiano** [comment]
was fixed by https://github.com/OpenMage/magento-lts/pull/3985 will we released in a few days
