### ISSUE TITLE
Edit attributes broken?

### ISSUE THREAD

**Issue by F1Red5** [OpenMage/magento-lts#3996]
### Preconditions (*)

1. OM latest version
2. PHP 7.4
3. Sample Data pack installed

### Steps to reproduce (*)

1. Go to admin panel, "Manage Attributes"
2. Select "Size" attribute, go to Labels/Options

### Expected result (*)

1. normal attribute edit page

### Actual result (*)

1. every option has a black square to select a color
2. same with "Color", "Shoe Size" attribute and others, but not for all

![Screenshot 2024-05-15 at 01-55-27 size _ Manage Attributes _ Attributes _ Catalog _ OpenMage Admin](https://github.com/OpenMage/magento-lts/assets/169857363/f460bd45-765c-44f2-9cbd-ed3a8aa361e6)

What it is is for?
Why have a color picker on size attributes?
Why everything is black? Even on "Color" Attribute.

**Comment by fballiano** [comment]
it's the new swatches enhanced, check the release notes https://github.com/OpenMage/magento-lts/releases/tag/v20.7.0 and the original PR

it's enabled for all swatches attributes and that square is black because it's the default for input type color

right @empiricompany?

**Comment by empiricompany** [comment]
Yes, and it seems from the screen that the CSS hasn't been properly updated.

**Comment by fballiano** [comment]
right, I didn't notice that cause I'm on a slow connection today, @F1Red5 probably just need a hard refresh of your browser's cache

**Comment by fballiano** [comment]
@F1Red5 it should look like this

<img width="614" alt="Screenshot 2024-05-15 alle 10 49 37" src="https://github.com/OpenMage/magento-lts/assets/909743/b1ab6c5e-1faf-445d-b154-0cacd73f8eea">
