### ISSUE TITLE
After upgrade to v20.7.0 I got some alert on Admin Login

### ISSUE THREAD

**Issue by starnetwork** [OpenMage/magento-lts#4007]
### Preconditions (*)

1. 20.7.0

### Steps to reproduce (*)

1. Login to Magento LTS Admin, click on Clicking here inside the alert box and getting Orphaned Role Resources empty page without any Roles.

### Expected result (*)

1. that magento admin will not show this alert.

### Actual result (*)

1. Attaching Screenshot of the error on admin login
2. Attaching screenshot of the error on "Clicking here"

![Screenshot 2024-05-23 132619](https://github.com/OpenMage/magento-lts/assets/626945/827134cf-a64b-43da-bf51-965c0323638b)
![Screenshot 2024-05-23 132647](https://github.com/OpenMage/magento-lts/assets/626945/f99e1632-3844-44e6-b05a-0ddca937490f)

**Comment by fballiano** [comment]
you see the alert but then when you click there's the "no records"? really weird

@kiatng what do you think?

btw this is the original PR https://github.com/OpenMage/magento-lts/pull/3647

**Comment by hirale** [comment]
confirmed.

**Comment by fballiano** [comment]
@kiatng true, it happens only right after login, if you refresh the alert disappears

**Comment by starnetwork** [comment]
@fballiano 
true, refresh and the alert disappears but it's back every time any admin do login again and again

**Comment by fballiano** [comment]
I know, but it was important to tell that to the original author of the PR for debug

**Comment by kiatng** [comment]
I did a test on the latest next branch:

adminhtml.xml, add a Test resource:
```xml
<config>
    <acl>
        <resources>
            <admin>
                <children>
                    <celera_crib translate="label" module="crib">
                        <title>Celera Modules</title>
                        <children>
                            <crib translate="title">
                                <title>Crib Services</title>
                                <sort_order>1000</sort_order>
                            </crib>
                            <test translate="title">
                                <title>Test</title>
                                <sort_order>1100</sort_order>
                            </test>
                        </children>
                    </celera_crib>
```

Then in backend > System > Roles > select a role and toggle the checkbox of the resource  > Save

![image](https://github.com/OpenMage/magento-lts/assets/1106470/be3c1002-8d00-464e-82d8-79ea3966d028)

Logout from backend.

Changed resource now to Test2 in adminhtml.xml 
```xml
                            <test2 translate="title">
                                <title>Test2</title>
                                <sort_order>1100</sort_order>
                            </test2>
```

Login to backend, notice of orphaned resource Test:

![image](https://github.com/OpenMage/magento-lts/assets/1106470/027ea194-5f4e-4516-a3b9-7f6447a5bcbc)

Click on the link, the orphaned resource is listed:

![image](https://github.com/OpenMage/magento-lts/assets/1106470/86756a4e-9c66-4990-8b07-1b044de5ab2e)

I do not know why the grid can be empty. I will think about it.

**Comment by kiatng** [comment]
@fballiano Could it be cache? Can you try refresh it?

**Comment by fballiano** [comment]
@kiatng no it's been reset many times

**Comment by kiatng** [comment]
@fballiano Need your help: what is the output array of `Mage::getModel('admin/roles')->getResourcesList2D();`? Do you see orphaned resources such as `admin/storepickup/holidays/action` listed in the array?

**Comment by fballiano** [comment]
yes there are:

<img width="398" alt="Screenshot 2024-05-27 alle 11 22 05" src="https://github.com/OpenMage/magento-lts/assets/909743/4089fdd2-c15a-4be0-9e03-26280ba3422f">

**Comment by JonLaliberte** [comment]
Just wanted to confirm the problem as well. 
After requesting a delete of ~30 orphaned roles, a message came up saying it deleted ~150. That's always scary.
Logged out, back in and the message came back, but the table is empty now.

**Comment by kiatng** [comment]
With @fballiano help, I finally managed to replicate the bug. Please allow a few days to find the cause.

The bug is that the notice about orphaned resources is wrong. However, I think the empty grid is correct, so there is no danger of wrongly deleting resources.

**Comment by kiatng** [comment]
The cause is actually an additional `<action>` node in the `adminhtml.xml` file:

```xml
<config>
    <!-- ... -->
    <acl> <!-- UNDER THIS ACL NODE -->
         <resources>
              <admin>
                <children>
                    <storepickup module="storepickup" translate="title">
                        <title>Store Pickup</title>
                        <sort_order>70</sort_order>
                        <children>
                            <stores module="storepickup" translate="title">
                                <title>Manage Stores</title>
                                <sort_order>0</sort_order>
                                <action>storepickup/adminhtml_store</action> <!-- REMOVE THIS LINE -->
                            </stores>
  ```
The `<action>` node is for assigning a menu item to a controller action. It should not be in the ACL.   

@fballiano Please test by removing all `<action>` nodes under `<acl>`, refresh the cache, and see if the orphaned resource notice is rendered.
