### ISSUE TITLE
Fatal error after upgrading from 20.1.1 to 20.8 when clearing cache from Admin Page

### ISSUE THREAD

**Issue by samex** [OpenMage/magento-lts#4018]
**After upgrading OpenMage from version 20.1.1 to 20.8, I encountered a fatal error when attempting to clear the cache from the Admin Page.** 

### Environment:
1. OpenMage 20.8
2. PHP Version 7.4.28, Apache, MariaDB

### Reproduce
1. Update OpenMage from version 20.1.1 to 20.8.
2. Flush the cache from the admin page.

### Expected
1. Cache should be cleared without errors.
2. Website should function correctly.

### Actual result
1. Error message is displayed on any page:
```
Fatal error:  Uncaught Error: Call to undefined method Mage_Core_Model_Config::getCacheSaveLock() in /app/htdocs/app/code/core/Mage/Core/Model/App.php:436
Stack trace:
#0 /app/htdocs/app/code/core/Mage/Core/Model/App.php(347): Mage_Core_Model_App->_initModules()
# 1 /app/htdocs/app/Mage.php(761): Mage_Core_Model_App->run(Array)
# 2 /app/htdocs/index.php(56): Mage::run('', 'store')
# 3 {main}

Next Error: Call to undefined method Mage_Core_Model_Config::releaseCacheSaveLock() in /app/htdocs/app/code/core/Mage/Core/Model/App.php:449
Stack trace:
#0 /app/htdocs/app/code/core/Mage/Core/Model/App.php(347): Mage_Core_Model_App->_initModules()
#1 /app/htdocs/app/Mage.php(761): Mage_Core_Model_App->run(Array)
#2 /app/htdocs/index.php(56): Mage::run('', 'store')
#3 {main}
  thrown in /app/htdocs/app/code/core/Mage/Core/Model/App.php on line 449
```
Workaround: 

**If the cache is flushed from CLI, the site works correctly, but clearing the cache from the admin page results in the above error.**

I have tried using PHP 8.2, but encountered numerous errors with third-party modules that need to be resolved. PHP 7.4 still seems to work for now.

**Comment by fballiano** [comment]
I can't reproduce the error on a fresh install

<img width="1374" alt="Screenshot 2024-05-28 alle 09 29 48" src="https://github.com/OpenMage/magento-lts/assets/909743/174be906-1022-455e-a4b9-ca3db8266042">

the method is in the correct file

<img width="685" alt="Screenshot 2024-05-28 alle 09 30 51" src="https://github.com/OpenMage/magento-lts/assets/909743/d8312533-b987-4542-b27d-2249f76a9ed5">

do you have something in app/code/local/Mage overriding core files?

**Comment by samex** [comment]
Thank you for your quick and accurate response. Indeed, I had core files in the code/local directory. I deleted them, and now it is working as expected. Thanks again!
