### ISSUE TITLE
Error when saving product with image without description

### ISSUE THREAD

**Issue by MateusM3** [OpenMage/magento-lts#4023]
### Preconditions (*)

1. OpenMage 20.8.0
2. PHP 8.2

### Steps to reproduce (*)

1. Open the Catalog -> Create Product -> Upload Images -> with out description (label) -> Save

### Expected result (*)

1. Saving the product with an empty label like previous versions, may be the version of PHP that is more careful regarding the array key not existing

### Actual result (*)

![error-img-default](https://github.com/OpenMage/magento-lts/assets/20692202/7a8f4323-2563-480b-9146-aedcc9e60fbd)

**Comment by fballiano** [comment]
@MateusM3 can you test https://github.com/OpenMage/magento-lts/pull/4024?

**Comment by MateusM3** [comment]
Thaks @fballiano ! But Its was partially corrected, still with the error on line 170, I corrected it as follows, taking your correction as an example
![image](https://github.com/OpenMage/magento-lts/assets/20692202/ed4a1727-730a-4dfd-ab7c-9c6ccb63104a)

Can you update your Pull request with this correction too?

**Comment by kiatng** [comment]
I cannot reproduce the error on ver21 beta2.

**Comment by fballiano** [comment]
@kiatng on v21 I see the same error, did you enable developer mode there too?

**Comment by fballiano** [comment]
@MateusM3 how do you trigger the error you see on line 170? I can't reproduce it with my patch #4024

**Comment by MateusM3** [comment]
@fballiano I tested it here and it worked, thank you!
Would it be possible to release a version 20.9.1 with this fix? I wanted to update here about having to overwrite the class

**Comment by sreichel** [comment]
@all-contributors add @MateusM3 bug
