### ISSUE TITLE
N98-magerun tests fails since #2993

### ISSUE THREAD

**Issue by F1Red5** [OpenMage/magento-lts#4034]
Currently working on N98-magerun with latest releases.

Since #2993 (v20.1.0) some unit tests fail.

- see https://github.com/netz98/n98-magerun/pull/1430
- see https://github.com/netz98/n98-magerun/actions/runs/9426609489/job/25969713460?pr=1430

Before this PR tests run w/o errors/failures.

- see https://github.com/netz98/n98-magerun/actions/runs/9426014476/job/25968412182

@davidhiendl can you please re-check your code?

Additional note:

- php7.4 ... 11 failures
- php8.x ... 4 errors, 7 failures

**Comment by davidhiendl** [comment]
@fballiano Sorry for not getting around to it sooner. Is this resolved? From the PR https://github.com/OpenMage/magento-lts/pull/4036 it looks like `getDefaultAttributes` was blacklisted from tests for some reason hence why it was not caught before. What is weird to me is how that method can be missing in those circumstances and that it requires a (in my opinion) somewhat not nice is-defined check.

**Comment by fballiano** [comment]
I merged the related PR. since we can't control the development of magerun unless we have specific issues I think we can close this one.
