### ISSUE TITLE
[Backend Navbar] Empty spaces in the classes

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#4091]
Analyzing the source code of the Backend page, I found that in the navigation bar there are empty spaces in some classes and not in others. The problem does not come from the PHTML template.

![screenshot](https://github.com/OpenMage/magento-lts/assets/8360474/25899ac7-2910-4b9a-9889-6e731085a0c8)

It is a legacy from Magento. I confirmed it in production in a store based on v1.9.4.5.

**Comment by kiatng** [comment]
According to [stackoverflow](https://stackoverflow.com/questions/21439859/html5-compliant-trailing-space-in-class-attribute) referencing the various docs, it is valid to have leading and trailing spaces in class names.

**Comment by ADDISON74** [comment]
Thank you @kiatng. From what I can see, those discussions are from 10 years ago.

Do you have any idea what would be the reason why the Magento team chose to use leading spaces? Could be a good idea to remove them just for visual effect?

**Comment by fballiano** [comment]
it's just because in the templates there's gonna be something like

`class="<?php if (aaa) echo aaaa ?> <?php if(something) echo bbb ?> anotherclass"` which leads to those situations.

it's absolutely normal

**Comment by kiatng** [comment]
As pointed by @fballiano, less clutter in the code.

**Comment by ADDISON74** [comment]
Considering that it is not an issue in the source code, I close the report.
