### ISSUE TITLE
Zip-Release 20.10.0 incomplete or too many items?

### ISSUE THREAD

**Issue by alexh-swdev** [OpenMage/magento-lts#4093]
### Preconditions (*)
1. Downlaod the 20.10.0 release zip
2. deploy

### Steps to reproduce (*)

1. Call a product page 

### Expected result (*)

1. No errors, warning, log entries

### Actual result (*)

1. log entry about missing page-cache files
![grafik](https://github.com/user-attachments/assets/bdaaccce-6eea-433b-b069-73b44c678108)

In our current live installation as well as in my clean "Upgarde repo", there was no Page-Cache module.
In the magento-lts github, there is also no Page-Cache module
But in the releas zip, there it is:
![grafik](https://github.com/user-attachments/assets/2f8a9b17-cdcb-497d-b0bd-4248b6174873)

Is this on purpose? If so, are there missing files?

There are also community plugins in the zip file (Cm/Cache and Cm/RedisSession) which are not on github. Are those also supposed to be there?

**Comment by ADDISON74** [comment]
PageCache shouldn't be there, that module was removed from /app/code/core/Mage some time ago. The ZIP archive contains also the full vendor directory, like you ran the ``composer install`` command. @fballiano will provide you more information related to this version.

**Comment by alexh-swdev** [comment]
The vendor directory is fine. That's what the openmage-vX.Y.Z.zip exists, additionally to source archives. But something seemed to have gone wrong with the rest.

**Comment by fballiano** [comment]
sorry for the late answer, If I remember correctly those modules are still bundles in OM v19, but they are removed from OM v20

**Comment by sreichel** [comment]
PageCache should not be there at all, but thats no the problem ...

The template files is not copied to app/design/frontend ...

> There are also community plugins in the zip file (Cm/Cache and Cm/RedisSession) which are not on github. Are those also supposed to be there?

Yes. This should be there.

**Comment by sreichel** [comment]
Close it.

With the next release all files should be there.
