### ISSUE TITLE
Dataflow export error

### ISSUE THREAD

**Issue by urbancrew** [OpenMage/magento-lts#410]
Hi,
every time I use Dataflow to export products I get a whole bunch of rows in system.log. it says:
`ERR (3): Notice: Undefined index: website  in /app/code/core/Mage/Catalog/Model/Convert/Parser/Product.php on line 510`

So when i look on line 510 it says 'website' and follow up on $row I see it says 'websites' instead of 'website'. When I changed that then it worked fine. Typo?

So it just needs to be changed from 'websites' to 'website' on rows 423, 436 and 438 in /app/code/core/Mage/Catalog/Model/Convert/Parser/Product.php

Not sure if this is something that should be changed in this magento-lts as standard?

**Comment by tmotyl** [comment]
sure, please send us a PR

**Comment by theroch** [comment]
This issue can be closed, fixed in [2795f046] by dvdsndr <davids@swann.com> on 30.07.2017 at 10:47

**Comment by sreichel** [comment]
Fixed in https://github.com/OpenMage/magento-lts/pull/325
