### ISSUE TITLE
Missing translation new order mail

### ISSUE THREAD

**Issue by empiricompany** [OpenMage/magento-lts#4101]
I can't find any translation for:
"Items in your order"
"Item in your order"

Used in sales new order mail product list:
https://github.com/OpenMage/magento-lts/blob/fae22f59f95d4a8066eea6eb8aa7d8cfa94dcac7/app/design/frontend/rwd/default/template/email/order/items.phtml#L29

**Comment by ADDISON74** [comment]
I confirm this issue. Searching the whole code there are no references for them.

@empiricompany - Do you want me to add them to Mage_Sales.csv or you want to create the PR?

**Comment by ADDISON74** [comment]
I ask those who have administrative rights to link this issue to PR #4106. I can't do it anymore. Thank you.
