### ISSUE TITLE
Shouldn't the PHP requirement be raised to 5.4?

### ISSUE THREAD

**Issue by barbazul** [OpenMage/magento-lts#412]
Magento 1.9.x officially supports only 5.4, 5.5 and 5.6 http://docs.magento.com/m1/ce/user_guide/magento/system-requirements.html

Current composer.json file requires PHP >= 5.2.13

Magento clearly would not work on PHP 5.2 nor there should be anyone out there still using 5.2

**Comment by alcipir** [comment]
Definitely, is there any reason not to raise the required version on the composer file?

**Comment by barbazul** [comment]
I dare say we should raise it to 5.6 since 5.4 and 5.5 are no longer supported by PHP, but that's another story

**Comment by alcipir** [comment]
And why not 7? Seriously, the performance gains are enormous, I really wanted to know the rationale behind still supporting PHP 5.6

**Comment by colinmollenhour** [comment]
Technically there are commercial organizations supporting PHP 5.4 and up. For example Debian 7 is EOL in May 2018 and uses PHP 5.4 and Ubuntu 14.04 LTS is EOL in April 2019 and uses PHP 5.5. I think CentOS 6 is still supporting PHP 5.3. I don't recommend running any of these but just because the official PHP ends support doesn't mean that support has completely ended across the board.

However, I would also consider this project to be more of a "power-user" derivative and think that dropping support for old versions and even making PHP 7 the minimum would not be unreasonable. As @alcipir said PHP 7 is so much faster that running on 5.x is basically inexcusable. Also with Docker now it is a piece of cake to run the latest version of PHP on just about any machine (as long as it is 64bit and not too old of a kernel).

**Comment by barbazul** [comment]
To raise the requirement to 7 would mean to also include the corresponding compatibility fixes which might fall a little outside of this project scope, but you would definitely not hear any complaints from me if this happens

**Comment by sreichel** [comment]
> To raise the requirement to 7 would mean to also include the corresponding compatibility fixes which might fall a little outside of this project scope,

PHP7 fixes are in since 1.9.2.x.

Does it makes sense (are there any advantages?) to raise min. requrierment. Current code also works with 5.3 ... IMHO, this is only required, when/**if** we start adding features like Aoe_Layout code that requires 5.5+.

**Comment by colinmollenhour** [comment]
The advantages would be that we would have less backwards compatibility to worry about going forward, we could use new things like `??` operator, `array_column` (5.5+), etc. I don't think we should try to adopt things like traits that are core design features or go back and rewrite tons of code to use these new features, just allow the use of the little improvements going forward.

**Comment by barbazul** [comment]
I think 5.3 should be deprecated, no questions asked. Magento officially does not support that version, then this open fork should not support it either (since there is also no real benefit or reason for doing so).

Raising it above 5.4 (the official Magento minimum) is a matter that does deserve further discussion. My position is that there is benefit in not having to support really old versions of PHP and also raising awareness about not running an ecommerce solution in unsupported, unmaintained, unsecure platforms.

That said, I would not raise the minimum above 5.6 under any circumstance.

**Comment by colinmollenhour** [comment]
So there are some objections to 7 being the minimum. Just to put this at rest for now (will eventually take care of itself as more versions hit EOL) I suggest as a compromise we set PHP 5.5.9 as the minimum (while it is EOL, it is supported by Ubuntu 14.04 LTS which could still be in widespread use).

So any objection to this?

    "php": ">=5.5.9",

**Comment by barbazul** [comment]
Sounds about right

**Comment by lfluvisotto** [comment]
http://php.net/supported-versions.php

PHP >= 5.5

**Comment by corbinu** [comment]
@colinmollenhour given 14.04 EOF I would say raise it to 5.5.9 now. Then in April raise it to 7.0 since thats the version in Ubuntu 16.04

**Comment by sreichel** [comment]
PHP5.6 is EOL since beginning of this you ... so i'd raise minimumrequirements to PHP7 at least.
