### ISSUE TITLE
Error when saving product with image without description

### ISSUE THREAD

**Issue by MateusM3** [OpenMage/magento-lts#4134]
The problem continues to occur, i noticed that it was fixed in the issue #4023 but, in the current version  20.10.2 it continues to happen

**Preconditions (*)**
OpenMage 20.10.2
PHP 8.2

**Steps to reproduce (*)**
Open the Catalog -> Create Product -> Upload Images -> with out description (label) -> Save

**Expected result (*)**
Saving the product with an empty label like previous versions, may be the version of PHP that is more careful regarding the array key not existing

**### Actual result (*)**

![image](https://github.com/user-attachments/assets/d070f967-8a42-4fac-b940-4d9923d1dde1)

**Comment by empiricompany** [comment]
i cannot reproduce this issues

![result](https://github.com/user-attachments/assets/e08fcd12-aac7-4bcf-be1c-22a6683163fa)


on latest OpenMage 10.10.2 / php 8.2

devmode is enabled and error level is setted to debug
![devmode](https://github.com/user-attachments/assets/5c4e58ce-08e5-4c19-83b2-70a472ce26e4)

![devmode](https://github.com/user-attachments/assets/273949d4-c75b-41da-989e-f94c33476ed4)

![devmode2](https://github.com/user-attachments/assets/251c5361-1a43-43ec-911f-ee78d2825f7c)

**Comment by empiricompany** [comment]
Here you said the patch had fixed the problem https://github.com/OpenMage/magento-lts/issues/4023#issuecomment-2150111650

`Mage_Catalog_Model_Product_Attribute_Backend_Media` contains the patch?
https://github.com/OpenMage/magento-lts/pull/4024/files

i see in your composer update you have a package named `k13/overwrite_customer_module_openmage`
maybe this rewrite the class?

**Comment by MateusM3** [comment]
It's not working here, about the module this module is private to another function, I'm debugging here and it enters the normal core class

One thing I noticed that you're doing differently is not selecting the "base image", "small image" and "thumb"

**Comment by empiricompany** [comment]
> It's not working here, about the module this module is private to another function, I'm debugging here and it enters the normal core class
> 
> One thing I noticed that you're doing differently is not selecting the "base image", "small image" and "thumb"

I think I also tried selecting the image as you say, but I'll try tomorrow better by making sure I do it

Have you checked if the class is updated correctly with the patch?

**Comment by sreichel** [comment]
Looks like 3rd-party code. Please share a stacktrace ...

**Comment by empiricompany** [comment]
@MateusM3 please review the patch in this PR https://github.com/OpenMage/magento-lts/pull/4136 if works for you

**Comment by sreichel** [comment]
@all-contributors add @MateusM3 bug
