### ISSUE TITLE
Main branch does not correspond to the release tag 20.10.2

### ISSUE THREAD

**Issue by empiricompany** [OpenMage/magento-lts#4135]
I am working on the main repository and the version is not being updated. Am I missing something?

Is this commit https://github.com/OpenMage/magento-lts/commit/890929fdbfb3fd0ad53ce761ef140a0bcb910c26 missing? How is that possible?
https://github.com/OpenMage/magento-lts/compare/v20.10.1...v20.10.2

https://github.com/OpenMage/magento-lts/blob/cabdc8bedb434c698c316ddbc6fe9c314c387fa7/app/Mage.php#L217

**Comment by sreichel** [comment]
Confirmed ...

- `composer require openmage/magento-lts:dev-main` (wrong)
- `composer require openmage/magento-lts:20.10.2` (correct)

**Comment by elidrissidev** [comment]
Maybe he created the tag locally and pushed it but didn't push the `main` branch? is that even possible? that's my only guess.

**Comment by Flyingmana** [comment]
`git fetch origin v20.10.2 -t`
`gitk origin v20.10.2`

![image](https://github.com/user-attachments/assets/87d8ca83-26b4-4f04-b4cf-921dcfb82e7c)

https://github.com/OpenMage/magento-lts/actions/runs/10125134246

![image](https://github.com/user-attachments/assets/e71c768d-1c32-44b9-b16b-7a36792018a1)


I created a patch branch `patch-v20.10.x`, as I wanted to avoid taking in any other new commits for just a fixup release.
I also did not see a reason to merge this change into main https://github.com/OpenMage/magento-lts/commit/890929fdbfb3fd0ad53ce761ef140a0bcb910c26 as this will only get overwritten anyway

I was not the one deleting this branch, but maybe the person who did can explain themselves.


I hope this answers all questions.

**Comment by sreichel** [comment]
The deletion of that branch is irrelevant. This issue is caused by not have it merged into main.

To "explain myself" .. last year we removed all non-release branches (exscluding functionals tests) for [housekeeping](https://github.com/OpenMage/magento-lts/discussions/3277) and disallowed to create new ones. With the 20.10.2 release that branch was obsolete.

**Comment by sreichel** [comment]
@all-contributors add @empiricompany  bug
