### ISSUE TITLE
Unable to get children categories when use the option "Use Flat Catalog Category" set to "Yes"

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#4191]
Steps to reproduce

Login as admin
Go To "System" -> "Configuration" -> "Catalog" -> "Frontend" -> "Use Flat Catalog Category" and please set to "Yes".
Reindex the "Category Flat Data" option and try to run the below code.

`$childCategories = Mage::getModel('catalog/category')->load($anyCatID)->getChildrenCategories()`

It will not give any child categories and if you change the above option to "No" you will get all the sub-categories;

**Comment by sreichel** [comment]
Note for me ... https://magento.stackexchange.com/a/58450/46249

I'll test it later.

**Comment by sreichel** [comment]
Can you provide a pull request?

**Comment by sreichel** [comment]
It seems to be default/normal behavoir.

Suggestion: Enable Flat

**Comment by sreichel** [comment]
Closed.

Feel free to add a PR, but i think it works as it should.
