### ISSUE TITLE
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Credis_Client' not found in httpdocs/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php

### ISSUE THREAD

**Issue by matteotestoni** [OpenMage/magento-lts#4224]
### Preconditions (*)

1. 20.*
2. migration from 19.5.3 to 20.*

### Steps to reproduce (*)

1. in composer.json change "openmage/magento-lts": "19.5.*", to "openmage/magento-lts": "20.*.*",
2. /opt/plesk/php/7.4/bin/php -d memory_limit=-1 composer.phar update
3. rm -rf app/code/core/Zend lib/Cm lib/Credis lib/mcryptcompat lib/Pelago lib/phpseclib lib/Zend

### Expected result (*)

1. openmage works
2.

### Actual result (*)

1. Error 500
2.

**Comment by sreichel** [comment]
Please check if the class exists in

> vendor/colinmollenhour/credis/Client.php

**Comment by matteotestoni** [comment]
vendor/colinmollenhour/credis/Client.php - present - 62530Bytes 

this is my composer.json

{
    "name": "rswstudio/solemar",
    "require": {
        "aydin-hassan/magento-core-composer-installer": "*",
        "openmage/magento-lts": "20.1.*",
        "fballiano/openmage-cloudflare-turnstile": "^0.4.0",
        "colinmollenhour/cache-backend-redis": "^1.14",
        "colinmollenhour/magento-redis-session": "^3.2.0"  
    },
    "extra": {
        "magento-core-package-type": "magento-source",
        "magento-root-dir": ".", 
		"magento-core-deploy" : {
			"excludes": [ 
				".htaccess",
				"app/etc/local.xml"
			],
			"ignore-directories": [
				"lib/Zend"
			],
			"git-ignore-append": false
		}
	},
    "config": {
        "allow-plugins": {
            "cweagans/composer-patches": true,
            "aydin-hassan/magento-core-composer-installer": true,
            "magento-hackathon/magento-composer-installer": true
        }
    }
}

**Comment by sreichel** [comment]
Ahh, okay ... composer install ... then ignore my last comment. You dont need it in your composer.json.

I'd remove vendor  directy and run composer install again.

**Comment by matteotestoni** [comment]
my new composer.json
{
    "name": "rswstudio/solemar",
    "require": {
        "aydin-hassan/magento-core-composer-installer": "*",
        "openmage/magento-lts": "20.1.*",
        "fballiano/openmage-cloudflare-turnstile": "^0.4.0"
    },
    "extra": {
        "magento-core-package-type": "magento-source",
        "magento-root-dir": ".", 
		"magento-core-deploy" : {
			"excludes": [ 
				".htaccess",
				"app/etc/local.xml"
			],
			"ignore-directories": [
				"lib/Zend"
			],
			"git-ignore-append": false
		}
	},
    "config": {
        "allow-plugins": {
            "cweagans/composer-patches": true,
            "aydin-hassan/magento-core-composer-installer": true,
            "magento-hackathon/magento-composer-installer": true
        }
    }
}

composer install
(deleted some existing files... 
 app/code/community/Cm/Cache/Backend/Redis.php already exists and is not a symlink (set extra.magento-force to override)
app/code/community/Cm/RedisSession already exists

and nothing

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Zend_Cache_Backend' not found in [/httpdocs/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fvendor%2Fcolinmollenhour%2Fcache-backend-redis%2FCm%2FCache%2FBackend&subscriptionId=1&file=Redis.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1):39\nStack trace:\n#0 [/httpdocs/lib/Varien/Autoload.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Flib%2FVarien&subscriptionId=1&file=Autoload.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(58): include()\n#1 [internal function]: Varien_Autoload->autoload()\n#2 [internal function]: spl_autoload_call()\n#3 /httpdocs/app/code/core/Mage/Core/Model/Cache.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp%2Fcode%2Fcore%2FMage%2FCore%2FModel&subscriptionId=1&file=Cache.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(202): class_exists()\n#4 [/httpdocs/app/code/core/Mage/Core/Model/Cache.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp%2Fcode%2Fcore%2FMage%2FCore%2FModel&subscriptionId=1&file=Cache.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(122): Mage_Core_Model_Cache->_getBackendOptions()\n#5 [/httpdocs/app/code/core/Mage/Core/Model/Config.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp%2Fcode%2Fcore%2FMage%2FCore%2FModel&subscriptionId=1&file=Config.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(1440): Mage_Core_Model_Cache->__construct()\n#6 [/httpdocs/app/Mage.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp&subscriptionId=1&file=Mage.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(524): Mage_Core_Model_Config->getModelInstance()\n#7 [/httpdocs/app/code/core/Mage/Core/Model/App.php](/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp%2Fcode%2Fcore%2FMage%2FCore%2FModel&subscriptionId=1&file=App.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1)(422): Mage::getModel()\n#8 /httpdocs/app/code/core/Mage/Core/Mode...'

**Comment by matteotestoni** [comment]
something with htaccess?

**Comment by sreichel** [comment]
Now Zend_Cache_Backend is not found ...

> app/code/community/Cm/Cache/Backend/Redis.php already exists and is not a symlink

Remove it ... it will be installed via composer.

Try `composer dump-autload`.

(will try to help later ... away for some hours)

**Comment by matteotestoni** [comment]
there was a vendor folder outside the root and after deleted site start working
Same in another site

**Comment by matteotestoni** [comment]
$autoloaderPath = getenv('COMPOSER_VENDOR_PATH');
Where is set this environment variable called in mage.php?
because in another site search vendor outside openmage folder

**Comment by sreichel** [comment]
You can add this to your composer.json

```
    "config": {
        "vendor-dir": "/path/to/vendors"
    },
```
