### ISSUE TITLE
Override/remove nodes in system.xml

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#431]
Not sure to make a PR ...

It's possible to override nodes and set cutom value, but it's not possible to set nodes value to emtpy/null.

I wanted to disable an existing backend model (same for other nodes) like

    <fields>
        <some_field>
            <backend_model />

... but this throws an exception in `Mage_Adminhtml_Block_System_Config_Form::initFields()`

    if ($element->backend_model) {
        $model = Mage::getModel((string)$element->backend_model);
        if (!$model instanceof Mage_Core_Model_Config_Data) {
            Mage::throwException('Invalid config field backend model: '.(string)$element->backend_model);
        }

Why not 

    if ($element->backend_model && (string)$element->backend_model) {

or

    $backendModel = (string)$element->backend_model;
    if (!empty($backendModel)) {

At the momet you have to add your own empty model.

**Comment by colinmollenhour** [comment]
What about just overriding the backend_model to be the parent class commonly extended for new backend models? e.g.

    <backend_model>core/config_data</backend_model>

**Comment by sreichel** [comment]
This was to easy :P
