### ISSUE TITLE
[PHP 8.4] Deprecated functionality: strcasecmp(): Passing null to parameter #2 ($string2) of type string is deprecated

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#4314]
**This is the error message** 

Deprecated functionality: strcasecmp(): Passing null to parameter #2 ($string2) of type string is deprecated  in /var/www/html/app/code/core/Mage/Eav/Model/Entity/Attribute/Source/Abstract.php on line 88

```php
/**
     * @param string $value
     * @return string|null
     */
    public function getOptionId($value)
    {
        $bc_warning = false;
        foreach ($this->getAllOptions() as $option) {
            if (strcasecmp($option['label'], $value) == 0) { <= THIS IS THE LINE
                return $option['value'];
            }
            if ($option['value'] == $value) {
                $bc_warning = true;
            }
        }
```

I am getting this error when running extension MageWorx SEO Suite Ultimate. Just accesss the Frontend.

It must be

```php
 if (strcasecmp($option['label'], $value ?? '') == 0) {
```

**Comment by sreichel** [comment]
Maybe it should be fixed in the extension?

**Comment by ADDISON74** [comment]
It can be fixed in the extension, but it was not necessary as long as the PHP version was lower than 8. When I switched to the new versions with Openmage, the error also appeared. Other extensions may also generate this error. It seems to be fixed with OpenMage. I also found errors in the extension, but I fixed them there.

**Comment by sreichel** [comment]
> Other extensions may also

... have bad code. ;)

Compare null to `$option['label']` makes no sense. Better check fur null before.
