### ISSUE TITLE
[PHP 8.x] Deprecated functionality: strtotime(): Passing null to parameter #1 ($datetime)

### ISSUE THREAD

**Issue by addison74** [OpenMage/magento-lts#4338]
**[Test Environment]**

Windows 11 + WSL
Docker 4.34.4
DDEV 1.2.5 (Apache 2.4.62, PHP 8.4.ORC1, MariaDB 10.11.9) with MAGE_IS_DEVELOPER_MODE=1
Magento Sample Data

**Steps to reproduce this issue**

Go to **Backend** > **Catalog** > **Manage Products**
Edit any product from the grid
Add Related/Cross/Up sells to the product then Save

The product changes are saved but you will see this error message

```
Deprecated functionality: strtotime(): Passing null to parameter #1 ($datetime)
of type string is deprecated in 
/var/www/html/app/code/core/Mage/CatalogRule/Model/Resource/Rule.php on line 187
```

![datetime](https://github.com/user-attachments/assets/a9a884f3-66b3-4a8c-afb3-c0176cc675e2)

**Comment by sreichel** [comment]
@all-contributors add @addison74 bug
