### ISSUE TITLE
Scope label is misaligned.

### ISSUE THREAD

**Issue by dev-venkatesh** [OpenMage/magento-lts#4355]
Steps to reproduce.

Go To -> System -> Configuration and see any option, the scope label is misaligned.

![scope-label](https://github.com/user-attachments/assets/07bc8769-c536-4fed-b5af-30ff48dbca62)

**Comment by sreichel** [comment]
Whats wrong with the alignment to top of the input-field?

We should not put it in the middle (espacially not for textareas, multiselects etc)

**Comment by addison74** [comment]
On the one hand, the texts on the left are aligned vertically at the top, as are the others from the right. There is a symmetry that is beneficial to the eye, especially for text areas having big heights. The same implementation is found in the legacy theme.

If you have solid arguments to change, you can propose a PR. Until then I will close this report.
