### ISSUE TITLE
Complete permissions

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#437]
There are some admin grids with mass-action dropdown, but only some are covered by ACL settings ...

E.g. sales order grid ... every mass action has its own ACL settings

- https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/Block/Sales/Order/Grid.php#L158

- https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php#L660

.. but this i missing for other grid like manage products/customers.

**Proposal**

Add ACL settings for every mass action.

**Comment by elidrissidev** [comment]
I'm interested to work on this issue, but I'd like to gather some opinions first. Since adding new permissions will require the store admin to explicitly grant them to the users that need them, should we consider this to be a breaking change?

**Comment by luigifab** [comment]
I think this is not a problem.

**Comment by elidrissidev** [comment]
Ok, I will create a PR for `1.9.4.x`.
