### ISSUE TITLE
Should i use magento-lts with Inchoo_PHP7 ?

### ISSUE THREAD

**Issue by jhoelzl** [OpenMage/magento-lts#439]
Hello,

i am using the magento-lts repo for a project, but i was wondering if i should or not use in addition the module https://github.com/Inchoo/Inchoo_PHP7?

Is this necessary or are there also PHP7 fixes in magento-lts?

Regards,
Josef

**Comment by seansan** [comment]
Lts already supports php7 as is

We run it too

If you think this is not clear. Please amend the readme.

**Comment by jhoelzl** [comment]
Okay, thanks!
