### ISSUE TITLE
do not clear cache when there is no product id

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#44]
Magento calls cleanCache on before_save in product even if there is no product ID yet (product was just created).
This can lead to unnecessary cache clearing.

see
https://github.com/OpenMage/magento-lts/blob/1.9.2.1/app/code/core/Mage/Catalog/Model/Product.php#L618

the clean cache should be wrapped in 
if ($this->getId()) {
}

**Comment by LeeSaferite** [comment]
Could you submit a PR?

**Comment by tmotyl** [comment]
sure I will :)
