### ISSUE TITLE
Possible Array Access warnings in Captcha Observer

### ISSUE THREAD

**Issue by Hanmac** [OpenMage/magento-lts#4414]
https://github.com/OpenMage/magento-lts/blob/31ff920d0d2465726bc1807ddaae060274066d1b/app/code/core/Mage/Captcha/Model/Observer.php#L274-L278

In this line, if for some reason the Post if empty, or it doesn't have the specific Key, it could throw different errors depending on if the whole Post is missing or just part of the key.

Like these:

> Undefined array key $formId
> Trying to access array offset on null

Should this be taken care of the function by adding `?? ''` ?
If the String is empty, the Captcha Observer will deny access anyway.

@sreichel what is your opinion about this?

**Comment by sreichel** [comment]
PR welcome :)

**Comment by sreichel** [comment]
@all-contributors add @Hanmac bug

**Comment by sreichel** [comment]
@all-contributors add @Hanmac bug
