### ISSUE TITLE
Estimate Shipping Costs allows arbitrary country id to be set on quote

### ISSUE THREAD

**Issue by gstdp** [OpenMage/magento-lts#4417]
### Preconditions (*)

1. Openmage 20.0.20

### Steps to reproduce (*)

1. Submit a post request to Mage_Checkout_CartController `estimatePostAction` with arbitrary values for the form fields (in this case `country_id`). In this case an attacker was attempting injection attacks, and set an invalid country_id on their quote shipping address.

### Expected result (*)

1. Quote shipping address should not allow invalid values to be set.

### Actual result (*)

1. Shipping address will have invalid country id set.
2. Whenever a call is made to `Mage_Directory_Model_Resource_Country` `loadByCode` an exception will be thrown (line 58)

**Comment by colinmollenhour** [comment]
Hi @gstdp please review #4427. Thanks!
