### ISSUE TITLE
Magento Config Cache Stampeding Race Condition @Collin

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#445]
Magento Config Cache Stampeding Race Condition @colinmollenhour 

https://maxchadwick.xyz/blog/magento-1-config-cache-stampeding-race-condition

Wasnt sure we ever implemented this fix. If so, then naturally close ;) (could find it in the issue list)

**Comment by sreichel** [comment]
Not implemented yet ... duplictes #422?

**Comment by Flyingmana** [comment]
fixed by #545
