### ISSUE TITLE
Invoices grid. to show payment method with filtering

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#448]
Hi. The issue is that if store merchant like to create monthly statements by payment method source, its impossible to filter and export desired data.

For example: Id like to export Paypal or COD payments separately or invoices paid by bank transfer.
Small improvement 1 column extra , a lot of problem solved at once

thanks
Tomek

**Comment by seansan** [comment]
This might involve another join to payment type table. I am not sure the data is in grid flat  ... 

This also does the trick if you really need it
- Checkout https://github.com/mage-eag/mage-enhanced-admin-grids/tree/1.0.0-wip-edge and add almost any column you like
- Checkout Mirasvit Enhanced Reports, payment type report

**Comment by fballiano** [comment]
If you need this new column you can rewrite the grid and add the column yourself.

I'm closing the issue since it's more than 3 years since the last feedback, feel free to reopen it if you feel so, possibly with a PR. Thank you.
