### ISSUE TITLE
Changing Magento Meta Description Length from 255 to 320 chars

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#454]
Changing Magento Meta Description Length from 255 to 320 chars

Google now accepts 320 chars, but Magento cannot handle longer than 255

Need to update code to at least support 320

See also here: https://github.com/magento/magento2/issues/12996

**Comment by Flyingmana** [comment]
should not be very problematic, as mysql allows a higher limit for varchar since 5.0.3
https://stackoverflow.com/questions/13506832/what-is-the-mysql-varchar-max-size

Does anyone know, if this requires a change to the EAV table?

**Comment by seansan** [comment]
Interesting is that category meta is type text

**Comment by colinmollenhour** [comment]
Rather than continue to increase varchar size each time an attribute length should be increased I think anything >255 chars should just be migrated to text attribute backend type.

**Comment by sreichel** [comment]
Google has reverted this in May ...  think this can be closed @seansan ?

**Comment by seansan** [comment]
​​
haha yes I agree ;)

(silly Google)
