### ISSUE TITLE
Add To Cart Button in Category has faulty Redirect Url

### ISSUE THREAD

**Issue by SRaromicon** [OpenMage/magento-lts#455]
Hey Guys,

since SUPEE-8788 or Magento CE Version > 1.9.2.4, the redirect urls at Cart Buttons are faulty.
& is replaced with \&amp; and query part of the url is broken. 

Steps to reproduce:

1. Set Option "After Adding a Product Redirect to Shopping Car" (System->Checkout->Shopping Cart) to "No"
2. Go to Category with Layered Navigation enabled and select at least 2 Filter
3. Hit "Add To Cart"-Button directly in Category
4. Look at your Url in Browser. You will be redirected to Category URL with broken Query Part with replaced & -> \&amp;
e.g. https://www.example.com/testcategory.html?color=rot&amp;manufacturer=nike

This issue can be reproduces in many active Magento Stores.

Caused by:

This ist caused by Mage_Core_Helper_Url:

```php    
public function getCurrentUrl()
    {
        $request = Mage::app()->getRequest();
        $port = $request->getServer('SERVER_PORT');
        if ($port) {
            $defaultPorts = array(
                Mage_Core_Controller_Request_Http::DEFAULT_HTTP_PORT,
                Mage_Core_Controller_Request_Http::DEFAULT_HTTPS_PORT
            );
            $port = (in_array($port, $defaultPorts)) ? '' : ':' . $port;
        }
        $url = $request->getScheme() . '://' . $request->getHttpHost() . $port . $request->getServer('REQUEST_URI');
        return $this->escapeUrl($url);
//        return $this->_getUrl('*/*/*', array('_current' => true, '_use_rewrite' => true));
    }
```

Magento has replaced 

`return $url`
by
`return $this->escapeUrl($url);`

Which uses a htmlspecialchars. 

I think the currentUrl should only be escaped in Templates, so you won't break the query Part.

**Comment by seansan** [comment]
My concern is: why did they replace it? Was it to fix something else?

**Comment by SRaromicon** [comment]
Sorry don't know, what they were trying to fix, but it was the wrong place and breaking the redirect urls is a big issue.

In my opinion escapeUrl should be used, if your are writing the url into a template or html output.

**Comment by colinmollenhour** [comment]
Probably a case of overzealousness.. Agree that escaping should happen outside of the get method.

**Comment by SRaromicon** [comment]
I have checked the core usages and if i'am right, it is always used/inserted in a template after a base64 encode, so malicious code would not be executed by browser. Magento is using it mostly for the uenc Parameter.
The changes are not mentioned in release notes.

**Comment by Flyingmana** [comment]
are there other ways to fix it, which is not modifying the escaping method?

**Comment by fballiano** [comment]
Closing the issue since it doesn't have any feedback in 3 years, feel free to reopen it if you've something to add to help solve it. Thank you.
