### ISSUE TITLE
1938 release 27-2-2018

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#458]
http://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html

**Comment by cundd** [comment]
Related security patch: [SUPEE-10570](https://magento.com/security/patches/supee-10570)

**Comment by seansan** [comment]
Can we merge with 193x? https://github.com/OpenMage/magento-lts/pull/460

**Comment by colinmollenhour** [comment]
Merged!
