### ISSUE TITLE
Postal Code required in backend adminhtml order creation?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#464]
Postal Code required in backend adminhtml order creation?

Not sure about this one

we would expect to be able to create an order without an address (just email) because a customer pays and takes it in the store

but we cant do this: because there is just 1 address field that is mandatory: postal code

if we add a postal code trying to circumvent this: then Magento says hey! you should now also complete the rest

So: is this normal behavior? Or can/ should we mark the PC as not mandatory in backend

![image](https://user-images.githubusercontent.com/652395/37144975-e8999742-22bf-11e8-932e-9610b6b643da.png)

**Comment by colinmollenhour** [comment]
This is set dynamically (Javascript) based on config value because some countries require and some do not. I think that it is required when creating an order with no address is a bug. Possible workaround would be to select a country that does not require postcode before trying to submit.

**Comment by fballiano** [comment]
You'd need an invoicing address anyway and since this issue didn't get feedback by OP since 4 years, I'm closing it.
