### ISSUE TITLE
Create a composer meta package with magento mirrors

### ISSUE THREAD

**Issue by Schrank** [OpenMage/magento-lts#470]
https://twitter.com/Flyingmana/status/974253813409484801

Adding magento as a dependency for packages is hard, because we have a lot of magento mirrors, like:

- open mage LTS
- open mage magento mirror
- firegento mirror
- ...

So creating a composer meta package which expects one of the repos to be used might help here.

**Comment by schmengler** [comment]
Like this? https://magento.stackexchange.com/questions/84410/choose-which-file-to-install-via-composer-based-on-magento-version/84415#84415

> There is no official `magento/magento-ce` package, so the users of your extension will probably install Magento from a community managed mirror like https://github.com/firegento/magento-ce or from their own repository. These must replace the "virtual" `magento/magento-ce` package of the same version (there is a placeholder self.version, so that you don't need to adjust the composer.json for each version update):
> ```
> "replace": {
>     "magento/magento-ce": "self.version"
> }
> ```

**Comment by Schrank** [comment]
No a meta package which says "I am magento" and yo can fulfill me by installing either:

- openmage/mage-lts
- openmage/magento-mirror
- firegento/magento-mirror

or some other package which we don't know. Is some work to collect them all, but then a dependency on magento is possible.

**Comment by Flyingmana** [comment]
Closing this for now.
A meta package could be created also from other organisations if still needed, we then could add support for this in OpenMage.
But as OpenMage continuously moves forward and away from the original Magento1 version wise, this might become complicated to solve in a userfriendly way.
