### ISSUE TITLE
.shop domian is not including

### ISSUE THREAD

**Issue by hryksbt** [OpenMage/magento-lts#474]
Recently, ".shop" domain is going to become popular.
But that is not included in "lib/Zend/Validate/Hostname.php".
I know this is Zend matter. But User will think inconvenience.

**Comment by spinsch** [comment]
Your TLD is also included after 2018/01/25. (https://github.com/OpenMage/magento-lts/pull/387).
`lib/Zend/Validate/Hostname.php` will be overwriten by `app/code/core/Zend/Validate/Hostname.php`.

**Comment by tmotyl** [comment]
solved in mentioned PR

**Comment by hryksbt** [comment]
OK. Thank you,
