### ISSUE TITLE
Missing email address in guest orders via SOAP API

### ISSUE THREAD

**Issue by schmengler** [OpenMage/magento-lts#476]
The fix in https://magento.stackexchange.com/questions/90380/magento-customer-email-missing-in-guest-checkout-when-using-soap-api could be incorporated in magento-lts

This is a core bug:
- customer_email is set correctly to `quote.customer_email` in `shoppingCartCustomerSet` call
- in `shoppingCartCustomerAddresses` call, the email gets copied to billing address, but from `quote->getCustomer()->getEmail()` which is empty for guest customers
- in `shoppingCartOrder` call, customer_email is then copied from the empty value in the billing address

**Comment by sreichel** [comment]
@schmengler time for a PR?

**Comment by spinsch** [comment]
WIP

**Comment by vtrusevich** [comment]
Any news about expecting merging date?

**Comment by sreichel** [comment]
Closed with #550.
