### ISSUE TITLE
GDPR simple solution to delete your account

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#480]
One of the main elements in the new EU GDPR is the right

- to delete your personal data

Can we add a simple link to do this in customer account on frontend? (and backend)

https://magento.stackexchange.com/questions/102673/how-to-delete-account-information
https://magento.stackexchange.com/questions/193185/add-delete-my-account-link-in-customer-navigation-menu/193188#193188

**Comment by tomekjordan** [comment]
what's with customer orders invoices after account deletion? will it work the same way as admin removed customer?

**Comment by seansan** [comment]
Found another one does a little more: https://www.scommerce-mage.com/magento1-gdpr-compliance.html

**Comment by Flyingmana** [comment]
I would suggest we add links to GDPR extionsions (or a list with ones) in the Readme instead of adding this functionality.

**Comment by LeeSaferite** [comment]
I'm 100% behind adding links to GDPR compliance modules.

**Comment by sreichel** [comment]
IMHO we should not add links to (espacially) paid extensions.

Zero1 was free until recently, but now costs 269€.... and is definitely not worth the money.

**Comment by tomekjordan** [comment]
removed :)

**Comment by sreichel** [comment]
Keep an eye on this ... https://github.com/firegento/firegento-magesetup/issues?utf8=%E2%9C%93&q=gdpr

**Comment by clotted** [comment]
M1 and M2 extension worthy mention, haven't tested:
https://github.com/flurrybox  (free)
(also Plumrocket have released a paid extension, just mentioning)

**Comment by sreichel** [comment]
I'd like to close this  ... we should not add any features just because of GDPR. There are several module that can do this.
