### ISSUE TITLE
Catalog Frontend Search

### ISSUE THREAD

**Issue by kestraly** [OpenMage/magento-lts#486]
One thing that always bugged me on Catalog Search is not being able to control it a bit more.

Perhaps a modification to **Mage_CatalogSearch_Model_Resource_Fulltext::prepareResult**

I've never had a store that needed to use 'OR' for the like condition

`$likeCond = '(' . join(' OR ', $like) . ')';`

and would always use

`$likeCond = '(' . join(' AND ', $like) . ')';`

Secondly, if we could get an option in to automatically remove the ending 'S' from searches, with an option to turn if off. That would be amazing too. It makes searches much more valuable and means as a business profits increase, without having to install a clunky third party search module for something so simple.

**Mage_CatalogSearch_Helper_Data::getQueryText**

```
$vowels=array("a","e","o","i","u"); 				
if(!in_array(substr($this->_queryText, -2, 1), $vowels) && strlen($this->_queryText) >= 6) $this->_queryText = rtrim($this->_queryText, 's');
```

elfling

**Comment by fballiano** [comment]
Closing since we merged https://github.com/OpenMage/magento-lts/pull/1852

**Comment by kestraly** [comment]
Only took 4 years :)

However, it was the right move. I would say that the plural removal is also a big change required. But that's just me
