### ISSUE TITLE
Implement SUPEE-10752 June 27, 2018

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#493]
I believe a neww release 1939 was released also

I can imagine we apply  the patch to LTS (instead of complete 1938 vs 1939) but am not the expert on this

https://magento.com/security/patches/supee-10752

**Comment by Flyingmana** [comment]
we usually do just a merge from the openMage mirror into this repo. Does only need an extensive check for conflicts, as the OpenMage Mirror has already a quite reliable review and can be seen as trusted source.

**Comment by Flyingmana** [comment]
was done with https://github.com/OpenMage/magento-lts/commit/afc58e89714d5ec3c7a24b4af571bc3d4d66f0e3
