### ISSUE TITLE
Idea to diff against this Mage repo? contains several patches too

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#494]
Idea to diff against this Mage repo? contains several patches too

https://github.com/hans2103/Magento

**Comment by sreichel** [comment]
OpenMagen has its own repo with official releases: https://github.com/OpenMage/magento-mirror :)

**Comment by seansan** [comment]
​​
I saw the JS update: did they upgrade prototype?

**Comment by sreichel** [comment]
Magento has not updated Prototype, so magento-mirror still uses v1.7. Maybe open an issue for this .... ?

**Comment by Flyingmana** [comment]
I described the base we use for the sourcecode a bit different on the website, maybe its more clear now.
https://github.com/OpenMage/magento-lts/commit/52f4e37996a7d45d72ff3884c2f584660681aa39

as sreichel did say, we use a magento mirror as base, and the newest magento version usually contains all needed magento patches.

if you find a specific Patch in another project which may be useful, its always good to create a specific Ticket for this. Its quite some work to track all the personal forks and compare which patches they put somehow themself in.

In this case its really just the one for ab updated prototype, which would need some extensive testing to make sure it does not break something :(

anyway, I will close this Issue for now, as we did check the other repo. If you think the prototype update is worth it, please create a new ticket for this.
