### ISSUE TITLE
Error: Support for eval(code, scopeObject) has been removed

### ISSUE THREAD

**Issue by rafaelpatro** [OpenMage/magento-lts#498]
I'm not know this is an official issue but that fix solve my problem when I was trying to load ajax requests with script tags inside.

[Error: Support for eval(code, scopeObject) has been removed. Use |with (scopeObject) eval(code);| instead.](https://groups.google.com/forum/#!topic/prototype-scriptaculous/X9mIvoh2e4A)

It could provide a better understand...
[Prototype Ajax.Updater Eval Javascript Functions](https://stackoverflow.com/a/1812581/2832131)

**Comment by Flyingmana** [comment]
thats a very interesting issue. Sounds at least reasonable, somehow.

On the other side, Iam very skeptic about this and wonder if this is by purpose encapsulated in this way.

Does anyone have resources how other JavaScript frameworks handle script tags in ajax responses?

**Comment by fballiano** [comment]
Closing this since it's dead since 2018 and the OP closed his PR.
