### ISSUE TITLE
Auto increment problem

### ISSUE THREAD

**Issue by rafaelpatro** [OpenMage/magento-lts#502]
Hi guys

I'm looking for a secure way to fix zero values on auto increment columns. Anyone know how to do it?

It's more like a Mysql compatibility that could be fixed.

I'm upgrading Magento since 1.3.2.4 and Mysql since I don't remember. And don't know when it happens but some auto increment columns have 0 value. So I faced many errors when trying to maintain/replicate/optimize the database.

Despite of the Mysql errors Magento is working fine since almost 9 years. No issues related in M1.9.

**Comment by Flyingmana** [comment]
I suggest you go with this question to https://magento.stackexchange.com/
Not sure what we can do here to improve the situation with this problem, but I leave it open for now, maybe someone else has an Idea or experience with it, or can at least say if it is a problem with magento itself
