### ISSUE TITLE
Does M LTS support Php 7.2.x?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#505]
Does M LTS support Php 7.2.x?

**Comment by colinmollenhour** [comment]
I think the main blocker is that PHP 7.2 removed mcrypt so see #129 and #449.

Aside from that I don't know of any major issues but wouldn't be surprised if there are minor issues from things like PCRE2.

AFAIK, PHP 7.1 is the latest fully supported version. Pull requests welcome! :)

See: https://github.com/php/php-src/blob/PHP-7.3/UPGRADING

**Comment by seansan** [comment]
https://github.com/Inchoo/Inchoo_PHP7/wiki/PHP-7.1-and-7.2

**Comment by Flyingmana** [comment]
> getimagesize() and related functions now report the mime type of BMP images
    as image/bmp instead of image/x-ms-bmp, since the former has been registered
with the IANA (see RFC 7903).

may need a change

most other 7.3 related BC breaks dont affect Magento I think, but who knows which odd constructs are hidden internally somewhere.

**Comment by Flyingmana** [comment]
can someone look trough the changes of https://magento.com/tech-resources/download#download2240 ?

**Comment by colinmollenhour** [comment]
The bulk of it is updating the libraries like phpseclib and adding mcrypt_compat. As it is the official solution I see no reason to not go ahead and merge it even though if you're not using downloader probably a lot of that code is not needed. There are some other changes in there like some explicit type casting and adding arguments to overridden methods so it's better that we've done to date.

**Comment by seansan** [comment]
https://inchoo.net/magento/magento-1-official-php-7-2-patches/

**Comment by Quazz** [comment]
So the Inchoo solution needs to be removed and the patch applied.

**Comment by seansan** [comment]
https://github.com/hans2103/Magento?files=1

**Comment by corbinu** [comment]
After https://github.com/OpenMage/magento-lts/pull/557 I think all that needs to be done for this that the composer requirement should include 7.2 as a valid version.

**Comment by seansan** [comment]
For means of closure ;)

Has anyone tested 7.2 PHP support on their server? (with the merges above)

Running on production?

(if yes: then maybe I dare to take a leap on our accept server .... and we can close the issue)

@corbinu @Flyingmana @colinmollenhour

**Comment by seansan** [comment]
Update. Tested today on DEV. No problems so far. On moving to production nginx env. 
So seems to work fine. 1.9.4.x branch.

**Comment by corbinu** [comment]
@seansan Sweet! I have only worked with it in dev also as I only use OpenMage to develop extensions don't have any prod Magento installs

**Comment by jhoelzl** [comment]
Issue can be closed since magento-lts supports PHP 7.2 after merging Magento Core Update 1.9.4.1.
