### ISSUE TITLE
Unable To Remove Coupon From Cart When Shipping/Tax Is Estimated

### ISSUE THREAD

**Issue by SafrazSSears** [OpenMage/magento-lts#508]
In the Shopping Cart, when you use the estimate shipping/tax feature, apply the estimations to the order, add a coupon code to the order, and then remove the coupon, the Shopping Cart returns the "Coupon code was canceled." messages, however, the coupon remains attached to the quote/sale.
If you do not use the estimate shipping/tax feature, the coupon can be added and then removed without issue.

**LAMP Stack**
Linux: Ubuntu 16.04.10 (AWS Ubuntu 16.04 AMI)
Apache: Apache/2.4.18 (Ubuntu)
MySQL: Ver 15.1 Distrib 10.1.35-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP: PHP 7.0.30-0ubuntu0.16.04.1 (cli)

**Magento CE Version:** 1.9.3.9

**Modules Active In Local Pool:**
1. Inchoo_PHP7

**Modules Active In Community Pool:**
1. Cm_RedisSession

**Active Theme:** base/default

Is anyone else experiencing this issue? I am experiencing this after upgrading from Magento CE 1.9.2.4 to Magento CE 1.9.3.9.
The only variable under that consideration is that I am not running a clean Magento CE 1.9.3.9 database.

**Comment by rafaelpatro** [comment]
Yes, I can reproduce the issue in my store too.

Similar environment...
 - Linux: Ubuntu 16.04.3 (Hetzner dedicated)
 - Apache: Apache/2.4.27 (Ubuntu)
 - MySQL: Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
 - PHP: PHP 7.0.28-0ubuntu0.16.04.1 (fpm-fcgi)

I'm using the same modules...
 - Inchoo_PHP7
 - Cm_RedisSession

Theme: rwd/default

**Comment by SafrazSSears** [comment]
Has anyone tried with a similar environment, but using PHP 5 instead? This could be a PHP 7 compatibility issue.

**Comment by SafrazSSears** [comment]
This seems to be an old issue that has existed across a few minor versions, and I dug up a solution in Magento's Issue Tracking.

The issue lies in the app/code/core/Mage/Checkout/controllers/CartController.php file, within the couponPostAction() function.
Follow these steps to fix the issue -
1. Find this line:
`$this->_getSession()->addSuccess($this->__('Coupon code was canceled.'));`
2. Under that line, add:
`$this->_getSession()->setCartCouponCode($couponCode);`

Of course, it's better to extend than overwrite the core. You can create the following files to result in a module that will fix the bug. **Be sure to replace [VENDOR] with a vendor name of your choice.**

1. app/etc/modules/[VENDOR]_Checkout.xml
`<?xml version="1.0" encoding="UTF-8"?>
<config>
    <modules>
        <[VENDOR]_Checkout>
            <active>true</active>
            <codePool>local</codePool>
        </[VENDOR]_Checkout>
    </modules>
</config>`

2. app/code/local/[VENDOR]/Checkout/etc/config.xml
`<?xml version="1.0" encoding="UTF-8"?>

<config>
    <modules>
        <[VENDOR]_Checkout>
            <version>1.0.0</version>
        </[VENDOR]_Checkout>
    </modules>

    <frontend>
    		<routers>
      			<checkout>
        				<args>
          					<modules>
                        <[VENDOR]_Checkout before="Mage_Checkout">[VENDOR]_Checkout</[VENDOR]_Checkout>
          					</modules>
        				</args>
      			</checkout>
    		</routers>
    </frontend>
</config>`

3. app/code/local/[VENDOR]/Checkout/controllers/CartController.php
`<?php
require_once 'Mage/Checkout/controllers/CartController.php';

class [VENDOR]_Checkout_CartController extends Mage_Checkout_CartController
{
  public function couponPostAction()
  {
      /**
       * No reason continue with empty shopping cart
       */
      if (!$this->_getCart()->getQuote()->getItemsCount()) {
          $this->_goBack();
          return;
      }

      $couponCode = (string) $this->getRequest()->getParam('coupon_code');
      if ($this->getRequest()->getParam('remove') == 1) {
          $couponCode = '';
      }
      $oldCouponCode = $this->_getQuote()->getCouponCode();

      if (!strlen($couponCode) && !strlen($oldCouponCode)) {
          $this->_goBack();
          return;
      }

      try {
          $codeLength = strlen($couponCode);
          $isCodeLengthValid = $codeLength && $codeLength <= Mage_Checkout_Helper_Cart::COUPON_CODE_MAX_LENGTH;

          $this->_getQuote()->getShippingAddress()->setCollectShippingRates(true);
          $this->_getQuote()->setCouponCode($isCodeLengthValid ? $couponCode : '')
              ->collectTotals()
              ->save();

          if ($codeLength) {
              if ($isCodeLengthValid && $couponCode == $this->_getQuote()->getCouponCode()) {
                  $this->_getSession()->addSuccess(
                      $this->__('Coupon code "%s" was applied.', Mage::helper('core')->escapeHtml($couponCode))
                  );
                  $this->_getSession()->setCartCouponCode($couponCode);
              } else {
                  $this->_getSession()->addError(
                      $this->__('Coupon code "%s" is not valid.', Mage::helper('core')->escapeHtml($couponCode))
                  );
              }
          } else {
              $this->_getSession()->addSuccess($this->__('Coupon code was canceled.'));
              $this->_getSession()->setCartCouponCode($couponCode);
          }

      } catch (Mage_Core_Exception $e) {
          $this->_getSession()->addError($e->getMessage());
      } catch (Exception $e) {
          $this->_getSession()->addError($this->__('Cannot apply the coupon code.'));
          Mage::logException($e);
      }

      $this->_goBack();
  }
}`

**Comment by ADDISON74** [comment]
I will close this issue being resolved by https://github.com/OpenMage/magento-lts/pull/656.
