### ISSUE TITLE
getOrderItem don't always return OrderItem

### ISSUE THREAD

**Issue by maximehuran** [OpenMage/magento-lts#513]
https://github.com/OpenMage/magento-lts/blob/34afee089b4f4c80bf0340fb0c6c9b761b04d48b/app/code/core/Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php#L180

If you check this code, I think the logic is not correct.
In the `getValueHtml()` we have the line : 
`$result .= " " . $this->getOrderItem()->getOrder()->formatPrice($attributes['price']);`

And with this call, I have this error : 
```
PHP Fatal error:  Call to a member function formatPrice() on null in .../app/code/core/Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php on line 203
```

It seems logic because the `getOrderItem` does not always return an `OrderItem`

**Comment by maximehuran** [comment]
Same problem in `Mage_Bundle_Model_Sales_Order_Pdf_Items_Abstract`

**Comment by sreichel** [comment]
Hi, can you please debug `$this->getItem()` in `getOrderItem() ` method? Which class is the object from?

**Comment by maximehuran** [comment]
It's a `Mage_Sales_Model_Order_Invoice_Item`

**Comment by maximehuran** [comment]
I'm on this commit https://github.com/OpenMage/magento-lts/commit/f78f0c2421555d3c3f0f18f17a86cdd2a7315972
I will try to update and check if the issue stills exist

**Comment by sreichel** [comment]
Can you please add steps to reproduce?

**Comment by maximehuran** [comment]
https://github.com/OpenMage/magento-lts/commit/9312e9f6693b9d17fe2927222a7079a1f38c5606

The changes on `getOrderItems` make the problem.

To reproduce, create and order with a bundle product, and you'll have some issues in invoices, shipments and creditmemo : 

![image](https://user-images.githubusercontent.com/11380627/45146942-21963a80-b1c4-11e8-946d-e6dc957950b8.png)

![image](https://user-images.githubusercontent.com/11380627/45146954-28bd4880-b1c4-11e8-93d5-22a996d65263.png)

![image](https://user-images.githubusercontent.com/11380627/45146962-2eb32980-b1c4-11e8-8fe0-9fc791bf904a.png)

**Comment by maximehuran** [comment]
The problem occurs of course only when `isChildCalculated` is false.
I tried on a clean on this repo with a clean installation and have the problem

![image](https://user-images.githubusercontent.com/11380627/45148924-aedb8e00-b1c8-11e8-8fa7-612f5dcac82f.png)
