### ISSUE TITLE
Paypal IPN  _registerPaymentRefund()

### ISSUE THREAD

**Issue by kestraly** [OpenMage/magento-lts#540]
One issue I have noticed is when a Paypal order has been refunded with an offline credit memo in Magento and then refunded in Paypal afterwards.

Often to prevent mistakes happening, an offline credit memo will be created in Magento and then you log into Paypal to process the refund.

Unfortunately the IPN will hook back to Magento with the amount to refund, which is correct, however within **protected function _registerPaymentRefund()** once an offline Credit Memo has been created the online credit memo becomes zero.

So when it calculates how much to create the credit memo for, it returns zero

`$amount = $this->_order->getBaseCurrency()->formatTxt($payment->getBaseAmountRefundedOnline());`

However it doesn't stop the creation of the credit memo if it's zero.

It creates the credit memo and then notifies the customer of a zero value refund. Confusing for the customer as well as the merchant, especially since it comes after the initial offline credit memo, so looks like this payment has been reversed.

Possible solution would be to check the amount first, before processing the refund with something simple such as

`if($amount < 0.01) return;`

**Comment by ADDISON74** [comment]
4 years have passed since this report and the author has not been active on GitHub for a long time. I don't use the PayPal component so I can't express an opinion. Is this still an issue in OpenMage?

**Comment by ADDISON74** [comment]
In this case I will close it. Anyone can request to reopen it if he faces the reported issue.
