### ISSUE TITLE
magento 1.9.3.10 displays <br/> in gallery

### ISSUE THREAD

**Issue by magentox** [OpenMage/magento-lts#553]
It seems there is some trouble in gallery on 1.9.3.10. They say a picture is worth a thousand words:

**Gallery on 1.9.3.9:**
![capture10](https://user-images.githubusercontent.com/44047835/46781343-19e62a80-cd5c-11e8-8536-217803329706.png)

**Gallery on 1.9.3.10:**
![capture20](https://user-images.githubusercontent.com/44047835/46781344-19e62a80-cd5c-11e8-812b-c7fdbde5ec7b.png)

The file gallery.phtml in app\design\adminhtml\default\default\template\catalog\product\helper seems to be the one causing this problem.

**Comment by Flyingmana** [comment]
interesting, and not surprising. This release did introduce a high amount of escaping on a lot of places.
Does it usually display the name of a storeview there? Or any other part which can be changed by an admin?

**Comment by seansan** [comment]
I can confirm the error on TEST vs PRODUCTION

Your answer: No I dont see anything else here in production

[image: image.png]

**Comment by sreichel** [comment]
Closed with #596.

**Comment by ProxiBlue** [comment]
This change block patching of latest security patch : SUPEE-11155

https://magento.stackexchange.com/a/280148/202

**Comment by sreichel** [comment]
@all-contributors add @magentox bug

**Comment by sreichel** [comment]
@all-contributors add @magentox bug
