### ISSUE TITLE
infinite recursion in  Shopping Cart Price Rules - Promotion

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#56]
I was just hit by this issue in promo rules.
In Magento >= 1.14.1.0 or 1.9.1.0 if you use "total quantity is 3 for a subselection of items in the cart..." rule, Magento will go out of memory because of the infinite recursion.

See great explanation and hotfix in the stackoverflow:
http://magento.stackexchange.com/questions/53777/magento-enterprise-1-14-1-0-shopping-cart-price-rules-promotion-fatal-erro

**Comment by sreichel** [comment]
Seems fixed in 1.9.3.0. Tested w/o any problems with 1.9.3.1 ...  can someone verify?

**Comment by drobinson** [comment]
Looks like this is solved here b52913af2965d9b5cd26c9392d5f73d6563b561a
