### ISSUE TITLE
Log stacktrace for errors when developer mode is off

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#568]
When developer mode is off, magento error handler will log error message to the syslog.
see `functions.php -> mageCoreErrorHandler `.
It would be very usefull for debugging if Magento log also the stacktrace, as the message is often not useful (especially when the error happens somwehere deep in magento, but was caused by wrong data passed by custom module).

Right now I'm working it around by custom log writer like:
config.xml
```
<global>
        <log>
            <core>
                <writer_model>Macopedia_Base_Model_Log_Writer_Stream</writer_model>
            </core>
        </log>
    </global>
```
stream.php
```
<?php
 class Macopedia_Base_Model_Log_Writer_Stream extends Zend_Log_Writer_Stream
{
    /**
     * Write a message to the log.
     *
     * @param  array  $event  event data
     * @return void
     * @throws Zend_Log_Exception
     */
    protected function _write($event)
    {
        $line = $this->_formatter->format($event);
        if ($event['priority'] < Zend_Log::WARN) {
            $line .= $this->getTraceString();
            $line .= PHP_EOL;
        }
        if (false === @fwrite($this->_stream, $line)) {
            throw new Zend_Log_Exception("Unable to write to stream");
        }
    }

    protected function getTraceString() {
        $d = debug_backtrace();
        $out = '';
        foreach ($d as $i=>$r) {
            if ($i < 4) {
                continue;
            }
            // sometimes there is undefined index 'file'
            @$out .= "[$i] {$r['file']}:{$r['line']}\n";
        }
        return $out;
    }
}
```

**Comment by colinmollenhour** [comment]
Logs are used for many things in addition to just errors so I don't think it is a good assumption that a stacktrace is always wanted, or even for specific severity levels. This is one of those cases where I think if you find the core functionality lacking you should install the Firegento_Logger extension and we should leave the core simple.

Here is a sample screenshot of Firegento_Logger config on one system:

![image](https://user-images.githubusercontent.com/38738/48561800-c5841c80-e8be-11e8-8d42-1750eb8e5267.png)

There are many more options but out of the box if you just use Magento Default and Advanced Format you will get exactly what you're looking for. That said, I can't recommend Sentry highly enough.

**Comment by tmotyl** [comment]
Hi @colinmollenhour 
Thanks for pointing me to the Firegento_Logger. Will take a look.
