### ISSUE TITLE
add and advertise Firegento_Logger as suggested Module on website

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#569]
with #568 and #556 we had two Requests, which already can get solved by the 3th party module Firegento_Logger.
As there is a general interest, we should make it easy to find and understand this modules.

**Comment by sreichel** [comment]
Add it to composer suggest? :+1:

**Comment by fballiano** [comment]
I think composer suggest is the best way at the moment. I wouldn't include a new module to the default install but suggesting it seems perfect.

**Comment by fballiano** [comment]
with this PR: https://github.com/OpenMage/documentation/pull/3 on the documentation repo we should be able to close this issue (let's close it already, it's on the docu repo anyways)
