### ISSUE TITLE
Mage_CatalogRule_Model_Rule: detect changes and only then run the indexer. Advise?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#573]
In this function, should we / can we - check if there are products modified? (if there is a need to reindex)

Suppose no rule is applicable and no changes are made: then why run the reindexer?

```
    /**
     * Apply all price rules, invalidate related cache and refresh price index
     *
     * @return Mage_CatalogRule_Model_Rule
     */
    public function applyAll()
    {
        $this->getResourceCollection()->walk(array($this->_getResource(), 'updateRuleProductData'));
        $this->_getResource()->applyAllRules();
        $this->_invalidateCache();
        $indexProcess = Mage::getSingleton('index/indexer')->getProcessByCode('catalog_product_price');
        if ($indexProcess) {
            $indexProcess->reindexAll();
        }
    }
```

**Comment by seansan** [comment]
Suppose we add a new method? It gives us a global hint if there are rules for any store

here app/code/core/Mage/CatalogRule/Model/Resource/Rule.php

`/**
     * Get active rules based on date now and if active
     *
     * @return array
     */
    public function getActiveRulesCount()
    {
        $date     = Mage::app()->getLocale()->date()->getTimestamp();
        $adapter = $this->_getReadAdapter();
        $select = $adapter->select()
            ->from($this->getTable('catalogrule'))
            ->where('is_active = ?', 1)
            ->where('from_time = 0 or from_time < ?', $date)
            ->where('to_time = 0 or to_time > ?', $date)
            ->order('sort_order');
        return $adapter->fetchAll($select);
    }`

**Comment by tmotyl** [comment]
I've just stumbled upon similar issue.
I have 0 catalog rules in db, yet Magento runs reindex (including creation of temporary tables on each product save).
![image](https://user-images.githubusercontent.com/515397/88109855-82a63c00-cbab-11ea-8d3f-6a304ee64e0f.png)

I think that we could add a return inside applyAllRulesToProduct

```php
public function applyAllRulesToProduct($product)
    {
        if (is_numeric($product)) {
            /** @var Mage_Catalog_Model_Product $product */
            $product = Mage::getModel('catalog/product')->load($product);
        }

        $productWebsiteIds = $product->getWebsiteIds();

        /** @var Mage_CatalogRule_Model_Resource_Rule_Collection $rules */
        $rules = Mage::getModel('catalogrule/rule')->getCollection()
            ->addFieldToFilter('is_active', 1);

       //FIX
        if ($rules->count() === 0) {
            return $this;
        }
// FIX

        foreach ($rules as $rule) {
            $websiteIds = array_intersect($productWebsiteIds, $rule->getWebsiteIds());
            $this->getResource()->applyToProduct($rule, $product, $websiteIds);
        }

        $this->getResource()->applyAllRules($product);
        $this->_invalidateCache();

        Mage::getSingleton('index/indexer')->processEntityAction(
            new Varien_Object(array('id' => $product->getId())),
            Mage_Catalog_Model_Product::ENTITY,
            Mage_Catalog_Model_Product_Indexer_Price::EVENT_TYPE_REINDEX_PRICE
        );

        return $this;
```
