### ISSUE TITLE
Request Preferred Currency from FedEx

### ISSUE THREAD

**Issue by chetradigi** [OpenMage/magento-lts#584]
I created FedEx account profile with default Japanese Yen currency.
I always got response with Japanese Yen currency in my English Store View even I set base currency to USD also.
I already asked FedEx Support about this they told me only your side can solve by setting preferred currency.I want to get response USD currency from FedEx Web service to my English Store View in Magento 1.9.3.8. How to do that?
Could you give any suggestion or you have to fix about this?
Thanks

**Comment by kestraly** [comment]
It will all be within Mage_Usa_Model_Shipping_Carrier_Fedex

Does this help your question?
https://magento.stackexchange.com/questions/214537/magento-fedex-set-base-currency

I can see that currencyCode is currently set as
`$currencyCode = Mage::app()->getStore()->getBaseCurrencyCode();`

However there is also the following comment 
The "RATED..." rates are expressed in the currency of the origin country
