### ISSUE TITLE
Custom Option price show wrong in multiple websites

### ISSUE THREAD

**Issue by chetradigi** [OpenMage/magento-lts#585]
We has two websites:
	1. Main Website
		- Japanese is our store view
		- Base Currency is Japanese Yen(JPY)		
	2. USD Website
		- Base Currency is US Dollar(USD)
		- English is our store view
Our default config Base Currency is Japanese Yen(JPY).
We created production custom option that Input Type is Radio Buttons we face:
	1.When we select Japanese in "Choose Store View" the price of our custom option in edit form is the same after saved and edit (working fine).
	2.But when we select English in "Choose Store View" the price of our custom option in edit form is not the same after saved and edit (Wrong).	
	It's because of when we enter in English Store ex.40 mean 40$ I found that Magento was converted to 0.3532 (40*0.008829) 
	that 0.008829 is exchange rate but when we edit Magento not convert that amount from base value to USD 
	it's just 0.36 (it was rounded).
	
	My suggestion is Magento 1.9.x should update to store price in two fields that are price and base_price in this table `catalog_product_option_type_price`  
	that base_price is the converted price and price is the price that enter in selected store view.
	I want to know what is your solution for this case?

**Comment by kestraly** [comment]
Is this the issue you're having?

https://stackoverflow.com/questions/22808459/magento-multiple-currency-conversion-on-custom-options-prices

**Comment by chetradigi** [comment]
Thank for your respond my error case is the same your reference link but it's difference about the way of change product information
in my case the step is something as bellow:

Step1	
	- first I create product with add Custom Option as Input Type is Radio Buttons with Fixed Price Type  
	- Then I set price 40 (mean 40$ because I select English store view base currency of this store is USD)
	- Finally I saved
Step2
	- Edit that product
	- I click custom option to see the value that I just enter in Step1 but I don't see the price as 40 but I saw price is 0.36 it means 
Magento was converted to from 40 that I enter when create to 0.36 to store in database
	So you have to give me the proper solution for fixed this case better then give me the reference that isn't clear it can solve or not.
	Thanks you in advance
