### ISSUE TITLE
Indexer lock process

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#593]
Should the lock function return the true or false status of the method call?

$ret = false;
$ret = $this->_getLockInstance()->setLock($this->getProcessLockName(), $this->getData('use_file_lock'));
        return $ret;

I see child functions have true/false returns but now it is lost?

    /**
     * Lock process without blocking.
     * This method allow protect multiple process runing and fast lock validation.
     *
     * @return Mage_Index_Model_Process
     */
    public function lock()
    {
        $this->_getLockInstance()->setLock($this->getProcessLockName(), $this->getData('use_file_lock'));
        return $this;
    }

**Comment by fballiano** [comment]
Although you're right, changing the return value of a public method is a breaking change that I'd avoid.

I'll close the issue since it didn't have any movement in 3 years, you're welcome to reopen it if you feel so, possibly with a PR. Thank you.
