### ISSUE TITLE
Events being fired twice in Mage_Catalog_Model_Resource_Category_Flat_Collection

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#597]
The events `catalog_category_collection_load_after` and `catalog_category_collection_load_before`
are being triggered twice in Mage_Catalog_Model_Resource_Category_Flat_Collection.
See methods _beforeLoad and _afterLoad, and their implementations in parent class Mage_Core_Model_Resource_Db_Collection_Abstract.
Both child and parent methods have the same code like:
```
Mage::dispatchEvent($this->_eventPrefix . '_load_after',
                            array($this->_eventObject => $this));
```
I think _beforeLoad and _afterLoad methods can be deleted from Mage_Catalog_Model_Resource_Category_Flat_Collection

**Comment by Flyingmana** [comment]
merged
