### ISSUE TITLE
Integrity constraint violation in core_session 1.9.4.0

### ISSUE THREAD

**Issue by rvelhote** [OpenMage/magento-lts#600]
Hello,

I've noticed this error happening a few times per day in my `php_errors.log` file. I'm not really sure what caused it but I have a feeling it might be related to issue #394 which deals with sessions.

When I query the `core_session` table there are no entries with these identifiers.

In `Mage_Core_Model_Resource_Session->write` there is a check for the `session_id` value that updates the row in case the identifier already exists. Perhaps there is a concurrency issue where `destroy` is called and `write` is called but the check returns that it doesn't exist but the value was not deleted yet. Or perhaps it's an issue with MariaDB (10.1.34) `query_cache` enabled?

Is anyone experiencing this issue?

Best regards,
Ricardo

```
[08-Feb-2019 07:52:13 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5olo7h5i6jh9a024qtdtgegk7qp94nbp' for key 'PRIMARY' in /var/www/html/magento/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/magento/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/html/magento/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/html/magento/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/html/magento/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/html/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `co...', Array)
#5 /var/www/html/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `co...', Array)
#6 /var/www/html/magento/lib/Zend/Db/Adapter/Abstract.php(576): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `co...', Array)
#7 /var in /var/www/html/magento/lib/Zend/Db/Statement/Pdo.php on line 235
```

**Comment by colinmollenhour** [comment]
Perhaps try setting transaction isolation level to `READ COMMITTED`?
Also try disabling MariaDb query cache, it seems it MySQL is removing it in 8.0. Not sure what MariaDb's plans are offhand.

**Comment by rvelhote** [comment]
In our use case QueryCache is very efficient and it's actually worth it. I will try to add `SQL_NO_CACHE` to the read operation and see if it will have some effect.

**Comment by rvelhote** [comment]
I've added `SQL_NO_CACHE` to the query the selects the current session row however the error still appears occasionally. I really don't understand the conditions under which this error happens. I am thinking about using `insertOnDuplicate` instead of the regular `insert` in this specific place just to fix this particular issue.

**Comment by fballiano** [comment]
I'm closing this issue since it didn't have any movement in movement in 3 years, feel free to reopen it, possibly with a PR to help up out. Thank you!
