### ISSUE TITLE
Php 7.2 + M1.9.4.x / object(Varien_Data_Form_Element_Collection) does not support Countable

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#604]
object(Varien_Data_Form_Element_Collection) does not support Countable

Warning: count(): Parameter must be an array or an object that implements Countable  Observer.php

This is an extension. But Varien_Data_Form_Element_Collection is core. According to the warning it should support Countable 

http://php.net/manual/en/function.count.php#refsect1-function.count-changelog

**Comment by LeeSaferite** [comment]
Looking at the code it's a simple matter of adding the `Countable` interface since the class already implements the `count()` method. `Countable` has been around since 5.1 so it shouldn't break anything.

**Comment by LeeSaferite** [comment]
It might be good to search for any other classes that implement `IteratorAggregate` but not `Countable`

**Comment by seansan** [comment]
I’d like to help but this is above my php knowledge. Thanks for the
feedback i will try to read more about it. Or if someone else knows how to
add it - that would be appreciated.

**Comment by seansan** [comment]
https://stackoverflow.com/questions/2297714/how-to-implement-the-countable-interface-in-php

**Comment by LeeSaferite** [comment]
It's literally adding `, Countable` to the end of this line: https://github.com/OpenMage/magento-lts/blob/1.9.3.x/lib/Varien/Data/Form/Element/Collection.php#L34

**Comment by seansan** [comment]
Comma Countable

And if I understand right there needs to be a count method in the class?

**Comment by LeeSaferite** [comment]
The method is already there, it just doesn't have the matching interface.
