### ISSUE TITLE
Children loading media improvement ?

### ISSUE THREAD

**Issue by maximehuran** [OpenMage/magento-lts#618]
https://github.com/OpenMage/magento-lts/blob/f78f0c2421555d3c3f0f18f17a86cdd2a7315972/app/code/core/Mage/ConfigurableSwatches/Model/Observer.php#L131

Maybe we can juste use 
```
$mediaProductIds  = $productType->getChildrenIds($product->getId())
```
To avoid the call of `getUsedProducts` which loads a lot of things just to retrieve children IDs after ?

**Comment by maximehuran** [comment]
Forget it...
we need to keep 
```
$childrenProducts = $productType->getUsedProducts(null, $product);
$product->setChildrenProducts($childrenProducts);
```

**Comment by seansan** [comment]
Not clear. Don’t change the code? Or is the last contribution the suggested change?

**Comment by kkrieger85** [comment]
@maximehuran As I understand your comments, this issue can be closed?
