### ISSUE TITLE
Google Chart API Deprecated 14th March 2019

### ISSUE THREAD

**Issue by rvelhote** [OpenMage/magento-lts#623]
Hello everybody!

Actually there is already a [patch](https://community.magento.com/t5/Magento-DevBlog/Google-Image-Charts-deprecation-and-update-for-M1/ba-p/125006) for this specific issue, which will be available in `1.9.4.1`, so no need to work on this unless we want to improve how it looks (not as cool as before) ;)

I have a PR ready to go but I'm not sure if it will be useful because it will be released in the next Magento version. As an alternative there is a [Magento Module](https://github.com/onilab/magento-1-google-api-chart-fix) that uses the Javascript API from Google Charts (I have not tested this module yet).

~~As many of you might have noticed, getting into the Magento Admin Area no longer displays the nice sales graph. This happened because the chart uses a specific [Google Charts API](https://developers.google.com/chart/image/docs/making_charts) that has been marked deprecated since March 14th and [turned off today](https://groups.google.com/d/msg/google-chart-api/rZtHTyYgyXI/4JmoYfJDAwAJ).~~

~~From a quick read, the API that Magento was using is replaced by a Javascript library which might yield the same results. Perhaps this will be as simple as, instead of returning an image, the `DashboardController::tunnelAction` should return JSON and load it into the JS library.~~

~~The JS library has this [example](https://developers.google.com/chart/interactive/docs/php_example) which might be what we need (excluding the jQuery dependency).~~

~~There's an [issue](https://github.com/magento/magento2/issues/21599) in the Magento 2 repository about the same thing.
I will try to work on this later today and submit a PR but if someone else if ready to give it a shot it would be super ;)~~

Thank you,
Ricardo

**Comment by sreichel** [comment]
See #639
