### ISSUE TITLE
Patch SUPEE-11086/Magento 1.9.4.1

### ISSUE THREAD

**Issue by cundd** [OpenMage/magento-lts#627]
Magento Security information: https://magento.com/security/patches/supee-11086
Related Issue [magento-mirror #73](https://github.com/OpenMage/magento-mirror/pull/73)

**Comment by iamniels** [comment]
I applied the patch to the 1.9.4.x branch. Pull request here: https://github.com/OpenMage/magento-lts/pull/631

**Comment by Flyingmana** [comment]
is there currently someone, who will need this patch also for the 1.9.3.x branch?

**Comment by Flyingmana** [comment]
https://github.com/OpenMage/magento-lts/pull/639

**Comment by tmotyl** [comment]
@Flyingmana I think 1.9.3.x should also get this patch

**Comment by cundd** [comment]
This ticket can be closed, is that correct? Or should it remain open for 1.9.3.x?

**Comment by Flyingmana** [comment]
would like to keep it open for 1.9.3.x

**Comment by seansan** [comment]
If was applied to 4.x already then maybe add 3.x to title

**Comment by kkrieger85** [comment]
@cundd , @Flyingmana Could you please update issue title to
`Patch SUPEE-11086/Magento 1.9.3.x.`

**Comment by cundd** [comment]
Or close this one and create a new ticket?

**Comment by kkrieger85** [comment]
That would be the more proper way. 

Please add reference to this issue in new issue :)
