### ISSUE TITLE
Authorize.net Direct Post Signature Key patch

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/magento-lts#636]
Just to make sure this doesn't get overlooked, although Direct Post really shouldn't be used anyway. :)

https://magento.com/tech-resources/download#download2280

This patch updates Authorize.Net Direct Post integration to continue processing payments beyond March 14th 2019 (see MD5 Hash End of Life & Signature Key Replacement). There are additional steps that you need to execute after installing this patch to ensure continued use of Authorize.Net – read more Update Authorize.Net Direct Post from MD5 to SHA-512.

**Comment by Flyingmana** [comment]
@colinmollenhour you probably did not back this download up, did you?

**Comment by jouriy** [comment]
just in case, the patch is available here: https://support.magento.com/hc/en-us/article_attachments/360026121651/PATCH_SUPEE-11085_EE_1.14.4.0_v1-2019-02-28-04-59-38.sh and all instructions are still available in https://support.magento.com/hc/en-us/articles/360024368392-Update-Authorize-Net-Direct-Post-from-MD5-to-SHA-512
