### ISSUE TITLE
Packagist 1.9.4.x-dev seems to be stuck on old commit

### ISSUE THREAD

**Issue by akira28** [OpenMage/magento-lts#638]
Using composer I noticed that the version didn't change even if there were new commits in the repo. Packagist version seems to be stuck at daf983128b0922645520d0478143fa88fbc8db4b

**Comment by Flyingmana** [comment]
not sure if I did solve it already, but I did add a webhook (the old Github Services are deprecated)
I did use my own API key, but Iam not listed as a maintainer, so I dont know how reliable this works.
Maybe @LeeSaferite  or @drobinson can check the connection again, or even add me as a Maintainer on Packagist.

**Comment by akira28** [comment]
this issue can be closed, it now works correctly
