### ISSUE TITLE
Mage::log() not working on new Magento update (1.9.4.1)

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#646]
Log seems broken, when log files does not exist .... https://magento.stackexchange.com/a/268396/46249

Hope for next official update?

**Comment by Flyingmana** [comment]
Iam aware of this Issue, I guess we will accept a community provided fix for this Issue after the merge

**Comment by themew** [comment]
Fixed here > https://gist.github.com/piotrekkaminski/0596cae2d25bf467edbd3d3f03ab9f8f
but nothing from Magento about a V2 patch.

**Comment by seansan** [comment]
Hi, was this fixed maybe and pushed to 4.x? (having this probem too now)

**Comment by themew** [comment]
> Hi, was this fixed maybe and pushed to 4.x? (having this probem too now)

The patch works or you can manually edit the app/Mage.php file

**Comment by colinmollenhour** [comment]
Can someone else approve one or more of #648, #652 or #670? All three are correct in my opinion, but we need at least one of them to fix this issue.

**Comment by colinmollenhour** [comment]
Merged #670.

**Comment by aadmathijssen** [comment]
This issue has been fixed in CE 1.9.4.2 with exactly the same changes as in #670.
