### ISSUE TITLE
Wrong price displayed in cart when qty in cart is higher than stock.

### ISSUE THREAD

**Issue by Hexmage** [OpenMage/magento-lts#647]
Since 1.9.3.0 a bug was introduced which may cause the cart to display the wrong price for a product. 

How to reproduce:
- Create a product that has managed stock and isn't backorderable
- Add product to cart.
- Add the product to your cart until its qty exceeds its stock.

Expected result:
- Product price is still the original price and subtotal is the total for all products in the cart. You can't go to the checkout.

Actual result:
- Product price is significantly lower than the original price (depends on how far you went over the stock). You can't go to the checkout.

The cause:
Mage_Sales_Model_Quote_Address_Total_Subtotal line 114
`} else if (!$quoteItem->getParentItem() && !$item->getHasError()) {`
Because `&& !$item->getHasError()` got added the product price doesn't update anymore after it has gained an error, like in this case not having enough stock. But it is using the not updated value to incorrectly calculate the new subtotal.

**Comment by sreichel** [comment]
Closed with #650.
