### ISSUE TITLE
How to handle escaped strings with added HTML from core functionality

### ISSUE THREAD

**Issue by nige-one** [OpenMage/magento-lts#649]
More or less every adminhtml output of user-definable strings is escaped, which is a good thing. But since some outputs are enriched with HTML coming from core functionality this leads to ugly output.

My example in adminhtml is the product's image table where the header titles (base image, small image, thumbnail etc) are enriched with the attribute's scope
https://github.com/OpenMage/magento-lts/blob/77a837aba9166502378d3bb64920ccf5e862b95e/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Gallery/Content.php#L144-L145

The scope is intended to be shown on a new line by utilizing a `<br/>` which is added by a block helper class.
https://github.com/OpenMage/magento-lts/blob/77a837aba9166502378d3bb64920ccf5e862b95e/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Gallery.php#L120-L127

This enriched output is escaped afterwards, which leads to an ugly output.
https://github.com/OpenMage/magento-lts/blob/77a837aba9166502378d3bb64920ccf5e862b95e/app/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml#L61-L63

The question is how to handle that. My proposal is to redesign the template by adding a second table header line to take semantics into account.
Any opinions on that? What are the chances to get my idea merged in here? Can you name any other similar ugly outputs to fix?

**Comment by tmotyl** [comment]
Hi do I get it correctly this PR is related to this issue? 
https://github.com/OpenMage/magento-lts/pull/596/files
@nige-one I would also say that the template should be updated.

**Comment by nige-one** [comment]
@tmotyl exactly. Thanks for your input

**Comment by sreichel** [comment]
#596 merged.
