### ISSUE TITLE
PEAR lib files use obsolete class instantiation

### ISSUE THREAD

**Issue by rodrigoriome** [OpenMage/magento-lts#660]
Some PEAR library files still use a very old way of instantiating classes which is the "&new", AKA assignment by reference. I suggest that all such occurrences, such as the occurrences of "&this", be replaced by the new way. Even because it is no longer supported. See the link below

https://stackoverflow.com/questions/39711137/is-pass-by-reference-supported-in-php-7

**Comment by Flyingmana** [comment]
Yes, we should fix them. Maybe they are already fixes in the original repos?

can we maybe replace them with composer references instead?

**Comment by akira28** [comment]
Magento uses PEAR 1.7.2, maybe it would be good to upgrade to the latest version 1.10.9 https://pear.php.net/package/PEAR but I don't know about the implications

**Comment by luigifab** [comment]
PEAR [was removed](https://github.com/OpenMage/magento-lts/commit/c02c9ed53b990a7549a89c03346d755aa11e263e) from OpenMage.
