### ISSUE TITLE
Warning: is_readable() expects parameter 1 to be a valid path

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#666]
From https://magento.stackexchange.com/questions/270687/warning-is-readable-expects-parameter-1-to-be-a-valid-path

Not sure if supress error is best idea ... see #85 

Untested, but a file_exists() check before c/should cover this.

**Comment by manezaf8** [comment]
The thing is we are not suppose to update the [  lib ] Folder since we working with big data and most of the functions are related, so how to go about it to stop this warning from happening ?
