### ISSUE TITLE
Warning: md5() expects parameter 1 to be string, array given in app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 152

### ISSUE THREAD

**Issue by kanevbg** [OpenMage/magento-lts#667]
The issue is in
```md5($cookie->get($secureCookieName))```
as the cookie value may be manipulated to be non-string value. When that happens the warning is produced. In the expected use-case we will have always string.

**Comment by kkrieger85** [comment]
Fixed in #668

**Comment by sreichel** [comment]
@all-contributors add @kanevbg bug
