### ISSUE TITLE
SUPEE-7405 issues when not using Apache mod_php

### ISSUE THREAD

**Issue by Elfen-Service** [OpenMage/magento-lts#67]
Many people have problems after the patch because using php-fpm or similiar.
I think it would be a good idea to change lib/Varien/File/Uploader.php to work again on such systems.

**Comment by tmotyl** [comment]
@Elfen-Service can you elaborate a little bit about the issue?

**Comment by Elfen-Service** [comment]
@tmotyl

Magento changed the chmod in line 219 and 541 so that images could not be deliverd by the webserver.
For example look at htis thread: http://stackoverflow.com/questions/34957448/chmod-640-for-uploaded-file-after-supee-7405-patch
Meanwhile in the actual version it was changed to 666 and 777 which in my opinion is also a wrong way.
The ideal would be 664 and 775 i think.
So the system user and group (for example php as magento:magento) from the fpm-process could create/modify an the webserver which runs under another user/group (for example nginx as default-www:default-www) could read the folders ans files to deliver them.

**Comment by seansan** [comment]
Can this issue be closed? It seems the 2nd version of the patch addresses this issue. 
https://stackoverflow.com/questions/34957448/chmod-640-for-uploaded-file-after-supee-7405-patch

**Comment by Elfen-Service** [comment]
Nothing changed. sinde my last post on 9 Jun 2016.
Theoretically it is working since the newer patch.
But the actual used permissions are still 666 and 777.
In my opinion this is still the wrong way.
For security reasons alone it should be at least 664 and 775.

**Comment by seansan** [comment]
Do you suggest to
- accept the newer patch and close the issue?
or
- do you want to submit a pull request to fix the issue?

Thanks for helping out. What do you use in production currently?

**Comment by Elfen-Service** [comment]
Than i would say to make a request fix.
I use Magento LTS 1.9.3.9.
With a personal personal fix using chmod($destinationFile, 0644); and @mkdir($destinationFolder, 0755, true).
As suggested the best for all out there would be using 0664 and 0775.

**Comment by sreichel** [comment]
I'd close to do some cleanup. Please reopen if its still an issue.
