### ISSUE TITLE
Replace Magento Notifications

### ISSUE THREAD

**Issue by kkrieger85** [OpenMage/magento-lts#683]
https://github.com/OpenMage/magento-lts/blob/9f9a99ba397e00c7471b2234ef1e61cc48d600f7/app/code/core/Mage/AdminNotification/etc/config.xml#L94

**Comment by kkrieger85** [comment]
Proposal: Create own notification rss in https://github.com/OpenMage/OpenMage.github.io to inform user.

Alternative: Remove AdminNotification at all

**Comment by spinsch** [comment]
After adobe has bought magento, the notifications feels like shitty newsletter with useless information about migration service for magento 2.

I'm also happy if we change something on the notification system.

**Comment by Flyingmana** [comment]
doing it as part of the website sounds ok, but would do it in a separate repository to have a better access-controll and more strict rules.
Reason is, this would be a message to all stores, so we need to make the process of adding something as robust, as a contribution to the core code itself.

Another point is, would we want to use this for tracking installs?
It would be an opportunity for this and have more useful numbers then the downloads.

Doing it via github pages would prevent this for now, as we do not have access to the access.log, so this would be good if we definitely do not want to track it over this.

**Comment by kkrieger85** [comment]
> doing it as part of the website sounds ok, but would do it in a separate repository to have a better access-controll and more strict rules.

👍 
> Reason is, this would be a message to all stores, so we need to make the process of adding something as robust, as a contribution to the core code itself.

👍 

> Another point is, would we want to use this for tracking installs?
> It would be an opportunity for this and have more useful numbers then the downloads.

If so, we should offer an opt-out

**Comment by Flyingmana** [comment]
I started the Repository https://github.com/OpenMage/Web_Notifications
which currently is available via https://openmage.github.io/Web_Notifications/index

Will need to look in which format we need to provide the Feed, to prepare the template accordingly.

**Comment by spinsch** [comment]
Just noticed in my test environment that the feed URL triggers a 301 redirect and throws an error in my magento system.log

`https://openmage.github.io/Web_Notifications/notifications_v1.rss `
goes to 
`http://www.openmage.org/Web_Notifications/notifications_v1.rss`

**Comment by Flyingmana** [comment]
indeed, reason is probably https://github.com/OpenMage/OpenMage.github.io/commit/fea9d0fab5a14b8393ba61c6dfcb9a77a7662845 from @LeeSaferite 

i guess we should either update the url, or allow following redirects(is this possible?)

**Comment by fballiano** [comment]
Is the notification really needed? I've always felt (with all the stores I've worked on) that it was just "in the way" and nobody ever paid attention to those notifications. Most of the stuff is handled by developers/consultants which almost never use the backend...

Same goes for both adobe's notification and 3rd party modules notifications.

In my opinion it would be better to disable/remove the feature.

**Comment by kkrieger85** [comment]
Partly done in https://github.com/OpenMage/magento-lts/pull/994

**Comment by fballiano** [comment]
This was managed, although not completely, in https://github.com/OpenMage/magento-lts/pull/994 so, since we've no update since 1.5years, I'm closing this one.
