### ISSUE TITLE
Possible coupon code improvement

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#71]
http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions/comment-page-1/#comment-53337

and updated code here:
https://gist.github.com/peterjaap/bf9aa2086f06a1a41fa1

**Comment by sreichel** [comment]
Close? Sames as #167 ...

**Comment by tmotyl** [comment]
closing as duplicate
