### ISSUE TITLE
[Bug] Mage_Directory_Helper_Data::getRegionCollection()

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#713]
> Fatal error: Uncaught Error: Call to undefined method Mage_Directory_Helper_Data::getAddress()

```
Mage::helper('directory')->getRegionCollection();
```

**Comment by Sekiphp** [comment]
This error is generated here:
`    /**
     * Retrieve region collection
     *
     * @return Mage_Directory_Model_Resource_Region_Collection
     */
    public function getRegionCollection()
    {
        if (!$this->_regionCollection) {
            $this->_regionCollection = Mage::getModel('directory/region')->getResourceCollection()
                ->addCountryFilter($this->getAddress()->getCountryId())
                ->load();
        }
        return $this->_regionCollection;
    }`

Similar method is implemented in `Mage_Directory_Block_Data` but there is defined country filter using this function: 
`    public function getCountryId()
    {
        $countryId = $this->getData('country_id');
        if (is_null($countryId)) {
            $countryId = Mage::helper('core')->getDefaultCountry();
        }
        return $countryId;
    }`

It's hard to say, what implementation is correct. It seems, that this function never worked before. I think, that right implementation is create optional parameter for filtering.

**Comment by sreichel** [comment]
#718

**Comment by real34** [comment]
For the record, this issue is still occurring since 19.4.4.
The fix was reverted as part of https://github.com/OpenMage/magento-lts/pull/773#pullrequestreview-409273882 as it seemed to create another problem.

Should it be reopened?

**Comment by Flyingmana** [comment]
should be fixed with next release, please reopen if its not the case
