### ISSUE TITLE
Does OpenMage LTS support Php 7.3.x?

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#716]
formal followup to https://github.com/OpenMage/magento-lts/issues/505

I just checked by installing Openmage for demo purposes on a 7.3 (and also a MySql 5.7)
You can check the demo out on http://www.openmage.cotya.org

I did once go through the Order Process and could finish the order without an error page shown.

But I could find a warning in magerun for some syntax issue.

**Comment by rvelhote** [comment]
I was doing some tests with PHP 7.3 (Debian Buster) on the original core (not LTS) and I didn't find any errors in our instance. Everything that I touched worked well. Still pending some more detailed tests.

Looking at 7.3 [backwords incompatibility docs](https://www.php.net/manual/en/migration73.incompatible.php) and [deprecation docs](https://www.php.net/manual/en/migration73.deprecated.php) I think there will not be many problems; at least with core.

**Comment by iamniels** [comment]
We are running in problems with arrays in SOAP requests. Both when Magento is the SOAP client and when Magento is the SOAP server. Other than arrays, SOAP requests work fine. Unfortunately a large part of our APIs rely on arrays over SOAP.

**Comment by Flyingmana** [comment]
@iamniels I did not work much with this part yet, do you by chance have a small php example for the client, and an curl request for the server I can use as base to investigate this?

**Comment by Flyingmana** [comment]
maybe its not even directly related to soap, it could be one of them:
https://www.php.net/manual/en/migration73.incompatible.php

maybe "Strict Interpretation of Integer String Keys on ArrayAccess" (just leaving this here as a note for myself)

**Comment by iamniels** [comment]
When I make a POST request with the following contents, Magento returns the Exception that the second argument of the Multicall function needs to be an array and it is an object. I made the request with the regular SoapClient with only the `trace` option enabled. The error suddenly disappeared after upgrading several Debian packages on one machine. And it disappeared after a reboot on another machine. I would guess it is an error within the PHP SOAP package, not in Magento.

    POST /index.php/api/ HTTP/1.1
    Host: xxx
    Connection: Keep-Alive
    User-Agent: PHP-SOAP/7.3.9-1+ubuntu18.04.1+deb.sury.org+1
    Content-Type: text/xml; charset=utf-8
    SOAPAction: "urn:Action"
    Content-Length: 1148
    Cookie: PHPSESSID=xxx;

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Magento"
                       xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                       SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:multiCall>
                <sessionId xsi:type="xsd:string">xxx</sessionId>
                <calls SOAP-ENC:arrayType="xsd:ur-type[1]" xsi:type="ns1:FixedArray">
                    <item SOAP-ENC:arrayType="xsd:ur-type[2]" xsi:type="SOAP-ENC:Array">
                        <item xsi:type="xsd:string">sales_order_shipment.sendMail</item>
                        <item SOAP-ENC:arrayType="xsd:string[1]" xsi:type="SOAP-ENC:Array">
                            <item xsi:type="xsd:string">100000001</item>
                        </item>
                    </item>
                </calls>
                <options xsi:nil="true"/>
            </ns1:multiCall>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

**Comment by iamniels** [comment]
[This error](https://magento.stackexchange.com/questions/146600/adding-bundle-items-to-cart-creates-recursive-dependency-error) pops up on PHP 7.3 and not on PHP 7.2. The suggested fix works.

**Comment by colinmollenhour** [comment]
Fixed in #894
