### ISSUE TITLE
Resetting the catalog product model must empty the array _storeValuesFlags

### ISSUE THREAD

**Issue by kanevbg** [OpenMage/magento-lts#724]
https://magento.com/tech-resources/bug-tracking/issue/index/id/1094

**Steps to reproduce:**
Store View 1 (ID=1)
Store View 2 (ID=2)

Add product to both store views. (in the code the product is with id=10)
In store view 1 setup the name of the product to "Use Default Value" and in store view 2 to be specific for that store.

_// Please setup these variables_
```
$storeOneId = 1;
$storeTwoId = 2;
$productId = 10;
```
```
$product = Mage::getModel('catalog/product')->setStoreId($storeTwoId)->load($productId);
var_dump($product->getExistsStoreValueFlag('name'));

$product->reset()->setStoreId($storeOneId)->load($productId);
var_dump($product->getExistsStoreValueFlag('name'));
```

**THE FIX:**
In the reset method that code must be added before "return $this;" :
$this->_storeValuesFlags = array();
to clear previously flagged attributes as available for the store view.

**Expected Result:**
bool(true) bool(false)

**Actual Result:**
bool(true) bool(true)

**Comment by colinmollenhour** [comment]
I think I would approve of this fix. Please create a PR. Thanks!
