### ISSUE TITLE
[WIP] Cleanup: Round 1 - DOC block updates

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#725]
Just an overview for already opened or ready PRs ... I'll add further PRs as soon I think I#m done with round 1 :)

Round 1:

- just doc blocks
- PSR2 automatic fixes
- all other changes (added missing properties/...) will be removed
- there are some missing typehints for parameters ... pls don't worry, will be fixed in round 2 :)

---

Pull requests ...

- [x]  Admin
- [ ]  Adminhtml - classname designpack
- [x]  AdminNotification
- [x]  Api
- [x]  Api2
- [x]  Bundle
- [x]  Captcha
- [x]  Catalog
- [x]  CatalogIndex
- [x]  CatalogInventory
- [x]  CatalogRule
- [x]  CatalogSearch
- [x]  Checkout
- [x]  Cms
- [x]  ConfigurableSwatches
- [x]  Contacts
- [x]  Core
- [x]  Cron
- [x]  CurrencySymbol
- [x]  Customer
- [x]  Directory
- [x]  Downloadable
- [x]  Eav
- [x]  GiftMessage
- [x]  ImportExport
- [x]  Index
- [x]  Log
- [x]  Media
- [x]  Newsletter
- [x]  Oauth
- [x]  Page
- [x]  PageCache
- [x]  Payment
- [x]  Persistent
- [x]  Poll
- [x]  ProductAlert
- [x]  Rating
- [x]  Reports
- [x]  Review
- [ ]  Rss
- [x]  Rule
- [x]  Sales
- [x]  SalesRule
- [x]  Sendfriend
- [x]  Shipping
- [x]  Sitemap
- [x]  Tag
- [x]  Tax
- [ ]  Uploader (0)
- [x]  Weee
- [x]  Widget
- [x]  Wishlist

Changes in lib

- [x] Varien
- [ ] Zend

Exluded (at least in "round 1"):

- Authorizenet
- Backup
- Centinel
- Connect
- Dataflow
- GoogleAnalytics
- <s>GoogleBase</s> (removed, see #1002)
- GoogleCheckout
- Install
- Paygate
- Paypal
- PaypalUk
- Usa
- XmlConnect

**Comment by colinmollenhour** [comment]
Nice work, @sreichel and thanks for tackling this big project! I'm fully on-board with all of the doc block-only updates I've seen so far. Thanks for splitting them up from the other updates so they can be reviewed separately.

Does anyone have any objection to deviating from the normal 2+ reviewers for the doc-block-only PRs as long as the Travis-CI checks passed (no PHP syntax errors)? The faster we get these merged the less likely we'll run into merge conflicts with future PRs.

**Comment by tmotyl** [comment]
go for it :)

**Comment by sreichel** [comment]
> Does anyone have any objection to deviating from the normal 2+ reviewers for the doc-block-only PRs as long as the Travis-CI checks passed (no PHP syntax errors)?

How about ... I'll request rewievs as soon i think the PR is ready? @colinmollenhour @Flyingmana @tmotyl ?

Current PRs are small modules, but changelists are already long. Comming PRs include bigger ones (Sales, Customer, ...) and have PSR2 errors fixed too (whitespaces, linebreak, indentations) so changelists get more longer ...

I could also split PRs into 2-3 commits (block, models, helpers, ....) if needed?

(just working on Adminhtml, Catalog and Sales .... expect ~50 PRs during next day :P)

>  The faster we get these merged the less likely we'll run into merge conflicts with future PRs.

:+1:  I'prefer this PRs get merged before all other code changes ...

**Comment by sreichel** [comment]
I'm done! :)

Startet with far +25k warnings in PHPstorm, complaining about undefined methods, now its down to >8k. 

Most unresolved issues are calls on Varien_Objects or in unedited modules like XmlConnect ... 

EVERY method should have a doc block now. Typehints for parameter are nearly complete - possible that i've missed some. In this case please just leave a comment, w/o request changes. I'll collect it and fix it at the end with one PR.

**Comment by sreichel** [comment]
@tmotyl i've just requested reviews from @Flyingmana and @colinmollenhour. Would like to help? :)

**Comment by rvelhote** [comment]
Thank you so much for the hard work!
Can you please let me know what tools/plugins/configs are you using for these docblock reviews with PHPStorm? I always have MessDetector + Code Sniffer when developing.

**Comment by sreichel** [comment]
@rvelhote I've used PHPStorm + CS + xDebug and with more added doc blocks phpstan. Phpstan shows missing typehints, type-mismatches, ...

**Comment by sreichel** [comment]
Mhhh. Bit disappointing ...

**Comment by Flyingmana** [comment]
Sorry, properly reviewing all this changes is quite time consuming and we have a certain lack of reviewers. With the amount of changed lines this will likely take also most of next year, till we are through all of them.

**Comment by sreichel** [comment]
Bump.

**Comment by sreichel** [comment]
See #416
