### ISSUE TITLE
EOL Phase 2: support jQuery in place of PrototypeJS for the frontend

### ISSUE THREAD

**Issue by kanevbg** [OpenMage/magento-lts#739]
Which means to implement every component used by default in the frontend with Prototype JS to be working with jQuery only and no Prototype JS.

It may be need to be a new theme I have not investigated what will be needed to achieve.

This will allow more efficient frontend resources.

**Comment by colinmollenhour** [comment]
jQuery is almost as obsolete as Prototype. Prototype still works. This would be a ton of effort for little gain.

However, I would advocate instead to build a GraphQL API layer that is compatible with Magento 2's GraphQL API and then you could use any frontends built for Magento 2, specifically the [PWA Studio](https://magento-research.github.io/pwa-studio/), with little to no effort. That said, I think this project would be outside the scope of magento-lts but I would be interested in supporting it nonetheless.

**Comment by kanevbg** [comment]
Right, please close.

**Comment by tmotyl** [comment]
if anybody want to go the getting rid of prototype path, here is the validation part ported:
https://github.com/jayelkaake/valid8
