### ISSUE TITLE
Array to string conversion when adding reviews from backend

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#741]
Repoduce:

- set a filter on entity column in Catalog -> Mange Products grid
- go to Catalog -> Customer Reviews
- add New Review

Expected:

- product list apears

Actually:

- empty product list or array to string conversion when dev mode is on.
- need to reset filter in product grid to add reviews

**Comment by colinmollenhour** [comment]
I would guess that the product grid for adding a review should use a unique grid id to avoid the conflict with the main product grid?
