### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by theroch** [OpenMage/magento-lts#785]
Magento <=1.9.4.1

Since PHP 7.2 count throws something like:

ERR (3): Warning: count(): Parameter must be an array or an object that implements Countable  in /srv/www/htdocs/www_dwd-shop_de/app/code/core/Mage/Catalog/Model/Resource/Abstract.php on line 74

because of changes in [count](https://www.php.net/manual/en/function.count.php)

**Comment by theroch** [comment]
A patch coul be:
```
Index: app/code/core/Mage/Catalog/Model/Resource/Eav/Attribute.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/code/core/Mage/Catalog/Model/Resource/Eav/Attribute.php	(revision 1969621936e49b3e1f7d8aabe64e89874ce3dd94)
+++ app/code/core/Mage/Catalog/Model/Resource/Eav/Attribute.php	(revision ec867d51ff4fda08ab4cd0c3076a41f768489f91)
@@ -249,10 +249,13 @@
             if (is_array($this->getData('apply_to'))) {
                 return $this->getData('apply_to');
             }
-            return explode(',', $this->getData('apply_to'));
-        } else {
-            return array();
-        }
+            $applyTo = explode(',', $this->getData('apply_to'));
+            if (is_array($applyTo)) {
+                return $applyTo;
+            }
+        }
+
+        return array();
     }
 
     /**

```

**Comment by sreichel** [comment]
Can you please add step to reproduce?

**Comment by colinmollenhour** [comment]
According to docs `count` should only return a non-array if the first argument is an empty string which is impossible in this case. Perhaps you have an extension implementing a different `getApplyTo` method?

**Comment by theroch** [comment]
> According to docs `count` should only return a non-array if the first argument is an empty string which is impossible in this case. Perhaps you have an extension implementing a different `getApplyTo` method?

You are rigtht it is the first argument, not the second one. I've also looked for extensions implementing a different `getApplyTo` method, but there is no other method.
I will do some debugging to get the root cause.

**Comment by theroch** [comment]
OK I've found the root cause, it's a proprietary modul which uses catalog/resource_abstract but the attribute model is the default entity attribute model.
