### ISSUE TITLE
Patch SUPEE-11155/Magento 1.9.4.2

### ISSUE THREAD

**Issue by cundd** [OpenMage/magento-lts#786]
Magento published version 1.9.4.2 including SUPEE-11155

**Comment by cundd** [comment]
See pull request on magento-mirror: https://github.com/OpenMage/magento-mirror/pull/75

**Comment by Flyingmana** [comment]
as usuall, we will merge from the Mirror as soon as it did go through the merge process there and was approved.

**Comment by cundd** [comment]
@Flyingmana are my issues not helpful? I thought that it may help to have it noted here

**Comment by Flyingmana** [comment]
it is usefull :)
I just wanted to add a status, before someone puts work on creating a separate PullRequest, which then may be less helpful for the existing process

**Comment by wytzejan** [comment]
Just want to notify that OpenMage/magento-mirror#75 is merged and done! :-)

**Comment by cundd** [comment]
Can this issue be closed? I think I've overseen the update.

**Comment by Flyingmana** [comment]
update was done with https://github.com/OpenMage/magento-lts/pull/791
and no complains yet, so I think its done, so will close this Issue here
