### ISSUE TITLE
This should be reverted, as it is not an issue in 1.9.4.x and blocks SUPEE-11155

### ISSUE THREAD

**Issue by ProxiBlue** [OpenMage/magento-lts#787]
https://github.com/OpenMage/magento-lts/blob/f306599b0840faa2b230af840f3c10638625ff6c/app/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml#L62

ref: https://magento.stackexchange.com/a/280148/202

**Comment by ProxiBlue** [comment]
https://github.com/OpenMage/magento-lts/pull/788

**Comment by Flyingmana** [comment]
will be solved/covered by #786

**Comment by ProxiBlue** [comment]
Closing as per comment will be resolved in #786 - no need to keep open (+PR)
