### ISSUE TITLE
Product image not visable in Backend

### ISSUE THREAD

**Issue by anushka27** [OpenMage/magento-lts#79]
Hi,

I am using Magento 1.9.2.4. 

When I add a new product and want to upload an productimage, this image doesn't appear. After clicking on the upload button, you see that upload is 100%, but then nothing happens. No image.

How can this bug fixed?
![schermafbeelding 2016-04-14 om 11 18 45](https://cloud.githubusercontent.com/assets/18460040/14523206/bdbfe4c2-0232-11e6-8fb4-36df92bafccd.png)

**Comment by sreichel** [comment]
It seems it's not a LTS related problem ... vote 4 close or more information ...

**Comment by tmotyl** [comment]
@anushka27 this sounds to be your installation or infrastructure issue. If you found a solution please comment here maybe it will help others.
