### ISSUE TITLE
Tier price discounts not working in configurable products.

### ISSUE THREAD

**Issue by MeerUmair** [OpenMage/magento-lts#794]
This is our products :-

http://kannojapan.com/700809554.html
Try to change the product from the list pricing will be change but discounts not. 

This is a video link where you can find out the problem what we are facing.
https://www.loom.com/share/ef324902cfdf4e11962b36c3ee37ec50

**Comment by fballiano** [comment]
This seems to be a problem with the custom theme, I tested it on the official theme and it's working as expected
