### ISSUE TITLE
Admin Password Recovery

### ISSUE THREAD

**Issue by rvelhote** [OpenMage/magento-lts#795]
A few days ago I wandered by mistake into the password recovery screen for the backend and I noticed that it wasn't working at all. The browsers error console showed many errors related to missing

```
ReferenceError: Class is not defined captcha.js:25:15
TypeError: document.observe is not a function forgotpassword:43:14
ReferenceError: varienForm is not defined forgotpassword:63:34
```

In `app/design/adminhtml/default/default/template/resetforgottenpassword.phtml` there is a `script` tag with the following `src` attribute

```
<?php echo $this->getJsUrl() ?>index.php/x.js?f=prototype/prototype.js,prototype/validation.js,mage/adminhtml/events.js,mage/adminhtml/form.js,scriptaculous/effects.js
```

The problem is `<?php echo $this->getJsUrl() ?>index.php/x.js` does not exist at all. If I replace it with `<?php echo $this->getJsUrl() ?>index.php/js/` (because the js folder has an index.php that appears to concatenate files) it will work.

Does anyone else confirm?

**Comment by luigifab** [comment]
There is a pending PR (#1618) that drop this `<?php echo $this->getJsUrl() ?>`.

**Comment by ADDISON74** [comment]
PR #1618 was merged. @rvelhote please reply if it solves your issue.
