### ISSUE TITLE
PHP Fatal error: Uncaught Mage_Core_Model_Store_Exception in /app/code/core/Mage/Core/Model/App.php:1384

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#803]
Hi, noticed this php 7.2 error - it triggers when we non-existant store code is passed from nginx to M1. 

However the error is more about getStore not working in this case. Maybe we can log a system error and not an exception here. Even redirect tot the default store?

https://stackoverflow.com/questions/23127464/uncaught-exception-mage-core-model-store-exception

**Question**: Any ideas? would be interested in a small change ... to avoid the crash itself ... or to avoid the "uncaught-ness"

`[26-Aug-2019 22:10:53 UTC] PHP Fatal error:  Uncaught Mage_Core_Model_Store_Exception in /app/code/core/Mage/Core/Model/App.php:1384
Stack trace:
#0 /app/code/core/Mage/Core/Model/App.php(864): Mage_Core_Model_App->throwStoreException()
#1 /app/Mage.php(363): Mage_Core_Model_App->getStore('nonexistingstore_code')
#2 /options.css.php(16): Mage::getStoreConfig('shoppersettings', 'nonexistingstore_code')
#3 {main}
  thrown in /app/code/core/Mage/Core/Model/App.php on line 1384`

After some google I see it is always/often linked to getstore not working

Could we add a try/catch?

    public static function getStoreConfig($path, $store = null)
    {
        try {
            return self::app()->getStore($store)->getConfig($path);
        } catch (Exception $e) {
            self::logException($e);
            die;
        }
    }

**Comment by seansan** [comment]
Can close. Issue was php file issuing CSS and sometimes could not detect the store code.

**Comment by ashamlou** [comment]
Hi! I have the same issue. How to resolve?

**Comment by ashamlou** [comment]
@seansan
