### ISSUE TITLE
Theme data not updated when switching package

### ISSUE THREAD

**Issue by azambon** [OpenMage/magento-lts#807]
When one changes the currently active package by invoking `Mage_Core_Model_Design_Package::setPackageName()`, the theme data is not updated or reset.

Suppose that one has a non-default admin theme, `default/customername` and suppose that there is a cronjob that tries to send emails from some specific, non admin store view, let's say store view 1. Also assume that the package and theme of such store view are something like `package1` and `default` respectively.
When the `Mage_Core_Model_Design_Package` is first loaded, it correctly loads the admin configuration with package `default` and theme `customername`. Then, when the code tries to render the email, Magento initiates an app emulation and switches the package to the one configured for store view 1 by calling `Mage_Core_Model_Design_Package::setPackageName('package1')`. The problem is that no one changes the theme data, and so Magento looks for the data in `package1/customername`, which does not exist.
It is true that the app emulation code calls `Mage_Core_Model_Design_Package::setTheme('')`, but such a call does not reset the default theme. And this can cause issues.

**Comment by fballiano** [comment]
I'm closing this issue since we have its PR https://github.com/OpenMage/magento-lts/pull/808
