### ISSUE TITLE
filePutContent ERR (3): Warning: chdir(): No such file or directory (errno 2)

### ISSUE THREAD

**Issue by roberto-ebizmarts** [OpenMage/magento-lts#809]
On https://github.com/OpenMage/magento-lts/blob/1.9.4.x/lib/Varien/Io/File.php
the method filePutContent log a message like:
"ERR (3): Warning: chdir(): No such file or directory (errno 2)"
due to not using **@chdir**
public function filePutContent($filename, $src)
    {
        @chdir($this->_cwd);
        $result = @file_put_contents($filename, $src);
        **chdir**($this->_iwd);
        return $result;
    }

Not big thing, but create not necessary logs.

**Comment by ADDISON74** [comment]
If this is an issue in OpenMage we should create a PR.

**Comment by fballiano** [comment]
Fixed by https://github.com/OpenMage/magento-lts/pull/1269
