### ISSUE TITLE
fopen() and fclose() missing as public methods for  Varien_Io_File class

### ISSUE THREAD

**Issue by roberto-ebizmarts** [OpenMage/magento-lts#810]
Hi, team.
Congrats for the library Varien_Io_File. It has been useful.
On https://github.com/OpenMage/magento-lts/blob/1.9.4.x/lib/Varien/Io/File.php
many functions helps Magento developers to avoid coding standard notifications about using directly **mkdir(), file_exists()**...So I have used this library in order to "clean" our project code. And I arrived to the point where I didn't find any function which allow developers replace **fopen()** and **fclose()** PHP functions.
And maybe it will be necessary a new method which allows to access the resource returned by the new **fopen() function** equivalent.
I think this is a need, there is not an equivalent way to access to the returned value for **fopen()** function. And sometimes, some third party functions/methods use this **resource** as a param.
Thanks.

**Comment by roberto-ebizmarts** [comment]
The coding standard is MEQP1.

In the end, that library uses internally the fopen() method, and offers several common and useful methods. So, why not to add these simple methods?
 But, don't worry, it is not a issue. I just look for an alternative. If it is not possible, not problem.
@colinmollenhour, thanks.
Thanks, @Flyingmana

**Comment by colinmollenhour** [comment]
Ahh, I see now your motivation more clearly. If it is the marketplace you are concerned about then you should be asking Magento to patch the official version, but that is futile given that M1 is EOL as far as they are concerned. I'm not opposed to accepting your PR, btw, just offering you some alternatives.

**Comment by roberto-ebizmarts** [comment]
Thanks, @colinmollenhour 
Have a nice day.

**Comment by sreichel** [comment]
@all-contributors add @roberto-ebizmarts bug
