### ISSUE TITLE
Solve problem with Magento Connect Tls: Magento 1.9.2 Unknown cipher in list: TLSv1

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#82]
In downloader/lib/Mage/HTTP/Client/Curl.php, try changing:

$this->curlOption(CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
to
$this->curlOption(CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);

http://magento.stackexchange.com/questions/73748/magento-1-9-2-unknown-cipher-in-list-tlsv1

**Comment by Flyingmana** [comment]
thx, have added a PR and can merge it after two reviews

**Comment by Flyingmana** [comment]
was "resolved" by magento, at least in 1.9.3.1
