### ISSUE TITLE
Newsletter Subscription Success - No Emails sent

### ISSUE THREAD

**Issue by hejhog** [OpenMage/magento-lts#822]
No Newsletter Success Emails are sent to the customer when confirming subscription - as per settings in System > Customers > Newsletter

/app/code/core/Mage/Newsletter/controllers/SubscribeController.php
**public function confirmAction()**  has no action to send success email

**Comment by hejhog** [comment]
The above is related to Guest subscribers but also has the following "issues".
No check to evaluate if the the guest email is already in the subscriber list.
No check to evaluate if the guest  has already confirmed.

The following resolves the issue:
/app/code/core/Mage/Newsletter/controllers/SunscribeController.php
Add to public function newAction() approx line 56
```
                //Check if  Guest User Email already exists
                $existingSubscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email)->getId();
                if (!empty($existingSubscriber) && !$customerSession->isLoggedIn()):
                    Mage::throwException($this->__('This email address is already registered.'));
                endif;
```

Replace public function confirmAction() with:
```
    public function confirmAction()
    {
        $id    = (int) $this->getRequest()->getParam('id');
        $code  = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
            $subscriber = Mage::getModel('newsletter/subscriber')->load($id);
            $session    = Mage::getSingleton('core/session');

            
            if ($subscriber->getStatus() == $subscriber::STATUS_SUBSCRIBED){ //Check if already confirmed
                $session->addNotice($this->__('This email address is already confirmed.'))
                      
            } elseif($subscriber->getId() && $subscriber->getCode()) {
                    if($subscriber->confirm($code)) {
                        $status = $subscriber->sendConfirmationSuccessEmail(); //Send Success email
                        $session->addSuccess($this->__('Your subscription has been confirmed.'));
                    } else {
                        $session->addError($this->__('Invalid subscription confirmation code.'));
                    }
            } else {
                $session->addError($this->__('Invalid subscription ID.'));
            }
        }

        $this->_redirectUrl(Mage::getBaseUrl());
    }
```

**Comment by ADDISON74** [comment]
A commit should be created in order to fix this issue.

**Comment by ADDISON74** [comment]
@hejhog - could you please create a PR that we can then discuss?

**Comment by hejhog** [comment]
I have implemented the changes to the latest SubscribeController file (FormKey validation has since been added).  However, I have NOT tested.

<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magento.com for more information.
 *
 * @category    Mage
 * @package     Mage_Newsletter
 * @copyright  Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Newsletter subscribe controller
 *
 * @category    Mage
 * @package     Mage_Newsletter
 * @author      Magento Core Team <core@magentocommerce.com>
 */
class Mage_Newsletter_SubscriberController extends Mage_Core_Controller_Front_Action
{
    /**
     * Use CSRF validation flag from newsletter config
     */
    const XML_CSRF_USE_FLAG_CONFIG_PATH = 'newsletter/security/enable_form_key';

    /**
      * New subscription action
      */
    public function newAction()
    {
        if (!$this->_validateFormKey()) {
            $this->_redirectReferer();
            return;
        }

        if ($this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
            $session            = Mage::getSingleton('core/session');
            $customerSession    = Mage::getSingleton('customer/session');
            $email              = (string) $this->getRequest()->getPost('email');

            try {
                if (!Zend_Validate::is($email, 'EmailAddress')) {
                    Mage::throwException($this->__('Please enter a valid email address.'));
                }

                if (Mage::getStoreConfig(Mage_Newsletter_Model_Subscriber::XML_PATH_ALLOW_GUEST_SUBSCRIBE_FLAG) != 1 &&
                    !$customerSession->isLoggedIn()) {
                    Mage::throwException($this->__('Sorry, but administrator denied subscription for guests. Please <a href="%s">register</a>.', Mage::helper('customer')->getRegisterUrl()));
                }

                //Check if Guest User Email already exists
                $existingSubscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email)->getId();
                if (!empty($existingSubscriber) && !$customerSession->isLoggedIn()) {
                    Mage::throwException($this->__('This email address is already registered. Please contact us if you require any assistance.'));
                }

                $ownerId = Mage::getModel('customer/customer')
                        ->setWebsiteId(Mage::app()->getStore()->getWebsiteId())
                        ->loadByEmail($email)
                        ->getId();
                if ($ownerId !== null && $ownerId != $customerSession->getId()) {
                    Mage::throwException($this->__('This email address is already assigned to another user.'));
                }

                $status = Mage::getModel('newsletter/subscriber')->subscribe($email);
                if ($status == Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE) {
                    $session->addSuccess($this->__('Confirmation request has been sent.'));
                } else {
                    $session->addSuccess($this->__('Thank you for your subscription.'));
                }
            } catch (Mage_Core_Exception $e) {
                $session->addException($e, $this->__('There was a problem with the subscription: %s', $e->getMessage()));
            } catch (Exception $e) {
                $session->addException($e, $this->__('There was a problem with the subscription.'));
            }
        }
        $this->_redirectReferer();
    }

    /**
     * Subscription confirm action
     */
    public function confirmAction()
    {
        $id    = (int) $this->getRequest()->getParam('id');
        $code  = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
            $subscriber = Mage::getModel('newsletter/subscriber')->load($id);
            $session = Mage::getSingleton('core/session');

            if ($subscriber->getStatus() == $subscriber::STATUS_SUBSCRIBED){ //Check if already confirmed
                $session->addNotice($this->__('This email address is already confirmed.'))
                      
            } elseif($subscriber->getId() && $subscriber->getCode()) {
                    if($subscriber->confirm($code)) {
                        $status = $subscriber->sendConfirmationSuccessEmail(); //Send Success email
                        $session->addSuccess($this->__('Your subscription has been confirmed.'));
                    } else {
                        $session->addError($this->__('Invalid subscription confirmation code.'));
                    }
            } else {
                $session->addError($this->__('Invalid subscription ID.'));
            }
        }

        $this->_redirectUrl(Mage::getBaseUrl());
    }

    /**
     * Unsubscribe newsletter
     */
    public function unsubscribeAction()
    {
        $id    = (int) $this->getRequest()->getParam('id');
        $code  = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
            $session = Mage::getSingleton('core/session');
            try {
                Mage::getModel('newsletter/subscriber')->load($id)
                    ->setCheckCode($code)
                    ->unsubscribe();
                $session->addSuccess($this->__('You have been unsubscribed.'));
            } catch (Mage_Core_Exception $e) {
                $session->addException($e, $e->getMessage());
            } catch (Exception $e) {
                $session->addException($e, $this->__('There was a problem with the un-subscription.'));
            }
        }
        $this->_redirectReferer();
    }

    /**
     * Check if form key validation is enabled in newsletter config.
     *
     * @return bool
     */
    protected function _isFormKeyEnabled()
    {
        return Mage::getStoreConfigFlag(self::XML_CSRF_USE_FLAG_CONFIG_PATH);
    }
}

**Comment by ADDISON74** [comment]
@fballiano - I updated his posts because he didn't use Git code markup correctly.

**Comment by fballiano** [comment]
this part is not needed and it doesn't check the website_id

```
                //Check if Guest User Email already exists
                $existingSubscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email)->getId();
                if (!empty($existingSubscriber) && !$customerSession->isLoggedIn()) {
                    Mage::throwException($this->__('This email address is already registered. Please contact us if you require any assistance.'));
                }
```

since it's done by this:

```
                $ownerId = Mage::getModel('customer/customer')
                        ->setWebsiteId(Mage::app()->getStore()->getWebsiteId())
                        ->loadByEmail($email)
                        ->getId();
                if ($ownerId !== null && $ownerId != $customerSession->getId()) {
                    Mage::throwException($this->__('This email address is already assigned to another user.'));
                }
```

**Comment by fballiano** [comment]
this is missing a semicolon:

`                $session->addNotice($this->__('This email address is already confirmed.'))`

what the heck man, this code can't work at all

**Comment by ADDISON74** [comment]
I didn't make any changes to the code he added. I just made it look like one written in PHP. If you need help I can make a comparison in the current code and the one provided by him and see what needs to be added for fixing the bug. I will look also over his initial post where he reported the issue.

**Comment by fballiano** [comment]
I know @ADDISON74 :-) I was saying that to the original author :-)

**Comment by fballiano** [comment]
converted to PR https://github.com/OpenMage/magento-lts/pull/2195
