### ISSUE TITLE
Travis not working

### ISSUE THREAD

**Issue by midlan** [OpenMage/magento-lts#826]
It seems, that travis stopped working few days ago. New pull requests are not tested with travis:

https://github.com/OpenMage/magento-lts/pull/825

**Comment by Flyingmana** [comment]
they are still running: https://travis-ci.org/OpenMage/magento-lts/pull_requests
But they dont give any feedback to Github.

I also notice, it still has the old default branch(1.9.3.x) configured, not the current one.
And there are entries missing in the Build History.
Also it does not list 1.9.4.x as active branch(or branch at all)
I did change the config on Travis Side to also "Build pushed branches" and not only "Build pushed pull requests", this seemed to trigger the PullRequest runs again.

I cant check the configured Service on the Repository, I think only @LeeSaferite can.

**Comment by colinmollenhour** [comment]
I just manually triggered a build on 1.9.4.x as it said it had never been triggered. I think this will fix it but we'll see.

**Comment by midlan** [comment]
on my PR #852 travis didn't triggered

**Comment by Flyingmana** [comment]
it was at least started https://travis-ci.org/OpenMage/magento-lts/builds/610750039

either travis has problems, or they only send a state after the build ended

**Comment by midlan** [comment]
it finished but the check did not appear at the PR

**Comment by Flyingmana** [comment]
I think everything which we had run via travis, now also runs via github actions

**Comment by midlan** [comment]
seems like everything is now moved to travis. Let's delete the `.travis.yml`?

**Comment by colinmollenhour** [comment]
Yes, I think we can abandon Travis now

**Comment by midlan** [comment]
Travis removed in #1250, closing.
