### ISSUE TITLE
Quickwin/Idea: Add item id to list as info in front of row (or behind)

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#828]
Quickwin/Idea: Add item id to list as info in front of row (or behind)

![image](https://user-images.githubusercontent.com/652395/66657409-0fe15b00-ec40-11e9-9db1-de171ec9cc74.png)

**Comment by sreichel** [comment]
Pleas update title ;)

**Comment by fballiano** [comment]
Closing because I've created https://github.com/OpenMage/magento-lts/pull/2060
