### ISSUE TITLE
My patch for PHP 7

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#830]
Hello

I share my custom patches for Magento 1.9.4.2 and OpenMage to make some changes:
- compatibility for PHP 7.0 / 7.1 / 7.2 / 7.3 without suppress warning
- number of items in product attribute grid
- default sort order for customer group grid, promo catalog grid, promo quote grid
- remove the ":" after "From" and "To" of the date filters ("From:" is correct in english, but "De:" is incorrect in french because a space is missing)
- HTML fixes
- undefined index fixes

Licensed under the WTFPL, so do as you want of them. Perhaps there are some mistakes.

[magento-1942-v10.diff](https://github.com/OpenMage/magento-lts/files/3720392/1942-v10.txt)
[openmage-v10.diff](https://github.com/OpenMage/magento-lts/files/3720393/openmage-v10.txt)

Run `git apply magento-1942-v10.diff` or `git apply openmage-v10.diff` to apply the patch.

_patch also valid for 1.9.4.3_

**Comment by Flyingmana** [comment]
if the WTFPL does not allow to put the change under OSL-3, we can not use it.

**Comment by luigifab38** [comment]
I'm sorry, I meant do whatever you want, there is no copyright.

**Comment by seansan** [comment]
Quite a diff ;) thanks 

Would it be possible to pull some changes in sort by sort? (Grouped per a problem)

**Comment by seansan** [comment]
Sorry ... to add this this. Some changes can be merged immediately I guess like undefined index and html and .... ? Without a bc break ... others might need a more thorough check

**Comment by luigifab** [comment]
Yes, I can create some diff grouped by problem (html, undefined index, php7, default sort order...) if necessary.

**Comment by kiatng** [comment]
Why not create some pull requests, it would make review and merge easier, I think the community would be grateful too.

**Comment by seansan** [comment]
I agree ;)

I think the community is VERY GRATEFULL for all additions

But also careful of merging too large changes all at once ... don't know
why, but this is just what I have seen ... probably has a string relation
to a community where no management or leader exists ;)

So making some compartmentalized would really be a great help! With some
information on what it fixes (references) and notes I am certain the
seniors around here are glad to merge

GREAT WORK!

**Comment by luigifab** [comment]
Okay, I have created my first merge requests. I hope it's good.
