### ISSUE TITLE
Translations proposal

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#831]
I created a script to create CSV translation files automatically (it search all translations in php/phtml/xml files, it load existing translations from CSV files, and it update the CSV files) for my modules.

I also get many translations pack many months ago and generated CSV translation files for Magento 1.9.4.2 for 57 locales: ar_KW, ar_MA, ar_SA, az_AZ, be_BY, bg_BG, ca_ES, cs_CZ, cy_GB, da_DK, de_CH, de_DE, el_GR, en_AU, en_GB, es_AR, es_CL, es_CO, es_ES, es_MX, es_PA, et_EE, fa_IR, fi_FI, fr_CA, fr_FR, gl_ES, he_IL, hr_HR, hu_HU, hy_AM, id_ID, is_IS, it_IT, ja_JP, ka_GE, ko_KR, lt_LT, lv_LV, mk_MK, ms_MY, nb_NO, nl_NL, pl_PL, pt_BR, pt_PT, ro_RO, ru_RU, sk_SK, sl_SI, sq_AL, sv_SE, th_TH, tr_TR, uk_UA, zh_CN, zh_TW.

Even if there are many mistakes in theses translations, I think that OpenMage, like Redmine do, must includes all translations by default.

I can share my script or I can regenerate the CSV files from OpenMage files.

**Comment by Flyingmana** [comment]
having it as a script inside the repository may be useful for the future

**Comment by luigifab38** [comment]
Here the script: [translate.php](https://github.com/OpenMage/magento-lts/files/3725624/translate.php.txt) + [translate.xsl](https://github.com/OpenMage/magento-lts/files/3725625/translate.xsl.txt)

Update line 396/397/398/399 an run it: `php .../translate.php`

**Comment by colinmollenhour** [comment]
I'm not sure what you mean by this:

> Even if there are many mistakes in theses translations, I think, and I absolutely sure that OpenMage, like Redmine do, must includes all translations by default.

But if Magento is missing a translation for a string that appears in the code, the string itself will be used in untranslated form.

Nice work on the script! The "proper" place to put this would be in `shell/` and then the proper way to structure those scripts is to extend `Mage_Shell_Abstract`. It could be converted pretty easily, and the constants should use Magento's base path and the output should go into Magento's `var/` directory. E.g. `$this->_getRootPath() . DIRECTORY_SEPARATOR . 'var' . DIRECTORY_SEPARATOR . 'translate'`. See 'shell/log.php' or 'shell/indexer.php' as examples.

**Comment by luigifab38** [comment]
First, I say that for the translations found on magentocommerce.com/translations with help of web.archive.org.

I will try to update the script soon to put it in shell directory.

**Comment by luigifab** [comment]
> But if Magento is missing a translation for a string that appears in the code, the string itself will be used in untranslated form.

Yes, but, Openmage can include translations in [many languages](https://github.com/versedi/Magento-Locales).

I have reimplemented my custom script as a PHP class. Here is [the project](https://github.com/luigifab/translator). How it work? That's simple, for example:

* git clone the [translator project](https://github.com/luigifab/translator) in _.../openmage/shell/translator/_ directory
* git clone the [magento locales archive](https://github.com/versedi/Magento-Locales) in _.../openmage/shell/translator/versedi/_ directory
* edit the configuration (_$updateTranslationMagentoFull_), set _dir_ option: `'dir'   => '../../',`
* edit the configuration (_$updateTranslationMagentoFull_), set _packs_ option: `'packs' => ['./versedi/app/locale/'],`
* run the script: `php shell/translator/translate.php magento-full`

And tada! CSV files are created in _.../openmage/app/locale/*/_

**Comment by JKouvakis** [comment]
I could suggest a project I opened in crowdin

https://crowdin.com/project/openmage/

**Comment by luigifab** [comment]
Good, but can we import easily a cleaned version of _app/locale/en_US/*.csv_ files? Can we also import very old languages packs (legally?) ?

**Comment by JKouvakis** [comment]
as I see it has an option to upload csv per file...

**Comment by JKouvakis** [comment]
the problem is tha has to be done file by file... so if you want i can continue this project if the admins approve it...

**Comment by luigifab** [comment]
After https://github.com/OpenMage/magento-lts/discussions/1950, translations extracted [here](https://github.com/luigifab/openmage-translations).
I will create a composer file later.
