### ISSUE TITLE
Auto trim GET and POST

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#832]
An idea for the index.php to auto trim GET and POST data:

```
array_walk_recursive($_GET, static function (&$val) { $val = trim($val); });
array_walk_recursive($_POST, static function (&$val) { $val = trim($val); });
```

**Comment by Flyingmana** [comment]
while this may help in many cases, there is no guarantee nobody will have spacing characters in the beginning or end of a value.

**Comment by midlan** [comment]
definitelly dangerous and breaking thing

**Comment by luigifab** [comment]
Okay, if you don't like, no problem.
