### ISSUE TITLE
SUPEE-11219

### ISSUE THREAD

**Issue by stijnhau** [OpenMage/magento-lts#839]
Anyone working on including this patch in the this project?

**Comment by Flyingmana** [comment]
For the 1.9.4 branch we will merge the official release, as soon as we had enough people reviewing https://github.com/OpenMage/magento-mirror/pull/80#issuecomment-543657917

For the 1.9.3.x branch we will accept a PR with the patched version(but we recommend using the 1.9.4.x branch)
