### ISSUE TITLE
Replacement for Webservicex (currency rates import)

### ISSUE THREAD

**Issue by spinsch** [OpenMage/magento-lts#843]
Since Webservicex doesn't work for the currency import anymore I would like to connect another API. 

Do you think this makes sense and which service would be best?
Magento 2 for example uses fixer.io

There is already an implementation for Magento 1 but I don't know if it is compatible with our license. https://github.com/philwinkle/Philwinkle_Fixerio

**List of currency converter services:**
- https://ratesapi.io/
- https://fixer.io/
- https://currencylayer.com/
- https://free.currencyconverterapi.com/

**Comment by Flyingmana** [comment]
This may be a good first case for adding something as a composer dependency then.

Or we ask him, if he would like to contribute it.

**Comment by colinmollenhour** [comment]
The 1.9.4.3 update (just merged) adds support for two new currency APIs.

**Comment by spinsch** [comment]
I really need to be more careful. I'm still on an older branch.

Sorry
