### ISSUE TITLE
Checkout process stuck on Shipping Method

### ISSUE THREAD

**Issue by cundd** [OpenMage/magento-lts#847]
I had a case where I was stuck during the checkout in the Shipping Method section.
I had to patch `base/default/template/checkout/onepage/payment.phtml` and add `id="checkout-payment-method-load"` to the fieldset as described in https://magento.stackexchange.com/questions/50179/magento-1-9-checkout-stuck-on-shipping-methods.

Is this something that would fit into magento-lts?

```
--- openmage/www/app/design/frontend/base/default/template/checkout/onepage/payment.phtml	2019-10-30 10:50:07.000000000 +0100
+++ custom/www/app/design/frontend/default/theme510/template/checkout/onepage/payment.phtml	2019-10-31 11:21:41.000000000 +0100
@@ -34,7 +34,7 @@
 //]]>
 </script>
 <form action="" id="co-payment-form">
-    <fieldset>
+    <fieldset id="checkout-payment-method-load">
         <?php echo $this->getChildHtml('methods') ?>
     </fieldset>
     <?php echo $this->getBlockHtml('formkey') ?>
```

**Comment by colinmollenhour** [comment]
Yes, please submit a pull request. Thanks!

**Comment by Flyingmana** [comment]
no problem, thats what we have our review process for :)
