### ISSUE TITLE
replace money_format function-call

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#858]
the class \Varien_Filter_Money makes use of the deprecated money_format function.

this should get replaced with NumberFormatter::formatCurrency()

https://www.php.net/manual/en/numberformatter.formatcurrency.php
https://wiki.php.net/rfc/deprecations_php_7_4

**Comment by roman204** [comment]
seems to me this class is obsolete i can't find any usage of it.

**Comment by sreichel** [comment]
@Flyingmana this is not used and a candidate to remove ...  isnt it? (#374)

**Comment by seansan** [comment]
Is this something we can merge? and use NumberFormatter::formatCurrency()

To my understanding the 20.0.x releases are for php 7.4+?

**Comment by sreichel** [comment]
@Flyingmana 

I've searched all modules from "ModuleFostering" and no one makes use of it. It's a "good first issue" ... just remove it. (There are a few modules that directly use `money_format()`, so removing it should not harm)
