### ISSUE TITLE
SUPEE-10415 and 404: Page Not Found issue

### ISSUE THREAD

**Issue by onlinebizsoft** [OpenMage/magento-lts#864]
https://maxchadwick.xyz/blog/supee-10415-causing-every-page-to-404

This is real problem and I have faced with many sites and the problem become bigger when we use with a HTTP cache (and cache 404 response) like Turpentine varnish module,.....

Should we apply a fix to magento lts core ?

**Comment by Flyingmana** [comment]
fascinating, will need to look closer into this. I wonder why it did not happen before the patch, as the config if there should be logging at all, was also a db based config.

In general yes, we should fix this. The bigger questions is how.
But this can also be discussed on the PullRequest then.

**Comment by colinmollenhour** [comment]
Definitely agreed with Max's assessment, as few dependencies as possible should be required when using Mage::log. In my opinion, `dev/log/allowedFileExtensions` should not even be configurable and should just be hard-coded as `['log', 'txt', 'html', 'csv']` and then a simple `in_array` used to check the extension so there are no config values and no helpers consulted.
