### ISSUE TITLE
How to use the null- or notnull-operator with (complex) filter in Magento (1.9) API SOAP v2

### ISSUE THREAD

**Issue by growit-chris** [OpenMage/magento-lts#872]
Since the Magento community in StackExchange seems to be dead (at least for version 1.x), I ask my question here. I hope you can help me. After all, it's a 'problem' of the Magento API. ;-)

**How to use the null- or notnull-operator with (complex) filter in Magento (1.9) API SOAP v2**

**For example:**
* [sales_order_list api function](https://devdocs.magento.com/guides/m1x/api/soap/sales/salesOrder/sales_order.list.html)
* [filter operators](https://www.fontis.com.au/blog/web-services-api-filter-operators)

**Possible solutions:**
* value = "notnull"
* value = ""
* value = null
* value = "true"
* value = "1"
* use simple filter
* anything else?!?!

**Who knows the answer?**

**Comment by colinmollenhour** [comment]
`['key' => ['null' => true]]`

**Comment by growit-chris** [comment]
Hi Collin,

first of all many thanks for the feedback. You are awesome! :-)

I still have a little follow-up question:

In the Magento API SOAP V2 the value field is of type string, so it should look like this, right?

`['key' => ['null' => 'true']]`

Thanks and best regards,

Chris

**Comment by colinmollenhour** [comment]
I think the value doesn't actually matter and the presence of the key is all that matters, so probably yes but I don't know for sure. See `\Varien_Db_Adapter_Pdo_Mysql::prepareSqlCondition`
