### ISSUE TITLE
[RFC] Review mergeFiles logic in case of missing file

### ISSUE THREAD

**Issue by mmenozzi** [OpenMage/magento-lts#874]
Hi guys,
given this line in the `Mage_Core_Helper_Data::mergeFiles()` method:

https://github.com/OpenMage/magento-lts/blob/143b03dd51bbdf92bd165942fa3c5a14a2d9b178/app/code/core/Mage/Core/Helper/Data.php#L752

In case one of the source file doesn't exists on filesystem the merge is performed repeatedly at every request.

I agree that this should never happen because if a file is not on filesystem it should not be used by the application.

But if by mistake a CSS is removed from filesystem and the developer forgot to remove the related layout XML rule, we have other CSS files merged again and again at every request.

What do you think? It's worth to find a better way to handle merging in case of missing files or simply we don't want to "support" this kind of mistake.

**Comment by colinmollenhour** [comment]
Good observation. I think it would be appropriate to not re-merge the files every request as you stated, and an error should be logged when a file is missing.

**Comment by mmenozzi** [comment]
I agree.

**Comment by ADDISON74** [comment]
If this is an issue in OpenMage please create a PR for being tested. Thank you.
