### ISSUE TITLE
Creditmemo resets State back to PROCESSING

### ISSUE THREAD

**Issue by rvelhote** [OpenMage/magento-lts#875]
When creating a creditmemo (online or offline is irrelevant) for an order that is already has `state = 'complete'` Magento will revert back to `state = processing`.

https://github.com/OpenMage/magento-lts/blob/89adc787a8cd9af36dea6c7c55c91e70d3671db4/app/code/core/Mage/Sales/Model/Order/Payment.php#L728

This can cause issues with orders being shipped twice by mistake. Can anyone explain the reasoning behind resetting back to processing or is this a bug?

I believe this is equivalent to: https://github.com/OpenMage/magento-lts/pull/617

Thank you,
Ricardo

**Comment by fballiano** [comment]
tested, can't reproduce

**Comment by fballiano** [comment]
If somebody has more info please feel free to reopen
