### ISSUE TITLE
Would it be an idea to add a release # or some kind of v number here?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#881]
Would it be an idea to add a release # or some kind of v number here?

![image](https://user-images.githubusercontent.com/652395/72525837-578e0900-3865-11ea-9e00-43c698a63bbf.png)

**Comment by Flyingmana** [comment]
Yes, it would be a good idea.
I think also stating there its OpenMage would be a good idea.

But thats a very heavy visible change, so we should start an RFC about how this should look, and maybe how strong and in which way we want to signalize we are OpenMage, and a fork of Magento

**Comment by seansan** [comment]
i meant only in the backend ; so the admin would know which version he is
on; can also be somewhere else

**Comment by Flyingmana** [comment]
even for the Admin area this could be relevant, Iam not sure how the Agencies or rather their customers could react to this, so I want to have some more people approving it

**Comment by seansan** [comment]
Lets give it some time like 2 weeks or so ;)

Its not a biggy is it?

**Comment by aterjung** [comment]
I would welcome it if at least the Version info would show that we ware on OpenMage. At least my customers are irritated that they pay for the migration to OpenMage without a visible sing of it.

**Comment by sreichel** [comment]
> even for the Admin area this could be relevant, Iam not sure how the Agencies or rather their customers could react to this, so I want to have some more people approving it

I see only PROs here.

For agencies it's up to them (or their customers) to use official releases or this one.

IMHO ... show official version and LTS realeas number like ...

_Magento ver. 1.9.4.5 ([LTS](https://github.com/OpenMage/magento-lts) 19.4.2)_

@Flyingmana how about add release version as XML node?

**Comment by colinmollenhour** [comment]
I agree it could be good to show both versions. To me using 19.x.x is really confusing though because it looks confusing against the 1.9.x.x.. Why not just start LTS versioning at 1.0.0 (and maybe back-date and increment them based on past releases)?

**Comment by kiatng** [comment]
With all the code fixes and merges, _magento-lts_ isn't the same as the official code base. So, I think it should have its own identity, something like _Mage-LTS ver a.b.c.d (Magento ver 1.9.4.5)_.

**Comment by tmotyl** [comment]
I think we should state both MageLTS name and version as well as which magento version it's based on.

**Comment by Flyingmana** [comment]
@sreichel we have the Version number available in the Mage Class.

We need to add the usage on several places then analog to how Magento is doing it till now.
We should also think of removing the Magento Version at one point in the templates, but thats maybe another ticket then.

**Comment by Flyingmana** [comment]
Is there still a place left, where we need to add the new OpenMage release Version number?

**Comment by fballiano** [comment]
Closing this one since it seems to have been fixed with @sreichel https://github.com/OpenMage/magento-lts/pull/1014
