### ISSUE TITLE
Fix Class Inheritance (upstream PHP7 compat)

### ISSUE THREAD

**Issue by drobinson** [OpenMage/magento-lts#89]
https://github.com/Inchoo/Inchoo_PHP7/commit/bba4bfdffce4545b29f58bd22922c3e62816dbd9

**Comment by tmotyl** [comment]
@drobinson  the change desn't look like something we should merge does it?

**Comment by colinmollenhour** [comment]
Yes, that seems to be only related to Inchoo_PHP7
