### ISSUE TITLE
Why does the admin login take so long?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#893]
Ok we have various extensions and a lot of data. But today I realized wow! the admin login takes really long on average (feel).... 

Is there something we can do to speed this up?

**Comment by kkrieger85** [comment]
@seansan Do you use Magento or OpenMage? 

I faced slow Admin Login in two Magento stores. Only first login is slow, every more login is fast. I figured out, that in Magento Stores, retrieving Admin-Notification RSS Feed fails and runs in timeouts.. 

Maybe this could also be your issue

**Comment by seansan** [comment]
Openmage/magento-lts

I thought I already disabled this but will check again. What is the best
way to do this?

**Comment by kkrieger85** [comment]
@seansan Disable observer-event:

```
     <adminhtml>
        <events>
            <controller_action_predispatch>
                <observers>
                    <adminnotification>
                        <type>disabled</type>
                    </adminnotification>
                </observers>
            </controller_action_predispatch>
        </events>
    </adminhtml>
```

**Comment by seansan** [comment]
Thanks I understand the fix

One other way to go?

>> RSS Feed fails and runs in timeouts

Could we reduce the timeouts? Or skip these calls?

Where are the time outs set?

And/or of RSS fails we cancel the specific call for say 1 day

**Comment by seansan** [comment]
Would this do the same?


To disable these admin notification messages follow the following steps:

Login to your Magento Admin Panel
Go to System >> Configuration >> Advanced
Disable the Mage_AdminNotification module

**Comment by kkrieger85** [comment]
@seansan Skipping calls is the best solution, imho

I guess, timeout settings are global settings for curl-requests. 

Disabling Mage_AdminNotification in Backend -> Config-> Advanced only suppresses output for this module but doesn't stop requesting RSS Feeds.

**Comment by seansan** [comment]
OK this makes it more clear
