### ISSUE TITLE
API Attribute Codes (upstream PHP7 compat)

### ISSUE THREAD

**Issue by drobinson** [OpenMage/magento-lts#90]
https://github.com/Inchoo/Inchoo_PHP7/commit/47eff1b72d6a9b937b8de200ecb01ba1b681bbd6

**Comment by drobinson** [comment]
Merged https://github.com/OpenMage/magento-lts/pull/62

**Comment by drobinson** [comment]
Actually I don't think this has been merged yet...sorry - whoever opened this issue didn't give it a very descriptive title.

**Comment by tmotyl** [comment]
@drobinson I've just compared the https://raw.githubusercontent.com/OpenMage/magento-lts/1.9.3.x/app/code/core/Mage/Catalog/Model/Product/Link/Api/V2.php
with file from inchoo you've mentioned and I see no differences.
Can you confirm that this issue can be closed?

**Comment by sreichel** [comment]
Since inchoo removed all model rewrites this can be closed. Same for #89.

> 2.0.1
> Tested on M CE 1.9.3.* & M EE 1.14.3.*.
> This version removes all model overwrites and Mage_Core_Model_File_Uploader overload. That's fixed in 1.9.3 core.
