### ISSUE TITLE
Warning: Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#906]
Last version form LTS 1.9.4.x + php 7.1

We use redis so maybe log there; but not sure it is directly related or to session in general

Error occurs many times in our logs as a warning. I am not sure myself how to solve this.

Feb 22, 2020 1:22:46 PM | Logged Error | Warning: Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0
-- | -- | --
Feb 22, 2020 1:22:46 PM | Logged Error | Warning: Unknown: Failed to write session data using user defined save handler. (session.save_path: ) in Unknown on line 0

**Comment by kestraly** [comment]
What PHP version is this on?

Is it related to session garbage collection being on? I guess it would relate to clearing old sessions?

**Comment by seansan** [comment]
7.1
Garbage collection not sure need to check on iPhone
Would you turn that off? Or does it need a fix?

**Comment by seansan** [comment]
; Enables or disables the circular reference collector.
; http://php.net/zend.enable-gc
zend.enable_gc = On

**Comment by kestraly** [comment]
Everything I know about that error, oftern requires it to be turned off and then manually set up a clean job.

**Comment by seansan** [comment]
updating session.save_path: /tmp still does not solve the error although it seems to occur less

what I dont understand is that sessions are stored in redis, not on disk

or could it be the case that maybe redis is unavailable a short period then it falls back to disk?

it must be related to some file/disk filerights issue

2020-09-07T10:33:41+00:00 ERR (3): Warning: Unknown: Cannot call session save handler in a recursive manner  in Unknown on line 0
2020-09-07T10:33:41+00:00 ERR (3): Warning: Unknown: Failed to write session data using user defined save handler. (session.save_path: /tmp)  in Unknown on line 0

**Comment by jcpla** [comment]
Hi,
we had the same issue with redis sessions (and also using nexcess turpentine module causing 503 errors)

We fix that warning by increasing this config in local.xml
`<max_concurrency>6</max_concurrency>                 <!-- maximum number of processes that can wait for a lock on one session; for large production clusters, set this to at least 10% of the number of PHP processes -->`
==> we set a bigger number, 25 in our case

**Comment by joshua-bn** [comment]
In `Cm\RedisSession\Handler`
```
                // Limit concurrent lock waiters to prevent server resource hogging
                if ($waiting >= $this->_maxConcurrency) {
                    // Overloaded sessions get 503 errors
                    $this->_redis->hIncrBy($sessionId, 'wait', -1);
                    $this->_sessionWritten = true; // Prevent session from getting written
                    $writes = $this->_redis->hGet($sessionId, 'writes');
                    $this->_log(
                        sprintf(
                            'Session concurrency exceeded for ID %s; displaying HTTP 503 (%s waiting, %s total '
                            . 'requests)',
                            $sessionId, $waiting, $writes
                        ),
                        LoggerInterface::WARNING
                    );
                    throw new ConcurrentConnectionsExceededException();
                }
```
