### ISSUE TITLE
New Patch Magento

### ISSUE THREAD

**Issue by lucasfpiovesan12** [OpenMage/magento-lts#908]
Do we know that official Magento support will end this year, when you have just continued with corrections? If so, how did they launch? Like a release for example?

**Comment by Flyingmana** [comment]
Hi @lucasfpiovesan12 

Iam not sure I understand your questions.

We are completely independent from Magento, and as far as we know, they will not change plans about ending their support.
And our plans for support are independent from anything Mangento does
