### ISSUE TITLE
Missing $_eventPrefix ... worth to be fixed?

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#92]
Before i start a PR, i just want to know if you would accept it.

There are some models w/o $_eventPrefix set, e.g. `Mage_Cms_Model_Block`. Let's assume you want to observe CMS-Block save, you have to use one of these generic events `model_save_before` or `core_abstract_save_before` and check instance of the object. It works, but life could be easier :)

**Comment by seansan** [comment]
maybe some other events can be added too then? 

before_email_send
after_email_formatted
newsletter subscription

something like that?

the question is whether one would still observe these "new" events in upcoming extension .... on the other hand: why not if it helps someone?

**Comment by LeeSaferite** [comment]
Yes, we would accept the PR as long as it followed the existing patterns. I personally classify it as a bug that some models are missing event prefix information.

**Comment by LeeSaferite** [comment]
Just be prepared that it may take a few iterations to get accepted. 😃

**Comment by sreichel** [comment]
@LeeSaferite here we go ... #249  :)
