### ISSUE TITLE
Product default category list order

### ISSUE THREAD

**Issue by artbambou** [OpenMage/magento-lts#924]
Good afternoon everyone,

I would like your opinion about this line referenced in the project :
https://github.com/OpenMage/magento-lts/blob/c6f200cb6bc3c4ace0d9b54d0d0df0ad0432ba8f/app/code/core/Mage/Catalog/Block/Product/List/Toolbar.php#L165

You are agree with me, it doesn't take in account the configuration for each category value in admin catalog ?

Why Magento doesn't call getDefaultSortBy (default_sort_by) by default ? Even if we do not have filled a value for this field in database Magento by default will get this value in the core_config_data 

Classes concerned : 

1. Mage_Catalog_Model_Category => getDefaultSortBy function
2. Mage_Catalog_Model_Config

Any feedback will be appreciated.

Ilan

**Comment by colinmollenhour** [comment]
Please provide further proof of a bug, or a pull request if you would like to propose a change.
