### ISSUE TITLE
without the tool in admin panel

### ISSUE THREAD

**Issue by loopCM** [OpenMage/magento-lts#926]
when I install the magento-lts, The configure->tool can not use

**Comment by tmotyl** [comment]
I dont understand this issue. Please describe it better (steps, screenshot) otherwise it will be closed.

**Comment by loopCM** [comment]
ok,I check my admin panel

**Comment by loopCM** [comment]
![image](https://user-images.githubusercontent.com/1188048/79125292-8833ff00-7dd0-11ea-83d3-82f83cae9915.png)
There are no backup and Compilation options here

**Comment by Flyingmana** [comment]
yes, we removed the compile option, because the benefit was very little but caused a lot of problems.

We removed the backup option, as we assumed only very few people using it. This may have been a wrong assumption. Most people we know backup the database via database specific tools, as they are a lot more flexible and performant then doing it via Magento.

We still need to add documentation for this.

**Comment by loopCM** [comment]
Yes, thank you very much for your reply, I hope to have a backup function, a document is better.

**Comment by loopCM** [comment]
I think a big part of people is to use it, I think leaving these functions than the convenience brought by the delete it will be better, maybe you can set a the enable/disable function, so it will be more convenient, because I think you the original idea is to develop this branch magento1 can more people are going to continue to use, thank you very much for your hard work

**Comment by colinmollenhour** [comment]
The backup feature is half-baked. To restore from it you would have to know how to do that anyway so it gives users who don't know how to create a backup a false sense of security.

If you really want it, you can restore this removed code from the magento mirror repo, but I don't think anyone in this project is interested in supporting this code and I think it is better that it is removed than to leave it in place as it poses a security risk and a stability risk (e.g. filling up your disk with backups) and if we aren't really supporting it then it should be removed so people are not under the false impression that the tool is supported.

Looks like we do need to remove the "Tools" menu from the XML though as this is empty now..

**Comment by simbus82** [comment]
> yes, we removed the compile option, because the benefit was very little but caused a lot of problems.
> 
> We removed the backup option, as we assumed only very few people using it. This may have been a wrong assumption. Most people we know backup the database via database specific tools, as they are a lot more flexible and performant then doing it via Magento.
> 
> We still need to add documentation for this.

We have ~10 magento and our people are instructed to do a backup for every "critical" change (even before promotion for example).
In a transition like this you can't remove elements by assumption without data.

**Comment by colinmollenhour** [comment]
Perhaps it can be resurrected as a module in a separate repo that can easily be included using Composer?

**Comment by loopCM** [comment]
> > yes, we removed the compile option, because the benefit was very little but caused a lot of problems.
> > We removed the backup option, as we assumed only very few people using it. This may have been a wrong assumption. Most people we know backup the database via database specific tools, as they are a lot more flexible and performant then doing it via Magento.
> > We still need to add documentation for this.
> 
> We have ~10 magento and our people are instructed to do a backup for every "critical" change (even before promotion for example).
> In a transition like this you can't remove elements by assumption without data.

This is what I want to talk about, because this is useful when you have multiple magento's

**Comment by colinmollenhour** [comment]
Well it appears this was actually disabled in core and not by OpenMage.. 
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/etc/modules/Mage_All.xml#L237

So it turns out we just disabled unknowingly (to me at least) when this update was merged.. 

@simbus82, as to your point about the data, it seems the data shows that since Nov 28, 2018 only two users have cared that Mage_Backup was disabled.

If you want to use it, (I still advise not to but at your own risk you can do whatever you want), just enable it again by adding an xml file to app/etc/modules:

```xml
<config>
    <modules>
        <Mage_Backup>
            <active>true</active>
        </Mage_Backup>
    </modules>
</config>
```

**Comment by kiatng** [comment]
Backup was disabled officially in 1.9.4.0, documented [here](https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html#ce19-1940):

> Note that after updating to this release, third-party modules that depend upon Magento core backup functionality will no longer work. Alternatively, you can use one of these two methods to enable database backups:
> 
> Change **false** to **true** in the **config** > **modules** > **Mage_Backup** > active setting of `app/etc/modules/Mage_All.xml`.
From the Admin, change the **System** > **Configuration** > **Advanced** > **Disable  Modules Output** > **Mage_Backu**p from **disabled** to **enabled**.

**Comment by simbus82** [comment]
Thank you for all clarification!
I tell this to my team (and customers) to start use a more robust "instant" backup method.

**Comment by ADDISON74** [comment]
Starting with version 1.9.4.0 Mage_Backup module is deactivated/disabled as mentioned before by @kiatng,  but Tools link still appears in the System menu. 

A small change into the code code is needed to avoid seeing an empty link (see my report here #1368). My suggestion is to keep Tools link hidden if the Mage_Backup is deactivated/disabled. Once someone wants to activate the module and its output this link should appear as expected in Tools submenu.

The other link in Tools submenu called Compilation was a necessity to be removed from Magento as PHP 7 has its own opcache or we use Varnish to improve the performance.

To maintain a back compatibility for those who will migrate to OpenMage my suggestion is not removing this module from code core just leaving it in place. Even I prefer my own backups with cronjobs some 3rd party modules could depend on it.
