### ISSUE TITLE
Magento error: Front controller reached 100 router match iterations

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#93]
Magento error: Front controller reached 100 router match iterations

I recall seeing an issue about this here but I could not find it

Apparently according to the link below this is a confirmed error and a fix exists

Can we apply this fix against the code? (sorry I dont know how to diff against github)

Please confirm and apply fix

https://github.com/convenient/magento-ce-ee-config-corruption-bug#update-good-news-a-patch-from-magento

https://github.com/convenient/magento-ce-ee-config-corruption-bug/blob/master/PATCH_SUPEE-4755_EE_1.13.1.0_v1.sh#L172

**Comment by seansan** [comment]
Turned out to be 2 files with wrong chmod http://stackoverflow.com/a/33684913

**Comment by seansan** [comment]
Sorry to open this again. But after the patch we are still seeing this error. Now two mornings in a row. 

I have added code below because our action is to flush all cache. So why not make the system do it itself (instead of me hurrying to the desktop)

    public function dispatch() in front.php

        Varien_Profiler::start('mage::dispatch::routers_match');
        $i = 0;
        while (!$request->isDispatched() && $i++ < 100) {
            foreach ($this->_routers as $router) {
                /** @var $router Mage_Core_Controller_Varien_Router_Abstract */
                if ($router->match($request)) {
                    break;
                }
            }
        }
        Varien_Profiler::stop('mage::dispatch::routers_match');
        if ($i>100) {
            // Mage::throwException('Front controller reached 100 router match iterations');
            $requestData = array(
            'path_info' => $request->getPathInfo(),
            'module' => $request->getModuleName(),
            'action' => $request->getActionName(),
            'controller' => $request->getControllerName(),
            'controller_module' => $request->getControllerModule(),
            'route' => $request->getRouteName()
            );
            $st = '';
            foreach ($requestData as $key => $val) {
                $st .= "[{$key}={$val}] ";
            }
            Mage::logException('Front controller reached 100 router match iterations' . $st);
            Mage::app()->getCacheInstance()->flush();
            $url = Mage::getBaseUrl();
            Mage::app()->getFrontController()->getResponse()->setRedirect($url);
        }

**Comment by tmotyl** [comment]
instead we should review and merge this: https://github.com/OpenMage/magento-lts/issues/422

**Comment by hryksbt** [comment]
Is this issue resolved by some patch?
