### ISSUE TITLE
EU Vies Vat number validation service changed? Need Dutch Dev to check

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#940]
In app/code/core/Mage/Customer/Helper/Data.php

this is hardcoded

    const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl';

whilst new url is (I think)

    const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/checkVatTestService.wsdl';

Explained here

https://ec.europa.eu/taxation_customs/vies/technicalInformation.html

Needs check from Dutch DEV

**Comment by iamniels** [comment]
https://github.com/OpenMage/magento-lts/pull/937

**Comment by seansan** [comment]
haha! great ;)
