### ISSUE TITLE
Magento security patch: SUPEE-11314 / 1.9.4.5

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/magento-lts#941]
A new patch was released April 28, 2020:

[ce-1.9.4.4-1.9.4.5-2020-04-29-05-53-41.diff.txt](https://github.com/OpenMage/magento-lts/files/4561865/ce-1.9.4.4-1.9.4.5-2020-04-29-05-53-41.diff.txt)

**Comment by tmotyl** [comment]
@colinmollenhour are you up to providing patch for magelts? What is the flow? We first patch mage mirror and then lts?

**Comment by seansan** [comment]
Thx guys! As always ;)

**Comment by colinmollenhour** [comment]
I'm not sure when I would be able to get to it so if someone else would like to that would be great.

I think historically the patch has been on magento-mirror first and then lts by merging the latest mirror.

**Comment by colinmollenhour** [comment]
Looks like we already have one at #944

**Comment by seansan** [comment]
Is this The V2 version of the patch? There seems to be a critical hack in v1 version https://twitter.com/colinodell/status/1260683841452363776

**Comment by Flyingmana** [comment]
we did the version update instead, I dont know if this is also affected, also did also the M1 version got a second version?

**Comment by sreichel** [comment]
v2 seems not to be part of 1.9.4.5 ... this should be checked in time.

**Comment by sreichel** [comment]
Diff between v1 and v2 are only four lines, that are already in.
