### ISSUE TITLE
Discussion: Consider using PHP CS Fixer and/or PHPStan

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/magento-lts#947]
- Initially run CS Fixer to update all code to conform to a standard
- Add Travis pipeline or Github Action to throw error when CS Fixer output is different from pushed code (showing diff)

https://github.com/OpenMage/magento-lts/pull/693#discussion_r416685506
#365

**Comment by colinmollenhour** [comment]
@sreichel What are the pros/cons of PHP CS Fixer and PHPStan and are they completely redundant?

**Comment by tmotyl** [comment]
Php fixer just take care of CGL and can fix the formatting. While phpstan does static code analysis but cant fix code. 

So we need both :)

**Comment by sreichel** [comment]
> @sreichel What are the pros/cons of PHP CS Fixer and PHPStan and are they completely redundant?

As @tmotyl said. No, they aren't redundant.

IMHO cs-fixer is "just" a nice to have to have code matching PSR2 standard or whatever. phpstan/psalm is to prevent logical problems .... can't find it actually, but there was a nice article about predicted or expected variables ....

**Comment by kkrieger85** [comment]
+1 for phpcsfixer for PSR2
`php php-cs-fixer.phar fix /path/to/project --rules=@PSR2`

This could also improve to review PR like https://github.com/OpenMage/magento-lts/pull/1035 and all other PR consider code style
