### ISSUE TITLE
Use && and || operators instead of „or” and „and”

### ISSUE THREAD

**Issue by tmotyl** [OpenMage/magento-lts#958]

**Comment by sreichel** [comment]
Dont' forget .... https://github.com/kalessil/phpinspectionsea/blob/master/docs/control-flow.md#non-optimal-if-conditions

**Comment by sreichel** [comment]
Id reopen .... it was "only" `and` statements .... ;) Thanks!

**Comment by tmotyl** [comment]
Ah sorry, you’re right
