### ISSUE TITLE
Solve #912 without the use of the error suppressor

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#959]
Find a way to solve #912 without the use of the error suppressor `@`, so we do not cause Issues if `scream.enabled` is activated

**Comment by sreichel** [comment]
Fixed in #966

**Comment by ADDISON74** [comment]
Was this report resolved by #966? It was closed in June 2020 and reopened on the same day.

**Comment by fballiano** [comment]
I think all of the PRs related to this issue are merged, closing
