### ISSUE TITLE
Code reviews welcome

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#973]
Hey

i'm contributing here since years, now i ask for your help. **Please do some reviews**,

I spent weeks to add doc blocks and annotions to make work easier. These PRs are nearly one year old and still lack of reviews. They are not perfect and can/will be improved ....

I'd like to help with "serious" problems, but I also want to have the code style issues been fixed ....

Thanks!

**Comment by sreichel** [comment]
Just one review(s) left, thanks @tmotyl.

Review size ...

```
Mage_Catalog +4,917 −2,594
Mage_CatalogInventory +352 −208
Mage_CatalogRule +411 −203
Mage_CatalogSearch +304 −180
Mage_Checkout +1,017 −393
Mage_Core +2,719 −1,459
Mage_Customer +1,665 −808
Mage_Directory +239 −119
Mage_Downloadable +612 −305
Mage_Eav +1,510 −721
Mage_Giftmessage +420 −331
Mage_ImportExport +161 −132
Mage_Index +147 −98
Mage_Media +95 −34
Mage_Newsletter +333 −217
Mage_Oauth +144 −123
Mage_Page +303 −82
Mage_Payment +232 −97
Mage_Persistant +59 −53
Mage_Poll +156 −75
Mage_ProductAlert +227 −133
Mage_Rating +335 −144
Mage_Reports +724 −438
Mage_Review +453 −158
Mage_Rule +486 −88
Mage_Sales +5,317 −2,914
Mage_SalesRule +603 −307
Mage_Sendfriend +78 −52
Mage_Shipping +320 −212
Mage_Sitemap +60 −40
Mage_Tax +684 −313
Mage_Weee +229 −125
Mage_Widget +173 −112
Mage_Wishlist +247 −170
Varien_ +896 −200
```

**Comment by sreichel** [comment]
Thanks for effort! `Mage_Sales` was one of the largest changes and its in. Next big ones are on the road .... nice progress!

Some already reviewed or with at least two review ... #780, #776, #758, **#703, #702, #701**

**Comment by sreichel** [comment]
Woooha :))

Thanks @colinmollenhour for latest reviews .... with `Mage_Eav` there is only one "bigger" PR left. Nice progress :+1:

**Comment by colinmollenhour** [comment]
I'm doing what I can, those things are brutal. :) Nice work though, and thanks also to @tmotyl for being first to review them!

**Comment by sreichel** [comment]
Only 17 small one left ... nice :+1:

**Comment by sreichel** [comment]
Thanks @colinmollenhour for merging last ones, thanks for reviews .... I already work on Adminhtml` and it su* .... it is painful.

**Comment by tmotyl** [comment]
@sreichel would it be possible to add some static analysis with whitelist for the modules which are fixed now, or is it too early?

**Comment by sreichel** [comment]
@tmotyl yes i can do, but ... 

- even for level 0 or 1 you have to exclude sniffs.(e.g missing parent constructor or properbly undefined vars in set in try/catch-blocks)
- exclude some files completly where it is not possible to resolve return values (maybe /ignoreMethod option is added in later phpstan release)
- still use far outdated `phpstan 0.8.x` ... magento1-extension has to be updated for `phpstan 0.12.x`. Someone? (there is already _closed_ a [PR](https://github.com/inviqa/phpstan-magento1/pull/5) for v0.12.x)

**Comment by tmotyl** [comment]
Can we use fork https://github.com/vianetz/phpstan-magento1/ (which sounds to be compatible) directly or does it require additional changes (then I would go for a fork in openmage)

**Comment by sreichel** [comment]
I'll try it out over the weekend.
