### ISSUE TITLE
Warning: SimpleXMLElement::__construct() .../Feed.php on line 172

### ISSUE THREAD

**Issue by leganzaro** [OpenMage/magento-lts#976]
Last version form LTS 1.9.4.x and php 7.2.30.

We've encountered the issue when we tried to use "Flush Magento Cache" from backend. The error occurs in our logs as a warning and we are not sure how to solve this.

```
Logged Error 	Warning: SimpleXMLElement::__construct(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and body in /***/Mage/AdminNotification/Model/Feed.php on line 172
Logged Error 	Warning: SimpleXMLElement::__construct(): </body> in /***/Mage/AdminNotification/Model/Feed.php on line 172
Logged Error 	Warning: SimpleXMLElement::__construct(): ^ in /***/Mage/AdminNotification/Model/Feed.php on line 172
Logged Error 	Warning: SimpleXMLElement::__construct(): Entity: line 7: parser error : Opening and ending tag mismatch: body line 3 and html in /***/Mage/AdminNotification/Model/Feed.php on line 172
Logged Error 	Warning: SimpleXMLElement::__construct(): Entity: line 7: parser error : Premature end of data in tag html line 1 in /***/Mage/AdminNotification/Model/Feed.php on line 172
```

**Comment by tmotyl** [comment]
the data returned by url is 
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
the called url is: ‌https://openmage.github.io/Web_Notifications/notifications_v1.rss

which redirects to http version:

HTTP/2 301 
server: GitHub.com
content-type: text/html
location: http://www.openmage.org/Web_Notifications/notifications_v1.rss

**Comment by leganzaro** [comment]
Thank you @tmotyl. 

Based on your response, the solution in our case is to copy the core file "../AdminNotification/etc/config.xml" to local and remove the feed url.

**Comment by colinmollenhour** [comment]
@Flyingmana Any reason not to enable Enforce HTTPS?
![image](https://user-images.githubusercontent.com/38738/82050039-6b1b7600-9685-11ea-9f69-fea1e3c942aa.png)
