### ISSUE TITLE
Documentation Around Version Numbers

### ISSUE THREAD

**Issue by cdbessig** [OpenMage/magento-lts#985]
I believe some clarity around this would be good.  For example, I read that 19.4.1 should be used as per [here](http://www.openmage.org/magento-lts/install.html). 

However, when I place that on top of my magento code (just a zip file download and a copy over), in the admin panel I get Magento ver. 1.9.4.4.  

If I go to the github repo and just do git clone https://github.com/OpenMage/magento-lts.git  then copy the files over I get Magento ver. 1.9.4.5

I never see anything like 19.4.1.  Worse off, when I git clone https://github.com/OpenMage/magento-lts.git  I got commits from today.  I was under the assumption that a LTS version should have released versions and not just pull in all of the latest commits.

My recommendations here are as follows:

* Establish true documentation on how to upgrade / version numbers / etc.
* Add an OpenMage LTS version number in the footer of admin above or below current magento version. (Or replace completely, if allowed by liscense)

Maybe I am just confused, or perhaps this will confuse others as well.

Thanks!

**Comment by sreichel** [comment]
You're right. Documentation needs udates ...

- disable outdated wiki pages
- github.io sample should reflect latest version (change version to `~19.4`?)
- if you just clone, you'll clone from main branch (1.9.4.x) with all daily changes

Btw ... show version is already discussed here #881

**Comment by fitzjohnit** [comment]
Hi,

Yes I think it needs updating as didn't work for me either. Using "19.4.x" (which took from the further instructions link) did and I'm now on version 1.9.4.5 from Magento's point of view. I've created a pull request #992 to amend the README.md which hopefully is correct and will get accepted if so.

Thanks,

Ed

**Comment by fballiano** [comment]
Agree, there's the need for a more clear documentation about the versioning.
